// vivekananda_ta.dart
// ஸ்வாமி விவேகானந்தா மேற்கோள்கள் மற்றும் கட்டுரைகள்

import '../articlesquotes.dart';

final vivekanandaSaintTa =   Saint(
  'vivekananda',
  'சுவாமி விவேகானந்தர்',
  'assets/images/vivekananda.jpg',
  [
    'எழுந்திரு, விழித்தெழு; இலக்கு அடையும் வரை நின்றிடாதே.',
    'ஒரு எண்ணத்தை ஏற்று கொள்; அதையே உன் வாழ்க்கையாக்கு — அதை சிந்தி, கனவு காண், அதிலேயே வாழ்.',
    'வீரனாக இரு; எப்போதும் சொல் — “எனக்கு பயமில்லை.” பயமே மரணம்; பயமே பாவம்; பயமே நரகம்.',
    'இந்த உலகம் ஒரு பெரிய நெறிப் பயிற்சி மையம்; ஆன்மீக வலிமை பெற நாம் இங்கு பயிற்சி பெற வேண்டும்.',
    'கீதையைப் படிப்பதை விட, கால்பந்து விளையாட்டின் மூலம் சொர்க்கத்திற்கு அருகாகலாம்.',
    'உண்மைக்காக அனைத்தையும் தியாகம் செய்யலாம்; ஆனால் எதற்காகவும் உண்மையை தியாகம் செய்ய முடியாது.',
    'ஜீவராசிகளை சேவிப்பவன், உண்மையில் சிவனை வழிபடுகிறான்.',
    'ஓ இந்தியா! தாழ்த்தப்பட்டோர், அறியாமையாளர், ஏழைகள், கல்வியறியாதோர், செருப்புச் செய்பவர், தூய்மைப் பணியாளர் — இவர்கள் உன் இரத்தமும் மாம்சமும்; உன் சகோதரர்கள் என்பதை மறந்திடாதே.',
    'நாம் எங்கள் சிந்தனைகள் உருவாக்கியவர்களே; ஆகவே சிந்தனையை கவனித்துக் கொள்; சொற்கள் இரண்டாம் நிலை; சிந்தனைகள் உயிரோடு நீண்ட பயணம் செய்கின்றன.',
    'அமெரிக்க சகோதரிகளும் சகோதரர்களும், நீங்கள் அளித்த அன்பான வரவேற்புக்கு பதிலளிக்க எழும்பும் இந்த தருணம் சொல்ல முடியாத மகிழ்ச்சியை என் இதயத்தில் நிரப்புகிறது.',
    'அனைத்து சக்தியும் உன்னுள் உள்ளது; நீ எதையும் செய்ய வல்லவன்.',
    'தன்னை பலவீனன் என்று எண்ணுவது மிகப் பெரிய பாவம்.',
    'வலிமை வாழ்க்கை; பலவீனம் மரணம். விரிவு வாழ்க்கை; சுருக்கு மரணம். அன்பு வாழ்க்கை; வெறுப்பு மரணம்.',
    'உலகம் நம்மை வலிமையாக்கும் பெரும் பயிற்சி அரங்கம்.',
    'நீ என்ன சிந்திக்கிறாயோ அதுவாக ஆகிறாய்; உன்னை பலவீனன் என நினைத்தால் பலவீனன்; வலிமைமிகு என நினைத்தால் வலிமைமிகு.',
    'எழுந்து நில்; துணிவுடன் இரு; வலிமையுடன் இரு; முழுப் பொறுப்பையும் ஏற்று, உன் விதியை உருவாக்குபவன் நீயென்பதை அறி.',
    'என் வீர இளைஞர்களே! நீங்கள் பெரிய செயல்களுக்கு பிறந்தவர்கள் என்ற நம்பிக்கை கொள்.',
    'தன்னம்பிக்கை இல்லாமல் இறைவன் மீது நம்பிக்கை கொள்ள முடியாது.',
    'வீரனாக இரு; எப்போதும் சொல் — “எனக்கு பயமில்லை.”',
    'ஆன்மாவிற்கு இயலாதது எதுவும் இல்லை என்று ஒருபோதும் நினைக்காதே.',
    'இந்த உடல் எத்தனை நாள் நிலைக்கும்? மனித உடலைப் பெற்றபின் உள்ளார்ந்த ஆத்மாவை எழுப்பி — “நான் பயமற்ற நிலையை அடைந்தேன்” என்று அறிவி.',
    'அளவற்ற பொறுமை, தூய்மை, விடாமுயற்சி வேண்டும்; வெற்றி தவறாது வரும்.',
    'அளவற்ற பொறுமை கொண்டால் வெற்றி உன்னதே.',
    'போராடுபவன், முயற்சி செய்யாதவனை விட மேல்.',
    'சுதந்திரமாக இரு; யாரிடமும் எதிர்பார்க்காதே; பிறரிடமிருந்து உதவி தேடியது வீணென்பதை வாழ்க்கை காட்டும்.',
    'பயமின்மையே கற்பிக்கப்பட வேண்டிய ஒரே மதம்.',
    'யாரையும் காத்திருக்காதே; இயன்றதை செய்; யாரையும் நம்பி நம்பிக்கை அமைக்காதே.',
    'நீ நாடும் வலிமையும் துணையும் அனைத்தும் உன்னுள் உள்ளது.',
    'வாழ்க்கையில் ஆபத்தை ஏற்று கொள்; வென்றால் வழிநடத்துவாய்; தோற்றால் வழிகாட்டுவாய்.',
    'குணநலன் உருவாக, மன வலிமை வளர, அறிவு விரிவடைய, தனக்கே தானாக நிற்கக் கற்றுத் தரும் கல்வியே வேண்டும்.',
    'கல்வி என்பது தகவல்களை மூளையில் குவிப்பது அல்ல.',
    'சிந்தனையின் ஓட்டத்தையும் விருப்பத்தின் வெளிப்பாட்டையும் கட்டுப்படுத்தி பலன் தருவது கல்வி.',
    'கல்வியின் சாரம் மன ஒருமுகப்படுத்தலே; தகவல் சேகரிப்பு அல்ல.',
    'முதலில் குணநலனை உருவாக்கு; அதுவே உயர்ந்த கடமை.',
    'செல்வமும் புகழும் கல்வியும் பலன் தராது; அன்பும் குணநலனும் தடைகளை உடைக்கும்.',
    'ஆயிரம் தடுமாற்றங்களால் குணநலம் உருவாகிறது.',
    'ஒரு மனிதன் சிறிய செயல்களில் எப்படி நடக்கிறான் என்பதைப் பாரு; அதுவே அவன் உண்மையான குணநலம்.',
    'மீண்டும் மீண்டும் செய்யும் பழக்கங்களே குணநலனாக மாறுகின்றன.',
    'ஒவ்வொரு செயலும் சிந்தனையும் மனத்தில் பதிப்பை உருவாக்கும்; அவற்றின் மொத்தமே குணநலம்.',
    'ஒரே எண்ணத்தை ஏற்று அதை முழு வாழ்க்கையாக்கு; மூளை, தசை, நரம்புகள் அனைத்தும் அதனால் நிரம்பட்டும்; அதுவே வெற்றியின் வழி.',
    'எதையும் எதிர்பார்க்காத சுயநலமற்ற மனிதரே உண்மையான வெற்றியாளர்.',
    'செயலுக்காக செய்; வழிபாட்டுக்காக வழிபடு; நன்மை நல்லதென்பதால் செய்; வேறு எதையும் நாடாதே.',
    'உண்மையை போதித்து கடமைக் களத்தில் மரணமடைவது, உலக வாழ்க்கையில் வீணாக வாழ்வதை விட உயர்ந்தது.',
    'வாழ்வின் முழு ரகசியம் பயமின்மை.',
    'ஒரு நாளில் பிரச்சினைகள் இல்லையெனில் தவறான பாதையில் செல்கிறாய் என அறிந்து கொள்.',
    'அளவற்ற பொறுமையும் ஆற்றலும் உள்ளவரே வெற்றி பெறுவார்.',
    'விடாமுயற்சி செய்; இப்போதுதான் தொடக்கம்; ஒருபோதும் மனம் தளராதே.',
    'இதயமும் அறிவும் மோதும் போது இதயத்தைப் பின்பற்று.',
    'தூய்மையும் சுயநலமின்மையும் உடையவரே இறைவனை காண்கிறார்; இறைவனை காண்பது இறைவனாக ஆகுதல்.',
    'இந்த வாழ்க்கை குறுகியது; உலக வீண்பெருமைகள் நிலையற்றவை; பிறருக்காக வாழ்பவர்களே உண்மையில் வாழ்கிறார்கள்.',
    'பெரும் தடைகளை தாண்டியே பெரிய சாதனைகள் நிறைவேறும்.',
    'முழுமையான சுயநலமின்றி உறுதியாக உழை; பயப்படாதே; பெரிய செயல்கள் நிகழும்.',
    'பிறருக்கு நன்மை செய்வதனால் இதயம் தூய்மையடையும்.',
    'ஆன்மீக வாழ்க்கைக்கு மிகப்பெரிய துணை தியானம்; அடுத்தது நல்ல நட்பு.',
    'நம்மை சூடாக்கும் நெருப்பு நம்மை எரிக்கவும் முடியும்; குறை நெருப்பில் இல்லை.',
    'உதவ முடியாதவர்களிடம் ஒருவர் எப்படி நடக்கிறார் என்பதே அவரது குணநலனின் சோதனை.',
    'பிறரிடமிருந்து நல்லதை கற்று கொள்; ஆனால் உன் வழியில் அதை உட்கொள்; அவர்களாக மாறாதே.',
    'அருகிலுள்ள கடமையைச் செய்வதிலிருந்து உயர்வு தொடங்குகிறது.',
    'மகிழ்ச்சியுடன் இரு; உன் இலட்சியத்தைப் பிடித்து கொள்; அனைவருக்கும் பணியாளர் ஆகு.',
    'மனிதனில் ஏற்கனவே உள்ள தெய்வீகத்தை வெளிப்படுத்துவது மதம்.',
    'உள் வளர்ச்சி மூலமே உயர்வு; உன் ஆன்மாவே உன் ஆசான்.',
    'ஒவ்வொரு மனித உடலிலும் இறைவன் இருக்கிறான் என்பதை உணரும் தருணமே விடுதலை.',
    'அனைவரின் நலனுக்காக வாழ்வதே மதம்; தனக்காக செய்வது மதம் அல்ல.',
    'உன் இயல்புக்கு உண்மையாக இருப்பதே உயர்ந்த மதம்; தன்னம்பிக்கை கொள்.',
    'சுமந்து கொள்ள மட்டும் அல்ல; பற்றின்றி இரு.',
    'மத நம்பிக்கைகளின் பல்வகை தன்மை நன்மை; அவை அனைத்தும் ஆன்மீக வாழ்வை ஊக்குவிக்கின்றன.',
    'மதம் மனிதர்களை பிரிப்பதற்காக அல்ல; ஒன்றிணைப்பதற்காக.',
    'மத உணர்வு உருவாகும் முதல் அறிகுறி மகிழ்ச்சி.',
    'கண்மூடித் நம்பிக்கை ஆன்மாவை வீழ்த்தும்; ஆய்ந்து நம்பு.',
    'அன்பும் பக்தியும் கொண்டு மதத்தை அணுகு; இதயம் உண்மையை அறிவிக்கும்.',
    'உன் இயல்புக்கு உண்மையாக இருப்பதே உயர்ந்த மதம்; தன்னம்பிக்கை கொள்.',
    'ஏழையிலும் எதுவுமில்லாதவரிலும் பெரிய இறைவன் இருக்கிறான்; செல்வந்தன் அனைவருக்கும் பணியாளர்.',
    'நான் வாழும் வரை என் இருப்பை நான் கட்டுப்படுத்துவேன்.',
    'முழுமையாக அமைதியாகவும் பற்றின்றியும் இருந்தால் உண்மையான செயல் சாத்தியம்.',
    'தேடாதே; தவிர்க்காதே; வரும் அனைத்தையும் ஏற்று கொள்.',
    'எதையும் சொந்தம் கொள்ளாது அனைத்தையும் இறைவனுக்கு ஒப்புவித்து — “உன் சித்தமே நடக்கட்டும்” என்று சொல்.',
    'நாமே மகிழ்ச்சியாக இருப்பதோடு பிறரையும் மகிழ்ச்சியாக்க வேண்டும்.',
    'மனித வாழ்க்கையின் இலக்கு சுதந்திரம்.',
    'ஒவ்வொரு ஆன்மாவும் தெய்வீகத் திறன் கொண்டது.',
    'ஒரு நாளில் ஒருமுறை உன்னுடன் பேசிக் கொள்; இல்லையெனில் உலகின் அறிவாளியை சந்திக்கும் வாய்ப்பை இழப்பாய்.',
    'உண்மை ஆயிரம் விதமாக சொல்லப்பட்டாலும் உண்மையே.',
    'நம் சிந்தனைகளே நம்மை உருவாக்குகின்றன; நல்லதும் கெட்டதும் அவற்றின் பலன்.',
    'மனம் பைத்தியக்கார குரங்கு போன்றது; விருப்பம் அதை கட்டும் கயிறு.',
    'ஆன்மீக வாழ்க்கைக்கு மிகப் பெரிய துணை தியானம்; அடுத்தது நல்ல நட்பு.',
    'மனம் உலகையே வெல்லக்கூடிய சக்தி.',
    'எதற்கும் அஞ்சாதே; பயம் வரும் தருணமே வீழ்ச்சி.',
    'பிரபஞ்சத்துடன் இசைந்தால் நம்முடனும் இசைவாய் இருப்போம்.',
    'வெற்றி பெறும் மனம் உறுதியான விருப்பத்துடன் இணைந்து விடாமுயற்சி செய்கிறது.',
    'மனத்தில் பதிந்த அனுபவங்களின் மொத்தமே மனித குணநலம்.',
    'தூய்மையும் உயர்ந்த போதனையின் வாழும் எடுத்துக்காட்டும் உடையவரே உண்மையான ஆசான்.',
    'நம் சிந்தனைகளே நம்மை உருவாக்குகின்றன; ஆகவே சிந்தனையை கவனித்துக் கொள்.',
    'அனைத்து ஞானமும் நம்முள் உள்ளது; அதை வெளிப்படுத்துவது மனமே.',
    'உலக ஞானம் மனம் என்ற வடிகட்டியின் மூலம் நம் உணர்வில் வெளிப்படுகிறது.',
    'மனித மனம் ஞானத்தின் பெரும் களஞ்சியம்; சிந்தனைகள் அதன் வழி.',
    'மனம் காட்டு குதிரை போன்றது; இந்திரியங்கள் கட்டுப்பாட்டு கயிறு; விருப்பமே ஓட்டுநர்.',
    'மனதை கட்டுப்படுத்து; மகிழ்ச்சியும் துன்பமும் அதிலிருந்தே தோன்றுகின்றன.',
    'வலிமையான சிந்தனைகள் நிஜத்தை உருவாக்கும்; வலிமையான மனம் மலைகளை நகர்த்தும்.',
    'நீ சிந்திப்பது நீ ஆகிறாய்; உணர்வது உன்னை ஈர்க்கிறது; கற்பனை செய்பது உருவாகிறது.',
    'மனம் நன்மைக்கும் தீமைக்கும் கருவி; அதை பயன்படுத்துவது உன் தேர்வு.',
    'பிறருக்காக வாழ்பவர்களே உண்மையில் வாழ்கிறார்கள்.',
    'உலகில் உள்ள வேறுபாடுகள் அளவின் வேறுபாடு; ஒற்றுமையே அனைத்தின் ரகசியம்.',
    'பிறரிடமிருந்து நல்லதை கற்று, உன் வழியில் அதை உட்கொள்.',
    'பிரபஞ்சத்துடன் இசைந்தால் நம்முடனும் இசைவாய் இருப்போம்.',
    'பிழைகளை துணிவுடன் சுட்டிக்காட்டவும், நல்லவற்றை பாராட்டவும் வேண்டும்.',
    'யாரையும் காயப்படுத்தாதே; பொறாமை கொள்ளாதே; வெறுக்காதே; அன்பே ஒரே சட்டம்.',
    'பிறருடன் சண்டை போடாதே; சகிப்புத்தன்மையுடன் இரு; அனைத்து மதங்களையும் உண்மையாக ஏற்று கொள்.',
    'பெரியோர் சிந்திப்பார்கள்; ஆனால் அவர்கள் செயலில் நிறைவேற்றுவார்கள்; அதுவே வித்தியாசம்.',
    'மனிதனின் தெய்வீகத்தை உணர்த்தி, வாழ்க்கையின் ஒவ்வொரு செயலிலும் அதை வெளிப்படுத்துவதே என் இலக்கு.',
    'வெளி, உள் இயற்கையை கட்டுப்படுத்தி தெய்வீகத்தை வெளிப்படுத்துவதே வாழ்க்கையின் குறிக்கோள்.',
    'ஒவ்வொரு ஆன்மாவும் தெய்வீகத் திறன் கொண்டது; செயல், வழிபாடு, தியானம், தத்துவம் ஆகியவற்றின் மூலம் அதை வெளிப்படுத்து; சுதந்திரம் பெறு.',
    'எழுந்திரு, விழித்தெழு; இலக்கு அடையும் வரை நின்றிடாதே; பலவீனம் மரணம்; வலிமை வாழ்க்கை.',
    'உள் வளர்ச்சியே உண்மையான உயர்வு; உன் ஆன்மாவே உன் ஆசான்.',
    'உன் இயல்புக்கு உண்மையாக இரு; தன்னம்பிக்கை கொள்.',
    'அனைத்து சக்தியும் உன்னுள் உள்ளது; நீ பலவீனன் அல்ல என்பதை நம்பு.',
    'வாழ்வின் முழு ரகசியம் பயமின்மை; யாரையும் சாராதே.',
    'தூய்மை, பொறுமை, விடாமுயற்சி — வெற்றியின் மூன்று தூண்கள்; அவற்றை மீறும் அன்பு.',
    'எழுந்து நில்; துணிவுடன் இரு; வலிமையுடன் இரு; உன் விதியை உருவாக்குபவன் நீயென்பதை அறி.',
    'இதயமும் அறிவும் மோதும் போது இதயத்தைப் பின்பற்று.',
    'ஒரு நாளில் ஒருமுறை உன்னுடன் பேசிக் கொள்; இல்லையெனில் உன்னையே இழப்பாய்.',
    'நம்மை சூடாக்கும் நெருப்பு நம்மை எரிக்கவும் முடியும்; குறை நெருப்பில் இல்லை.',
    'ஒவ்வொரு மனித உடலும் இறைவனின் ஆலயம் என்பதை உணரும் தருணமே விடுதலை.',
    'மனிதனில் ஏற்கனவே உள்ள தெய்வீகத்தை வெளிப்படுத்துவது மதம்.',
    'உலகின் அனைத்து வேறுபாடுகளும் அளவின் வேறுபாடு; ஒற்றுமையே ரகசியம்.',
    'சௌகரியம் உண்மையின் அளவுகோல் அல்ல; உண்மை பல நேரங்களில் சௌகரியமற்றது.',
    'உலகம் நம்மை வலிமையாக்கும் பெரும் பயிற்சி அரங்கம்.',
    'பசியிலும் அறியாமையிலும் வாழும் கோடிக்கணக்கானவர்களை புறக்கணிப்பவன் துரோகி.',
    'தன்னை பலவீனன் என்று எண்ணுவது மிகப் பெரிய பாவம்.',
    'நம் சிந்தனைகளே நம்மை உருவாக்குகின்றன; ஆகவே சிந்தனையை கவனித்துக் கொள்.',
    'பொருள் உலகால் அசைக்கப்படாதவன் அமரத்துவத்தை அடைகிறான்.',
    'தன்னம்பிக்கை இல்லாமல் இறைவன் மீது நம்பிக்கை இல்லை.',
    'அனைத்து தெய்வங்களில் நம்பிக்கை இருந்தாலும் தன்னம்பிக்கை இல்லையெனில் மீட்சியில்லை.',
    'பிறரிடமிருந்து நல்லதை கற்று கொள்; ஆனால் அவர்களாக மாறாதே.',
    'வாழ்க்கையில் ஆபத்தை ஏற்று கொள்; வென்றால் வழிநடத்துவாய்; தோற்றால் வழிகாட்டுவாய்.',
    'ஒரே வேலையை ஒரே நேரத்தில் செய்; அதில் முழு உள்ளத்தையும் செலுத்து.',
    'வெளி இயற்கை என்பது உள் இயற்கையின் விரிவாக்கம்.',
    'வீரனாக இரு; எப்போதும் சொல் — “எனக்கு பயமில்லை.” இதை அனைவருக்கும் கூறு.',
    'பிறருக்கு நன்மை செய்யும் அளவிற்கு இதயம் தூய்மையடையும்; அதில் இறைவன் குடியிருப்பார்.',
    'வலிமையே மதம்; பலவீனம் பாவம்.',
    'எதையும் சொந்தம் கொள்ளாது அனைத்தையும் இறைவனுக்கு ஒப்புவித்து — “உன் சித்தமே நடக்கட்டும்” என்று சொல்.',
    'ஆசை குறைந்தால் செயல் சிறக்கும்; அமைதி அதிகமானால் பலன் பெருகும்.',
    'அனுபவமே உண்மையான ஆசான்; பேசுவதால் மட்டும் உண்மை புரியாது.',
    'அன்பு விரிவு; சுயநலம் சுருக்கு.',
    'மூளையும் தசைகளும் இணைந்து வளர வேண்டும்.',
    'இலக்கை குறைக்காதே; திறனை உயர்த்து.',
    'நீ நம்புவது நீ ஆகிறாய்; பலவீனம் நம்பினால் பலவீனம்; வலிமை நம்பினால் வலிமை.',
    'உடல், அறிவு, ஆன்மீகத்தில் பலவீனம் தருவது அனைத்தையும் விஷமாக நிராகரி.',
    'முதலில் உடல் வலிமையை வளர்த்து; பின்னர் மனக் கட்டுப்பாடு சாத்தியம்.',
    'எதற்கும் அஞ்சாதே; பயமின்மையே உடனடி சொர்க்கம் தரும்.',
    'ஒருமுகப்படுத்தும் சக்தியே ஞானக் களஞ்சியத்தின் சாவி.',
    'ஏழைகள், பலவீனர்கள், நோயாளிகள், அறியாமையாளர்கள் — இவர்களை இறைவனாக எண்ணி சேவை செய்.',
    'தியானம் ஆன்மீக வாழ்க்கையின் மிகப் பெரிய துணை; அதில் பொருள் பற்றுகளை விடுவோம்.',
    'உலகம் பெற்ற அனைத்துப் ஞானமும் மனத்திலிருந்து வந்தது; பிரபஞ்ச நூலகம் உன் மனத்தில் உள்ளது.',
    'இந்த பூமி வீரர்களால் அனுபவிக்கப்படுகிறது — இது மாறாத உண்மை.',
    'செயலின் பலனைத் துறந்து நன்மையை நன்மைக்காக செய்.',
    'ஒவ்வொரு செயலும் நகைச்சுவை, எதிர்ப்பு, ஏற்றுக்கொள்வது என்ற நிலைகளை கடக்கும்.',
    'அனைத்து கல்வியும் மனிதனை உருவாக்குவதற்கே இருக்க வேண்டும்.',
    'சுயநலமின்மை அதிக பலன் தரும்; அதை கடைப்பிடிக்க பொறுமை தேவை.',
    'போராடுபவன் முயற்சி செய்யாதவனை விட மேல்.',
    'விரிவு வாழ்க்கை; சுருக்கு மரணம்.',
    'தேடாதே; தவிர்க்காதே; வரும் அனைத்தையும் ஏற்று கொள்.',
    'உண்மை எந்த சமூகத்துக்கும் அடிமை அல்ல.',
    'தங்கமாக மாற நெருப்பில் கரைய வேண்டும்.',
    'சிந்தனை, பேச்சு சுதந்திரமே முன்னேற்றத்தின் முதல் நிபந்தனை.',
    'குணநலம், மன வலிமை, அறிவு விரிவு தரும் கல்வி வேண்டும்.',
    'உண்மையான சில உறுதியான மனிதர்கள் ஒரு ஆண்டில் கூட்டம் நூறு ஆண்டில் செய்யாததைச் செய்வார்கள்.',
    'வாழ்க்கையின் ரகசியம் இன்பம் அல்ல; அனுபவத்தின் மூலம் கற்றல்.',
    'பலன் எதிர்பார்ப்பு உள்ள இடத்திலேயே பற்று உருவாகிறது.',
    'சிதைந்து போவதை விட உழைத்து சோர்வது மேல்.',
    'வயது அதிகரிக்கையில் ஆண்மையும் உறுதியும் வாழ்க்கையின் சாரம் என உணர்கிறேன்.',
    'நல்லவனாக இருப்பதும் நன்மை செய்வதும் — அதுவே மதத்தின் முழு சாரம்.',
    'தன்னை வென்றவன் பிரபஞ்சத்தை வென்றவன்.',
    'அனைத்து துன்பமும் பற்றிலிருந்து; அனைத்து வேதனையும் ஆசையிலிருந்து.',
    'பிறருக்காக சேவை செய்து உடலை அர்ப்பணிப்பவர்கள் பாக்கியசாலிகள்.',
    'மனம் தீவிரமாக விரும்பினால் எதுவும் சாத்தியம்.',
    'ஆன்மாவிற்கு பாலின வேறுபாடோ குறையோ இல்லை.',
    'மதம் உணர்வு; பேச்சோ கோட்பாடோ அல்ல.',
    'நாம் என்னவோ அதற்குப் பொறுப்பானவர்கள்; எப்படியாக வேண்டுமோ அப்படியாக ஆகும் சக்தி நமக்குண்டு.',
    'முயற்சி செய்தால் முட்டாளும் ஞானியாகலாம்.',
    'சுதந்திரமாக இருப்பதற்கு துணிந்து, சிந்தனை எங்கு அழைத்துச் செல்கிறதோ அங்கு செல்.',
    'செயலையே வழிபாடாக கருது.',
    'பயங்கரத்தை துணிவுடன் எதிர்கொள்.',
    'நிறைவேற்றம் வரை உயிரையே பணயம் வைக்கும் மனவலிமையை எதுவும் தடுக்க முடியாது.',
    'பிறருள் உன்னை உணர கற்று கொள்.',
    'கட்டுப்பாடற்ற மனம் என்றும் வீழ்ச்சிக்கு இட்டுச் செல்லும்.',
    'நம் இதயத்திலும் அனைத்து உயிர்களிலும் இறைவனை காணவில்லை என்றால் எங்கு தேடுவோம்?',
    'அனைத்து சக்தியும் உன்னுள் உள்ளது; நீ பலவீனன் அல்ல என்பதை நம்பு.',
    'வாழ்வின் முழு ரகசியம் பயமின்மை.',
    'உன் கால்களில் நீயே நில்; மனிதனாக இரு.',
    'இந்த வாழ்க்கை கடினமானது; துணிவுடன் கடந்து செல்.',
    'மனிதனின் உண்மையான மகத்துவம் தன்னலமற்ற தியாகத்தில் உள்ளது.',
    'இருப்பின் ஒற்றுமையை உணர்ந்தவன் எங்கும் இறைவனை காண்கிறான்.',
    'குணநலம் அறிவை விட உயர்ந்தது.',
    'பணியில் ஈடுபட்டால் அனைத்தும் எளிதாகும்.',
    'பயம் தோன்றும் தருணமே அடிமைத்தனம்.',
    'உண்மை ஆயிரம் விதமாக சொல்லப்பட்டாலும் உண்மையே.',
    'கல்வி தகவல் குவிப்பு அல்ல; வாழ்க்கை உருவாக்கும் சிந்தனைகளின் உட்கருத்தாக்கம்.',
    'நாட்டிற்கு தேவையானது வலிமை.',
    'ஒரு எண்ணம் முழு மனத்தையும் ஆட்கொண்டால் அது நிஜமாகிறது.',
    'நீ செய்வதை முழு இதயம், மனம், ஆன்மாவுடன் செய்.',
    'அனைத்து உயிர்களிலும் ஒரே இறைவனை காண்பவனே உண்மையாகக் காண்கிறான்.',
    'இந்த பிரபஞ்சம் ஒரு முடிவற்ற இருப்பு.',
    'நீயாக இருப்பதற்கு துணிந்து இரு.',
    'சுதந்திரம் ஆன்மாவின் பாடல்.',
    'அனைத்து ஞானமும் சுயத்தில் உள்ளது.',
    'முழு உலகமும் இறைவனின் விளையாட்டு அரங்கம்.',
    'யாரையும் காத்திருக்காதே; இயன்றதை செய்; யாரையும் சாராதே.',
    'ஆட்சி செய்ய அல்ல; பிறருக்கு உதவ வாழ்.',
    'நீ உயிரோடு இருந்து செயல்பட முடிகிறது என்பதற்கு நன்றி கொள்.',
    'உன் தெய்வீகத்தை வெளிப்படுத்து.'
  ],
  [
    Article(
        heading: 'Swami Vivekananda: Short life sketch',
        body: 'The great secret of true success, of true happiness, is this: the man or woman who asks for no return, the perfectly unselfish person, is the most successful.” -Swami Vivekananda'

            '\n\nSwami Vivekananda (1863-1902) was one of the most distinguished spiritual leaders of India. As a patriot-saint, he encouraged Indians to serve their country by focusing on the economically disadvantaged. He left behind a legacy of spiritual awakening and national revival.'

            '\n\nIn 1890, Swami Vivekananda set out as a parivrajaka (monastic wanderer) across India. During his two-year sojourn, he became convinced about two things related to India. He saw the future India resplendent and had an action plan for its uplift.'

            '\n\nVivekananda was an instant success at the Parliament of Religions in Chicago. He laid down the basis of cooperation between religions of how it is impossible to impose a single dogma on everyone. Just like plants, a Hindu, Buddhist or Christian "must assimilate the spirit of the others".'

            '\n\nHe visited America from 1893 to 1896, giving lectures in public and private gatherings in the East Coast and Mid-West of America as well as in London.'

            '\n\nOn May 1, 1897, Swami Vivekananda founded the Ramakrishna Mission in Calcutta. His purpose behind setting up this organisation was to spread the teachings of Sri Ramakrishna. The motto of this institution is for one\'s spiritual liberation and the welfare of the world. The Ramakrishna Mission, maintains an impeccable reputation in work related to the spiritual and social welfare of the nation. Swamiji has also inspired the establishment of a number of other organisations, such as the Vivekananda Kendra.'

            '\n\nIn 1899, Swami Vivekananda left for his second trip to the West and reached London on July 31. On July 4, 1902, he finally attained mahasamadhi at Belur Math.'

            '\n\nVivekananda\'s most important work in the West was to sow the seeds of Vedanta. Vedanta is the message of the oneness of Existence; it is derived from the teachings of the Upanishads. Vivekananda underscored the dimension of religious pluralism and universalism.'

            '\n\nHe taught that there is only one reality and that all paths (religions) lead to the same goal (God-realisation).'

            '\n\nVivekananda synthesised the several Yogas (means of spiritual realisation) after reading the Bhagavad Gita. According to him, the four Yogas are diverse ways of achieving the same spiritual objective. He had shown the way for the practical application of the lofty Vedantic ideal of oneness.'

            '\n\nIn his historic speech delivered on 11th September, 1893 in the world parliament of religions, Chicago he spoke about how Hinduism is a religion which has taught the world tolerance and universal acceptance.'

            '\n\nSwami Vivekananda\'s emphasis on service to humanity as a way of both human fulfillment and soul uplift sets him apart from many other religious and spiritual leaders around the world. In fact, the zeal with which he preached this ideal transformed him from pure spirituality to a throbbing empathy for colonial India\'s suffering, poverty-stricken masses.'

            '\n\nSwami Vivekananda’s work and vision had a deep impact not only in India but throughout the globe which was witnessed from his numerous followers and even western disciples like Sister Nivedita, Sister Christine and many others.'

            '\n\nHis legacy will remain eternal.'
    ),
    Article(
        heading: 'Address to World Parliament of Religions',
        body: 'Sisters and Brothers of America, It fills my heart with joy unspeakable to rise in response to the warm and cordial welcome which you have given us. I thank you in the name of the most ancient order of monks in the world; I thank you in the name of the mother of religions; and I thank you in the name of millions and millions of Hindu people of all classes and sects. \n\nMy thanks, also, to some of the speakers on this platform who, referring to the delegates from the Orient, have told you that these men from far-off nations may well claim the honour of bearing to different lands the idea of toleration. I am proud to belong to a religion which has taught the world both tolerance and universal acceptance. We believe not only in universal toleration, but we accept all religions as true. I am proud to belong to a nation which has sheltered the persecuted and the refugees of all religions and all nations of the earth. I am proud to tell you that we have gathered in our bosom the purest remnant of the Israelites, who came to Southern India and took refuge with us in the very year in which their holy temple was shattered to pieces by Roman tyranny. I am proud to belong to the religion which has sheltered and is still fostering the remnant of the grand Zoroastrian nation. I will quote to you, brethren, a few lines from a hymn which I remember to have repeated from my earliest boyhood, which is every day repeated by millions of human beings: “As the different streams having their sources in different places all mingle their water in the sea, so, O Lord, the different paths which men take through different tendencies, various though they appear, crooked or straight, all lead to Thee.” \n\n  The present convention, which is one of the most august assemblies ever held, is in itself a vindication, a declaration to the world of the wonderful doctrine preached in the Gita: “Whosoever comes to Me, through whatsoever form, I reach him; all men are struggling through paths which in the end lead to me.” Sectarianism, bigotry, and its horrible descendant, fanaticism, have long possessed this beautiful earth. They have filled the earth with violence, drenched it often and often with human blood, destroyed civilisation and sent whole nations to despair. Had it not been for these horrible demons, human society would be far more advanced than it is now. But their time is come; and I fervently hope that the bell that tolled this morning in honour of this convention may be the death-knell of all fanaticism, of all persecutions with the sword or with the pen, and of all uncharitable feelings between persons wending their way to the same goal.'

    ),
    Article(
        heading: 'Karma and Its effect on character',
        body:
        'The word Karma is derived from the Sanskrit Kri, to do; all action is Karma. Technically, this word also means the effects of actions. In connection with metaphysics, it sometimes means the effects, of which our past actions were the causes. But in Karma-Yoga we have simply to do with the word Karma as meaning work. The goal of mankind is knowledge. That is the one ideal placed before us by Eastern philosophy. Pleasure is not the goal of man, but knowledge. Pleasure and happiness come to an end. It is a mistake to suppose that pleasure is the goal. The cause of all the miseries we have in the world is that men foolishly think pleasure to be the ideal to strive for. After a time man finds that it is not happiness, but knowledge, towards which he is going, and that both pleasure and pain are great teachers, and that he learns as much from evil as from good. As pleasure and pain pass before his soul they have upon it different pictures, and the result of these combined impressions is what is called man\'s "character". If you take the character of any man, it really is but the aggregate of tendencies, the sum total of the bent of his mind; you will find that misery and happiness are equal factors in the formation of that character. Good and evil have an equal share in moulding character, and in some instances misery is a greater teacher than happiness. In studying the great characters the world has produced, I dare say, in the vast majority of cases, it would be found that it was misery that taught more than happiness, it was poverty that taught more than wealth, it was blows that brought out their inner fire more than praise.\n\nNow this knowledge, again, is inherent in man. No knowledge comes from outside; it is all inside. What we say a man "knows", should, in strict psychological language, be what he "discovers" or "unveils"; what a man "learns" is really what he "discovers", by taking the cover off his own soul, which is a mine of infinite knowledge.\n\nWe say Newton discovered gravitation. Was it sitting anywhere in a corner waiting for him? It was in his own mind; the time came and he found it out. All knowledge that the world has ever received comes from the mind; the infinite library of the universe is in your own mind. The external world is simply the suggestion, the occasion, which sets you to study your own mind, but the object of your study is always your own mind. The falling of an apple gave the suggestion to Newton, and he studied his own mind. He rearranged all  the previous links of thought in his mind and discovered a new link among them, which we call the law of gravitation. It was not in the apple nor in anything in the centre of the earth.\n\nAll knowledge, therefore, secular or spiritual, is in the human mind. In many cases it is not discovered, but remains covered, and when the covering is being slowly taken off, we say, "We are learning," and the advance of knowledge is made by the advance of this process of uncovering. The man from whom this veil is being lifted is the more knowing man, the man upon whom it lies thick is ignorant, and the man from whom it has entirely gone is all-knowing, omniscient. There have been omniscient men, and, I believe, there will be yet; and that there will be myriads of them in the cycles to come. Like fire in a piece of flint, knowledge exists in the mind; suggestion is the friction which brings it out. So with all our feelings and action — our tears and our smiles, our joys and our griefs, our weeping and our laughter, our curses and our blessings, our praises and our blames — every one of these we may find, if we calmly study our own selves, to have been brought out from within ourselves by so many blows. The result is what we are. All these blows taken together are called Karma — work, action. Every mental and physical blow that is given to the soul, by which, as it were, fire is struck from it, and by which its own power and knowledge are discovered, is Karma, this word being used in its widest sense. Thus we are all doing Karma all the time. I am talking to you: that is Karma. You are listening: that is Karma. We breathe: that is Karma. We walk: Karma. Everything we do, physical or mental, is Karma, and it leaves its marks on us.\n\nThere are certain works which are, as it were, the aggregate, the sum total, of a large number of smaller works. If we stand near the seashore and hear the waves dashing against the shingle, we think it is such a great noise, and yet we know that one wave is really composed of millions and millions of minute waves. Each one of these is making a noise, and yet we do not catch it; it is only when they become the big aggregate that we hear. Similarly, every pulsation of the heart is work. Certain kinds of work we feel and they become tangible to us; they are, at the same time, the aggregate of a number of small works. If you really want to judge of the character of a man, look not at his great performances. Every fool may become a hero at one time or another. Watch a man do his most common actions; those are indeed the things which will tell you the real character of a great man. Great occasions rouse even the lowest of human beings to some kind of greatness, but he alone is the really great man whose character is great always, the same wherever he be.\n\nKarma in its effect on character is the most tremendous power that man has to deal with. Man is, as it were, a centre, and is attracting all the powers of the universe towards himself, and in this centre is fusing them all and again sending them off in a big current. Such a centre is the real man — the almighty, the omniscient — and he draws the whole universe towards him. Good and bad, misery and happiness, all are running towards him and clinging round him; and out of them he fashions the mighty stream of tendency called character and throws it outwards. As he has the power of drawing in anything, so has he the power of throwing it out.\n\nAll the actions that we see in the world, all the movements in human society, all the works that we have around us, are simply the display of thought, the manifestation of the will of man. Machines or instruments, cities, ships, or men-of-war, all these are simply the manifestation of the will of man; and this will is caused by character, and character is manufactured by Karma. As is Karma, so is the manifestation of the will. The men of mighty will the world has produced have all been tremendous workers — gigantic souls, with wills powerful enough to overturn worlds, wills they got by persistent work, through ages, and ages. Such a gigantic will as that of a Buddha or a Jesus could not be obtained in one life, for we know who their fathers were. It is not known that their fathers ever spoke a word for the good of mankind. Millions and millions of carpenters like Joseph had gone; millions are still living. Millions and millions of petty kings like Buddha\'s father had been in the world. If it was only a case of hereditary transmission, how do you account for this petty prince, who was not, perhaps, obeyed by his own servants, producing this son, whom half a world worships? How do you explain the gulf between the carpenter and his son, whom millions of human beings worship as God? It cannot be solved by the theory of heredity. The gigantic will which Buddha and Jesus threw over the world, whence did it come? Whence came this accumulation of power? It must have been there through ages and ages, continually growing bigger and bigger, until it burst on society in a Buddha or a Jesus, even rolling down to the present day.\n\nAll this is determined by Karma, work. No one can get anything unless he earns it. This is an eternal law. We may sometimes think it is not so, but in the long run we become convinced of it. A man may struggle all his life for riches; he may cheat thousands, but he finds at last that he did not deserve to become rich, and his life becomes a trouble and a nuisance to him. We may go on accumulating things for our physical enjoyment, but only what we earn is really ours. A fool may buy all the books in the world, and they will be in his library; but he will be able to read only those that he deserves to; and this deserving is produced by Karma. Our Karma determines what we deserve and what we can assimilate. We are responsible for what we are; and whatever we wish ourselves to be, we have the power to make ourselves. If what we are now has been the result of our own past actions, it certainly follows that whatever we wish to be in future can be produced by our present actions; so we have to know how to act. You will say, “What is the use of learning how to work? Everyone works in some way or other in this world.” But there is such a thing as frittering away our energies. With regard to Karma-Yoga, the Gita says that it is doing work with cleverness and as a science; by knowing how to work, one can obtain the greatest results. You must remember that all work is simply to bring out the power of the mind which is already there, to wake up the soul. The power is inside every man, so is knowing; the different works are like blows to bring them out, to cause these giants to wake up.\n\nMan works with various motives. There cannot be work without motive. Some people want to get fame, and they work for fame. Others want money, and they work for money. Others want to have power, and they work for power. Others want to get to heaven, and they work for the same. Others want to leave a name when they die, as they do in China, where no man gets a title until he is dead; and that is a better way, after all, than with us. When a man does something very good there, they give a title of nobility to his father, who is dead, or to his grandfather. Some people work for that. Some of the followers of certain Mohammedan sects work all their lives to have a big tomb built for them when they die. I know sects among whom, as soon as a child is born, a tomb is prepared for it; that is among them the most important work a man has to do, and the bigger and the finer the tomb, the better off the man is supposed to be. Others work as a penance; do all sorts of wicked things, then erect a temple, or give something to the priests to buy them off and obtain from them a passport to heaven. They think that this kind of beneficence will clear them and they will go scot-free in spite of their sinfulness. Such are some of the various motives for work.\n\nWork for work\'s sake. There are some who are really the salt of the earth in every country and who work for work\'s sake, who do not care for name, or fame, or even to go to heaven. They work just because good will come of it. There are others who do good to the poor and help mankind from still higher motives, because they believe in doing good and love good. The motive for name and fame seldom brings immediate results, as a rule; they come to us when we are old and have almost done with life. If a man works without any selfish motive in view, does he not gain anything? Yes, he gains the highest. Unselfishness is more paying, only people have not the patience to practice it. It is more paying from the point of view of health also. Love, truth, and unselfishness are not merely moral figures of speech, but they form our highest ideal, because in them lies such a manifestation of power. In the first place, a man who can work for five days, or even for five minutes, without any selfish motive whatever, without thinking of future, of heaven, of punishment, or anything of the kind, has in him the capacity to become a powerful moral giant. It is hard to do it, but in the heart of our hearts we know its value, and the good it brings. It is the greatest manifestation of power — this tremendous restraint; self-restraint is a manifestation of greater power than all outgoing action. A carriage with four horses may rush down a hill unrestrained, or the coachman may curb the horses. Which is the greater manifestation of power, to let them go or to hold them? A cannonball flying through the air goes a long distance and falls. Another is cut short in its flight by striking against a wall, and the impact generates intense heat. All outgoing energy following a selfish motive is frittered away; it will not cause power to return to you; but if restrained, it will result in development of power. This self-control will tend to produce a mighty will, a character which makes a Christ or a Buddha. Foolish men do not know this secret; they nevertheless want to rule mankind. Even a fool may rule the whole world if he works and waits. Let him wait a few years, restrain that foolish idea of governing; and when that idea is wholly gone, he will be a power in the world. The majority of us cannot see beyond a few years, just as some animals cannot see beyond a few steps. Just a little narrow circle — that is our world. We have not the patience to look beyond, and thus become immoral and wicked. This is our weakness, our powerlessness.\n\nEven the lowest forms of work are not to be despised. Let the man, who knows no better, work for selfish ends, for name and fame; but everyone should always try to get towards higher and higher motives and to understand them. "To work we have the right, but not to the fruits thereof:" Leave the fruits alone. Why care for results? If you wish to help a man, never think what that man\'s attitude should be towards you. If you want to do a great or a good work, do not trouble to think what the result will be.\n\nThere arises a difficult question in this ideal of work. Intense activity is necessary; we must always work. We cannot live a minute without work. What then becomes of rest? Here is one side of the life-struggle — work, in which we are whirled rapidly round. And here is the other — that of calm, retiring renunciation: everything is peaceful around, there is very little of noise and show, only nature with her animals and flowers and mountains. Neither of them is a perfect picture. A man used to solitude, if brought in contact with the surging whirlpool of the world, will be crushed by it; just as the fish that lives in the deep sea water, as soon as it is brought to the surface, breaks into pieces, deprived of the weight of water on it that had kept it together. Can a man who has been used to the turmoil and the rush of life live at ease if he comes to a quiet place? He suffers and perchance may lose his mind. The ideal man is he who, in the midst of the greatest silence and solitude, finds the intensest activity, and in the midst of the intensest activity finds the silence and solitude of the desert. He has learnt the secret of restraint, he has controlled himself. He goes through the streets of a big city with all its traffic, and his mind is as calm as if he were in a cave, where not a sound could reach him; and he is intensely working all the time. That is the ideal of Karma-Yoga, and if you have attained to that you have really learnt the secret of work.\n\nBut we have to begin from the beginning, to take up the works as they come to us and slowly make ourselves more unselfish every day. We must do the work and find out the motive power that prompts us; and, almost without exception, in the first years, we shall find that our motives are always selfish; but gradually this selfishness will melt by persistence, till at last will come the time when we shall be able to do really unselfish work. We may all hope that some day or other, as we struggle through the paths of life, there will come a time when we shall become perfectly unselfish; and the moment we attain to that, all our powers will be concentrated, and the knowledge which is ours will be manifest.'

    ),
    Article(
        heading: 'Swami Vivekananda on India',
        body:
        'Swami Vivekananda’s quotes, comments and sayings—\n\nAll history of Indian life is the struggle for the realisation of the ideal of the Vedanta through good or bad fortune.\n\nAs Western ideas of organization and external civilisation are penetrating and pouring into our country, whether we will have them or not, so Indian spirituality and philosophy are deluging the lands of the West. None can resist it, and no more can we resist some sort of material civilization from the West. A little of it, perhaps, is good for us, and a little spiritualisation is good for the West; thus the balance will be preserved. It is not that we ought to learn everything from the West, or that they have to learn everything from us, but each will have to supply and hand down to future generations what it has for the future accomplishment of that dream of ages — the harmony of nations, an ideal world. Whether that ideal world will ever come I do not know, whether that social perfection will ever be reached I have my own doubts; whether it comes or not, each one of us will have to work for the idea as if it will come tomorrow, and as if it only depends on his work, and his alone. Each one of us will have to believe that every one else in the world has done his work, and the only work remaining to be done to make the world perfect has to be done by himself. This is the responsibility we have to take upon ourselves.\n\nBelieve, believe, the decree has gone forth, the fiat of the Lord has gone forth — India must rise, the masses and the poor are to be made happy.\n\nCome, be men! Come out of your narrow holes and have a look abroad. See how nations are on the march! Do you love your country? Then come, let us struggle for higher and better things; look not back, no, not even if you see the dearest and nearest cry. Look not back, but forward!\n\nEach nation has a main current in life in India it is religion. Make it strong and the waters on either side must move along with it.\n\nGive and take is the law; and if India wants to raise herself once more, it is absolutely necessary that she brings out her treasures and throws them broadcast among the nations of the earth, and in return be ready to receive what others have to give her. Expansion is life, contraction is death. Love is life, and hatred is death. We commenced to die the day we began to hate other races; and nothing can prevent our death unless we come back to expansion, which is life.\n\nGive up jealousy and conceit. Learn to work unitedly for others. This is the great need of our country.\n\nHere in India, it is religion that forms the very core of the national heart. It is the backbone, the bed-rock, the foundation upon which the national edifice has been built.\n\nHere is the blessed land, the foundation, the backbone, the life-centre is religion and religion alone.\n\nI consider that the great national sin is the neglect of the masses, and that is one of the causes of our downfall. No amount of politics would be of any avail until the masses in India are once more well educated, well fed, and well cared for. They pay for our education, they build our temples, but in return they get kicks. They are practically our slaves. If we want to regenerate India, we must work for them. I want to start two central institutions at first — one at Madras and the other at Calcutta — for training young men as preachers. I have funds for starting the Calcutta one. English people will find funds for my purpose.\n\nI discard the idea that India was ever passive.\n\nI have come to this conclusion that there is only one country in the world which understands religion — it is India.\n\nIndia had plenty of spirituality, so much so that her spiritual greatness made India the greatest nation of the then existing races of the world; and if traditions and hopes are to be believed, those days will come back once more to us, and that depends upon you.\n\nIn India the mother is the centre of the family and our highest ideal. She is to us the representative of God, as God is the mother of the Universe.\n\nIn philosophy, we are even now head and shoulders above any other nation, as Schopenhaeur, the great German philosopher, has confessed\n\nIndia can never be Europe until she dies.\n\nIndia I loved before I came away. Now the very dust of India has become holy to me, the very air is now to me holy; it is now the holy land, the place of pilgrimage, the tirtha.\n\nIndia is India.\n\nIndia sets the example of real strength, that is meekness.\n\nIndia’s doom was sealed the very day they invented the word mleccha and stopped from communication with others.\n\nIndia’s heart must break, and the flow of spirituality will come out.\n\nIndia’s potentialities are great and will be called forth.\n\nIndia’s theme is religion. Social reform and everything else are secondary.\n\nLet each one of us pray day and night for the downtrodden millions in India who are held fast by poverty, priestcraft, and tyranny— pray day an night for them. I care more to preach religion to them than to the high and the rich. I am no metaphysician, no philosopher, nay, no saint. But I am poor, I love the poor.\n\nNational union in India must be a gathering up of its scattered spiritual forces. A nation in India must be a union of those whose hearts beat to the same spiritual tune.\n\nNowhere has activity been more pronounced than in this blessed land of ours, and the great proof of this activity is that our most ancient and magnanimous race still lives, and at every decade in its glorious career seems to take on fresh youth — undying and imperishable.\n\nOne thing I must tell you. Idolatry in India does not mean anything horrible. It is not the mother of harlots. On the other hand, it is the attempt of undeveloped minds to grasp high spiritual truths. The Hindus have their faults, they sometimes have their exceptions; but mark this, they are always for punishing their own bodies, and never for cutting the throats of their neighbours. If the Hindu fanatic burns himself on the pyre, he never lights the fire of Inquisition. And even this cannot be laid at the door of his religion any more than the burning of witches can be laid at the door of Christianity.\n\nPolitical greatness or military power is never the mission of our race; it never was, and, mark my words, it never will be.\n\nPriestcraft is the bane of India. Can man degrade his brother and himself escape degradation?\n\nReligion is the one and sole interest of the people of India.\n\nReligion is the peculiarity of the growth of the Indian mind.\n\nRemember that the nation lives in the cottage. But, alas! nobody ever did anything for them.\n\nShe is awakening, this motherland of ours, from her deep long sleep. None can desist her any more; never is she going to sleep any more; no outward powers can hold her back any more; for the infinite giant is rising to her feet.\n\nThe chief cause of India’s ruin has been the monopolizing of the whole education and intelligence of the land, by dint of pride and royal authority, among a handful of men.\n\nThe eyes of the whole world are now turned towards this land of India for spiritual food; and India has to provide it for all the races. Here alone is the best ideal for mankind; and Western scholars are now striving to understand this ideal which is enshrined in our Sanskrit literature and philosophy, and which has been the characteristic of India all through the ages.\n\nThe history of our race shows that India has always been most active.\n\nThe Indian mind is first religious, then anything else.\n\nThe one thing that is at the root of all evils in India is the condition of the poor.\n\nThe only hope of India is from the masses. The upper classes are physically and morally dead. . . .\n\nThe poor, the low, the sinner in India have no friends, no help — they cannot rise, try however they may. They sink lower and lower every day, they feel the blows showered upon them by a cruel society, and they do not know whence the blow comes. They have forgotten that they too are men.\n\nThough centuries of neglect on our part and contempt on the part of our conquerors have visibly dimmed the glories of ancient Āryâvarta, though many a stately column on which it rested, many a beautiful arch, and many a marvellous corner have been washed away by the inundations that deluged the land for centuries — the centre is all sound, the keystone is unimpaired. The spiritual foundation upon which the marvellous monument of glory to God and charity to all beings has been reared stands unshaken, strong as ever.\n\nTo my mind, the one great cause of the downfall and the degeneration of India was the building of a wall of custom — whose foundation was hatred of others — round the nation, and the real aim of which in ancient times was to prevent the Hindus from coming in contact with the surrounding Buddhistic nations.\n\nWe have had a negative education all along from our boyhood. We have only learnt that we are nobodies. Seldom are we given to understand that great men were ever born in our country. Nothing positive has been taught to us. We do not even know how to use our hands and feet! We master all the facts and figures concerning the ancestors of the English, but we are sadly unmindful about our own. We have learnt only weakness. Being a conquered race, we have brought ourselves to believe that we are weak and have no independence in anything. So, how can it be but that the Shraddha is lost? The idea of true Shraddha must be brought back once more to us, the faith in our own selves must be reawakened, and, then only, all the problems which face our country will gradually be solved by ourselves. \n\nWe know that to the Indian mind there is nothing higher than religious ideals, that this is the keynote of Indian life.\n\nWhat India wants is a new electric fire to stir up a fresh vigour in the national veins.\n\nWhen the real history of India will be unearthed, it will be proved that, as in matters of religion, so in fine arts, India is the primal Guru of the whole world.\n\n'
    ),
  ],
);
