// yogananda_ta.dart
// பரமஹம்ச யோகானந்தா மேற்கோள்கள் மற்றும் கட்டுரைகள்

import '../articlesquotes.dart';

final yoganandaSaintTa =   Saint(
  'yogananda',
  'பரமஹம்ச யோகானந்தர்',
  'assets/images/paramhansa.jpg',
  [
    'சாதாரணமாக ஓட விடாதே உன் வாழ்க்கையை; பிறர் செய்யாத ஒன்றைச் செய்—உலகையே மெய்மறக்கச் செய்யும் ஒன்றை.',
    'தோல்வியின் காலமே வெற்றியின் விதைகளை விதைக்க உகந்த காலம்.',
    'எவ்வளவு எளிமையாக முடியுமோ அவ்வளவு எளிமையாக இரு; வாழ்க்கை எவ்வளவு சிக்கலற்றதும் ஆனந்தமுமானதுமாக மாறுகிறது என்பதைப் பார்த்து ஆச்சரியப்படுவாய்.',
    'இக்கணத்தில் அமைதியாக வாழ்; முன் நிற்கும் அனைத்தின் அழகையும் காண். எதிர்காலம் தன்னைத் தானே பார்த்துக்கொள்ளும்.',
    'தன் இதய ஆனந்தம் மட்டும் ஆன்மாவை நிறைவு செய்யாது; பிறரின் மகிழ்ச்சியும் தன் மகிழ்ச்சியின் அங்கமாக வேண்டும்.',
    'உன்னை மாற்றிக்கொள்; உலகை மாற்றுவதில் உன் பங்கை நிறைவேற்றியதாகும்.',
    'தொடர்ச்சியான முயற்சி முடிவை தவிர்க்க முடியாததாக ஆக்குகிறது.',
    'அமைதியாகவும் சாந்தமாகவும் தன்னடக்கத்தில் இரு; அப்பொழுது வாழ்க்கை எவ்வளவு எளிதென அறியுவாய்.',
    'என் ஆன்மா இதயத்தில் புன்னகைக்க, இதயம் கண்களில் புன்னகைக்கட்டும்; துயர்ந்த இதயங்களில் ஆனந்தப் புன்னகையைப் பரப்ப.',
    'நிறைவேறாத ஆசைகளின் சக்தியே மனித அடிமைத்தனத்தின் வேர்.',
    'மகிழ்ச்சி சொத்துகளின் நிலைமையில் அல்ல; மனத்தின் நிலையில்தான்.',
    'வெற்றியும் ஆனந்தமும் உள்ளேயே உள்ள ரகசியம்; வெளியில் செல்வம் இருந்தும் உள்ளே இல்லையெனில் உண்மை வெற்றி இல்லை.',
    'அமைதி ஆன்மாவிலிருந்து வெளிப்படுகிறது; அதுவே உண்மையான ஆனந்தம் மலரும் புனித உள் சூழல்.',
    'உள் அமைதி இல்லாமல் செல்வம் குவித்தல், கடலில் குளித்தபடியே தாகத்தால் சாவதைப் போன்றது.',
    'உண்மையான வெற்றியாளர் தன் கொள்கைகளின்படி வாழும் திருப்தியுடனான ஆனந்த மனிதன்.',
    'உண்மை அமைதியும் மகிழ்ச்சியும் உன் உள்ளே கண்டடைய வேண்டும்; வெளி அனுபவங்கள் விளையாட்டாக இருக்கட்டும்.',
    'உல்லாசம் அடைவது எளிது; அமைதியான ஆனந்தத்தில் நிலைத்திருப்பதே கடினம்—அதுவே இலக்கு.',
    'ஒவ்வொரு இக்கணத்தையும் முழுமையாக வாழ்; எதிர்காலம் தானே கவனிக்கும்.',
    'அமைதியின் இருப்பில் நீ அதிகம் பயிற்சி பெறும்போது, அதன் சக்தி வாழ்க்கையில் வெளிப்படும்.',
    'இருப்பின் முழு ரகசியம்—பயம் இல்லாதிருத்தல்.',
    'கருணை ஆன்மாக்கள், குடும்பங்கள், தேசங்கள் இடையிலான சுவர்களை கரைக்கும் ஒளி.',
    'அளவில்லா சொத்துகளைக் காட்டிலும் சிறு ஆனந்தமே மேலானது.',
    'நீ ஏற்றுள்ள பாத்திரம் உன் உண்மையான இருப்பை மாற்றாது என்பதை உணர்.',
    'மனித உழைப்பின் உயர்ந்த பலன் கிடைப்பது அல்ல; அதனால் அவன் ஆகிறதுதான்.',
    'ஆன்மீக விழிப்பின் ஆசீர்வாதங்களுக்கு நீ தகுதியானவன்.',
    'தியானப் பயிற்சியால் இதயத்திற்குள் எடுத்துச் செல்லும் சொர்க்கத்தை உணர்வாய்.',
    'ஆன்மா தியானத்தை நேசிக்கிறது; ஏனெனில் ஆவியுடன் இணைதலில்தான் அதன் உச்ச ஆனந்தம்.',
    'தியானம் உடல் பந்தத்திலிருந்து ஆன்மாவை மீட்டெடுக்கும் உன்னத வழி.',
    'தியானம் தெய்வ அமைதி ஆன்மாவுக்குள் பொங்கும் ஊற்று.',
    'நீண்ட நேரம் அலைக்கும் மனத்துடன் தியானிப்பதைவிட, குறுகிய நேரம் ஆழமாய் தியானிப்பது மேல்.',
    'அமைதியாக இரு; நான் இறைவன் என்பதை உணர்.',
    'உச்ச முயற்சி செய்கிற பக்தனே இறைவனை அடைகிறான்; காரணங்கள் தேடுபவன் அல்ல.',
    'தியானத்தில் எங்கும் அவரை நோக்கிய கதவுகள் திறக்கும்.',
    'இறைவனை அடைய ஆவலோ அவசரமோ வேண்டாம்; சாந்தத்துடன் பொறுமையாக முன்னேறு.',
    'மனம் ஒரு சல்லடை போல்; அதனூடே உலகளாவிய அறிவு விழிப்புணர்வில் பாய்கிறது.',
    'நீ இறைவனை எவ்வளவு நேசிக்கிறாயோ, அவ்வளவு அனைவரையும் நேசிக்க வல்லவனாவாய்.',
    'எதையும் பெற முடியாதவர்களை ஒருவர் எப்படி நடத்துகிறார் என்பதே குணநலனின் அளவுகோல்.',
    'விருப்பம்போல் செய்யாதே; அப்பொழுது விருப்பமானதைச் செய்யலாம்.',
    'வெற்றியும் ஆனந்தமும் உள்ளேயே உள்ள ரகசியம்.',
    'பற்றுகளிலிருந்து விடுபடாமல் உண்மை மகிழ்ச்சி இல்லை.',
    'அன்பு எதிர்பார்ப்பின்றி அளிக்கிறது.',
    'அன்புக்குரியவரின் பரிபூரணத்தையே விரும்பி, அவரை நினைப்பதில் தூய ஆனந்தம் காண்பதே தெய்வீக அன்பு.',
    'அன்பே ஆன்மாக்களுக்கிடையிலான எல்லாச் சுவர்களையும் கரைக்கும் ஒளி.',
    'தியானத்தில் இறைவனுடன் ஒன்றுதலில்தான் உச்ச அன்பு அனுபவம்.',
    'இழந்த அன்புக்காக வருந்தாதே; அன்பு இழப்பதில்லை—பல இதயங்களில் ஒளிந்து விளையாடுகிறது.',
    'அன்பை ஒருமுறை அளித்தால் அது நிரந்தரம்; அருகாமைக்காக அல்ல, ஆன்மப் பரிபூரணத்திற்காக.',
    'முழு உலகமே ஆன்மாவின் விளையாட்டு மைதானம்.',
    'அவருடன் இணைவு பெற்றால் உலகத்தின் எந்தச் சிதைவும் அந்த ஆனந்தத்தைப் பறிக்க முடியாது.',
    'இறைவனின் எல்லையற்ற அன்பில் என் நித்திய இதயம் அனைத்தையும் தாங்கும்.',
    'என் இதயம் நித்திய அன்பின் ஆலயம்.',
    'உண்மையான நண்பனாக இருக்க, பிறரை உன்னைப் போல நேசி.',
    'அன்பு உணர்ச்சி அல்ல; படைப்பின் மையச் சத்தியம்.',
    'இறைவனின் அன்பு அனைத்தையும் விழுங்கும் அன்பு.',
    'பகலும் இரவும் இறைவன் அன்பில் மயங்கிவிடு.',
    'ஆன்மாவுக்கும் ஆவிக்கும் இடையிலான அன்பே பரிபூரண அன்பு.',
    'மரணமுள்ளவராய் நீ வரையறுக்கப்பட்டவன்; இறைவனின் பிள்ளையாய் எல்லையற்றவன்.',
    'மனித மனம் இறை விழிப்பின் ஒரு சுடர்.',
    'உன் எண்ணங்களே உன்னை உருவாக்குகின்றன.',
    'தீய எண்ணங்களில் திளைத்தால் நீயும் அருவருப்பாவாய்.',
    'உன்னுள் இருக்கும் இறை சக்தி, அதீத மனத்தில் உறைகிறது.',
    'மரணத்திற்கு பின்பும் நீ மாறுவதில்லை; உடலை மட்டும் விட்டு விடுகிறாய்.',
    'மனம் உலகை வெல்லக் கூடிய சக்தி.',
    'மரணம் உன்னைச் சீர்படுத்தும் என நம்பாதே.',
    'உன் விருப்பங்களை நிறைவேற்றும் சக்தி உன் மனவலிமையில் உள்ளது.',
    'மனம் பைத்தியக்குரங்கு; மனவலிமை அதை கட்டும் கயிறு.',
    'உண்மையான சுய ஆய்வே முன்னேற்றத்தின் உச்சக் கலை.',
    'தோல்வியின் காலமே வெற்றியின் விதைப்புக் காலம்.',
    'எண்ணங்களே நம்மை உருவாக்குகின்றன.',
    'கவனம் அதிகமானால் சாதனை எளிதாகும்.',
    'மனத்தை வெல்வதே விடுதலை.',
    'மரணம் அழகானது; தீமையெனில் இறைவன் அனுமதிக்கமாட்டான்.',
    'நோய்–ஆரோக்கியம், துயர்–மகிழ்ச்சி என்ற மாயையைக் கடந்து அகமாக இரு.',
    'அனைத்து ஆன்மாக்களும் இறைவனிலிருந்து தோன்றி மீண்டும் பரிபூரணத்துக்கே வளர்கின்றன.',
    'அலை கடலின் ஒரு பகுதி; படைப்பு அனைத்தும் ஆவிக் கடலின் அலைகள்.',
    'வாழ்க்கை குறுகியது; பிறருக்காக வாழ்வதே உண்மை வாழ்வு.',
    'மிகப் பெரிய போர் உன் மனத்துடனானதே.',
    'இன்றைய நாள் நாளைய நாளை தீர்மானிக்கிறது.',
    'எதற்கும் அஞ்சாதே; அனைவருக்கும் அன்பளி.',
    'பிரகாசமான எண்ணங்களைவிட அன்றாட பழக்கங்களே வாழ்க்கையை நடத்துகின்றன.',
    'தன் இலக்கை அறிந்த உறுதியானவனுக்கு உலகம் வழிவிடும்.',
    'எதையும் செய்ய முடியாதவர்களை நடத்தும் விதமே குணநலன்.',
    'எண்ணம் ஆகிறது; உணர்வு ஈர்க்கிறது; கற்பனை படைக்கிறது.',
    'வாழ்க்கைப் போட்டியில் வீரனாக இரு; உண்மைப் போட்டி உள்ளே.',
    'ஆழ்ந்த தியானச் செயலால் மன அலைச்சலை நீக்கு.',
    'முழுமையான ஆரோக்கியமும் ஆனந்தமும் மனக் கட்டுப்பாட்டில்தான்.',
    'பிறவிகளின் வழியாக உருவாக்கிய விழிப்புணர்வே நீ.',
    'கர்மம் தண்டனை அல்ல; காரண–விளைவு நீதிநியமம்.',
    'தன் பாதையைத் தேர்வுசெய்வதும் அதன் விளைவுகளை ஏற்கவும் மனிதன் பொறுப்பான்.',
    'உன் விதி உன் கைகளில் உள்ளது.',
    'மனவலிமை உன்னுள் இருக்கும் இறை உருவத்தின் கருவி.',
    'வலுவான சித்தம் தன் நிறைவை உருவாக்குகிறது.',
    'மனவலிமையை நன்மைக்கே பயன்படுத்து.',
    'உன் வாழ்க்கை சீரற்றது அல்ல; உன் உருவாக்கம்.',
    'வாழ்க்கையின் நோக்கம்—பிறருக்காகவும் இறைவனில் வாழ்வதும்.',
    'தன்னை பலவீனன் என எண்ணுவதுவே பெரும் பாவம்.',
    'பிரபஞ்சமே அவரது ஆலயம்.',
    'இந்த வாழ்க்கையின் நிழல்களுக்கு அடியில் அவரது அதிசய ஒளி உள்ளது.',
    'ஆன்மா உடலில் இல்லை; உடல் ஆன்மாவில் உள்ளது.',
    'அனைத்தும் இறை; அனைத்தும் ஒன்று.',
    'பொருள் உலகம் கனவு; மனத்தால் மாற்றக் கூடிய கனவு.',
    'உலகம் நம்மை வலுப்படுத்தும் பெரிய பயிற்சியகம்.',
    'தனித் தன்மையின் மாயையே துன்பத்தின் வேர்.',
    'நீ நித்திய ஆவிக் கடலின் ஒரு அங்கம்.',
    'தியானம் அதிகமானால் நீ உடல் அல்ல என்பதை உணர்வாய்.',
    'வாழ்க்கையின் உண்மை அர்த்தம்—இறைவனுடன் ஒன்றாக இருப்பதை உணர்தல்.',
    'பிறருக்கு நன்மை செய்வத록 இதயம் சுத்தமாகும்.',
    'உன்னிடம் உள்ள சிறந்ததை உலகிற்கு அளி.',
    'செல்வ விதி சுயநலமல்ல; தன்னலமற்ற தன்மை.',
    'எதிர்பார்ப்பில்லாதவனே உண்மையில் வெற்றியாளர்.',
    'பிறரைச் சேவிப்பதே இறை சேவை.',
    'கிரியா யோகம் மனத்தைக் கட்டுப்படுத்தி அனந்தத்தை அணுகும் அறிவியல் வழி.',
    'கிரியா பயிற்சியின் பலன்—உச்ச அமைதியும் ஆனந்தமும்.',
    'தியான ஆனந்தம் ஆயிரம் நித்திரைகளின் ஓய்வை தருகிறது.',
    'அகசாட்சாத்காரமே சத்தியத்துடன் ஒன்றாதல்.',
    'இந்த ஆன்மீக பாதையில் எந்த முயற்சியும் வீணாகாது.',
    'சிறிதளவு உண்மை தர்மமே பெரும் பயத்திலிருந்து காக்கும்.',
    'யோகம் கருத்தை அனுபவமாக மாற்றும் உறுதியான பாதை.',
    'பொருள் உலகில் பலன் வெளிப்படை; ஆன்மீகத்தில் அது நுட்பமானது.',
    'ஆன்மீகப் பலன் விழிப்புணர்வில் நுட்ப மாற்றங்களாகத் தொடங்கும்.',
    'உண்மை மதம் நோய், துன்பம், அறியாமை ஆகியவற்றிலிருந்து நிரந்தரப் பாதுகாப்பு.',
    'கடந்ததை மற; தெய்வத்தில் நிலைபெறாத நடத்தை நிலையற்றது.',
    'இக்கணத்தில் ஆன்மீக முயற்சி இருந்தால் எதிர்காலம் உயரும்.',
    'நீ எப்போதும் ஆவியின் பரிபூரண பிரதிபலிப்பு.',
    'அமரனாகிய நீ பூமி எல்லைகளால் உன்னைச் சுமத்தாதே.',
    'தியானம் ஆன்மாவுடன் ஒன்றுதல்.',
    'தியானம் இறைவன் இருப்பின் சான்று.',
    'பயிற்சியற்ற பார்வைக்கு தெய்வ ஒளி புலப்படாது.',
    'இறைவன் எல்லையற்றவன்; எல்லா ரூபங்களிலும் உறைகிறான்.',
    'உயிர்களுக்கிடையே உண்மை வேறுபாடு இல்லை.',
    'வேற்றுமை ஒரே மனத்தின் ஒன்றுமையிலிருந்து தோன்றுகிறது.',
    'விடுதலையடைந்தவன் அனைத்திலும் இறைவனைப் பார்க்கிறான்.',
    'இறைவன் விழிப்புணர்வே.',
    'சத்–சித்–ஆனந்தம்—நித்தியம், அறிவு, ஆனந்தம்.',
    'இறைவன் அனைவரின் ஆன்மாவாக இருந்தும் படைப்பில் சிக்கவில்லை.',
    'ஒரே விழிப்புணர்வு அனைத்தாக மாறுவதை அறிதலே ஞானம்.',
    'மாறுபடும் பொருட்களுக்காக ஞானிகள் வருந்தார்.',
    'உடல் அடையாளத்திலிருந்து விடுதலையில் அமைதி கிடைக்கும்.',
    'மாற்றங்களைக் கண்டு அசையாததே பரிபூரண நிலை.',
    'மாற்றங்களோடு ஒன்றுதலே துன்பம்.',
    'நித்திய ஆனந்தம் பொருள்களில் இல்லை; அமர ஆவியில் தியானத்தில் உள்ளது.',
    'நவீன வாழ்க்கை ஆசைகளையும் கவலைகளையும் பெருக்குகிறது.',
    'இந்த உலகில் பாதுகாப்பு இல்லை.',
    'மாறும் வடிவங்களில் சாரம் நிலைத்திருக்கிறது.',
    'மனித ஆன்மாவும் பிரபஞ்ச ஆன்மாவும் நித்தியம்.',
    'முதலில் தவறான பழக்கங்களை விடு; பின் நன்மையை வளர்த்து.',
    'முயற்சி தொடர்ந்தால் முன்னேற்றம் உறுதி.',
    'ஒருபோதும் கைவிடாதே.',
    'ஒவ்வொரு ஆன்மீக எண்ணமும் நித்திய நண்பன்.',
    'தீய வாசனை எதிரியாகும்.',
    'பொருள்–ஆன்மீக கடமைகளின் சமநிலையே உச்ச ஆனந்தம்.',
    'விழிப்புணர்வை பயிற்சியால் விடுவி.',
    'உடல் அலைச்சலை விட்டு உயர் ஆற்றலை நோக்கு.',
    'தற்கால இன்பத்தை மறுத்து நித்திய ஆனந்தத்தைத் தேர்வு செய்.',
    'உன்னை உடலென நினைக்காதே; ஆனந்த விழிப்புணர்வென நினை.',
    'உள்ளே உணராத சத்தியம் உனக்குச் சத்தியமல்ல.',
    'ஆன்மீக விழிப்பு அகசாட்சாத்காரத்தில்தான்.',
    'கோப்பை பெரிதாகினால்தான் கடல் அடையும்.',
    'பெறுதல் என்பது வளர்த்துக்கொண்ட திறன்.',
    'பலவீனத்தை விட்டு அரசப் பாதையில் எழு.',
    'மற்றவை காத்திருக்கலாம்; இறை தேடல் காத்திருக்காது.',
    'இவை உரைகள் அல்ல; விடுதலை தரும் சத்தியங்கள்.',
    'கிரியா யோகம் மனத்தை அமைதிப்படுத்தி அனந்தத்துடன் இணைக்கிறது.',
    'தியான ஆனந்தம் உறக்கத்திற்கும் அப்பால்.',
    'ஆனந்தம் வெளி நிகழ்வின் விளைவு அல்ல.',
    'உண்மை மதம் தெய்வ சத்தியத்தின் நேரடி அனுபவம்.',
    'ஆன்மீக முயற்சி பயத்திலிருந்தும் காக்கும்.',
    'ஆன்மீகப் பயன் நுட்பமானதாயினும் நித்தியம்.',
    'தெய்வத்தில் நிலை பாதுகாப்பை அளிக்கும்.',
    'தியானம் உள்ளுணர்வைத் திறக்கிறது.',
    'தெய்வ இருப்பு நுண்ணியது.',
    'பல ரூபங்கள் ஒரே தெய்வத்தால் தாங்கப்படுகின்றன.',
    'ஒன்றுமையை உணர்வதே விடுதலை.',
    'பொருள்கள் மறையும்; ஆன்மீக உணர்வே நிலைக்கும்.',
    'அமரத்துவமே ஆன்மாவின் இயல்பு.',
    'படைப்பின் சாரம் விழிப்புணர்வே.',
    'உண்மை ஞானம் உள்ளுணர்வில் நிலைக்கிறது.',
    'நித்தியத்தில் நிலைத்தால் மன அலைச்சல் மறையும்.',
    'மாற்றச் சுழற்சி ஆவியில் நிலைத்தவரை ஆளாது.',
    'ஆன்மீக அமைதிக்கான ஏக்கம் ஆழ்ந்தது.',
    'அமைதி அனுபவம் ஆன்மீக நிலையில் சார்ந்தது.',
    'ஞானியின் நிலைத்த முயற்சியே அவன் வெற்றி.',
    'ஒவ்வொரு ஆன்மீக எண்ணமும் நித்திய அமைதியின் அடித்தளம்.',
    'தெய்வ சத்தியத்தில் நிலை முன்னேற்றம்.',
    'தவறான எண்ணங்கள் வெல்லப்படும் வரை பகை.',
    'பொருள்–பக்தி இசைவில்தான் உச்ச ஆனந்தம்.',
    'உடல் அடையாளத்தைத் தாண்டும் பயிற்சியே விடுதலை.',
    'தொடர் தியானத்தில் உயர் நிலை பிறக்கும்.',
    'தெய்வ ஆனந்தத் தேர்வே விடுதலை விதி.',
    'மரண அடையாளம் மாயை.',
    'உள்ளே உணர்ந்தால்தான் சத்தியம் மாற்றும்.',
    'இறை உணர்வே உச்ச நோக்கம்.',
    'திறன் விரிவே ஆன்மீக வளர்ச்சி.',
    'நம்பிக்கை அல்ல; உணர்தலே விடுதலை.',
    'ஆன்மீகப் பாதை அரசப் பாதை.',
    'இறை தேடல் முதன்மை.',
    'இவை உயிர்ப்பூட்டும் சத்தியங்கள்.',
    'தியானம் ஒவ்வொரு கணத்தையும் அமரத்திற்கான படியாக மாற்றுகிறது.',
    'ஆனந்தம் இறை இருப்பின் உள்ளுணர்வு.',
    'வாழ்க்கையிலேயே விழிப்புணர்வை மாற்றுவதுதான் ஆன்மீகம்.',
    'ஒவ்வொரு ஆன்மீக நிமிடமும் அமைதியை விரிவாக்கும்.',
    'மனிதனுள் உள்ள தெய்வச் சுடரே முடிவற்ற அமைதியின் மூலம்.',
    'விழிப்புணர்வு உள்ளே திரும்பினால் வளர்ச்சி வேகமாகும்.',
    'மன அலைச்சல் ஆன்ம இயல்பை மறைக்கும் திரை.',
    'தியான மௌனத்தில் ஆன்மா நித்திய சத்தியத்தைப் பேசுகிறது.',
    'உண்மை அமைதி சூழ்நிலைகளைத் தாண்டியது.',
    'ஒவ்வொரு ஆன்மீக வெற்றியும் தெய்வ இணைப்பை வலுப்படுத்தும்.',
    'தெய்வ இருப்பு நுண்ணதாயினும் நிலைத்தது.',
    'பிரபஞ்சம் தெய்வ விழிப்பின் வெளிப்பாடு.',
    'பயம் தெய்வ அகத்தில் நிலைபெறும்போது நீங்கும்.',
    'தியானம் ஆன்மாவின் அமர இயல்பை வெளிப்படுத்துகிறது.',
    'நித்திய ஆனந்தமே உண்மையான சாதகனின் இறுதி உணர்வு.'
  ],
  [
    Article(
        heading: 'God alone',
        body: 'Who is it who knows all the secrets of all the Souls who ever lived, dazzling the world, and who are now lost and gone?\n\nGod alone! God alone!\n\nWho lived in the loneliness of the eternal void, before the atoms blinked their glittering eyes and danced through all Creation?\n\nGod alone! God alone!\n\nWe came out of Something, we know not what. We know that we live, laugh, and linger now, and most of us will not know what lies in the wilderness of the great Beyond when we fall asleep in the arms of peaceful death. Yet, who knows the secret of Life, both before and after this existence?\n\nGod alone! God alone!\n\nAll things are living; all things are dancing in the rhythm of eternal harmony. No one knows about the grand procession of Creation, which emerged from the mystic chamber of space. No one knows which part of this chamber of the endless void is occupied by objects and Beings, melted by the magic wand of death, except –\n\nGod alone! God alone!\n\nOur loved ones love us, and vow to love us forever, and yet they forget us when they sink into the Great Sleep. Their memories become frozen anon. Yet, who loves us forever without ever telling us, and who remembers us when all others forget us?\n\nGod alone! God alone!\n\nLife and death, stars and wind, love and hate, sorrow and pleasure, and man and beast dance and sleep on the Stygian stage of Time, hiding behind the scenes at death, and coming out to play again on the stage of Time in new costumes of flesh. No one remembers what he did before, or why he is so sure of this temporary rendezvous in this curious caravanserai except –\n\nGod alone! God alone!\n\nWhy God is playing this game, and why He keeps all this knowledge to Himself, only meagerly sharing it with us, His Children, is known by –\n\nGod alone! God alone!\n\nYet, if you roam no more, and come closer to the Infinite Shore within, and change yourself from the undesirable position of being a prodigal son to that of being a true celestial offspring, then you, too, may know all things that you want to know from none other than –\n\nGod alone! God alone!\n\nSince He knows all things, when you change into a demanding Son Divine, you too shall know all things from –\n\nGod alone! God alone!\n\nWhen all friends must leave you, who will be with you?\n\nGod alone! God alone!\n\nSince no things and no one are really yours, learn to love –\n\nGod alone! God alone!'
    ),
    Article(
        heading: 'Acquiring Happiness',
        body: 'Paramhansa Yogananda, November 1936:\n\nWe can never be happy unless we are progressing and seeking satisfaction in doing so, and unless we are guarding our happiness from all the influences which destroy it. Happiness comes, not by helplessly thinking, but by living it in all the moods and actions of life. No matter what you are doing, keep the undercurrent of happiness, the secret river of joy, flowing beneath the sands of various thoughts and the rocky soils of hard trials. Learn to be secretly happy within your heart in spite of all circumstances, and say to yourself, “Happiness is my greatest Divine birthright — the buried treasure of my Soul. I have found that at last I shall secretly be rich beyond the dream of Kings.”\n\nDo not make unhappiness a chronic habit, for it is anything but pleasant to be unhappy, while it is blessedness for yourself and others when you are happy. When it is so easy to wear a silver smile, or to pour sweet happiness through your voice, why be grouchy and scatter unhappiness around you? It is never too late to learn.\n\nHappiness grows by what it is fed on. Learn to be happy by being happy all the time. John said, “If I get money, I shall be happy.” He became wealthy; then he said, “I shall be happy if I get rid of my acute indigestion.” His indigestion was cured, but he thought, “If I get a wife, I shall be happy.” Then bedlam started, for he married a nagging, tongue-lashing woman. He divorced this wife, and after many years married again, but the second wife was worse than the first one. Then he thought that he would be happier if he divorced his second wife, so he did, but at the age of seventy he thought, “No, I shall never be happy unless I can be youthful again.” In this way people try but never reach their goal of happiness. They are like the man who raced in anger to bite his own nose, but never could, of course.\n\nIgnorant people, like animals, do not heed the lessons which accompany pain and pleasure. Most people live a life checkered with sadness and sorrow, for they do not avoid the actions which lead to suffering and do not follow the ways which lead to happiness. Then there are people who are always consciously over-sensitive to sorrow and happiness when they come. Such people are usually extremely crushed by sorrow and are overwhelmed by joy, thus losing their mental balance. There are very few people who, after burning their fingers in the fire of ignorance, learn to avoid misery-making acts.\n\nMany people wish to be happy, and yet they never make the effort to adopt the course of action which leads to happiness. Most people keep rolling down the hill of life only mentally wishing to climb the peak of happiness. They sometimes wake up if their enthusiasm for happiness survives the crash to the bottom of suffering. Most people lack imagination and never wake up until something terrible happens to arouse them from their nightmare of folly.\n\nStagnant people are unhappy, and extremely ignorant people scarcely know how it feels to be either happy or unhappy. They are unfeeling, like the stones. It is better to be unhappy about your own ignorance than to die happily with it. Wherever you are, remain awake and alive with your thought, perception, and intuition, ever ready, like a good photographer, to take pictures of exemplary conduct and to ignore bad behavior. Your highest happiness lies in your being ever ready in desiring to learn and in behaving properly.\n\nPeople seeking happiness must avoid the influence of bad habits which lead to evil actions, for evil actions produce misery sooner or later. Misery corrodes the body, mind, and soul like a silently burning acid, and cannot be endured long. That is why it should be strictly avoided.\n\nCure yourself of evil habits by cauterizing them with the opposite good habits. If you have a bad habit of telling lies, and by so doing have lost many friends, start the opposite good habit of telling the truth. It takes time to form a good habit or a bad one. It is difficult for a bad person to be good and for a good person to be bad; yet, remember that once you become good, it will be natural and easy for you to be good; likewise, if you cultivate an evil habit, you will be compelled to be evil in spite of your desire, and you have to pray, “Father, my Spirit is willing, but my flesh is weak.” That is why it is worth-while to cultivate the habit of being happy.\n\nThe man sliding down evil paths finds no resistance; but as soon as he tries to oppose his evil habits by the adoption of spiritual laws of discipline, he finds countless temptations roused to fight and foil his noble efforts.\n\nDo Not Judge Others\n\nYour individual happiness depends to large extent upon protecting yourself and your family from the evil results of gossiping. See no evil, speak no evil, hear no evil, think no evil, feel no evil. Most people can talk about other people for hours and thrive under the influence of gossip like the temporary influence of intoxicating poisonous wine. Isn’t it strange that people can smoothly, joyously, and with caustic criticism talk about the faults of others for hours but cannot endure reference to their own faults at all?\n\nIf you do not like to talk about your own faults, if it hurts you to do so, you certainly should feel more hurt when saying unkind, harmful things about other people. Train yourself and each member of your family to refrain from talking about others. “Judge not, that ye be not judged.”\n\nBy giving publicity to a man’s weakness, you do not help him. Instead, you either make him wrathful or discouraged, and you shame him, perhaps forever, so that he gives up trying to be good. When you take away the sense of dignity from a person by openly maligning him, you make him desperate.\n\nWhen a man is down, he is too well aware of his own wickedness. By destructive criticism, you push him still farther down into the mire of despondency into which he is already sinking. Instead of gossiping about him, you should pull him out with loving, encouraging words. Only when aid is asked should spiritual and moral help be offered. To your own children or loved ones you may offer your friendly, humble suggestions at any time and thus remove their sense of secrecy or delicacy.\n\nSmile and Be Happy\n\nMake your home a valley of smiles instead of a vale of tears. Smile now and never mind how hard it has been for you to do so. Smile now. All the time remember to SMILE NOW, and you will SMILE ALWAYS.\n\nSome people smile most of the time, while beneath the mask of laughter they hide a sorrow- corroded heart. Such people slowly pine away beneath the shadows of meaningless smiles. There are other people who smile once in a while, and they may also be very serious at times; yet beneath the hard, beautiful outer appearance there may be gurgling a million fountains of laughing peace.\n\nIf you enjoyed good health for fifty years and then were sick for three years, unable to get healed by any method, you would probably forget about the length of time that you enjoyed good health and laughed at the idea of sickness. Now your reaction should be exactly the opposite. Just because you may have been sick for three years is no reason for thinking that you will never be well again.\n\nLikewise, if you were happy a long time, and you have been unhappy a comparatively short time, you are apt to lose hope of ever being happy again. This is lack of imagination. The memory of a long-continued happiness should be a forceful subconscious habit to influence your conscious mind and ward off the consciousness of your present trouble.\n\nWhen wealth only is lost, nothing real is lost, for if one has health and skill one can still be happy and can make more money; but if health is lost, then most happiness is also lost, and when the principle of life is lost, all happiness is lost. After bathing yourself in the Ocean of Peace in dreamland, as you awake with happiness, say, “In sleepland I found myself free from mortal worries. I was a King of Peace. Now, as I work in the daytime and carry on my diurnal battles of duties, I will no longer be defeated by insurgent worries of the kingdom of wakefulness. I am a King of Peace in sleepland, and I shall continue to be such a King in the land of wakefulness. As I come out of my Kingdom of Peace in sleepland, I shall spread that same peace in my land of wakeful dreams.”'
    )
    ,
    Article(
        heading: 'Divine Love',
        body: 'Thou art the mystic echo from the caverns of heart, and the inaudible voice of feeling.\n\nThou unseen charmer of souls, Thou art the fountain flowing from the bosom of friendship.\n\nThou are the unseen cord of self-bound souls and the rays of secret warmth which break buds of feeling into blossoms of endearing, soulful words of poesy and loyalty.\n\nThou art the Divine Cupid, enticing mystic souls to pierce the heart of all living things.\n\nThou art the silent language of souls, and the invisible ink which lovers use to write letters on the pages of their hearts.\n\nThou art the mother of all affections, and in Thy breast of love throbs the heart of God.\n\nLove is the heart-beat of all life, and the angel of incarnation.\n\nLove is the silent conversation between two hearts, and it is the call of God to all creatures, animate and inanimate, to return to His house of Oneness.\n\nLove is born in the garden of soul progress, and it sleeps behind the darkness of outer attachments. It is the oldest and the sweetest nectar, preserved in the bottle of hearts.\n\nIt is the flame which burns all weeds of selfishness, and destroys the walls of family and patriotic narrowness.\n\nIt is the light which dissolves all walls between souls, families, and nations.\n\nIt is the unfading blossom of pure friendship in the garden of both young and mature souls.\n\nLove is the door to heaven, the complete song of souls.\n\nLove is the echo of God’s voice trying to reverberate through mute stones, through rain, wind, fragrance, vitalizing light and plumed songbirds; it reverberates through the cries and laughter of babies, through unconditioned mother love, and through dumb and articulate hearts.'
    ),
    Article(
        heading: 'Finding the joy in life',
        body: 'October 1936, “Finding the Joy in Life”\n\nYou want a thing as long as you are not able to get it; when you have secured it, sooner or later you will tire of it, and then you will want something else. Have you ever tried to find that will-o’-the-wisp of “something else” which you seek at the end of all accomplished desires?\n\nNo matter what you seek, you must seek it with joy, in expectation of having joy by possessing it, and you must feel joyous when you actually get it. When seeking different things directly or indirectly, in reality you are seeking joy. When seeking all things, it is really joy that you seek through all these things and the fulfillment of all desires.\n\nThen, why not seek joy directly? Why seek it through the medium of material desires and material things? You do not want those things in life which bring you sorrow. Neither do you want those things which promise a little joy in the beginning but sink you in deep remorse and suffering in the end.\n\nWhy seek joy by supplicating the favor of short-lasting material things? Why depend upon short-lasting material things for short-lasting joys? Material things and fulfillment of material desires are short-lasting; therefore, all joys born of them are short-lasting. Joys born of eating, smelling fragrance, listening to music, beholding beautiful objects, and touching pleasing things are short-lasting. They last only as long as the sensations born of the senses of taste, smell, hearing, sight, and touch last.\n\nYou do not want a tantalizing joy; you do not want a transitory joy which brings sorrow in its trail; you crave joy which will not disappear like the sudden flicker of gossamer wings beneath the flash of lightning. You should look for joy which will shine forever steadily, like the ever luminous radium.\n\nNeither do you want a joy which has too much sameness; you want a joy which changes and dances itself in many ways to enthrall your mind and keep your attention occupied and interested forever. Any joy that comes by fits and starts is tantalizing; any joy that is monotonous is, of course tiresome; any joy that only comes for a little while and brings sorrow at last is undesirable. Any joy that comes for a little while then flits away, sinking you in a state of indifference, and thus deepens that state by contrast, is torturing.\n\nThe joy that rhythmically changes all the time like the different poses of an actor, and yet remains unchangeable in itself, is what all of us are seeking. Such joy can only be found through regular, deep meditation. Such an ever-new, unchangeable fountain of joy alone can quench our joy-thirst.\n\nIf Nature gave to us all at once everything we wanted-wealth, power, and lost friends-we would sooner or later get tired of all of these, but one thing we can never get tired of, and that is Joy itself. By its very nature, ever-new Joy is the only thing that can never tire the mind or make it want to exchange Joy for something else.\n\nIn the pursuit of evil or good, you are always seeking joy. The former promises joy and gives sorrow; the latter may promise sorrow but will surely give lasting joy in the end. Lasting, ever-new Joy is God, and when you have found Him, you have the eternally elusive will-o’-the wisp “something else” which you always seek at the end of all fulfilled desires. Finding this “something else,” you will not seek any farther. Finding this ever-new joy, you will find everything in it that you ever sought.\n\nMaterial objects which give joy remain outside of the mind; they only gain entry into the mind through imagination. Joy, from its very nature, is something born of the mind and lives closest in it. External, material objects can be destroyed, but this joy within can never be destroyed if one knows how to keep it and unless the possessor of joy changes his mind and becomes sorrowful. This joy is ever-new and indestructible.\n\nDo not seek joy through material mediums, or desires born of such contact. Seek the unconditioned, indestructible Pure Joy within yourself, and you will then have found the ever-conscious, ever-new Joy-God. This joy is not an abstract quality of mind, but it is conscious, self-born, and is the conscious, self-expressing quality of Spirit. Seek it and be comforted forever.\n\nWhen you have attained this ever-new joy, you will not have become a cynic, hating everybody. Rather, it is then that you will be in a position fit to enjoy everything rightly. As an immortal child of God, you are supposed to enjoy everything with a lasting attitude of your eternal nature of perpetual joy. People who enjoy material things become materially-minded. It is a disgrace to behave like a discontented mortal when you are made in God’s image, and when you are immortal.\n\nWhen immortals behave like mortals, they experience the changes of joy, sorrow, and indifference in their natures. That is why you must destroy this grafted nature of changeability on your unchangeable nature of joy. And when you have found your own nature of unchangeable joy, you will be able to enjoy everything, either pleasant or disagreeable with your unchangeable, indestructible joy. Your joy will stand unshaken amidst the crash of breaking earthly pleasures.'
    )
  ],

);
