// anandmoyima_en.dart
// Anandamayi Ma quotes and articles

import '../articlesquotes.dart';

final anandmoyimaSaint = Saint(
  'anandmoyima',
  'Anandamayi Ma',
  'assets/images/anandmoyima.jpg',
  [
    'This body has come to your world to awaken divine love in human hearts.',
    'To love God is natural; not to love Him is artificial.',
    'God is everywhere, in everyone, and in everything.',
    'The aim of human life is to find God.',
    'When you realize the Self, you realize that there is nothing but the Self.',
    'Love, serve, remember God - this is the essence of all spiritual practice.',
    'God alone is real, everything else is His play.',
    'Be like a child - simple, innocent, and trusting in God.',
    'Surrender everything to God and He will take care of you.',
    'The path of love is the easiest path to God.',
    'See God in everyone and serve all as manifestations of the Divine.',
    'Joy is the nature of the Self - seek it within, not without.',
    'Whatever happens is for the best, trust in Divine will.',
    'Devotion purifies the heart and prepares it for Divine realization.',
    'The name of God is the greatest purifier.',
    'Meditation is communion with the Divine.',
    'The guru is the grace of God appearing in human form.',
    'Be established in the thought that you belong to God alone.',
    'God manifests Himself according to the devotee\'s understanding.',
    'The whole universe is God\'s temple.',
    'Love God without any expectation of reward.',
    'The Self is beyond happiness and sorrow, pleasure and pain.',
    'This world is a school where we learn to love God.',
    'Laughter and tears are both sacred when they come from love of God.',
    'See the One in the many and the many in the One.',
    'God is the nearest of the near and the dearest of the dear.',
    'The Divine Mother watches over all Her children.',
    'Every breath should be an offering to God.',
    'In joy and sorrow, in success and failure, remember God.',
    'The Self is eternal bliss - this is your true nature.',
    'Serve others as you would serve God, for they are not different.',
    'Prayer is the wings that lift the soul to the Divine.',
    'God\'s love is unconditional and infinite.',
    'The realized soul sees God everywhere and in everything.',
    'Desire nothing but God and you will have everything.',
    'The Divine play goes on eternally - be a conscious participant.',
    'Love is the bridge between the soul and God.',
    'In silence, God speaks to the heart.',
    'The pure heart reflects God like a clear mirror.',
    'Every moment is an opportunity to remember God.',
    'God is both within you and beyond you.',
    'The highest prayer is to become what you pray to.',
    'Truth, love, and beauty are aspects of the one Divine.',
    'Live in the world but keep your heart with God.',
    'The Divine Mother\'s love knows no boundaries.',
    'In selfless service, the ego dissolves and God shines forth.',
    'The purpose of life is to realize your divine nature.',
    'God\'s grace is always flowing - open your heart to receive it.',
    'See everything as a gift from God.',
    'The Self is the witness of all experiences but is itself beyond experience.',
    'As the Supreme dwells in all forms, so each and every form is His. Whether you call Him by one name or by another, whether you worship Him or not, He alone is. What matters is to awaken to That which ever is.',
    'Do not try to understand God with the mind. The mind can only move among names and forms. God is realized when the mind becomes still, when it ceases to wander and rests in its own source.',
    'Everyone is on his own path. Some walk quickly, some slowly, some stumble and fall. But all are moving towards the same goal, whether they know it or not.',
    'Just as fire burns whether you know it or not, so Truth is what it is, independent of your belief or disbelief. One has only to draw near to feel its warmth.',
    'The body comes and goes, but That which knows the body neither comes nor goes. Seek to know That, and you will know what is eternal.',
    'Whatever work you do, do it as an offering to the Supreme. When action is done without desire for its fruits, it purifies the heart and leads one naturally to peace.',
    'Silence is the highest teaching. In silence all doubts are resolved, all questions answered, for in silence the Self reveals itself.',
    'Why worry about the future? The One who has taken care of you until now will take care of you always. Surrender yourself entirely, and you will find that nothing is lacking.',
    'The mind creates bondage and the mind creates liberation. Turn it towards the Eternal, and it becomes your friend; turn it towards the transient, and it binds you.',
    'God-realization is not something new to be attained. It is only the removal of ignorance, the unveiling of what has always been present.',
    'As long as there is the sense of \'I am the doer,\' there will be restlessness. When actions happen through you rather than by you, peace naturally abides.',
    'Prayer is not asking for things; prayer is the opening of the heart. When the heart opens fully, the Presence that is always there is revealed.',
    'Each breath you take is a reminder of the Divine. If you remember Him even once with sincerity, that remembrance will never be lost.',
    'Do not compare your path with another\'s. What is suitable for one may not be suitable for another. The Supreme knows what each one needs.',
    'Suffering comes to awaken you, not to punish you. When its lesson is learned, suffering disappears.',
    'If you wish to know Truth, be simple. Simplicity is the doorway through which the Infinite enters the heart.',
    'The Guru does not give you something from outside. The Guru reveals to you what is already within.',
    'As water takes the shape of the vessel, so the Divine appears according to the attitude of the devotee.',
    'Attachment binds because it is based on the belief that happiness comes from objects. When this belief is seen to be false, attachment loosens.',
    'The more you try to grasp God, the farther He seems. When you stop grasping and let go, you find He was never absent.',
    'To remember God while walking, sitting, eating, or working is true spiritual practice. Nothing need be renounced outwardly.',
    'Restlessness arises from desire. When desire is fulfilled, another desire takes its place. Only the desire for Truth brings lasting peace.',
    'God is not far away. Distance exists only in imagination.',
    'When the ego bows down, Grace flows.',
    'Your nature is joy. If joy seems absent, it is because attention is turned outward instead of inward.',
    'Faith is not blind belief; it is trust born of inner experience.',
    'Whatever comes to you comes by His will. Accept it with gratitude, and it will become a means of growth.',
    'The world appears real so long as the mind clings to it. When the mind rests in the Self, the world loses its power to bind.',
    'One moment of true remembrance is worth years of mechanical practice.',
    'Love that expects nothing in return is divine love.',
    'Do not be discouraged by failure. Every sincere effort bears fruit, whether seen or unseen.',
    'The body is a temple; keep it pure, but do not mistake the temple for the Deity.',
    'God alone is the doer. When this is realized, life becomes effortless.',
    'The purpose of life is to awaken to what you truly are.',
    'What you seek is seeking you.',
    'True renunciation is renunciation of ego, not of objects.',
    'Where there is humility, there is Truth.',
    'Do not try to change others. Change yourself, and everything will change.',
    'The heart that yearns sincerely will surely find.',
    'Peace does not come from controlling circumstances, but from understanding their nature.',
    'In surrender there is strength, not weakness.',
    'The Divine plays in countless forms, yet remains ever One.',
    'When the mind becomes quiet, the Self shines forth.',
    'Patience is the companion of wisdom.',
    'Every experience has its place in the unfolding of consciousness.',
    'You are never alone; the Supreme is nearer than your breath.',
    'When desire ends, fear ends.',
    'Do not seek happiness; be still, and happiness will reveal itself.',
    'The journey ends where it began.',
    'Grace is always present; receptivity is needed.',
    'To see God in all beings is true worship.',
    'Even doubt can lead to Truth if pursued sincerely.',
    'Life itself is the teacher.',
    'The Self is self-luminous; it needs no proof.',
    'Do not hurry; the Eternal has no haste.',
    'Where love is, there God is.',
    'Seek the Seeker.',
    'Nothing belongs to you, yet nothing is denied you.',
    'The mind that rests in God is free.',
    'Joy is not caused; it is uncovered.',
    'What is destined will happen; your task is to remain aware.',
    'The name of God purifies even when repeated without understanding.',
    'In the end, only Truth remains.',
    'Be as you are, but know who you are.',
    'Effort is needed until effortlessness dawns.',
    'To give oneself completely is the highest offering.',
    'Where there is simplicity, there is clarity.',
    'God reveals Himself according to your capacity to receive.',
    'Attachment fades when understanding deepens.',
    'Nothing is outside the Divine.',
    'When you stop searching outside, you arrive.',
    'The Self is never bound; bondage is imagined.',
    'Live in the world, but do not belong to it.',
    'Truth is simple; the mind makes it complex.',
    'Every breath can be a prayer.',
    'Do not resist life; understand it.',
    'Peace is your natural state.',
    'In stillness, all answers arise.',
    'Let go, and you will be carried.',
    'The end is certain; only the pace varies.',
    'Grace works silently.',
    'Love dissolves separation.',
    'To know yourself is to know God.',
    'Nothing is wasted on the path.',
    'Where there is sincerity, there is progress.',
    'The Self alone is real.',
    'Outer discipline prepares the way for inner freedom.',
    'Awareness itself is liberation.',
    'What you truly are cannot be lost.',
    'Fear disappears when Truth is known.',
    'The One appears as many for the joy of play.',
    'Be empty, and you will be filled.',
    'The heart knows what the mind cannot grasp.',
    'When \'I\' disappears, only God remains.',
    'Seek That which does not change.',
    'Everything passes; That which knows does not.',
    'Silence is full.',
    'You are already home.',
    'Realization is recognition.',
    'All paths end in the same Truth.'
  ],
  [
    Article(
        heading: 'The Divine Mother\'s Teaching',
        body: 'Anandamayi Ma, known as the Bliss-Permeated Mother, was a living embodiment of divine love and joy. Her very presence was a teaching, radiating the unconditional love of the Divine Mother.\n\nShe taught that the ultimate goal of human life is God-realization. This is not something foreign to us but our very nature. We have simply forgotten who we are in the play of maya. Through spiritual practice, devotion, and the grace of God, we can remember our true divine nature.\n\nMa emphasized that God can be approached through any path - whether it be devotion (bhakti), knowledge (jnana), or action (karma). The important thing is sincerity and one-pointed dedication. She would say that whatever path one follows with love and faith will lead to the same goal.\n\nHer teaching was simple yet profound: love God, serve others, and remember the Divine in all circumstances. She showed that spirituality is not separate from daily life but should permeate every moment of our existence.'
    ),
    Article(
        heading: 'The Path of Divine Love',
        body: 'Anandamayi Ma embodied the path of pure devotion. She taught that love is the most natural way to approach the Divine, for God is love itself. When we love God with all our heart, mind, and soul, we gradually realize that there is nothing but God.\n\nThe path of love begins with devotion to a chosen form of God but ultimately leads to the realization that God is formless yet manifests in all forms. Ma would say that in the beginning, we see God as different from ourselves, but as love deepens, we realize that we and God are one.\n\nShe emphasized the importance of surrender (saranagati). Complete surrender to the Divine will brings peace and freedom from the burden of ego. When we truly surrender, we realize that everything is in God\'s hands and we are merely instruments of the Divine.\n\nMa\'s life was itself a demonstration of this surrender. She would often say, "This body does whatever it is moved to do by the Divine. There is no separate will here." This complete effacement of ego is the goal of the path of divine love.'
    ),
    Article(
        heading: 'Seeing God Everywhere',
        body: 'One of Anandamayi Ma\'s central teachings was the practice of seeing God in all beings and circumstances. She would say that when the devotee\'s vision is purified through spiritual practice, they begin to see the Divine presence everywhere.\n\nThis vision transforms one\'s entire relationship with the world. Instead of seeing separate individuals, one sees the one Divine playing different roles. Service to others becomes worship of God. Every interaction becomes an opportunity for spiritual growth.\n\nMa taught that this vision must be cultivated gradually through practice. In the beginning, we may need to make an effort to remember God, but eventually it becomes natural and effortless. The advanced devotee lives in constant communion with the Divine.\n\nShe would often remind her devotees that God is not distant but is the very life within all beings. The Divine is nearer than our own breath, closer than our own thoughts. Realizing this nearness of God is the fruit of spiritual practice and the source of eternal bliss.'
    )
  ],
);
