// nisargadatta_en.dart
// Nisargadatta Maharaj quotes and articles

import '../articlesquotes.dart';

final nisargadattaSaint =   Saint(
  'nisargadatta',
  'Nisargadatta maharaj',
  'assets/images/nisargadatta.jpg',
  [
    'You are not what you take yourself to be. Find out what you are.',
    'The real does not die, the unreal never lived.',
    'Wisdom tells me I am nothing. Love tells me I am everything. Between these two my life flows.',
    'You are the Supreme Reality. Don\'t be small-minded.',
    'To know what you are, you must first investigate and know what you are not.',
    'The consciousness in you and the consciousness in me, apparently two, are one, seek unity and that is love.',
    'All you need is to get rid of the tendency to define yourself.',
    'Once you realize that the road is the goal and that you are always on the road, not to reach a goal, but to enjoy its beauty and its wisdom, life ceases to be a task and becomes natural and simple.',
    'You are not the body. You are not even the mind. You are the awareness in which both appear.',
    'The moment you know your real being, you are afraid of nothing.',
    'Stop imagining yourself being or doing this or that and the realization that you are the source and heart of all will dawn upon you.',
    'Nothing you perceive is your own. Nothing you perceive has anything to do with you.',
    'Discard all traditional standards. Leave them to the adherents of tradition.',
    'Your true home is in nothingness, in emptiness of all content.',
    'When I look within and see that I am nothing, that is wisdom. When I look without and see that I am everything, that is love.',
    'The mind creates the abyss, the heart crosses it.',
    'Whatever you think you are, you are not.',
    'You take yourself to be a person, but you have never been born as a person.',
    'In reality you are not a thing, nor separate from other things.',
    'The search for reality is the most dangerous of all undertakings, for it destroys the world in which you live.',
    'All separation, every kind of estrangement and alienation is false.',
    'You are the ultimate potentiality of which the all-embracing consciousness is the manifestation and expression.',
    'The personal needs protection, the real needs no protection.',
    'Nothing can trouble you but your own imagination.',
    'Once you know with absolute certainty that nothing can trouble you but your own imagination, you come to disregard your desires and fears.',
    'You are not in the world, the world is in you.',
    'The feeling \'I am\' is your own. You cannot part with it, but you can impart it to anything, as in \'I am young\', \'I am rich\' etc.',
    'Between the banks of pain and pleasure the river of life flows. It is only when the mind refuses to flow with life, and gets stuck at the banks, that it becomes a problem.',
    'Freedom is from the known.',
    'Your weakness is due to your conviction that you were born into the world.',
    'Don\'t rely on your mind for liberation. It is the mind that brought you into bondage.',
    'The real teacher is life itself.',
    'You need not get at it, for you are it.',
    'Love says \'I am everything\'. Wisdom says \'I am nothing\'. Between the two, my life flows.',
    'The trinity: mind, self and spirit, when looked into, becomes unity.',
    'Just be. Let your true nature emerge. Don\'t disturb your mind with seeking.',
    'Your own self is your ultimate teacher. The outer teacher is merely a milestone.',
    'In your world everything must have a beginning and an end. If it does not, you call it eternal.',
    'The realized man sees the world as it is: one in essence, varied in appearance.',
    'Learn to look without imagination, to listen without distortion.',
    'It is the mind that tells you that the mind is there. Don\'t be deceived.',
    'Truth is not a reward for good behavior, nor a prize for passing some tests.',
    'That which makes you think that you are a human is not human.',
    'You have put so much energy into building a prison for yourself. Now spend as much on demolishing it.',
    'To understand that you are not the person, watch the person. Look at the person as a thing in consciousness.',
    'What is the difficulty in dropping the body-mind identity? After all, you are not the body-mind.',
    'You are afraid of death because you do not know yourself. The real you is deathless.',
    'What prevents you from knowing yourself as all and beyond all is the mind based on memory.',
    'The mind exists in time, we are beyond time.',
    'You are love itself - when you are not afraid.',
    // Additional profound quotes on Self-Knowledge and Awareness
    'You are not what you take yourself to be. You are not the body, nor the mind, nor the sense of being a person. You are the timeless awareness in which all these appear and disappear.',
    'The moment you know yourself as consciousness and not as a person, all suffering ends. What remains is peace, which is not an experience but your natural state.',
    'Before the body was, before the world appeared, you were. Stay with that sense of being prior to all concepts and let everything else go.',
    'The \'I am\' is the first doorway. Stay with it steadily. When even the \'I am\' dissolves, the Absolute remains.',
    'You are not in the world; the world is in you. You carry the entire universe within your consciousness.',
    'To know what you are, you must first investigate what you are not. Whatever can be seen, perceived, or experienced is not you.',
    'The true Self is not something to be attained. It is what you are when all false ideas about yourself are dropped.',
    'You imagine yourself to be limited, and then you suffer because of that limitation. In truth, there is no boundary to what you are.',
    'When you stop identifying with the body-mind, you discover that you were never bound, never in trouble, never incomplete.',
    'Awareness is not personal. The person appears in awareness, but awareness does not belong to the person.',
    // On Consciousness and the Absolute
    'Consciousness itself is a temporary state. It appears and disappears. That which knows consciousness is beyond it.',
    'The Absolute is not conscious of itself. Consciousness is a phenomenon that arises in the Absolute, like a wave on the ocean.',
    'You take consciousness to be yourself, but even consciousness is observed. Find that which is aware of consciousness.',
    'The body and the world arise together with consciousness. When consciousness is not, neither is the world.',
    'Prior to consciousness, there is no experience, no time, no space — yet you are. That is your true nature.',
    'Consciousness depends on the body, but the Absolute depends on nothing. Know the difference.',
    'When consciousness dissolves at death, what you truly are does not die, because it was never born.',
    'The Absolute cannot be spoken of. Whatever can be said is only about consciousness.',
    'Stay at the source of consciousness, and you will transcend it.',
    'You mistake the movement of consciousness for reality. Reality is that which does not move.',
    // On Self-Inquiry and Practice
    'Your only sadhana is to hold on to the sense \'I am\' and reject everything else as not-self.',
    'Do not try to change what appears. Only understand what you are, and everything will change by itself.',
    'Effort is required until effortlessness is discovered. Then even effort drops away.',
    'Self-inquiry is not a mental exercise. It is the steady refusal to identify with anything that appears.',
    'Watch your thoughts as you would watch clouds passing in the sky. Do not claim them as yours.',
    'The mind will not help you to transcend the mind. You must go beyond it by understanding it.',
    'When you observe the mind, you are already beyond it.',
    'Do not ask how long it will take. Just remain earnest and honest in your investigation.',
    'You do not need to purify the mind. Just stop identifying with it.',
    'Silence is not the absence of sound; it is the absence of identification.',
    // On Ego, Personhood & Identity
    'The person is a collection of memories, habits, and conditioning. You are not that collection.',
    'The ego is only an idea — a false center assumed by consciousness.',
    'When you say \'I suffer,\' investigate who this \'I\' is. You will not find it.',
    'The idea \'I am the doer\' is the bondage. When it goes, freedom is.',
    'Personality is not reality; it is a mask worn by consciousness.',
    'As long as you take yourself to be a person, you will live in fear.',
    'The sense of individuality comes with the body and ends with it.',
    'You cling to the person because you fear nothingness, but that nothingness is peace.',
    'When the person dissolves, what remains is not emptiness but fullness.',
    'The ego wants continuity; reality has none.',
    // On Suffering, Desire & Fear
    'All suffering is born of identification. You suffer because you take the transient to be yourself.',
    'Desire arises from the feeling of incompleteness, which itself is false.',
    'Fear exists only for the person. The Self knows no fear.',
    'When you know you are not the body, death loses its terror.',
    'Pain is physical; suffering is mental. You can transcend suffering by understanding.',
    'What you resist persists. What you understand dissolves.',
    'Desire is memory projected into the future.',
    'Freedom is not the fulfillment of desire, but freedom from desire.',
    'Suffering is a signal telling you that you are mistaken about yourself.',
    'When false identity ends, suffering ends with it.',
    // On the World and Reality
    'The world is not unreal, but it is not what you think it is. It is a projection of consciousness.',
    'The world appears real because you believe yourself to be part of it.',
    'When consciousness is still, the world is still.',
    'The universe exists only as long as it is perceived.',
    'You give reality to the world by taking it personally.',
    'The world has no independent existence apart from consciousness.',
    'Reality is simple; illusion is complex.',
    'The world is neither good nor bad. It only reflects your understanding.',
    'What you call \'real life\' is a stream of perceptions.',
    'The world is a show, but consciousness takes it seriously.',
    // On Guru, Grace & Teaching
    'The guru does not give you something new. He removes what is false.',
    'Grace is not an event; it is your very nature.',
    'When you are ready, the teaching finds you.',
    'The guru points, but you must see.',
    'Trust the teaching until you verify it for yourself.',
    'Faith in the guru is faith in your own Self.',
    'Words are only pointers. Do not cling to them.',
    'The highest teaching is silence.',
    'A true teacher does not comfort the ego; he destroys it.',
    'When understanding is complete, the guru disappears.',
    // On Liberation and Freedom
    'Liberation is not an achievement in time. It is the recognition of what is timeless.',
    'You are free now, but you imagine yourself to be bound.',
    'Freedom is not doing what you like, but not being compelled by desire.',
    'When there is no \'me,\' there is no bondage.',
    'Liberation is the end of the search.',
    'Nothing happens to the liberated one, because there is no one for it to happen to.',
    'The liberated state is ordinary, natural, and unnoticed.',
    'You do not become free; you discover that you were never bound.',
    'The highest state is not a state at all.',
    'When ignorance ends, nothing special happens — truth simply stands revealed.',
    // On Ultimate Truth
    'You are not a fragment of reality. You are reality itself.',
    'Whatever appears must disappear. What does not appear cannot disappear.',
    'The Absolute has no attributes, yet all attributes arise from it.',
    'You cannot know the Absolute as an object, because you are that.',
    'The Self is not experienced; it is that which experiences.',
    'When all questions cease, truth remains.',
    'Nothing needs to be added to you; only false ideas must be removed.',
    'What you truly are is beyond affirmation and denial.',
    'Be quiet and watch — that is all.',
    'The truth is simple, but the mind resists simplicity.',
    'Stay with the sense of being until even that dissolves.',
    'Do not try to grasp truth; let falsehood fall away.',
    'Understanding is the key, not experience.',
    'What is real is always present.',
    'You are prior to time.',
    'Nothing is wrong with reality; only your ideas are wrong.',
    'When the seeker disappears, the sought is revealed.',
    'Be empty of concepts.',
    'You are the witness, not the witnessed.',
    'You are — and that is enough.'
  ],
  [
    Article(
        heading: 'Who Am I? - The Fundamental Question',
        body: 'Nisargadatta Maharaj\'s teaching centered around the fundamental question "Who Am I?" He would relentlessly point his disciples to investigate their true nature beyond all concepts and identifications.\n\n"You are not what you take yourself to be," he would say. "Find out what you are." This investigation is not an intellectual exercise but a direct inquiry into the source of the \'I\' feeling.\n\nMaharaj taught that we habitually identify ourselves with the body, mind, thoughts, emotions, and various roles we play in life. But all these are objects that appear in consciousness. We are the consciousness in which they appear, not the objects themselves.\n\nThe process of self-inquiry involves negating all that you are not - "I am not the body, I am not the mind, I am not the thoughts" - until you arrive at what remains. What remains is pure awareness, pure being, your true nature.\n\n"To know what you are, you must first investigate and know what you are not," Maharaj emphasized. This process of elimination leads to the recognition of your fundamental nature as pure consciousness, beyond all attributes and limitations.\n\nThe question "Who Am I?" must be pursued with intense earnestness and sincerity. It is not enough to understand it intellectually; it must become a living inquiry that permeates every moment of your existence until the false sense of being a separate person dissolves completely.'
    ),
    Article(
        heading: 'The Nature of Consciousness',
        body: 'Nisargadatta Maharaj had a unique way of explaining consciousness that was both profound and accessible. He distinguished between the personal consciousness (which he called the "I am" feeling) and the absolute consciousness which is beyond all experience.\n\nThe "I am" is the first movement in consciousness, the primary concept that gives rise to all other experiences. Maharaj taught that we should hold on to this pure "I am" feeling without any additions like "I am this" or "I am that."\n\n"The consciousness in you and the consciousness in me, apparently two, are one," he would say. This understanding dissolves the illusion of separation and reveals the unity underlying all apparent diversity.\n\nMaharaj explained that consciousness is not produced by the brain or body. Rather, the body and brain appear in consciousness. Consciousness is not personal; it is universal, and what we take to be individual consciousness is simply a reflection of this universal consciousness.\n\nThe absolute reality is even beyond consciousness - it is that in which consciousness itself appears and disappears. This is your true nature, prior to consciousness, prior to existence and non-existence.\n\n"You are the Supreme Reality," Maharaj would declare. "Don\'t be small-minded." This Supreme Reality cannot be known as an object because you are it. It can only be recognized through the dissolution of all that you think you are.'
    ),
    Article(
        heading: 'The Illusion of the Person',
        body: 'One of Nisargadatta Maharaj\'s most radical teachings was about the illusory nature of the person. He would say, "You take yourself to be a person, but you have never been born as a person."\n\nThe person is simply a collection of memories, thoughts, and identifications that create an apparent continuity. But when examined closely, there is no solid entity that can be called a person. It is like a movie - individual frames creating an illusion of movement and story.\n\nMaharaj taught that the person is a mental construct, a bundle of concepts with no independent reality. "Whatever you think you are, you are not," he would insist. The person appears in you (consciousness) but you are not the person.\n\nThis understanding is liberating because it means that all the problems, limitations, and suffering of the person are also illusory. When you realize you are not the person, you are free from the person\'s destiny, karma, and conditioning.\n\n"Nothing you perceive is your own. Nothing you perceive has anything to do with you," Maharaj would say. This includes the body, mind, thoughts, and emotions that we usually consider to be ours.\n\nThe recognition that you are not the person is not a philosophical position but a direct realization that comes through earnest self-inquiry. When this recognition becomes stable and unshakeable, you abide as what you truly are - pure awareness, pure being, beyond all personal limitations.'
    ),
    Article(
        heading: 'Love and Wisdom - The Two Wings of Truth',
        body: 'Nisargadatta Maharaj beautifully expressed the paradox of realization in his famous statement: "Wisdom tells me I am nothing. Love tells me I am everything. Between these two my life flows."\n\nWisdom is the recognition of your true nature as pure awareness, which has no attributes, no form, no qualities - essentially nothing that can be grasped by the mind. From this perspective, you are the void, the emptiness in which all experience appears.\n\nLove, on the other hand, is the recognition that this same awareness is the very essence of everything that appears. You are not separate from anything; you are the one appearing as the many. This is the love that embraces all existence as your own self.\n\nThese are not contradictory truths but two aspects of the same realization. The absolute is both the void and the fullness, nothing and everything, transcendent and immanent.\n\n"When I look within and see that I am nothing, that is wisdom. When I look without and see that I am everything, that is love," Maharaj explained. This dual recognition is the hallmark of complete understanding.\n\nLiving from this understanding means being established in the peace of knowing yourself as nothing (no-thing) while simultaneously loving all that appears as your own manifestation. This is the natural state of the realized being - empty of self yet full of love for all.'
    ),
    Article(
        heading: 'Beyond Birth and Death',
        body: 'Nisargadatta Maharaj\'s teachings on death and immortality were particularly powerful and comforting. "The real does not die, the unreal never lived," he would say with absolute certainty.\n\nFrom his perspective, what we call birth and death are simply appearances in consciousness, like scenes in a dream. The body is born and dies, but you - the awareness in which the body appears - are never born and therefore cannot die.\n\n"You are afraid of death because you do not know yourself," Maharaj would point out. "The real you is deathless." This fear of death comes from identifying with the mortal body rather than recognizing yourself as immortal consciousness.\n\nMaharaj taught that we have never actually experienced birth or death. We have memories of the past and imagination about the future, but our actual experience is always of the present moment of awareness. This awareness has always been and always will be.\n\nThe understanding of your deathless nature is not a belief or consolation but a direct recognition. When you truly know yourself as pure awareness, the fear of death simply disappears because you realize there is nothing that can die.\n\n"Your weakness is due to your conviction that you were born into the world," he would say. In reality, the world appears in you; you do not appear in the world. This fundamental shift in understanding transforms your entire relationship with life and death.\n\nThe practical implication of this teaching is tremendous freedom and fearlessness. When you know yourself as the deathless reality, you can live fully and love completely without the shadow of mortality clouding your natural joy and peace.'
    )
  ],
);
