// ramakrishna_en.dart
// Ramakrishna Paramhansa quotes and articles

import '../articlesquotes.dart';

final ramakrishnaSaint = Saint(
  'ramakrishna',
  'Ramakrishna Paramhansa',
    'assets/images/ramkrishna.jpg',
  [
    'God can be realized through all paths. All religions are true. The important thing is to reach the roof. You can reach it by stone stairs or by wooden stairs or by bamboo steps or by a rope. You can also climb up by a bamboo pole.',
    'As long as I live, so long do I learn.',
    'The winds of grace are always blowing, but you have to raise the sail.',
    'If you want to go east, don\'t go west.',
    'God is in all men, but all men are not in God; that is why we suffer.',
    'The fabled musk deer searches the world over for the source of the scent which comes from itself.',
    'Knowledge leads to unity, but ignorance to diversity.',
    'As the tortoise lives both on land and in water, so does the perfect soul live in God and in the world.',
    'When the flower blooms, the bees come uninvited.',
    'The breeze of His grace is always blowing; set your sail to catch that breeze.',
    'The winds of God\'s grace are always blowing; it is for us to raise our sails.',
    'One cannot attain divine knowledge till one gets rid of pride.',
    'Disease is the tax which the soul pays for the body, as the tenant pays house-rent for the use of the house.',
    'He who has renounced all his desires is alone truly happy.',
    'If you desire many things, many things will seem but a few.',
    'Pray to God that your attachment to such transitory things as wealth, name, and creature comforts may become less and less every day.',
    'Do not seek illumination unless you seek it as a man whose hair is on fire seeks a pond.',
    'Water and oil cannot be mixed. Likewise, no spiritual progress is possible without renunciation.',
    'The magnetic needle always points to the north, and hence it is that the sailing vessel does not lose its course. So long as the heart of man is directed towards God, he cannot be lost in the ocean of worldliness.',
    'So long as one does not become simple like a child, one does not get divine illumination.',
    'Meditate upon the Knowledge and Bliss Eternal, and you will also have bliss.',
    'Many are the names of God and infinite the forms through which He may be approached. In whatever name and form you worship Him, through them you will realize Him.',
    'Realization of God cannot be achieved without ecstatic love for Him.',
    'So long as the bee is outside the petals of the lily, and has not tasted of its honey, it hovers around the flower emitting the buzzing sound; but when it is inside the flower, it noiselessly drinks the nectar. So long as a man quarrels and disputes about doctrines and dogmas, he has not tasted the nectar of true faith; when he has tasted it, he becomes quiet and full of peace.',
    'The world is indeed a mixture of truth and make-believe. Discard the make-believe and take the truth.',
    'God laughs on two occasions. He laughs when the physician says to the patient\'s mother, \'Don\'t be afraid, mother; I shall certainly cure your boy.\' God laughs, saying to Himself, \'I am going to take his life, and this man says he will save it!\' The physician thinks he is the master, forgetting that God is the Master. God laughs again when two brothers divide their land with a string, saying to each other, \'This side is mine and that side is yours.\' He laughs and says to Himself, \'The whole universe belongs to Me, but they say they own this portion or that portion.\'',
    'Through love one can see Him, touch Him, and feel Him.',
    'Don\'t you see a light there? That is the light of faith. It burns in every human heart.',
    'He is born in vain, who having attained the human birth, so difficult to get, does not attempt to realize God in this very life.',
    'If you first fortify yourself with the true knowledge of the Universal Self, and then live in the midst of wealth and worldliness, surely they will in no way affect you.',
    'The waves belong to the Ganges, not the Ganges to the waves. A man cannot realize God unless he gets rid of all such egotistic ideas as \'I am such an important man\' or \'I am so and so\'.',
    'The sun can give heat and light to the whole world, but he cannot do so when the clouds shut out his rays. Similarly as long as egotism veils the heart, God cannot shine upon it.',
    'Woman and gold alone is the world; that alone is maya. Because of it you do not see or obtain God.',
    'Common men talk bagfuls of religion but do not practice even a grain of it. The wise man speaks little, even though his whole life is religion expressed in action.',
    'So long as one does not possess the spirit of renunciation, one cannot live in peace.',
    'A devotee who can call on God while living a householder\'s life is a hero indeed. God thinks: \'He is blessed indeed who prays to me in the midst of his worldly duties. He is trying to find Me, overcoming a great obstacle - pushing away, as it were, a huge block of stone weighing a ton. Such a man is a real hero.\'',
    'If you want to realize God, then you must cultivate intense dispassion. You must renounce immediately what you feel to be standing in your way. You should not put it off till the future.',
    'The way to find God is through bhakti, jnana, or karma, whichever suits you best.',
    'It is easy to talk on religion, but difficult to practice it.',
    'Bondage is of the mind; freedom too is of the mind. If you say \'I am a free soul. I am a son of God who can bind me\' free you shall be.',
    'What Brahman is cannot be described. All things in the world - the Vedas, the Puranas, the Tantras, the six systems of philosophy - have been defiled, like food that has been touched by the tongue, for they have been read or uttered by the tongue. Only one thing has not been defiled in this way, and that is Brahman.',
    'A man is truly free, even here in this embodied state, if he knows that God is the true agent and he a mere instrument.',
    'Work, apart from devotion or love of God, is helpless and cannot stand alone.',
    'Kamini-kanchana (lust and gold) is the obstacle to yoga.',
    'So long as there is desire or want, there is misery. When there is no desire, when you are established in the Self, when nothing but the Self can satisfy you, there is perfect bliss.',
    'It is the mind that makes one wise or ignorant, bound or emancipated.',
    'When one has love for God, one doesn\'t feel any physical attraction to wife, children, relatives and friends. One retains only compassion for them.',
    'The joys of love and friendship, the pleasures of the senses, and all other enjoyments are but a reflection of that Bliss which comes from God.',
    'It is enough to have sincere yearning for God. Infinite are the paths and infinite are the ways that lead to Him.',
    'Live in the world like a waterfowl. The water clings to the bird, but the bird shakes it off. Live in the world like a mudfish. The fish lives in the mud, but its skin is always bright and shiny.',
    'You see many stars at night in the sky but find them not when the sun rises; can you say that there are no stars in the heaven of day? So, O man! Because you behold not God in the days of your ignorance, say not that there is no God.',
    'The grace of God is like insurance; it will help you in your time of need without any limit.',
    'As many faiths, so many paths. It is like water, which may be drunk from different vessels, but the water is the same.',
    'I see people are mad after the world, mad after money, mad after name and fame; but no one is mad after God.',
    'If one has sincere longing, one will surely realize God. There is no doubt about it.',
    'The mind is like a needle covered with mud, and God is like a magnet. The needle cannot be united with the magnet unless it is free from mud.',
    'When the flower blooms, the bees come uninvited. When the heart is pure, God reveals Himself.',
    'God can be realized through all paths, through all religions. There are different ways to reach the same house.',
    'As long as one has not realized God, one feels that He is \'there\'; but after realization, one sees that God is here and everywhere.',
    'The world is like water, and the mind is like milk. If you pour milk into water, they become one. But if you churn the milk into butter, it floats apart.',
    'One must be very careful while living in the world. Live like a mud fish—though it lives in mud, its skin remains bright.',
    'The mind that constantly thinks of God becomes like Him.',
    'Why does God make us suffer? To make us perfect.',
    'The aim of human life is to love God. Bhakti is the one essential thing.',
    'God is not far away. He is very near, nearer than the nearest.',
    'One does not attain spiritual wisdom by reading many books. One must dive deep.',
    'When a man has tasted divine bliss, he finds no pleasure in worldly enjoyments.',
    'The boat may be in the water, but the water should not be in the boat.',
    'One who has faith has everything; one who lacks faith lacks everything.',
    'Do all your duties, but keep your mind fixed on God.',
    'He who is sincere and earnest, he alone succeeds.',
    'The tree laden with fruits bends low. The truly great are always humble.',
    'God alone is the doer; man is only an instrument.',
    'Prayer is the key that opens God\'s heart.',
    'To see God is the goal of life. Everything else is secondary.',
    'The nearer you come to God, the more you feel love for all beings.',
    'One must have childlike faith to realize God.',
    'When the mind is pure, God reveals Himself naturally.',
    'The world is impermanent. Only God is eternal.',
    'Tears shed for God wash away the impurities of the heart.',
    'God laughs on two occasions: when physicians think they can save a man by medicine alone, and when pundits think they can bind Him by scriptures.',
    'One cannot realize God through dry reasoning. Love alone leads to Him.',
    'God reveals Himself in the heart of one who has longing.',
    'When the lotus blooms, the bees come. When the heart blooms, God appears.',
    'God is like an ocean of sweetness. No matter how much you taste, there is more.',
    'One who has surrendered everything to God has no fear.',
    'Why worry? He who has created you will take care of you.',
    'As long as there is \'I\' and \'mine\', ignorance remains.',
    'The mind becomes pure by chanting God\'s name.',
    'Through intense love, one can see God even with these eyes.',
    'A devotee wants God and God alone, nothing else.',
    'God can be realized in the kitchen as well as in the forest.',
    'Attachment to the world binds, attachment to God liberates.',
    'Faith is like a lamp in a dark room.',
    'One should weep for God as a child weeps for its mother.',
    'God is both with form and without form.',
    'The more you advance spiritually, the less you see faults in others.',
    'He who has renounced everything has truly gained everything.',
    'Knowledge without devotion is dry and barren.',
    'God is not attained by cleverness, but by simplicity.',
    'One should live in the world like a maidservant in a rich man\'s house.',
    'Without yearning, nothing can be achieved.',
    'God listens to sincere prayer.',
    'The name of God has great power in this age.',
    'The heart becomes pure by constant remembrance of God.',
    'One who has seen God sees Him everywhere.',
    'God reveals Himself in proportion to one\'s surrender.',
    'The essence of religion is love of God.',
    'When the mind is absorbed in God, the senses lose their power.',
    'He who has tasted divine joy finds worldly pleasure tasteless.',
    'God is the inner controller of all beings.',
    'The same God is worshipped by different names.',
    'One must go beyond good and evil to realize God.',
    'Devotion softens the heart and removes ego.',
    'The goal is not talk, but realization.',
    'God is attained not by argument, but by tears.',
    'When the ego disappears, God shines forth.',
    'The mind becomes calm when it rests in God.',
    'One who sees God in all beings never hates anyone.',
    'Renunciation does not mean giving up the world, but giving up attachment.',
    'God alone is real; the world is His play.',
    'The more you love God, the more you lose interest in worldly things.',
    'Surrender everything at the feet of God.',
    'Faith is the root of spiritual life.',
    'God can be realized here and now.',
    'One must practice spiritual discipline with patience.',
    'God\'s grace descends where there is humility.',
    'The path may be hard, but the goal is sweet.',
    'God is realized in the depth of silence.',
    'One must live in the world without being worldly.',
    'When the heart is filled with God, fear vanishes.',
    'The mind purified by devotion becomes steady.',
    'God reveals Himself in a loving heart.',
    'The greatest miracle is transformation of the heart.',
    'God is nearer than breath.',
    'True knowledge leads to love.',
    'He who loves God loves all.',
    'God is beyond words, yet felt by the heart.',
    'One must cling to God as a drowning man clings to a plank.',
    'The essence of all scriptures is devotion.',
    'God responds to earnest longing.',
    'The mind freed from desire becomes divine.',
    'One who seeks God sincerely will surely find Him.',
    'God is the inner light of all beings.',
    'To love God is the highest wisdom.',
    'The soul finds peace only in God.',
    'God is the friend of the devotee.',
    'Where there is devotion, there is God.',
    'The end of all spiritual paths is God-realization.',
    'Cry to God with a real cry, and He must answer.'
  ],
  [
    Article(
        heading: 'The Harmony of Religions',
        body: 'Ramakrishna\'s life was a living demonstration of the fundamental unity of all religions. He practiced different spiritual paths - Hinduism in its various forms, Islam, and Christianity - and realized that all lead to the same ultimate truth.\n\nHe often used the parable of reaching the roof by different staircases. Whether one climbs by stone stairs, wooden stairs, bamboo steps, or even a rope, the goal remains the same - to reach the roof. Similarly, all religions are different paths leading to the same divine destination.\n\nThis teaching was revolutionary in his time and remains relevant today. Ramakrishna showed through his own experience that religious differences are merely differences in approach, not in essence. The Supreme Reality is one, though it is called by different names and worshipped in different forms.\n\nHe emphasized that quarreling over religious doctrines shows one has not tasted the nectar of true faith. When one truly experiences God, all arguments cease, and one becomes filled with peace and understanding. His message of religious harmony continues to inspire millions across the world, promoting tolerance and mutual respect among different faiths.'
    ),
    Article(
        heading: 'God-Realization and Renunciation',
        body: 'Ramakrishna taught that the ultimate goal of human life is God-realization. He emphasized that this realization cannot come without intense yearning and renunciation. He often said that one must desire God as intensely as a drowning man desires air.\n\nRenunciation, in his teaching, does not necessarily mean abandoning the world and becoming a monk. Rather, it means giving up attachment to worldly things - wealth, fame, and sensual pleasures. One can live in the world while maintaining inner detachment, like a lotus leaf that floats on water but is never wet.\n\nHe particularly warned against "kamini-kanchana" (lust and gold) as the greatest obstacles to spiritual progress. These represent attachment to sensual pleasures and material wealth. As long as the mind is entangled in these, God-realization remains impossible.\n\nAt the same time, Ramakrishna acknowledged that living a spiritual life while performing worldly duties is the path of a true hero. A householder who remembers God while fulfilling family responsibilities is blessed indeed. Such a person overcomes tremendous obstacles, and God particularly values their efforts.\n\nThe key is to cultivate intense dispassion and to renounce immediately whatever stands in the way of God-realization, not postponing it to some future time.'
    ),
    Article(
        heading: 'The Role of the Guru and Divine Grace',
        body: 'Ramakrishna placed great importance on the role of the guru in spiritual life. He himself was a disciple of several teachers and later became the guru of many, including Swami Vivekananda. He taught that a true guru is essential for spiritual progress, as the guru removes the darkness of ignorance and shows the path to God.\n\nHowever, he also emphasized that the guru\'s grace and God\'s grace are ultimately one and the same. The guru is the manifestation of divine grace in human form, guiding the disciple toward the ultimate truth.\n\nRamakrishna often spoke about divine grace using beautiful metaphors. He said the winds of grace are always blowing, but we must raise our sails to catch them. God\'s grace is constantly available, but we must make ourselves receptive to it through spiritual practice and sincere yearning.\n\nHe compared God\'s grace to insurance, saying it will help in times of need without limit. Just as the sun\'s light is always shining but clouds may obstruct it, so too divine grace is always present, but our ego and ignorance may prevent us from receiving it.\n\nThe path to receiving grace, according to Ramakrishna, is through humility, devotion, and the sincere practice of spiritual disciplines. When the devotee is ready, grace descends naturally, leading to God-realization. He taught that no amount of personal effort alone can achieve the goal without the touch of divine grace, yet grace comes only to those who earnestly seek it.'
    ),
    Article(
        heading: 'Living in the World with Spiritual Wisdom',
        body: 'One of Ramakrishna\'s most practical teachings was how to live spiritually while engaged in worldly life. He recognized that not everyone can renounce the world and become a monk, yet spiritual life should not be limited to renunciates alone.\n\nHe gave several beautiful analogies for how to live in the world without being contaminated by it. Like a waterfowl that lives in water but whose feathers remain dry, or like a mudfish that lives in mud but whose skin remains bright and shiny, the spiritual aspirant should live in the world while remaining inwardly pure.\n\nRamakrishna taught that if one first fortifies oneself with true knowledge of the Universal Self, then living amid wealth and worldliness will not affect one negatively. The key is to establish oneself firmly in spiritual understanding before engaging fully with the world.\n\nHe emphasized the importance of regular spiritual practice even for householders. Setting aside time each day for prayer, meditation, and contemplation is essential. He advised people to create a space in their homes for worship and to maintain daily spiritual disciplines.\n\nRamakrishna also taught that service to others, when done with the right attitude, is service to God. Seeing God in all beings and serving them with love and compassion is a powerful spiritual practice. He showed through his own life that one could maintain the highest spiritual consciousness while interacting with people from all walks of life.\n\nHis message was clear: spiritual life is not separate from daily life. When every action is done with awareness of the Divine, when every person is seen as a manifestation of God, then the entire life becomes a spiritual practice. This practical approach to spirituality has made his teachings accessible and relevant to millions of people leading ordinary lives.'
    )
  ],
);
