// shankaracharya_en.dart
// Shankaracharya quotes and articles

import '../articlesquotes.dart';

final shankaracharyaSaint = Saint(
  'Shankaracharya',
  'Shankaracharya',
  'assets/images/shankaracharya.jpg',
  [
    'Brahman alone is real, the world is appearance.',
    'The Self is beyond birth and death, beyond all qualities and limitations.',
    'Knowledge alone can destroy ignorance, just as light alone can destroy darkness.',
    'That art thou - Tat tvam asi.',
    'I am Brahman - Aham Brahmasmi.',
    'Brahman is Existence, Consciousness and Bliss absolute.',
    'The Self is the witness of all, but is itself beyond witnessing.',
    'Maya is neither real nor unreal, but indescribable.',
    'The wise see the Self in all beings and all beings in the Self.',
    'Attachment is the root of all suffering.',
    'Renunciation is not running away from the world, but understanding its true nature.',
    'The guru is Brahman himself appearing in human form to guide the disciple.',
    'Liberation is not something to be attained, but something to be realized.',
    'The Self never changes, it is the eternal witness of all changes.',
    'Devotion to God is the purification of the heart.',
    'Knowledge and devotion are not different, they are two sides of the same coin.',
    'The three gunas bind the soul to samsara.',
    'Beyond the three gunas is the eternal, unchanging Self.',
    'Meditation is the direct means to Self-realization.',
    'The mind is the cause of bondage and liberation.',
    'When the mind is purified, the Self shines forth naturally.',
    'The scriptures are like a lamp that shows the way to the Self.',
    'Truth is one, though the wise call it by different names.',
    'The individual self and the Supreme Self are one and the same.',
    'Ignorance veils the Self like clouds veil the sun.',
    'The world is like a dream, real while experienced but unreal from the absolute standpoint.',
    'Karma binds only the ego, not the Self.',
    'The Self is beyond action and inaction.',
    'Desire is the fuel that keeps the wheel of samsara turning.',
    'Contentment is the greatest wealth.',
    'The wise are not disturbed by pleasure or pain.',
    'Peace is the nature of the Self.',
    'The Self needs no support, it is self-existent.',
    'Discrimination between the real and unreal is the beginning of wisdom.',
    'The Self is neither this nor that, but pure consciousness.',
    'In deep sleep, the Self alone remains.',
    'The Self is the light by which all else is known.',
    'Time and space are concepts of the mind.',
    'The Self is beyond time, space, and causation.',
    'Surrender to God is the easiest path to liberation.',
    'God is not separate from you, you are That.',
    'The ultimate reality is beyond all concepts and descriptions.',
    'Silence is the highest teaching.',
    'The Self realizes itself by itself.',
    'There is no path to the Self, you are already That.',
    'The wave is not different from the ocean.',
    'All diversity is superimposed on the one Reality.',
    'The Self is eternally free and pure.',
    'Bondage and liberation are concepts of the mind.',
    'The Self is the substratum of all experience.',
    'Brahman is real, the world is appearance, and the individual self is not different from Brahman. This is the essence of all Vedānta.',
    'So long as a man does not realize the Self, so long he must experience the bondage of ignorance, which is the cause of birth, death, and sorrow.',
    'Knowledge alone destroys ignorance, just as light alone removes darkness. Action cannot destroy ignorance, for ignorance is not opposed to action.',
    'The Self is the witness of the intellect and its activities, eternal, free, one, and full, distinct from the gross and subtle bodies.',
    'Just as the rope is mistaken for a snake in darkness, so the Self is mistaken for the body due to ignorance.',
    'The wise man should carefully discriminate between the real and the unreal, knowing that only Brahman is real and all else is transient.',
    'Liberation is not something to be produced, modified, or attained. It is simply the realization of one\'s own true nature.',
    'The Self is self-luminous and does not depend on any other means of knowledge. It is known when ignorance is destroyed.',
    'Neither by rituals, nor by progeny, nor by wealth, but by renunciation alone is immortality attained.',
    'The body, senses, and mind are objects of perception. The perceiver of all these is the Self, distinct and ever-free.',
    'One who has realized the Truth sees no difference between a learned scholar and an outcaste, between a cow and an elephant.',
    'Bondage and liberation are creations of ignorance. In truth, the Self is ever free.',
    'The mind purified by discrimination and detachment becomes fit to realize Brahman.',
    'As the sun illumines everything without effort, so the Self illumines all experiences.',
    'He who identifies himself with the body is ignorant; he who knows himself as the Self is liberated.',
    'Desire is the root of bondage. When desire is destroyed, the mind becomes tranquil.',
    'Renunciation is not the abandonment of actions, but the abandonment of the sense of doership.',
    'Just as space remains untouched by the objects within it, so the Self remains unaffected by the activities of the body and mind.',
    'The ignorant see diversity; the wise see the One Reality appearing as many.',
    'When ignorance is destroyed, the Self shines forth by itself, just as the sun shines when clouds disperse.',
    'The sense of \'I\' associated with the body is false. The real \'I\' is pure consciousness.',
    'The world is unreal in the sense that it has no independent existence apart from Brahman.',
    'The knower of Truth is free even while living, seeing all actions as belonging to the body alone.',
    'Without knowledge of the Self, liberation is impossible, even after countless rituals.',
    'Discrimination between the eternal and the non-eternal is the first step on the path of knowledge.',
    'The Self is neither the doer nor the enjoyer. Doership belongs to the ego born of ignorance.',
    'That which is seen is unreal; the seer alone is real.',
    'When the mind is purified, it reflects the light of the Self clearly.',
    'Just as dream objects vanish upon waking, so the world vanishes upon realization of Truth.',
    'The Self is beyond birth and death, beyond sorrow and delusion.',
    'Knowledge does not arise from action; it arises from inquiry guided by a teacher.',
    'The wise man lives unattached, like a witness, free from longing and fear.',
    'The sense of separateness is ignorance; non-duality is Truth.',
    'He who knows Brahman becomes Brahman.',
    'The Self is not an object of meditation; it is the very subject that meditates.',
    'Even a learned man is bound if he lacks discrimination and detachment.',
    'The wise renounce not the world, but the false notion of reality in the world.',
    'Ignorance projects the world; knowledge dissolves it.',
    'The Self is the same in waking, dream, and deep sleep.',
    'Liberation is freedom from ignorance, not a change of place or state.',
    'Attachment to the body is the cause of fear.',
    'The one Reality appears as many due to the power of illusion.',
    'Knowledge dawns when the mind becomes steady and pure.',
    'The Self is infinite, while the body is finite. Know this difference and be free.',
    'He who sees the Self everywhere attains supreme peace.',
    'The ego is the knot binding consciousness to the body.',
    'Only through knowledge does one cross the ocean of samsara.',
    'The Self is beyond speech and mind, yet it is self-evident.',
    'As clay alone is real in all clay forms, so Brahman alone is real in all names and forms.',
    'Detachment is born of understanding the impermanence of the world.',
    'Knowledge once arisen does not perish.',
    'The Self is untouched by virtue and vice.',
    'When ignorance is destroyed, the cycle of birth and death ends.',
    'The wise see actionless awareness in the midst of action.',
    'Inquiry into the Self is the direct means to liberation.',
    'The Self neither acts nor enjoys; it only illumines.',
    'Without renunciation, knowledge does not become steady.',
    'Brahman is one without a second.',
    'The liberated one sees the world as a passing appearance.',
    'Fear arises from duality.',
    'The Self is the light of lights.',
    'Knowledge destroys karma at the root.',
    'The wise one remains content in the Self alone.',
    'The Self is eternal, while the body is perishable.',
    'All sorrow belongs to the mind, not to the Self.',
    'Liberation is the direct knowledge of one\'s identity with Brahman.',
    'The Self is beyond all attributes.',
    'Just as ignorance causes bondage, knowledge causes freedom.',
    'The knower of Truth is ever satisfied.',
    'The Self is not affected by pleasure or pain.',
    'Brahman alone exists; plurality is imagined.',
    'The wise abandon desire for the fruits of action.',
    'Self-knowledge alone gives lasting peace.',
    'The Self is free from birth, decay, and death.',
    'The illusion of individuality arises from ignorance.',
    'The one who knows the Self transcends all sorrow.',
    'Knowledge dawns when the mind is purified by renunciation.',
    'The Self is ever pure.',
    'The world has only empirical reality, not absolute reality.',
    'The wise live unattached, like a lotus leaf in water.',
    'The Self is the witness of all experiences.',
    'Knowledge removes ignorance completely.',
    'The realized one sees no difference anywhere.',
    'The Self is beyond cause and effect.',
    'Detachment and knowledge go hand in hand.',
    'The Self alone is permanent.',
    'Bondage is imaginary; freedom is real.',
    'The knower of Brahman attains supreme bliss.',
    'The Self is not an object of experience, but the experiencer.',
    'All scriptures point to the knowledge of the Self.',
    'Ignorance alone causes transmigration.',
    'The Self is infinite consciousness.',
    'Knowledge once attained does not perish.',
    'The wise rest in the Self alone.',
    'Brahman is beyond all limitations.',
    'The Self is ever free.',
    'Liberation is here and now.',
    'The Self is the substratum of all appearances.',
    'Knowledge of the Self is the highest knowledge.',
    'Knowing \'I am Brahman,\' one becomes established in eternal peace.'
  ],
  [
    Article(
        heading: 'The Nature of Brahman',
        body: 'Brahman is existence absolute, consciousness absolute, and bliss absolute. It is without attributes (nirguna), beyond all qualities and limitations. It is not this, not that (neti neti), yet it is the reality behind all appearances.\n\nBrahman is the ultimate truth, the ground of all being. It is neither born nor does it die, neither increases nor decreases. It is eternal, infinite, and unchanging. The entire universe appears in Brahman like waves in the ocean, yet Brahman remains unaffected.\n\nTo realize Brahman is to understand that the individual self (Atman) and the Supreme Self (Brahman) are one and the same. This realization is not intellectual understanding but direct experience - the culmination of spiritual practice.\n\nBrahman cannot be known through the senses or mind, for it is the very consciousness by which all else is known. It is self-evident, self-luminous, and self-existent. When all superimpositions are removed, what remains is Brahman alone.'
    ),
    Article(
        heading: 'Maya and the World',
        body: 'Maya is the mysterious power by which the one appears as many. It is neither real nor unreal but indescribable (anirvachaniya). Maya veils the true nature of Brahman and projects the world of multiplicity.\n\nThe world, from the absolute standpoint, is neither real nor unreal. It appears real to the ignorant but is known to be apparent to the wise. Like a dream that seems real while being experienced, the world has empirical reality but no ultimate reality.\n\nMaya operates through the three gunas - sattva (harmony), rajas (activity), and tamas (inertia). These three qualities in various combinations create all the diversity we see. The wise transcend the gunas and realize their true nature beyond all qualities.\n\nUnderstanding maya is crucial for liberation. When we realize that the world is a superimposition on Brahman, we are no longer bound by it. We can function in the world while knowing its true nature.'
    ),
    Article(
        heading: 'The Path to Liberation',
        body: 'Liberation (moksha) is not something to be attained but something to be realized. We are already free; ignorance alone makes us feel bound. The path to liberation involves removing this ignorance through knowledge (jnana).\n\nThe traditional path involves three steps: hearing the truth (shravana), reflecting on it (manana), and meditating on it (nididhyasana). Through this process, the truth becomes direct experience.\n\nDiscrimination (viveka) between the real and unreal is essential. We must learn to distinguish between the Self and the not-self, the eternal and the temporary, consciousness and its contents.\n\nDispassion (vairagya) naturally follows discrimination. When we truly understand the temporary nature of worldly pleasures, attachment falls away naturally.\n\nThe four qualifications for spiritual practice are: discrimination, dispassion, the six virtues (including tranquility and self-control), and an intense desire for liberation. With these qualifications and the grace of a guru, liberation is assured.'
    )
  ],
);
