// articlesquotes.dart
// Contains saints, quotes, and articles data for the app.

class Article {
  final String heading;
  final String body;
  Article({required this.heading, required this.body});
}

class Saint {
  final String id;
  final String name;
  final String image;
  final List<String> quotes;
  final List<Article> articles;
  Saint(this.id, this.name, this.image, this.quotes, this.articles);
}

final saints = [
  Saint(
    'vivekananda',
    'Swami Vivekananda',
    'assets/images/vivekananda.jpg',
    [
      'Arise, awake, and stop not till the goal is reached.',
      'Take up one idea. Make that one idea your life — think of it, dream of it, live on that idea.',
      'Be a hero. Always say, \'I have no fear.\' Fear is death, fear is sin, fear is hell.',
      'The world is a grand moral gymnasium wherein we have all to take exercise so as to become stronger and stronger spiritually.',
      'You will be nearer to Heaven through football than through the study of the Gita.',
      'Everything can be sacrificed for truth, but truth cannot be sacrificed for anything.',
      'One who serves jiva, is indeed worshipping Shiva.',
      'O India! Forget not that the lower classes, the ignorant, the poor, the illiterate, the cobbler, the sweeper, are thy flesh and blood, thy brothers.',
      'We are what our thoughts have made us; so take care about what you think. Words are secondary. Thoughts live; they travel far.',
      'Sisters and brothers of America, it fills my heart with joy unspeakable to rise in response to the warm and cordial welcome which you have given us.',
  'All power is within you; you can do anything and everything.',
  'The greatest sin is to think yourself weak.',
  'Strength is life, weakness is death. Expansion is life, contraction is death. Love is life, hatred is death.',
  'The world is the great gymnasium where we come to make ourselves strong.',
  'Whatever you think, that you will be. If you think yourselves weak, weak you will be; if you think yourselves strong, strong you will be.',
  'Stand up, be bold, be strong. Take the whole responsibility on your own shoulders, and know that you are the creator of your own destiny.',
  'Have faith that you are all, my brave lads, born to do great things!',
  'You cannot believe in God until you believe in yourself.',
  'Be a hero. Always say, "I have no fear."',
  'Never think there is anything impossible for the soul.',
  'Don\'t be thwarted by anything. How many days will this body last, with its happiness and misery? When you have got the human body, then rouse the Atman within and say — I have reached the state of fearlessness!',
  'We must have infinite patience, infinite purity, and infinite perseverance. Success is bound to come.',
  'Have infinite patience, and success is yours.',
  'He who struggles is better than he who never attempts.',
  'Be free; hope for nothing from anyone. I am sure if you look back upon your lives you will find that you were always vainly trying to get help from others which never came.',
  'The only religion that ought to be taught is the religion of fearlessness.',
  'Do not wait for anybody or anything. Do whatever you can. Build your hope on none.',
  'All the strength and succor you want is within yourself.',
  'Take risks in your life. If you win, you can lead; if you lose, you can guide.',
  'We want the education by which character is formed, strength of mind is increased, the intellect is expanded, and by which one can stand on one\'s own feet.',
  'Education is not the amount of information that is put into your brain and runs riot there, undigested, all your life.',
  'The training by which the current and expression of will are brought under control and become fruitful is called education.',
  'To me the very essence of education is concentration of mind, not the collecting of facts.',
  'First make character—that is the highest duty you can perform.',
  'Money does not pay, nor name; fame does not pay, nor learning. It is love that pays; it is character that cleaves its way through adamantine walls of difficulties.',
  'Character has to be established through a thousand stumbles.',
  'Every fool may become a hero at one time or another. Watch a man do his most common actions; those are indeed the things which will tell you the real character of a great man.',
  'Character is repeated habits, and repeated habits alone can reform character.',
  'Every work that we do, every movement of the body, every thought that we think, leaves an impression on the mind-stuff. Our character is the sum-total of these marks.',
  'Take up one idea. Make that one idea your life - think of it, dream of it, live on that idea. Let the brain, muscles, nerves, every part of your body, be full of that idea, and just leave every other idea alone. This is the way to success.',
  'The great secret of true success, of true happiness, is this: the man or woman who asks for no return, the perfectly unselfish person, is the most successful.',
  'Work for work\'s sake. Worship for worship\'s sake. Do good because it is good to do good. Ask no more.',
  'It is better, far better to die on the field of duty, preaching the truth, than to die like a worldly worm.',
  'The whole secret of existence is to have no fear.',
  'In a day, when you don\'t come across any problems - you can be sure that you are travelling in a wrong path.',
  'He who has infinite patience and infinite energy at his back, will alone succeed.',
  'Persevere on, my brave lads. We have only just begun. Never despond! Never say enough!',
  'In a conflict between the heart and the brain, follow your heart.',
  'The man who is pure, who is unselfish, can alone see God. And to see God is to become God.',
  'This life is short, the vanities of the world are transient, but they alone live who live for others, the rest are more dead than alive.',
  'All great undertakings are achieved through mighty obstacles.',
  'Be perfectly unselfish, be steady and work on. We will do great things; do not fear.',
  'The more we come out and do good to others, the more our hearts will be purified.',
  'The greatest help to a spiritual life is meditation. The next is good company.',
  'The fire that warms us can also consume us; it is not the fault of the fire.',
  'The best test of a person\'s character is how they treat those who can do nothing for them.',
  'Learn everything that is good from others, but bring it in, and in your own way absorb it; do not become others.',
  'The only way to rise is by doing the duty next to us, and thus gathering strength, go on until we reach the highest state.',
  'Be cheerful. Hold on to your own ideal. Be the servant of all.',
  'Religion is the manifestation of the divinity already in man.',
  'You have to grow from the inside out. None can teach you, none can make you spiritual. There is no other teacher but your own soul.',
  'The moment I have realized God sitting in the temple of every human body, the moment I stand in reverence before every human being and see God in him - that moment I am free from bondage.',
  'To devote your life to the good of all and to the happiness of all is religion. Whatever you do for your own sake is not religion.',
  'The greatest religion is to be true to your own nature. Have faith in yourselves!',
  'Do not merely endure; be unattached.',
  'The varieties of religious belief are an advantage, since all faiths are good, so far as they encourage us to lead a religious life.',
  'Religion has no business to formulate social laws and insist on the difference between beings, because its aim and end is to obliterate all such fictions and monstrosities.',
  'The first sign that you are becoming religious is that you are becoming cheerful.',
  'To believe blindly is to degenerate the human soul. Be an atheist if you want, but do not believe in anything unquestioningly.',
  'We must approach religion with reverence and with love, and our heart will stand up and say, "This is truth, and this is untruth."',
  'The greatest religion is to be true to your own nature. Have faith in yourselves!',
  'He who is poor and has nothing, is the great God. He who is rich and has everything, is the servant of all.',
  'As long as I live, I will have control over my being.',
  'Be perfectly resigned, perfectly unconcerned; then alone can you do any true work.',
  'Neither seek nor avoid, take what comes.',
  'Feel nothing, know nothing, do nothing, have nothing, give up all to God, and say utterly, "Thy will be done."',
  'We must not only be bright and cheerful, but we must make others bright and cheerful.',
  'The goal of human life is to attain freedom.',
  'Each soul is potentially divine.',
  'Talk to yourself once in a day, otherwise you may miss meeting an intelligent person in this world.',
  'Truth can be stated in a thousand different ways, yet each one can be true.',
  'Our thoughts make us. If we are bad, we are but the result of our bad thoughts. If we are good, it is because of our good thoughts.',
  'The mind is like a mad monkey, and the will is the rope to tie it.',
  'The greatest help to a spiritual life is meditation. The next is good company.',
  'The mind is a power which can be used to conquer the world.',
  'Be not afraid of anything. You will do marvelous work. The moment you are afraid, you are nobody.',
  'The more we are in harmony with the universe, the more we are in tune with ourselves.',
  'The mind that is born to succeed joins itself to a determined will and perseveres.',
  'Each man\'s character is determined by the sum total of these impressions on the mind.',
  'The man who is pure and a living example of the highest teaching is a true teacher.',
  'We are what our thoughts have made us; so take care about what you think.',
  'All knowledge is within us. It is the human mind that manifests all knowledge.',
  'The mind acts as a sieve through which the universal knowledge flows into our consciousness.',
  'The human mind is a great reservoir of knowledge. Our thoughts are the only channel through which this knowledge flows out.',
  'The mind is like a wild horse, which has to be tamed. The senses are the reins, and the will is the rider.',
  'You have to control your mind. The mind is the source of all your joy and sorrow.',
  'Thoughts, when they are strong, create reality. A strong mind can move mountains.',
  'What you think, you become. What you feel, you attract. What you imagine, you create.',
  'The mind can be a powerful tool for good or evil. It is up to you to decide how to use it.',
      'They alone live who live for others.',
      'All differences in this world are of degree, and not of kind, because oneness is the secret of everything.',
      'Learn everything that is good from others, but bring it in, and in your own way absorb it.',
  'The more we are in harmony with the universe, the more we are in tune with ourselves.',
  'We must be bold enough, must be brave enough to speak of their defects, but at the same time we must give the credit that is due to them.',
      'Do not injure any one. Do not be jealous. Do not hate. Love is the only law.',
      'Do not quarrel with others. Be tolerant. Accept all religions as true.',
      'The great men think, and you and I also think. But there is a difference. We think and our bodies do not follow.',
  'My ideal indeed can be put into a few words and that is: to preach unto mankind their divinity, and how to make it manifest in every movement of life.',
  'The goal of life is to manifest the divine within by controlling nature, external and internal.'
    ],
    [
      Article(
        heading: 'Swami Vivekananda: Short life sketch',
        body: 'The great secret of true success, of true happiness, is this: the man or woman who asks for no return, the perfectly unselfish person, is the most successful.” -Swami Vivekananda'

      '\n\nSwami Vivekananda (1863-1902) was one of the most distinguished spiritual leaders of India. As a patriot-saint, he encouraged Indians to serve their country by focusing on the economically disadvantaged. He left behind a legacy of spiritual awakening and national revival.'

    '\n\nIn 1890, Swami Vivekananda set out as a parivrajaka (monastic wanderer) across India. During his two-year sojourn, he became convinced about two things related to India. He saw the future India resplendent and had an action plan for its uplift.'

    '\n\nVivekananda was an instant success at the Parliament of Religions in Chicago. He laid down the basis of cooperation between religions of how it is impossible to impose a single dogma on everyone. Just like plants, a Hindu, Buddhist or Christian "must assimilate the spirit of the others".'

    '\n\nHe visited America from 1893 to 1896, giving lectures in public and private gatherings in the East Coast and Mid-West of America as well as in London.'

    '\n\nOn May 1, 1897, Swami Vivekananda founded the Ramakrishna Mission in Calcutta. His purpose behind setting up this organisation was to spread the teachings of Sri Ramakrishna. The motto of this institution is for one\'s spiritual liberation and the welfare of the world. The Ramakrishna Mission, maintains an impeccable reputation in work related to the spiritual and social welfare of the nation. Swamiji has also inspired the establishment of a number of other organisations, such as the Vivekananda Kendra.'

    '\n\nIn 1899, Swami Vivekananda left for his second trip to the West and reached London on July 31. On July 4, 1902, he finally attained mahasamadhi at Belur Math.'

    '\n\nVivekananda\'s most important work in the West was to sow the seeds of Vedanta. Vedanta is the message of the oneness of Existence; it is derived from the teachings of the Upanishads. Vivekananda underscored the dimension of religious pluralism and universalism.'

    '\n\nHe taught that there is only one reality and that all paths (religions) lead to the same goal (God-realisation).'

    '\n\nVivekananda synthesised the several Yogas (means of spiritual realisation) after reading the Bhagavad Gita. According to him, the four Yogas are diverse ways of achieving the same spiritual objective. He had shown the way for the practical application of the lofty Vedantic ideal of oneness.'

    '\n\nIn his historic speech delivered on 11th September, 1893 in the world parliament of religions, Chicago he spoke about how Hinduism is a religion which has taught the world tolerance and universal acceptance.'

    '\n\nSwami Vivekananda\'s emphasis on service to humanity as a way of both human fulfillment and soul uplift sets him apart from many other religious and spiritual leaders around the world. In fact, the zeal with which he preached this ideal transformed him from pure spirituality to a throbbing empathy for colonial India\'s suffering, poverty-stricken masses.'

    '\n\nSwami Vivekananda’s work and vision had a deep impact not only in India but throughout the globe which was witnessed from his numerous followers and even western disciples like Sister Nivedita, Sister Christine and many others.'

    '\n\nHis legacy will remain eternal.'
      ),
      Article(
        heading: 'Address to World Parliament of Religions',
        body: 'Sisters and Brothers of America, It fills my heart with joy unspeakable to rise in response to the warm and cordial welcome which you have given us. I thank you in the name of the most ancient order of monks in the world; I thank you in the name of the mother of religions; and I thank you in the name of millions and millions of Hindu people of all classes and sects. \n\nMy thanks, also, to some of the speakers on this platform who, referring to the delegates from the Orient, have told you that these men from far-off nations may well claim the honour of bearing to different lands the idea of toleration. I am proud to belong to a religion which has taught the world both tolerance and universal acceptance. We believe not only in universal toleration, but we accept all religions as true. I am proud to belong to a nation which has sheltered the persecuted and the refugees of all religions and all nations of the earth. I am proud to tell you that we have gathered in our bosom the purest remnant of the Israelites, who came to Southern India and took refuge with us in the very year in which their holy temple was shattered to pieces by Roman tyranny. I am proud to belong to the religion which has sheltered and is still fostering the remnant of the grand Zoroastrian nation. I will quote to you, brethren, a few lines from a hymn which I remember to have repeated from my earliest boyhood, which is every day repeated by millions of human beings: “As the different streams having their sources in different places all mingle their water in the sea, so, O Lord, the different paths which men take through different tendencies, various though they appear, crooked or straight, all lead to Thee.” \n\n  The present convention, which is one of the most august assemblies ever held, is in itself a vindication, a declaration to the world of the wonderful doctrine preached in the Gita: “Whosoever comes to Me, through whatsoever form, I reach him; all men are struggling through paths which in the end lead to me.” Sectarianism, bigotry, and its horrible descendant, fanaticism, have long possessed this beautiful earth. They have filled the earth with violence, drenched it often and often with human blood, destroyed civilisation and sent whole nations to despair. Had it not been for these horrible demons, human society would be far more advanced than it is now. But their time is come; and I fervently hope that the bell that tolled this morning in honour of this convention may be the death-knell of all fanaticism, of all persecutions with the sword or with the pen, and of all uncharitable feelings between persons wending their way to the same goal.'

      )
    ],
  ),
  Saint(
    'sivananda',
    'Swami Sivananda',
    'assets/images/sivananda.jpg',
    [
      'An ounce of practice is worth a ton of theory!',
      'Put your heart, mind, and soul into even your smallest acts. This is the secret of success.',
      'If you do not find peace within, you will not find it anywhere else.',
      'Don\'t fear the darkness if you carry the light within.',
      'The mind is responsible for the feelings of pleasure and pain. Control of the mind is the highest Yoga.',
      'Cultivate peace first in the garden of your heart by removing the weeds of lust, hatred, greed, selfishness, and jealousy.',
      'Look within. Within you is the hidden God. Within you is the immortal soul.',
      'Love expects no reward. Love knows no fear. Love Divine gives - does not demand.',
      'Patient and regular practice is the whole secret of spiritual realization. Do not be in a hurry in spiritual life.',
      'Make others truly happy as you strive to make yourself happy. Speak a helpful word. Give a cheering smile. Do a kind act.',
  'Serve, love, give, purify, meditate, realize.',
  'An ounce of practice is better than a ton of theory.',
  'The spiritual path is a razor\'s edge.',
  'God is not a remote reality but the indwelling Reality, nearer to you than anything else on earth.',
  'Love is the greatest creative force in the world.',
  'This world is your best teacher. There is a lesson in everything. There is a lesson in each experience. Learn it and become wise.',
  'Self-analysis is the greatest art of progress.',
  'Where there is no selfishness, there is peace, joy, and illumination.',
  'You are the author of your own fate. You yourself have created this. You yourself are entirely responsible for this.',
  'The secret of perfect health, perfect happiness, and perfect success is to control your own mind.',
  'Be wise and realize the true purpose of life.',
  'Sow the seed of self-discipline. Water it with love.',
  'The crown of spiritual life is the vision of unity.',
  'Develop always positive and constructive thoughts.',
      'Renounce what is earthly, if you wish to attain what is eternal.',
      'Every failure is a stepping stone to success.',
      'The hardest thing on earth, if only one would be honest with oneself, is to be good in reality.',
      'Humility is not cowardice. Meekness is not weakness. They are spiritual powers.',
      'The divine within you is stronger than anything that is without you.',
      'True spirituality is to be an athlete in the race of life.',
      'As you think, so you become.',
      'Man sows a thought and reaps an action. He sows an action and reaps a habit. He sows a habit and reaps a character. He sows a character and reaps a destiny.',
      'A mountain is composed of tiny grains of earth. The ocean is made up of tiny drops of water. Even so, life is but an endless series of little details, actions, speeches, and thoughts.',
      'Destroy the evil-finding quality. Develop the good-finding quality.',
      'Fear is only in duality. Fear is Mind. When you are your Self, there is no fear.',
      'The mind is the cause of all pains and sorrows.',
      'Do not store in your brain useless information. Learn to unmind the mind.',
      'If you think about disaster, you will get it. Brood about death and you hasten your demise. Think positively and masterfully, with confidence and faith, and life becomes more secure.',
      'Every thought cuts a groove in our face.',
      'The mind is responsible for the feelings of pleasure and pain.',
      'A pure and calm mind is essential for wisdom.',
      'The mental ability to concentrate is inherent to all; it is not extraordinary or mysterious.',
      'Control of the mind is the highest Yoga.',
      'Thoughts become actions. Actions become habits. Habits become character. Character becomes destiny.',
      'The mind is like a wild horse, which has to be tamed.',
      'What limits the individual soul\'s vision? It is only the mind.',
      'Thoughts, when they are strong, create reality.',
  'The more you meditate, the more you will realize that you are not the body, but the immortal soul.',
  'The face is the index of the mind.',
  'The mind is a great reservoir of knowledge. Our thoughts are the only channel through which this knowledge flows out.',
  'Meditation is the dissolution of thoughts in Eternal awareness or Pure consciousness without objectification, knowing without thinking.',
  'Regular meditation opens the avenues of intuitional knowledge.',
  'The language of silence is the language of God, the language of silence is the language of the heart.',
  'Meditation is painful in the beginning but it bestows immortal bliss and supreme joy in the end.',
  'To achieve that state of lasting happiness and absolute peace, we must first know how to calm the mind, to concentrate and go beyond the mind.',
  'Practice meditation regularly. Meditation leads to eternal bliss.',
  'Introvert. Introspect. Investigate and intuit.',
  'To get rid of external conflicts we should go to the inner solitude.',
  'Prevent your mind from going outwards, become still and watch it.',
  'Silence is the gateway to the divine.',
  'Every moment in the waking state that is free from thought is a state of Samadhi.',
  'The more you delve into silence, the more you will hear the inner voice.',
  'The true meaning of meditation is to be one with the divine.',
  'Through meditation, you can discover your true Self.',
  'Meditation is the only way to find lasting peace.',
  'Every human being is the author of his own health or disease.',
  'Health is that state in which man jumps, sings, smiles, laughs, whistles and moves about hither and thither with joy and ecstasy.',
  'A sound mind in a sound body.',
  'Pain is the best thing in the world. It is an eye-opener. It awakens your dormant faculties.',
  'Physical health is to make sure the body functions well and has best rules of conduct, following the rhythm of nature.',
  'The more you understand Oneness, the healthier you are.',
  'The atoms, molecules and cells in their bodies produce discordant or inharmonious vibrations. They have no hope, confidence, faith, serenity and cheerfulness. They are unhappy.',
  'Your face is a mirror. Whatever you are thinking is immediately written on your face.',
  'An evil thought darkens the face and aura. A divine thought brightens the face and even the aura.',
  'Cultivate peace first in the garden of your heart.',
  'Love beautifies the giver and elevates the receiver.',
  'To love is to share and serve.',
  'Love expects no reward. Love knows no fear. Love Divine gives - does not demand.',
  'Love is the only law. Love is the only reality.',
  'Love is the greatest creative force in the world.',
  'Where there is love, there is God.',
  'The lessons of life has ever been \'Hatred is not overcome by hatred, by love alone is hatred conquered\'.',
  'Be kind to everyone, for everyone is fighting a great battle.',
  'Love all, serve all, for all are one in God.',
  'To serve others is to serve God.',
  'Put your heart, mind, and soul into even your smallest acts. This is the secret of success.',
  'Stand not a beggar before the door of science seeking power that kills more than heals.',
  'The harder the struggle, the more glorious the triumph.',
  'Never worry about what other people say or think. Do the right. Have a clear conscience and roam about happily.',
  'Today is your own. Tomorrow perchance may never come.',
  'A life without good health is a miserable condition.',
  'Be cheerful. Hold on to your own ideal. Be the servant of all.',
  'The law of karma is not a punishment; it is a law of cause and effect.',
  'The true goal of life is to get back to the source from which we came.',
  'The greatest help to a spiritual life is meditation. The next is good company.',
      'The more you come out and do good to others, the more your hearts will be purified.',
      'You are the master of your own destiny.',
      'The universe is a vast temple of His presence.',
  'Every soul is potentially divine.',
  'All knowledge is within us. It is the human mind that manifests all knowledge.',
      'God reveals Himself in different ways at different stages of evolution.',
      'This world is an overflow of the bliss of God.',
      'The true meaning of life is to realize that you are one with God.',
  'You are the spark of divinity. Assert this and roam fearlessly.',
  'Consciousness, though invisible, illumines everything.',
      'The more you love God, the more you will be able to love all others, for you will see God in them all.',
      'The goal of life is to manifest the divine within by controlling nature, external and internal.',
      'The only way to rise is by doing the duty next to us.',
  'All is God. All is Spirit. All is one.',
  'The goal of human life is to attain freedom.'
    ],
    [
      Article(
        heading: 'Karma Yoga',
        body: 'Paramatman is a profound and multifaceted concept in Hindu philosophy...'
      ),
      Article(
        heading: 'Article 2 about Saint Vivekananda',
        body: 'Body of article 2...'
      )
    ],
  ),
  Saint(
    'yogananda',
    'Paramhansa Yogananda',
    'assets/images/paramhansa.jpg',
    [
      'You must not let your life run in the ordinary way; do something that nobody else has done, something that will dazzle the world.',
      'The season of failure is the best time for sowing the seeds of success.',
      'Be as simple as you can be; you will be astonished to see how uncomplicated and happy your life can become.',
      'Live quietly in the moment and see the beauty of all before you. The future will take care of itself.',
      'The happiness of one\'s own heart alone cannot satisfy the soul; one must try to include, as necessary to one\'s own happiness, the happiness of others.',
      'Change yourself and you have done your part in changing the world.',
      'Persistence guarantees that results are inevitable.',
      'Remain calm, serene, always in command of yourself. You will then find out how easy it is to get along.',
      'Let my soul smile through my heart and my heart smile through my eyes, that I may scatter rich smiles in sad hearts.',
      'The power of unfulfilled desires is the root of all man\'s slavery.',
      'Happiness depends on the state of your mind, not on the state of your possessions.',
      'The secret of success and happiness is inside you. If you have found success and prosperity outside, but not inside, you are not truly successful.',
      'Peace emanates from the soul, and is the sacred inner environment in which true happiness unfolds.',
      'Having lots of money while not having inner peace is like dying of thirst while bathing in the ocean.',
      'A truly successful person is happy and contented and lives according to his or her own principles.',
      'You have to find true peace and happiness within yourself. Your outer experiences should be only fun.',
      'To be ecstatic is not difficult. To be calmly joyous is the difficult part. That is the ideal.',
      'Live each present moment completely and the future will take care of itself.',
      'The more you practice the presence of peace, the more you will feel the presence of that power in your life.',
      'The whole secret of existence is to have no fear.',
      'Kindness is the light that dissolves all walls between souls, families, and nations.',
      'A little joy in life is better than a lot of possessions.',
      'Realize that the acting out of whatever part you are called upon to play does not affect your real being.',
      'The highest reward for a man\'s toil is not what he gets for it, but what he becomes by it.',
    'You are worthy of the blessings of spiritual consciousness.',
    'By the practice of meditation, you will find that you are carrying within your heart a portable paradise.',
    'The soul loves to meditate, for in contact with the Spirit lies its greatest joy.',
    'Meditation is the greatest way of resurrecting your soul from the bondage of the body.',
    'Meditation is the spring from which God\'s peace flows into your soul.',
    'To meditate a short time with depth is better than to meditate for long hours with the mind running wild.',
    'Be still and know that I am God.',
    'The devotee who makes the supreme effort is the one who finds God. Not the one who keeps seeking excuses.',
    'When you meditate, you will find doors opening to Him everywhere.',
    'Do not get excited or impatient in your efforts to find God. Be patient. Move toward your divine goal ever calmly, with tranquillity.',
    'The mind acts as a sieve through which the universal knowledge flows into our consciousness.',
    'The more you love God, the more you will be able to love all others, for you will see God in them all.',
    'The best test of a person\'s character is how they treat those who can do nothing for them.',
    'Do not do what you want, and then you may do what you like.',
    'The secret of success and happiness is inside you.',
    'You cannot be truly happy unless you are free from all attachments.',
    'Love gives without expecting anything in return.',
    'To wish for perfection for the loved one, and to feel pure joy in thinking of that soul, is divine love; and that is the love of true friendship.',
    'Love is the light that dissolves all walls between souls, families, and nations.',
    'The greatest love you can experience is in communion with God in meditation.',
    'Grieve not for lost love... Love itself is never lost, but just plays hide-and-seek with you in many hearts.',
    'Once you give your love, it must be forever. Not because you want to be near that person, but because you want perfection for that soul.',
    'The whole world is a playground for the soul.',
    'When you have communion with Him, not all the ravages of the world can take away that Joy and Peace.',
    'In the infinite love of God, my breast of eternity is large enough to hold everything in me.',
    'My heart is a temple of eternal love.',
    'To be a true friend, you must love others as yourself, for only then can you understand their needs and sorrows.',
    'Love is not a sentiment; it is the truth at the core of creation.',
    'The love of God, the love of the Spirit, is an all-consuming love.',
    'Be so drunk with the love of God night and day that you won\'t know anything but God.',
    'The love between the soul and Spirit is the perfect love, the love you are all seeking.',
    'As a mortal being you are limited, but as a child of God you are unlimited.',
    'The human mind is a spark of the almighty consciousness of God.',
    'Your thoughts make you. If you are bad, you are but the result of your bad thoughts. If you are good, it is because of your good thoughts.',
    'If you permit your thoughts to dwell on evil you yourself will become ugly.',
    'The power of God within you, the power of limitless control, lies in the superconscious mind.',
    'You are exactly the same after death as you were before. Nothing changes; you only give up the body.',
    'The mind is a power which can be used to conquer the world.',
    'Don\'t depend on death to liberate you from your imperfections.',
    'You have within you the power to accomplish everything you want; that power lies in the will.',
    'The mind is like a mad monkey, and the will is the rope to tie it.',
    'True self-analysis is the greatest art of progress.',
    'The season of failure is the best time for sowing the seeds of success.',
    'Our thoughts make us. What we think, we become.',
    'The more you concentrate, the more you will be able to do what you want to do.',
    'To overcome the mind is to be free.',
    'Death is really beautiful; if it were a bad thing, God would not let it happen to us.',
    'Dismiss this phantasma of disease and health, sorrow and joy. Rise above it. Become the Self.',
    'All souls come from God—individualized rays of pure Spirit—and evolve back to their native perfection.',
    'The wave is the same as the ocean, though it is not the whole ocean. So each wave of creation is a part of the eternal Ocean of Spirit.',
    'This life is short, the vanities of the world are transient, but they alone live who live for others, the rest are more dead than alive.',
    'The greatest battle you will ever fight is with your own mind.',
    'Every tomorrow is determined by every today.',
    'Be afraid of nothing. Hating none, giving love to all, feeling the love of God, seeing His presence in everyone.',
    'It is not your passing thoughts or brilliant ideas so much as your plain everyday habits that control your life.',
    'The whole world stands aside for the person who knows where he is going and is determined to get there.',
    'The best test of a person\'s character is how they treat those who can do nothing for them.',
    'What you think, you become. What you feel, you attract. What you imagine, you create.',
    'Be an athlete in the race of life; but remember that the true race is the one that is run within.',
    'By deliberate deeper acts of meditation each seeker must remove his restlessness.',
    'The secret of perfect health, perfect happiness, and perfect success is to control your own mind.',
    'You are the sum total of the consciousness we ourselves have created over a period of incarnations.',
    'The law of karma is not a punishment; it is a law of cause and effect. It is a law of perfect justice.',
    'Every man has the right to choose his own path, but he must also accept the consequences of his choices.',
    'Your destiny is in your hands, for you have the power to change your thoughts and actions.',
    'Your will power is the instrument of the image of God within you.',
    'A strong will, by its dynamic force, creates a way for its fulfillment.',
    'Be sure that your will power is used constructively, not for harmful purposes or trifling things.',
    'Your life is not a result of chance, but of your own making.',
    'The purpose of life is to live for others and to live in God.',
    'The greatest sin is to think yourself weak.',
    'The universe is a vast temple of His presence.',
    'Just beneath the shadows of this life is His wondrous Light.',
    'The soul is not in the body, but the body is in the soul.',
    'All is God. All is Spirit. All is one.',
    'The material world is a dream, but a dream that can be changed by the power of your mind.',
    'The world is the great gymnasium where we come to make ourselves strong.',
    'The illusion of a separate self is the source of all suffering.',
    'You are a part of the eternal Ocean of Spirit.',
    'The more you meditate, the more you will realize that you are not the body, but the immortal soul.',
    'The true meaning of life is to realize that you are one with God.',
    'The more you come out and do good to others, the more your hearts will be purified.',
    'Give to the world the best you have, and the best will come back to you.',
    'The law of prosperity is not governed by the law of selfishness, but by the law of unselfishness.',
    'The great secret of true success, of true happiness, is this: the man or woman who asks for no return, the perfectly unselfish person, is the most successful.',
    'To serve others is to serve God.'
    ],
    [
      Article(
        heading: 'Karma Yoga',
        body: 'Paramatman is a profound and multifaceted concept in Hindu philosophy...'
      ),
      Article(
        heading: 'Article 2 about Saint Vivekananda',
        body: 'Body of article 2...'
      )
    ],
  ),
  Saint(
    'raman',
    'Maharishi Raman',
    'assets/images/raman.jpg',
    [
      'Your own Self-Realization is the greatest service you can render the world.',
      'There is neither creation nor destruction, neither destiny nor free will, neither path nor achievement. This is the final truth.',
      'Happiness is your nature. It is not wrong to desire it. What is wrong is seeking it outside when it is inside.',
      'The question “Who am I?” will destroy all other questions.',
      'Wanting to reform the world without discovering one’s true self is like trying to cover the world with leather to avoid the pain of walking on stones and thorns.',
      'Silence is also conversation.',
      'The mind is nothing but thoughts. Stop thinking and show me the mind.',
      'The only useful purpose of the present birth is to turn within and realize the Self.',
      'No one succeeds without effort. Those who succeed owe their success to perseverance.',
      'Let what comes come. Let what goes go. Find out what remains.',
      'The question \'Who am I?\' is not a mere mental exercise. It is the highest form of spiritual practice.', 'The \'I\' thought is the root of all other thoughts. Holding on to it and tracing it back to its source is the only way to destroy all thoughts.', 'The Self is ever-present. You do not need to seek it, only to cease seeking what is not the Self.', 'The final truth is this: the \'I\' is not a thought; it is consciousness itself.', 'All that is required to realize the Self is to be still.', 'You are the Self. Be that.', 'To ask \'Who am I?\' is to turn the mind inwards and dive deep into the source.', 'Just as a snake is seen only in the rope, the ego is seen only in the Self.', 'The ego is the mind. The mind is the source of all desires.', 'The ego is not a real entity. It is a thought-form, a shadow that disappears when the light of the Self shines.', 'The mind is a phantom. It is nothing but a bundle of thoughts.', 'When the mind subsides, the Self is realized. The mind is the obstacle.', 'Realization is not a new acquisition. It is the rediscovery of your eternal nature.', 'The body and mind are not you. You are the witness of both.', 'When the \'I\' thought disappears, all other thoughts disappear with it.', 'Silence is the most potent form of spiritual instruction.', 'The best spiritual practice is to remain in stillness.', 'Realization is not something to be attained; it is something to be revealed in the absence of thought.', 'The silence of the heart is more eloquent than any speech.', 'True knowledge is not in the intellect; it is in the heart, and it is revealed in silence.', 'The ultimate state is the state of silence, where there is no \'I\' or \'you\'.', 'The Self is realized in a state of utter quietude.', 'To be still is the highest form of prayer.', 'True peace is the absence of all thoughts.', 'Meditation is not about thinking about God, but about being in the state of stillness, which is God.', 'The mind is a restless monkey. The only way to tame it is to be still.', 'Silence is the eternal state of the Self.', 'The more you are in silence, the more you will understand the truth.', 'Silence is not the absence of sound, but the presence of stillness.', 'The only true prayer is to be still and know that \'I am\'.', 'God is not an external being. God is the Self.', 'The world is an illusion. The Self alone is real.', 'Everything you see is God. Everything you hear is God.', 'The world is nothing but a projection of the mind.', 'There is no reality apart from the Self.', 'The world is not a separate entity from you.', 'The universe is in you, not you in the universe.', 'The only reality is the Self. The world, the ego, and God are all in the Self.', 'The world is a dream. The dreamer is the Self.', 'God is the source of all, the witness of all, and the reality of all.', 'There is only one reality, and that is consciousness.', 'God is love. Love is the light of the Self.', 'The world is an idea. The only reality is the Self.', 'The world is a manifestation of God, but God is not limited by the world.', 'The Self is the substratum of all existence.', 'Action is not the cause of bondage; the sense of doership is.', 'True action is effortless and spontaneous. It flows from the state of being.', 'Do not worry about the results of your actions. Let the Self take care of everything.', 'Action performed without the sense of doership leads to liberation.', 'Karma is a chain of cause and effect, but the Self is free from karma.', 'Live in the world, but not of the world.', 'The only way to be free from karma is to realize the Self.', 'Perform your duties without attachment to the results.', 'Surrender to the will of God, and all your actions will be effortless.', 'The one who has realized the Self has no karma.', 'Do not be a slave to your senses or your desires.', 'The more you serve others, the more you will realize the Self in them.', 'The highest form of action is to be a witness of all actions.', 'Action is a result of thought. Silence is the absence of both.', 'The world is a stage. Play your role, but do not forget who you are.', 'The Guru is not a person. The Guru is the Self.', 'The Guru is within you. The Guru is the inner voice.', 'The true Guru is the one who leads you to the Self.', 'The Guru\'s grace is always there. It is up to you to receive it.', 'The best way to honor your Guru is to realize the Self.', 'The Guru is a mirror in which you can see your true Self.', 'The Guru\'s grace is necessary for Self-realization.', 'The Guru is not the body. The Guru is the consciousness that resides in all hearts.', 'The Guru is a guide, not a provider.', 'The Guru\'s grace is the wind that helps you sail. Your effort is the sail itself.', 'Trust in the Guru, and the Guru will guide you to the truth.', 'The Guru is the living embodiment of the truth.', 'The Guru is not separate from you. You are one with the Guru.', 'The Guru\'s teaching is to be silent.', 'The Guru is the one who helps you to go beyond the mind.', 'The mind is the ego in action.', 'The ego is the sense of \'I am the body\'.', 'When the ego dies, the Self shines forth.', 'The greatest obstacle to Self-realization is the ego.', 'The ego is a collection of thoughts, feelings, and memories.', 'The mind is a beautiful servant but a dangerous master.', 'Liberation is not about going somewhere else. It is about being here, now.', 'The only way to kill the ego is to surrender to the Self.', 'The mind is a great deceiver. It creates the illusion of a separate self.', 'The ego is a fortress built of fear and desires.', 'To be free is to be free from the mind.', 'The mind is a mirror. What you see in it is a reflection of your own thoughts.', 'The mind is the cause of all suffering. The Self is the source of all joy.', 'The ego is the root of all problems. It is the one that says \'I want\'.', 'The mind is a dream machine. It creates the world and all its illusions.', 'The mind is a river. The Self is the ocean.', 'Liberation is a state of being, not a destination.', 'The mind is a tool. You are the one who uses it.', 'The ego is a story we tell ourselves.', 'The mind is a prison. The Self is the key.', 'The mind is a cloud that obscures the sun of the Self.', 'The ego is a temporary illusion. The Self is the eternal reality.', 'The mind is a guest. The Self is the host.', 'Liberation is a state of perfect stillness and peace.', 'The only way to be free is to be yourself.'
    ],
    [
      Article(
        heading: 'Karma Yoga',
        body: 'Paramatman is a profound and multifaceted concept in Hindu philosophy...'
      ),
      Article(
        heading: 'Article 2 about Saint Vivekananda',
        body: 'Body of article 2...'
      )
    ],
  ),
];
