// nisargadatta_en.dart
// Nisargadatta Maharaj quotes and articles

import '../articlesquotes.dart';

final nisargadattaSaintSa =   Saint(
  'nisargadatta',
  'Nisargadatta maharaj',
  'assets/images/nisargadatta.jpg',
  [
    'यत् त्वं स्वं मन्यसे तन्न; यः असि तत् अन्वेषय।',
    'सत् न म्रियते; असत् कदापि न जीवितम्।',
    'प्रज्ञा वदति—अहं किञ्चन नास्मि। प्रेम वदति—अहं सर्वम्। एतयोर्मध्ये जीवनं प्रवहति।',
    'त्वं परमार्थ एव। संकीर्णचित्तो मा भव।',
    'यत् त्वं असि तत् ज्ञातुं प्रथमं यन्नासि तत् परिशीलय।',
    'मयि च त्वयि च या चेतना, द्वयमिव भाति; सा एका—एकत्वं मृगय, स एव प्रेम।',
    'स्वपरिभाषणवासनां केवलं त्यज।',
    'यदा त्वं जानासि—पन्थाः एव लक्ष्यः, त्वं नित्यं पथि एव, न लक्ष्यप्राप्तये, अपि तु तस्य सौन्दर्यप्रज्ञयोः आस्वादनाय—तदा जीवनं न भारः, सहजं सरलम्।',
    'त्वं न देहः। न मनोऽपि। यत्र देहमनोऽपि दृश्येते सा चेतना त्वम्।',
    'यदा स्वस्वरूपं जानासि, तदा कस्यापि न भयं।',
    '“अहं एवं करोमि” इति कल्पनां विरम; तदा सर्वस्य हृदयं स्रोतः च त्वमेव इति बोधः उदेति।',
    'यद् त्वं पश्यसि तत् तव न; तद् त्वया सह किञ्चिदपि न सम्बन्धते।',
    'परम्परागतमानान् सर्वान् त्यज; परम्परानुगामिभ्यः तान् त्यज।',
    'तव नित्यं गृहं शून्ये—सर्ववस्तुरहिते।',
    'यदा अन्तः पश्यामि “अहं किञ्चन नास्मि” इति—सा प्रज्ञा; यदा बहिः पश्यामि “अहं सर्वम्” इति—तत् प्रेम।',
    'मनः गर्तं निर्माति; हृदयम् तं तरति।',
    'यत् यत् त्वं मन्यसे “अहं अस्मि”, तत् न त्वम्।',
    'त्वं व्यक्तिं मन्यसे, किन्तु व्यक्तिरूपेण कदापि न जातः।',
    'वस्तुतः त्वं न कश्चन पदार्थः, न च परेभ्यः पृथक्।',
    'सत्यान्वेषणं सर्वेषु उद्योगेषु भयङ्करतमम्; यतः तद् यत्र त्वं वससि तं जगत् विनाशयति।',
    'सर्वभेदः, सर्ववियोगः, सर्वविमुखता च मिथ्या।',
    'यद् सर्वव्यापकचैतन्यस्य अभिव्यक्तिः, तस्य परमशक्तिसम्भावना त्वमेव।',
    'व्यक्तिविषयः रक्षणं अपेक्षते; सत्यं तु रक्षणं न अपेक्षते।',
    'त्वां बाधयितुं शक्नोति केवलं स्वकल्पना।',
    'यदा निश्चितं जानासि—स्वकल्पनैव त्वां बाधयति—तदा कामभययोः अवगणनं जायते।',
    'त्वं जगति न; जगत् त्वयि।',
    '“अहं” इति भावः स्वमेव। तं त्यक्तुं न शक्नोषि, किन्तु कस्यचित् उपाधौ दातुं शक्नोषि—“अहं युवा”, “अहं धनी” इति।',
    'दुःखसुखयोः तटीयोर्मध्ये जीवननदी प्रवहति। यदा मनः जीवनस्रवणं न अनुगच्छति, तटेषु बद्धं भवति, तदा समस्या।',
    'स्वातन्त्र्यं ज्ञातात्।',
    'तव दुर्बलता इयं—त्वं जगति जातः इति निश्चयः।',
    'मोक्षाय मनसि मा निर्भरः। मन एव त्वां बन्धने नीतवान्।',
    'सत्यगुरुः स्वयमेव जीवनम्।',
    'तं प्राप्तुं न आवश्यकम्; त्वमेव तत्।',
    'प्रेम वदति “अहं सर्वम्”; प्रज्ञा वदति “अहं किञ्चन नास्मि”; एतयोर्मध्ये जीवनं प्रवहति।',
    'मनः-आत्मा-प्राणत्रयी यदा परीक्ष्यते तदा एकत्वं भवति।',
    'केवलं भव। तव स्वभावः प्रादुर्भवतु। अन्वेषणेन मनः मा क्षोभय।',
    'तव स्वात्मैव परमाचार्यः। बाह्याचार्यः तु केवलं मीलस्तम्भः।',
    'तव लोके सर्वस्य आदिरन्तश्च आवश्यकः। यदि न, तदा तं नित्यं वदसि।',
    'सिद्धः जगत् यथावत् पश्यति—सारतः एकं, भूषया नानाविधम्।',
    'कल्पनाविना पश्य, विकृतिविना शृणु।',
    'मन एव वदति “मन अस्ति”; मा मोहय।',
    'सत्यं न सदाचारफलम्, न परीक्षापारितोषिकम्।',
    'यत् त्वां “मानवः” इति मन्यते, तत् मानवं न।',
    'स्वबन्धननिर्माणे बहुशक्तिं व्ययाय। इदानीं तस्य भङ्गेऽपि तावतीं व्ययाय।',
    'व्यक्तित्वत्यागाय व्यक्तिं पश्य; चेतनायां वस्तुवत् तां पश्य।',
    'देहमनोऽभिमानत्यागे का कठिनता? नूनं त्वं देहमनो न।',
    'मृत्युभयस्य कारणं स्वात्माज्ञानम्। सत्यस्वरूपं अमृतम्।',
    'सर्वातीतत्वबोधात् यत् बाधते तत् स्मृतिमूलं मनः।',
    'मनः काले वर्तते; वयं कालातीताः।',
    'यदा न भयम्, तदा त्वमेव प्रेमस्वरूपः।',
    'त्वं यन्न स्वं मन्यसे तन्न। देहः न, मनः न, व्यक्तित्वभावो न; एतत् सर्वं यत्र उदेति अस्तं च गच्छति सा अकालचेतना त्वम्।',
    'यदा त्वं स्वात्मानं चेतनारूपं पश्यसि, न व्यक्तिरूपं, तदा सर्वदुःखक्षयः। शेषं शान्तिः—न अनुभवः, तु तव स्वभावः।',
    'देहात् पूर्वं जगत् पूर्वं च त्वम् असि। सर्वसङ्कल्पातीतं “अहं अस्मि” इति भावं धारय; शेषं त्यज।',
    '“अहं अस्मि” प्रथमद्वारम्। तस्मिन् स्थिरं तिष्ठ। यदा “अहम्” अपि लीयते, तदा परं तिष्ठति।',
    'त्वं जगति न; जगत् त्वयि। समग्रं विश्वं तव चेतनायां धारयसि।',
    'स्वस्वरूपज्ञानाय प्रथमं अनात्मानं विविच्य जानीहि। यद् दृश्यते अनुभूयते वा तद् न त्वम्।',
    'सत्यात्मा न प्राप्तव्यः; यदा सर्वाः मिथ्यकल्पनाः पतन्ति, तदा यः असि स एव।',
    'त्वं सीमितः इति कल्पयित्वा दुःखं अनुभवसि; वस्तुतः तव सीमारेखा नास्ति।',
    'देहमनोऽभिमानं यदा त्यजसि, तदा ज्ञास्यसि—कदापि न बद्धः, न क्लिष्टः, न अपूर्णः।',
    'साक्षित्वं न वैयक्तिकम्। व्यक्तिः साक्षिणि प्रादुर्भवति; साक्षी तु व्यक्तेः न।',
    'चेतना स्वयमेव क्षणिका अवस्था। सा उदेति अस्तं च गच्छति। यद् चेतनां जानाति तत् तदतीतम्।',
    'परं तु स्वस्वरूपाबोधं न जानाति; चेतना तत्र तरङ्गवत् उदेति।',
    'त्वं चेतनां स्वं मन्यसे, किन्तु चेतना अपि दृश्यते। चेतनाप्रकाशकं अन्वेषय।',
    'देहजगत् चेतनया सह एव उदेते। चेतनायां नास्ति चेत् जगदपि न।',
    'चेतनापूर्वे न अनुभवः न कालो न देशः—तथापि त्वं असि; एष तव स्वरूपम्।',
    'चेतना देहाश्रिता; परं तु किमपि न आश्रयते। भेदं जान।',
    'मृत्यौ चेतना लीयते, किन्तु त्वं न म्रियसे; यतः कदापि न जातः।',
    'परं वक्तुं न शक्यते; यद् उच्यते तद् चेतनाविषयमेव।',
    'चेतनास्रोतसि तिष्ठ; तदा ताम् अतिक्रामसि।',
    'चेतनागतिरेव सत्यं इति भ्रान्तिः; सत्यं तु यद् न चलति।',
    'तव साधना एकैव—“अहं अस्मि” इति भावं धारय, शेषं सर्वं अनात्मा इति त्यज।',
    'यत् दृश्यते तं परिवर्तयितुं मा यतस्व; स्वस्वरूपं बोधय, ततः सर्वं स्वयमेव परिवर्तते।',
    'यावत् प्रयत्नः आवश्यकः, तावत् अप्रयत्नः न प्रकाशते; प्रकाशे तु प्रयत्नोऽपि पतति।',
    'आत्मविचारः न मानसिक-व्यायामः; यत् यत् दृश्यते तेन तादात्म्यं निराकर्तुं स्थिरनिश्चयः।',
    'मेघान् इव विचारान् पश्य; मा स्वत्वेन गृह्णीः।',
    'मनः मनं अतिक्रान्तुं न सहायः। मनोबोधेनैव मनातीतत्वं।',
    'यदा मनः पश्यसि, तदा त्वं तदतीतः।',
    'कालं मा पृच्छ। एकाग्रः सत्यनिष्ठश्च भव।',
    'मनः शुद्धिकरणं न आवश्यकम्; तेन तादात्म्यं मा कुरु।',
    'मौनं न शब्दाभावः; अभिमानाभावः।',
    'व्यक्तिः स्मृत्यभ्याससंस्कारसमूहः; त्वं तु न तस्य समूहः।',
    'अहङ्कारः केवलं कल्पना—चेतनाया मिथ्यकेन्द्रकल्पना।',
    '“अहं दुःखितः” इति वाक्ये “अहं” कः इति अन्वेषय; न लप्स्यसे।',
    '“अहं कर्ता” इति भावः बन्धः; तदभावे मुक्तिः।',
    'व्यक्तित्वं न सत्यं; चेतनाया मुखौष्ठिका।',
    'यावत् व्यक्तिमेव आत्मानं मन्यसे, तावत् भयजीवितम्।',
    'व्यक्तिभावः देहसह एव उदेति देहेन सह निवर्तते।',
    'शून्यताया भयात् व्यक्तिं धारयसि; सा शून्यता एव शान्तिः।',
    'व्यक्तिविलये न शून्यता, किन्तु पूर्णता।',
    'अहङ्कारः नित्यतां इच्छति; सत्ये तु न निरन्तरता।',
    'सर्वदुःखं तादात्म्यजन्यम्; क्षणिकं स्वं मत्वा दुःखं अनुभवसि।',
    'कामः अपूर्णताबोधात् जायते; सा अपूर्णता मिथ्या।',
    'भयं व्यक्तेः; आत्मा भयातीतः।',
    'देहाभिमानत्यागे मृत्युभयं नश्यति।',
    'वेदना देहिका; दुःखम् मानसिकम्। बोधेन दुःखं अतिक्रामसि।',
    'यत् प्रतिरोधयति तत् वर्धते; यत् बोधयति तत् लीयते।',
    'कामः स्मृतिः भविष्यम् आरोपिता।',
    'स्वातन्त्र्यं न कामपूर्तिः; कामविमुक्तिः।',
    'दुःखं सूचकः—त्वं स्वात्मनि भ्रान्तः।',
    'मिथ्याभिमाने जाते, दुःखम् अपि निवर्तते।',
    'जगत् न असत्, किन्तु यथा मन्यसे तथा न; चेतनाप्रतिबिम्बः।',
    'जगत् सत्यं भाति यतः त्वं तत्र भागः इति मन्यसे।',
    'चेतनास्थैर्ये जगत् स्थिरम्।',
    'विश्वं यावत् दृश्यते तावत् अस्ति।',
    'जगत् स्वकीयं कृत्वा एव तस्मै सत्यत्वं ददासि।',
    'जगत् चेतनाव्यतिरेकेण स्वतन्त्रं नास्ति।',
    'सत्यं सरलम्; माया जटिला।',
    'जगत् न शुभं न अशुभं; तव बोधप्रतिबिम्बम्।',
    'यत् “जीवनं” इति वदसि, तत् प्रत्यक्षधाराप्रवाहः।',
    'जगत् नाट्यम्; चेतना तु तं गम्भीरं करोति।',
    'गुरुः न नूतनं ददाति; असत्यं अपाकरोति।',
    'कृपा न घटना; तव स्वरूपमेव।',
    'यदा त्वं सिद्धः, तदा उपदेशः त्वां प्राप्नोति।',
    'गुरुः संकेतयति; त्वं तु पश्य।',
    'प्रथमं श्रद्धया अनुसर; ततो अनुभवेन परीक्षस्व।',
    'गुरौ श्रद्धा आत्मनि श्रद्धा।',
    'शब्दाः संकेताः; तेषु मा आसज्यस्व।',
    'परमा शिक्षा मौनम्।',
    'सत्यगुरुः अहङ्कारं न तर्पयति; तं नाशयति।',
    'पूर्णबोधे गुरुरपि तिरोहितः।',
    'मोक्षो न काले सिद्धिः; अकालस्य प्रत्यभिज्ञानम्।',
    'त्वं अधुना एव मुक्तः; बन्धं कल्पयसि।',
    'स्वातन्त्र्यं न यत् इच्छसि तत् करणम्; कामेन अनीतत्वाभावः।',
    'यत्र “अहं” न, तत्र बन्धो न।',
    'मोक्षः अन्वेषणस्य अन्तः।',
    'मुक्तस्य किमपि न भवति; यतः तत्र “कोऽपि” न।',
    'मुक्तावस्था सामान्यं सहजं च—अनालक्षितम्।',
    'त्वं मुक्तो भवसि इति न; त्वं कदापि न बद्धः इति जानासि।',
    'परमा अवस्था न अवस्था एव।',
    'अज्ञाननाशे किञ्चिदपि विशेषं न; सत्यं स्वयमेव स्थितम्।',
    'त्वं सत्यस्य खण्डः न; त्वमेव सत्यं।',
    'यद् प्रादुर्भवति तद् अवश्यं लीयते; यद् न प्रादुर्भवति तद् न लीयते।',
    'परं निर्गुणम्; तथापि सर्वगुणाः तस्मात् उद्भवन्ति।',
    'परमं वस्तु विषयत्वेन न ज्ञेयम्; यतः त्वमेव तत्।',
    'आत्मा न अनुभूयते; स एव अनुभावकः।',
    'यदा प्रश्नाः यान्ति, तदा सत्यं अवशिष्यते।',
    'त्वयि किमपि योजनीयम् न; मिथ्याधीः एव अपाकर्तव्या।',
    'यद् त्वं असि तत् विधाननिषेधातीतम्।',
    'मौनः भव, पश्य—एतदेव।',
    'सत्यं सरलम्; मनः सरलतां प्रतिहन्ति।',
    '“अहं अस्मि” इति भावे तिष्ठ, यावत् सोऽपि लीयते।',
    'सत्यं ग्रहीतुं मा यतस्व; असत्यं पततु।',
    'बोधः कुञ्जिका, न अनुभवः।',
    'यत् सत्यं तत् सदा वर्तमानम्।',
    'त्वं कालात् पूर्वम्।',
    'सत्ये दोषो न; तव कल्पनासु एव दोषः।',
    'अन्वेषकनाशे साध्यं प्रकाशते।',
    'सङ्कल्पैः शून्यः भव।',
    'त्वं साक्षी, न दृश्यः।',
    'त्वं—एतावत् पर्याप्तम्।'
  ],
  [
    Article(
        heading: 'Who Am I? - The Fundamental Question',
        body: 'Nisargadatta Maharaj\'s teaching centered around the fundamental question "Who Am I?" He would relentlessly point his disciples to investigate their true nature beyond all concepts and identifications.\n\n"You are not what you take yourself to be," he would say. "Find out what you are." This investigation is not an intellectual exercise but a direct inquiry into the source of the \'I\' feeling.\n\nMaharaj taught that we habitually identify ourselves with the body, mind, thoughts, emotions, and various roles we play in life. But all these are objects that appear in consciousness. We are the consciousness in which they appear, not the objects themselves.\n\nThe process of self-inquiry involves negating all that you are not - "I am not the body, I am not the mind, I am not the thoughts" - until you arrive at what remains. What remains is pure awareness, pure being, your true nature.\n\n"To know what you are, you must first investigate and know what you are not," Maharaj emphasized. This process of elimination leads to the recognition of your fundamental nature as pure consciousness, beyond all attributes and limitations.\n\nThe question "Who Am I?" must be pursued with intense earnestness and sincerity. It is not enough to understand it intellectually; it must become a living inquiry that permeates every moment of your existence until the false sense of being a separate person dissolves completely.'
    ),
    Article(
        heading: 'The Nature of Consciousness',
        body: 'Nisargadatta Maharaj had a unique way of explaining consciousness that was both profound and accessible. He distinguished between the personal consciousness (which he called the "I am" feeling) and the absolute consciousness which is beyond all experience.\n\nThe "I am" is the first movement in consciousness, the primary concept that gives rise to all other experiences. Maharaj taught that we should hold on to this pure "I am" feeling without any additions like "I am this" or "I am that."\n\n"The consciousness in you and the consciousness in me, apparently two, are one," he would say. This understanding dissolves the illusion of separation and reveals the unity underlying all apparent diversity.\n\nMaharaj explained that consciousness is not produced by the brain or body. Rather, the body and brain appear in consciousness. Consciousness is not personal; it is universal, and what we take to be individual consciousness is simply a reflection of this universal consciousness.\n\nThe absolute reality is even beyond consciousness - it is that in which consciousness itself appears and disappears. This is your true nature, prior to consciousness, prior to existence and non-existence.\n\n"You are the Supreme Reality," Maharaj would declare. "Don\'t be small-minded." This Supreme Reality cannot be known as an object because you are it. It can only be recognized through the dissolution of all that you think you are.'
    ),
    Article(
        heading: 'The Illusion of the Person',
        body: 'One of Nisargadatta Maharaj\'s most radical teachings was about the illusory nature of the person. He would say, "You take yourself to be a person, but you have never been born as a person."\n\nThe person is simply a collection of memories, thoughts, and identifications that create an apparent continuity. But when examined closely, there is no solid entity that can be called a person. It is like a movie - individual frames creating an illusion of movement and story.\n\nMaharaj taught that the person is a mental construct, a bundle of concepts with no independent reality. "Whatever you think you are, you are not," he would insist. The person appears in you (consciousness) but you are not the person.\n\nThis understanding is liberating because it means that all the problems, limitations, and suffering of the person are also illusory. When you realize you are not the person, you are free from the person\'s destiny, karma, and conditioning.\n\n"Nothing you perceive is your own. Nothing you perceive has anything to do with you," Maharaj would say. This includes the body, mind, thoughts, and emotions that we usually consider to be ours.\n\nThe recognition that you are not the person is not a philosophical position but a direct realization that comes through earnest self-inquiry. When this recognition becomes stable and unshakeable, you abide as what you truly are - pure awareness, pure being, beyond all personal limitations.'
    ),
    Article(
        heading: 'Love and Wisdom - The Two Wings of Truth',
        body: 'Nisargadatta Maharaj beautifully expressed the paradox of realization in his famous statement: "Wisdom tells me I am nothing. Love tells me I am everything. Between these two my life flows."\n\nWisdom is the recognition of your true nature as pure awareness, which has no attributes, no form, no qualities - essentially nothing that can be grasped by the mind. From this perspective, you are the void, the emptiness in which all experience appears.\n\nLove, on the other hand, is the recognition that this same awareness is the very essence of everything that appears. You are not separate from anything; you are the one appearing as the many. This is the love that embraces all existence as your own self.\n\nThese are not contradictory truths but two aspects of the same realization. The absolute is both the void and the fullness, nothing and everything, transcendent and immanent.\n\n"When I look within and see that I am nothing, that is wisdom. When I look without and see that I am everything, that is love," Maharaj explained. This dual recognition is the hallmark of complete understanding.\n\nLiving from this understanding means being established in the peace of knowing yourself as nothing (no-thing) while simultaneously loving all that appears as your own manifestation. This is the natural state of the realized being - empty of self yet full of love for all.'
    ),
    Article(
        heading: 'Beyond Birth and Death',
        body: 'Nisargadatta Maharaj\'s teachings on death and immortality were particularly powerful and comforting. "The real does not die, the unreal never lived," he would say with absolute certainty.\n\nFrom his perspective, what we call birth and death are simply appearances in consciousness, like scenes in a dream. The body is born and dies, but you - the awareness in which the body appears - are never born and therefore cannot die.\n\n"You are afraid of death because you do not know yourself," Maharaj would point out. "The real you is deathless." This fear of death comes from identifying with the mortal body rather than recognizing yourself as immortal consciousness.\n\nMaharaj taught that we have never actually experienced birth or death. We have memories of the past and imagination about the future, but our actual experience is always of the present moment of awareness. This awareness has always been and always will be.\n\nThe understanding of your deathless nature is not a belief or consolation but a direct recognition. When you truly know yourself as pure awareness, the fear of death simply disappears because you realize there is nothing that can die.\n\n"Your weakness is due to your conviction that you were born into the world," he would say. In reality, the world appears in you; you do not appear in the world. This fundamental shift in understanding transforms your entire relationship with life and death.\n\nThe practical implication of this teaching is tremendous freedom and fearlessness. When you know yourself as the deathless reality, you can live fully and love completely without the shadow of mortality clouding your natural joy and peace.'
    )
  ],
);
