// ramakrishna_en.dart
// Ramakrishna Paramhansa quotes and articles

import '../articlesquotes.dart';

final ramakrishnaSaintSa = Saint(
  'ramakrishna',
  'Ramakrishna Paramhansa',
    'assets/images/ramkrishna.jpg',
  [
    'सर्वैः पथिभिः भगवान् साक्षात्कर्तुं शक्यते। सर्वे धर्माः सत्याः। मुख्यं तु शिखरप्राप्तिः। पाषाणसोपानेन, काष्ठसोपानेन, वेणुसोपानेन, रज्ज्वा वा आरोढुं शक्यते; दण्डेनापि आरोहणं शक्यम्।',
    'यावत् जीवामि तावत् शिक्षे।',
    'अनुग्रहवाताः सदा वान्ति; त्वमेव नौकापटं उत्थापय।',
    'यदि पूर्वं गन्तुम् इच्छसि, पश्चिमं मा गच्छ।',
    'भगवान् सर्वेषु नरैः अन्तर्बद्धः; सर्वे तु भगवति न—तस्माद् दुःखम्।',
    'कस्तूरीमृगः स्वस्मादेव निर्गतं गन्धं मृगयन् जगत् परिभ्रमति।',
    'ज्ञानं एकत्वं नयति; अज्ञानं नानात्वं।',
    'कूर्मः यथा जलस्थलेषु उभयत्र वसति, तथा सिद्धपुरुषः भगवति जगति च वसति।',
    'यदा पुष्पं विकसति तदा मधुकराः अनाहूताः आगच्छन्ति।',
    'तस्य कृपावायुः सदा वान्ति; पताकां सज्जीकुरु।',
    'भगवतः कृपावायवः सदा वान्ति; अस्माभिः पताकाः उत्थापनीयाः।',
    'अहङ्कारं त्यक्त्वा विना दिव्यज्ञानं न लभ्यते।',
    'रोगो देहाय आत्मनः करः, यथा गृहभोगाय किरायाः।',
    'यो सर्वकामान् त्यक्तवान् स एव सुखी।',
    'बहून् इच्छन् बहु वस्तूनि अल्पानि इव पश्यति।',
    'धननामयशःसुखादिषु क्षणिकेषु आसक्तिः प्रतिदिनं न्यूनां भवेत् इति भगवन्तं प्रार्थय।',
    'यथा दग्धकेशः नरः तडागं मृगयते, तथा ईश्वरप्रकाशं मृगयस्व।',
    'जलं तैलं च न मिश्र्यते; एवमेव संन्यासं विना आध्यात्मविकासो न।',
    'चुम्बकसूचिः यथा उत्तरं दर्शयति, तथा हृदयं यदि भगवन्मुखं भवति तर्हि संसारसागरे न नश्यति।',
    'बालवद् सरलतां विना दिव्यप्रकाशं न लभ्यते।',
    'सत्-चित्-आनन्दं नित्यं ध्याय; ततः आनन्दं लप्स्यसे।',
    'भगवतः नामानि बहूनि, रूपाणि अनन्तानि। यस्मिन् नामरूपे त्वं उपाससे, तेनैव तं साक्षात्करिष्यसि।',
    'अतिप्रेम्णा विना भगवत्साक्षात्कारः न।',
    'यथा भ्रमरः कमलपत्रबाह्ये मधुं न रसयन् घोषं कुर्वन् भ्रमति, अन्तः प्रविश्य तु निःशब्दं मधुं पिबति—तथा यावत् मतवादविवादः तावत् श्रद्धारसास्वादनं न; रसानुभवे तु शान्तिः।',
    'जगत् सत्यासत्ययोर्मिश्रणम्; असत्यं परित्यज्य सत्यं गृहाण।',
    'भगवान् द्विषु अवसरयोः हसति—वैद्यः यदा “मातः मा शुचः, अहं तव पुत्रं निश्चयं चिकित्सयिष्यामि” इति वदति, भगवान् स्वहृदि हसति “अहमस्य प्राणं हरिष्यामि; अयं तु रक्षिष्यामि इति मन्यते।” पुनश्च द्वौ भ्रातरौ रज्ज्वा भूमिं विभज्य “इयं मम, इयं तव” इति वदतः; स हसन् वदति “सर्वं जगन्मम, किन्तु एते अंशं स्वं वदतः।”',
    'प्रेम्णा तं द्रष्टुं स्प्रष्टुं अनुभवितुं च शक्यते।',
    'किं न पश्यसि प्रकाशं? एष श्रद्धाद्वीपः। स सर्वमानवहृदये दीप्यते।',
    'मानवजन्म दुर्लभं लब्ध्वा, अस्मिन्नेव जीवने भगवद्भावं न यः साधयति, स व्यर्थं जातः।',
    'यदि सर्वात्मज्ञानं पश्यन् धनसंसारमध्ये वससि, तदा ते न त्वां बाधन्ते।',
    'गङ्गातरङ्गाः गङ्गायाः; गङ्गा तु तरङ्गाणां न। “अहं महान्” इत्याद्यहङ्कारभावान् त्यक्त्वा विना ईश्वरदर्शनं न।',
    'सूर्यः सर्वं तापयति प्रकाशयति च, किन्तु मेघैः आवृतः सन् न; एवमेव अहङ्कारावरणे हृदये भगवान् न प्रकाशते।',
    'स्त्री-धनमेव जगत्; सा एव माया—तया त्वं भगवन्तं न पश्यसि।',
    'सामान्यजनाः धर्मं बहु वदन्ति, अल्पं तु आचरन्ति; ज्ञानी तु अल्पं वदन् अपि कर्मणा धर्मं दर्शयति।',
    'संन्यासभावं विना शान्त्या सह वासो न शक्यते।',
    'यः गृहस्थोऽपि कर्तव्येषु वर्तन् भगवन्तं स्मरति स वीरः। भगवान् मन्यते—“एष मध्यमे संसारकर्मसु मां मृगयते; महाबाधां शिलाखण्डमिव धुत्वा स वीरः।”',
    'यदि भगवन्तं साक्षात्कर्तुम् इच्छसि, तीव्रं वैराग्यं संवर्धय। यत् त्वां बाधते तत् तत्क्षणं त्यज।',
    'भक्त्या ज्ञानेन कर्मणा वा—यः तव स्वभावानुकूलः, तेन भगवदन्वेषणं कुरु।',
    'धर्मकथनं सुकरं; आचरणं तु दुष्करम्।',
    'बन्धमोक्षौ मनसो धर्मौ। यदि त्वं “अहं मुक्तात्मा, अहं भगवतः पुत्रः; मां कः बद्धुं शक्नोति” इति वदसि, मुक्तो भविष्यसि।',
    'ब्रह्म किम् इति वक्तुं न शक्यते। वेदपुराणतन्त्रषड्दर्शनादयः जिह्वया पठितोक्तत्वात् जिह्वास्पृष्टभोज्यवत् कलङ्किताः; ब्रह्म तु तादृशकलङ्केन अस्पृष्टम्।',
    'यो देहस्थोऽपि मुक्तः, स यदा जानाति—भगवान् कर्ता, अहं निमित्तमात्रम्।',
    'भक्तिवर्जितं कर्म स्वबलहीनं, अकेलं न स्थातुं शक्नोति।',
    'कामिनी-काञ्चनं योगस्य विघ्नः।',
    'यावत् इच्छा तावत् दुःखम्। यदा इच्छा नास्ति, यदा आत्मनि प्रतिष्ठितः, यदा आत्मैव तृप्तिहेतुः, तदा परमानन्दः।',
    'मन एव जनयति विद्वत्त्वमविद्वत्त्वं बन्धं मोक्षं च।',
    'यदा भगवति प्रेम अस्ति, तदा भार्या-पुत्र-स्वजनमित्रेषु शारीराकर्षणं न; करुणा एव अवशिष्यते।',
    'स्नेहमैत्र्यसुखेन्द्रियभोगाः सर्वे भगवद्ब्रह्मानन्दस्य प्रतिबिम्बरूपाः।',
    'पर्याप्तं यत् भगवति यथार्थाकाङ्क्षा। पथाः अनन्ताः, मार्गाः अपि अनन्ताः।',
    'जगति जलपक्षिवत् वस—जलं पक्षिणि न लिप्यते। कीचकमत्स्यवत् वस—कीचे वसन्नपि त्वक् दीप्तिमती।',
    'रात्रौ नभसि तारा दृश्यन्ते; सूर्योदये न। किं तु तारा न सन्ति इति? एवमेव अज्ञानदिने भगवन्तं न पश्यन् “नास्ति भगवान्” इति मा वद।',
    'भगवदनुग्रहः बीमोपमः—आपत्काले असीमं सहाय्यं करोति।',
    'यथा बहवः धर्माः तथा बहवः पथाः; पात्रभेदेन जलपानवत्, जलं तु एकमेव।',
    'लोकाः जगति धननामयशःप्रसिद्धिषु उन्मत्ताः; भगवति तु कोऽपि उन्मत्तो न।',
    'यस्य यथार्थं लालसा, स निश्चयेन भगवन्तं प्राप्स्यति—न संशयः।',
    'मनः इव मृदाललेपिता सूचिः, भगवान् इव चुम्बकः; मृदाललेपशुद्धौ एव योगः।',
    'यदा पुष्पं विकसति, मधुकराः आगच्छन्ति; हृदयशुद्धौ भगवान् प्रकाशते।',
    'सर्वैः पथिभिः सर्वधर्मैश्च भगवान् साक्षात्कर्तुं शक्यते; एकं गृहम् प्रति बहवः मार्गाः।',
    'यावत् भगवान् न साक्षात्कृतः, तावत् स “तत्र” इव भाति; साक्षात्कारे तु “अत्र सर्वत्र” इति दृश्यते।',
    'जगत् जलवत्, मनः क्षीरवत्। क्षीरं जले क्षिप्तं एकं भवति; क्षीरं मन्थनात् नवनीतं जातं तु पृथक् तिष्ठति।',
    'जगति वसन् सावधानः भव; कीचकमत्स्यवत्—कीचे वसन्नपि त्वक् निर्मला।',
    'यद् मनः सततं भगवन्तं चिन्तयति, तद् तद्रूपं भवति।',
    'किमर्थं भगवान् दुःखं ददाति? परिपूर्णत्वाय।',
    'मानवजीवनस्य उद्देश्यः भगवत्प्रेम; भक्तिः एव मुख्यं साधनम्।',
    'भगवान् दूरं न; अत्यन्तं समीपः, समीपात् अपि समीपतरः।',
    'बहुग्रन्थपठनात् आध्यात्मिकप्रज्ञा न; अन्तर्मग्नः भव।',
    'यः दिव्यानन्दं रसयति स संसारभोगेषु रुचिं न प्राप्नोति।',
    'नौका जले स्यात्, परं जलं नौकायां मा स्यात्।',
    'यस्य श्रद्धा स सर्वं लभते; अश्रद्धस्य सर्वं नश्यति।',
    'कर्तव्यं कुरु, मनः तु भगवति स्थापय।',
    'यः सच्चिदानन्दं इच्छति स एव सफलः।',
    'फलभारवृक्षः नमति; महान्तः नम्राः।',
    'भगवान् एव कर्ता; मनुष्यः निमित्तमात्रम्।',
    'प्रार्थना भगवद्धृदयद्वारकुञ्चिका।',
    'भगवद्दर्शनं जीवनस्य लक्ष्यः; अन्यद् सर्वं गौणम्।',
    'यावत् भगवति समीपं गच्छसि, तावत् सर्वभूतेषु प्रेम वर्धते।',
    'बालसदृशी श्रद्धा विना भगवद्बोधो न।',
    'मनः शुद्धं चेत् भगवान् स्वयमेव प्रकाशते।',
    'जगत् अनित्यं; भगवान् एव नित्यः।',
    'भगवदर्थं बाष्पाः हृदयमलान् धावयन्ति।',
    'भगवान् द्विषु अवसरयोः हसति—यदा वैद्याः औषधेनैव रक्षां मन्यन्ते, यदा पण्डिताः शास्त्रेण तं बद्धुं मन्यन्ते।',
    'शुष्कतर्केण भगवद्बोधो न; प्रेम्णैव तं प्राप्नोति।',
    'यस्य हृदये लालसा, तत्र भगवान् प्रकाशते।',
    'यदा कमलं विकसति मधुकराः आगच्छन्ति; यदा हृदयं विकसति भगवान् प्रादुर्भवति।',
    'भगवान् माधुर्यसमुद्रः; यथायथं आस्वादयसि तथापि अधिकं शेषम्।',
    'यः सर्वं भगवति समर्पयति स भयहीनः।',
    'किं चिन्तयसि? यः त्वां सृष्टवान् स त्वां पालयिष्यति।',
    'यावत् “अहं” “मम” इति, तावत् अज्ञानम्।',
    'नामकीर्तनं मनः शुद्धयति।',
    'तीव्रप्रेम्णा नेत्राभ्यामपि भगवन्तं द्रष्टुं शक्यते।',
    'भक्तः भगवन्तमेव इच्छति, नान्यत्।',
    'रसोइगृहेऽपि अरण्येऽपि भगवान् साक्षात्कर्तव्यः।',
    'जगति आसक्तिः बध्नाति; भगवति आसक्तिः मोचयति।',
    'श्रद्धा अन्धकारगृहे दीपवत्।',
    'बालवत् माता-प्रति रुदन् इव भगवदर्थं रुद।',
    'भगवान् साकारोऽपि निराकारोऽपि।',
    'यथा यथा आध्यात्मिकं वर्धसे, तथा तथा परेषां दोषदर्शनं क्षीयते।',
    'यः सर्वं त्यक्तवान् स एव सर्वं लब्धवान्।',
    'भक्तिवर्जितं ज्ञानं रूक्षं निष्फलम्।',
    'चातुर्येण न भगवान् प्राप्यते; सरलतया।',
    'लोके धनिनः गृहे दासीवत् वस।',
    'लालसा विना किमपि न सिद्ध्यति।',
    'भगवान् सच्चिदानन्दप्रार्थनां शृणोति।',
    'अस्मिन् युगे भगवन्नाम महाशक्तिमत्।',
    'सततस्मरणेन हृदयं शुद्ध्यति।',
    'यः भगवन्तं दृष्टवान् स सर्वत्र तमेव पश्यति।',
    'समर्पणप्रमाणानुसारं भगवान् आत्मानं प्रकाशयति।',
    'धर्मसारः भगवत्प्रेम।',
    'यदा मनः भगवति लीयते, इन्द्रियाणि बलं जहति।',
    'दिव्यारसानुभवे लोकभोगाः निरसाः भवन्ति।',
    'भगवान् अन्तर्यामिन् सर्वभूतानाम्।',
    'एक एव भगवान् बहुनामभिः पूज्यते।',
    'सदसत्पभेदात् परं गत्वा भगवान् ज्ञेयः।',
    'भक्तिः हृदयमृदुं करोति, अहङ्कारं च नाशयति।',
    'लक्ष्यं न वाक्यं, अपि तु साक्षात्कारः।',
    'तर्केण न; अश्रुभिः भगवान् प्राप्यते।',
    'अहङ्कारनाशे भगवान् प्रकाशते।',
    'मनः भगवति विश्राम्यति चेत् शान्तं भवति।',
    'यः सर्वभूतेषु भगवन्तं पश्यति स कञ्चिदपि न द्वेष्टि।',
    'संन्यासः न जगत्यागः; आसक्तित्यागः।',
    'यथा यथा भगवति प्रेम वर्धते, तथा तथा लोकरुचिः क्षीयते।',
    'भगवत्पादयोः सर्वं समर्पय।',
    'श्रद्धा आध्यात्मजीवनस्य मूलम्।',
    'इहैव इदानीं भगवान् साक्षात्कर्तव्यः।',
    'धैर्येण साधना करणीयाः।',
    'नम्रतायां कृपा अवतरति।',
    'पन्थाः कठिनः, लक्ष्यं तु मधुरम्।',
    'मौनगहनतायां भगवान् साक्षात्क्रियते।',
    'जगति वसन् अपि जगत्सदृशो मा भव।',
    'हृदये भगवति पूर्णे भयम् नश्यति।',
    'भक्त्या शुद्धं मनः स्थैर्यं लभते।',
    'प्रेममय हृदये भगवान् प्रकाशते।',
    'हृदयपरिवर्तनं परमो अद्भुतः।',
    'भगवान् श्वासात् अपि समीपः।',
    'यथार्थज्ञानं प्रेमं जनयति।',
    'यो भगवन्तं प्रीयते स सर्वान् प्रीयते।',
    'भगवान् शब्दातीतः; हृदये तु अनुभूयते।',
    'यथा निमग्नः काष्ठं ध्रियते, तथा भगवत् आश्रयं धृहि।',
    'सर्वशास्त्रसारः भक्तिः।',
    'तीव्राकाङ्क्षायां भगवान् प्रत्युत्तरं ददाति।',
    'कामवर्जितं मनः दिव्यं भवति।',
    'यः भगवन्तं अन्वेष्टि स निश्चयेन तं प्राप्नोति।',
    'भगवान् अन्तरज्योतिः सर्वभूतानाम्।',
    'भगवत्प्रेम परमा प्रज्ञा।',
    'आत्मा शान्तिं केवलं भगवति एव लभते।',
    'भगवान् भक्तस्य सुहृत्।',
    'यत्र भक्तिः तत्र भगवान्।',
    'सर्वमार्गाणां अन्तः भगवत्साक्षात्कारः।',
    'यथार्थया आर्तनादेन भगवन्तं आह्वय; स प्रत्युत्तरं दास्यति।'
  ],
  [
    Article(
        heading: 'The Harmony of Religions',
        body: 'Ramakrishna\'s life was a living demonstration of the fundamental unity of all religions. He practiced different spiritual paths - Hinduism in its various forms, Islam, and Christianity - and realized that all lead to the same ultimate truth.\n\nHe often used the parable of reaching the roof by different staircases. Whether one climbs by stone stairs, wooden stairs, bamboo steps, or even a rope, the goal remains the same - to reach the roof. Similarly, all religions are different paths leading to the same divine destination.\n\nThis teaching was revolutionary in his time and remains relevant today. Ramakrishna showed through his own experience that religious differences are merely differences in approach, not in essence. The Supreme Reality is one, though it is called by different names and worshipped in different forms.\n\nHe emphasized that quarreling over religious doctrines shows one has not tasted the nectar of true faith. When one truly experiences God, all arguments cease, and one becomes filled with peace and understanding. His message of religious harmony continues to inspire millions across the world, promoting tolerance and mutual respect among different faiths.'
    ),
    Article(
        heading: 'God-Realization and Renunciation',
        body: 'Ramakrishna taught that the ultimate goal of human life is God-realization. He emphasized that this realization cannot come without intense yearning and renunciation. He often said that one must desire God as intensely as a drowning man desires air.\n\nRenunciation, in his teaching, does not necessarily mean abandoning the world and becoming a monk. Rather, it means giving up attachment to worldly things - wealth, fame, and sensual pleasures. One can live in the world while maintaining inner detachment, like a lotus leaf that floats on water but is never wet.\n\nHe particularly warned against "kamini-kanchana" (lust and gold) as the greatest obstacles to spiritual progress. These represent attachment to sensual pleasures and material wealth. As long as the mind is entangled in these, God-realization remains impossible.\n\nAt the same time, Ramakrishna acknowledged that living a spiritual life while performing worldly duties is the path of a true hero. A householder who remembers God while fulfilling family responsibilities is blessed indeed. Such a person overcomes tremendous obstacles, and God particularly values their efforts.\n\nThe key is to cultivate intense dispassion and to renounce immediately whatever stands in the way of God-realization, not postponing it to some future time.'
    ),
    Article(
        heading: 'The Role of the Guru and Divine Grace',
        body: 'Ramakrishna placed great importance on the role of the guru in spiritual life. He himself was a disciple of several teachers and later became the guru of many, including Swami Vivekananda. He taught that a true guru is essential for spiritual progress, as the guru removes the darkness of ignorance and shows the path to God.\n\nHowever, he also emphasized that the guru\'s grace and God\'s grace are ultimately one and the same. The guru is the manifestation of divine grace in human form, guiding the disciple toward the ultimate truth.\n\nRamakrishna often spoke about divine grace using beautiful metaphors. He said the winds of grace are always blowing, but we must raise our sails to catch them. God\'s grace is constantly available, but we must make ourselves receptive to it through spiritual practice and sincere yearning.\n\nHe compared God\'s grace to insurance, saying it will help in times of need without limit. Just as the sun\'s light is always shining but clouds may obstruct it, so too divine grace is always present, but our ego and ignorance may prevent us from receiving it.\n\nThe path to receiving grace, according to Ramakrishna, is through humility, devotion, and the sincere practice of spiritual disciplines. When the devotee is ready, grace descends naturally, leading to God-realization. He taught that no amount of personal effort alone can achieve the goal without the touch of divine grace, yet grace comes only to those who earnestly seek it.'
    ),
    Article(
        heading: 'Living in the World with Spiritual Wisdom',
        body: 'One of Ramakrishna\'s most practical teachings was how to live spiritually while engaged in worldly life. He recognized that not everyone can renounce the world and become a monk, yet spiritual life should not be limited to renunciates alone.\n\nHe gave several beautiful analogies for how to live in the world without being contaminated by it. Like a waterfowl that lives in water but whose feathers remain dry, or like a mudfish that lives in mud but whose skin remains bright and shiny, the spiritual aspirant should live in the world while remaining inwardly pure.\n\nRamakrishna taught that if one first fortifies oneself with true knowledge of the Universal Self, then living amid wealth and worldliness will not affect one negatively. The key is to establish oneself firmly in spiritual understanding before engaging fully with the world.\n\nHe emphasized the importance of regular spiritual practice even for householders. Setting aside time each day for prayer, meditation, and contemplation is essential. He advised people to create a space in their homes for worship and to maintain daily spiritual disciplines.\n\nRamakrishna also taught that service to others, when done with the right attitude, is service to God. Seeing God in all beings and serving them with love and compassion is a powerful spiritual practice. He showed through his own life that one could maintain the highest spiritual consciousness while interacting with people from all walks of life.\n\nHis message was clear: spiritual life is not separate from daily life. When every action is done with awareness of the Divine, when every person is seen as a manifestation of God, then the entire life becomes a spiritual practice. This practical approach to spirituality has made his teachings accessible and relevant to millions of people leading ordinary lives.'
    )
  ],
);
