// shankaracharya_en.dart
// Shankaracharya quotes and articles

import '../articlesquotes.dart';

final shankaracharyaSaintSa = Saint(
  'Shankaracharya',
  'Shankaracharya',
  'assets/images/shankaracharya.jpg',
  [
    'ब्रह्मैव सत्यं जगन्मिथ्या।',
    'आत्मा जन्ममरणातीतः सर्वगुणसीमानां च परः।',
    'ज्ञानमेवाज्ञानं नाशयति यथा प्रकाशोऽन्धकारम्।',
    'तत्त्वमसि।',
    'अहं ब्रह्मास्मि।',
    'ब्रह्म सत्-चित्-आनन्दस्वरूपं निरपेक्षम्।',
    'आत्मा सर्वस्य साक्षी; स्वयन्तु साक्षित्वातीतः।',
    'माया न सत् नासत्—अनिर्वचनीया।',
    'पण्डिताः सर्वेषु भूतेष्वात्मानं पश्यन्ति सर्वभूतानि चात्मनि।',
    'आसक्तिः सर्वदुःखानां मूलम्।',
    'संन्यासो न जगद्व्यपगमनम्, किं तु तस्य यथार्थस्वभावबोधः।',
    'गुरुरेव ब्रह्म मानवरूपेण शिष्यं पथ्यते।',
    'मोक्षो न लभ्यः कश्चिद् नूतनः; स्वात्मतत्त्वस्य बोध एव।',
    'आत्मा न विक्रियते; स सर्वविकाराणां नित्यः साक्षी।',
    'ईश्वरभक्तिः हृदयशुद्धिरेव।',
    'ज्ञानं भक्तिश्च न भिन्नौ; एकस्यैव सत्यस्य द्वौ पक्षौ।',
    'त्रयो गुणाः जीवयन्ति संसारे बन्धनम्।',
    'गुणत्रयातीतः शाश्वतोऽविकारी आत्मा।',
    'ध्यानं स्वात्मसाक्षात्काराय प्रत्यक्षोपायः।',
    'मनो बन्धमोक्षयोः कारणम्।',
    'मनःशुद्धौ सति आत्मा स्वयमेव प्रकाशते।',
    'शास्त्राणि प्रदीपवत् आत्मपन्थानं दर्शयन्ति।',
    'सत्यं एकम्; विप्राः बहुधा वदन्ति।',
    'जीवात्मा परमारात्मा चैक एव।',
    'अज्ञानं मेघवदात्मानं सूर्यवत् आवृणोति।',
    'जगत् स्वप्नवत्—अनुभवे सत्यं, परमार्थतः मिथ्या।',
    'कर्म अहङ्कारमेव बध्नाति, नात्मानम्।',
    'आत्मा क्रियाक्रियातीतः।',
    'कामः संसारचक्रस्य इन्धनम्।',
    'सन्तोषः परमं धनम्।',
    'ज्ञानी सुखदुःखयोर्न विचाल्यते।',
    'शान्तिरात्मस्वभावः।',
    'आत्मा निराधारः स्वयंसिद्धः।',
    'सत्यासत्यविवेको विवेकस्य आरम्भः।',
    'आत्मा न नेति नेति—केवलं शुद्धचितन्यम्।',
    'सुषुप्तौ आत्मैव अवशिष्यते।',
    'येन सर्वं ज्ञायते स आत्मज्योतिः।',
    'कालदेशौ मनोविकल्पौ।',
    'आत्मा कालदेशहेतुत्वातीतः।',
    'ईश्वरशरणागतिर्मोक्षस्य सुकरः पन्थाः।',
    'ईश्वरस्त्वत्त्वतः भिन्नो न; त्वमेव तत्।',
    'परमार्थः सर्वविकल्पवर्णनातीतः।',
    'मौनं परमा शिक्षा।',
    'आत्मा स्वयमेवात्मानं प्रकाशयति।',
    'आत्मनि मार्गो नास्ति; त्वमेव तत्।',
    'तरङ्गो न सागरात् भिन्नः।',
    'नानात्वं एकस्मिन् सत्ये अध्यारोपितम्।',
    'आत्मा नित्यं मुक्तः शुद्धश्च।',
    'बन्धमोक्षौ मनोविकल्पौ।',
    'आत्मा सर्वानुभवानां आधारः।',
    'ब्रह्मैव सत्यं जगन्मिथ्या जीवो ब्रह्मैव नापरः—एष वेदान्तसारः।',
    'यावत् स्वात्मा न साक्षात्कृतः तावत् अज्ञानजन्यं जन्ममरणशोकबन्धनं अनुभूयते।',
    'ज्ञानमेवाज्ञानं नाशयति यथा प्रकाशोऽन्धकारम्; कर्म नाज्ञाननाशकं, कर्मणा तस्याविरोधात्।',
    'आत्मा बुद्धेः क्रियाणां च साक्षी—नित्यः मुक्तः एकः पूर्णः स्थूलसूक्ष्मदेहभेदात् भिन्नः।',
    'यथा रज्जुः तमसि सर्पत्वेन कल्प्यते, तथा अज्ञानात् देहात्मबुद्धिः जायते।',
    'ज्ञानी नित्यानित्यवस्तुविवेकं कृत्वा, ब्रह्मैव सत्यं शेषं क्षणभङ्गुरं विदित्वा विचिन्तयेत्।',
    'मोक्षो न उत्पाद्यः न विकार्यः न प्राप्यः; स्वस्वरूपस्य बोध एव।',
    'आत्मा स्वयम्प्रकाशः; अन्यप्रमाणापेक्षो न, अज्ञाननाशे स ज्ञायते।',
    'न कर्मणा न प्रजया न धनेन, केवलं त्यागेनैव अमृतत्वं प्राप्यते।',
    'देहइन्द्रियमनः विषयाः; तेषां सर्वेषां द्रष्टा आत्मा नित्यः मुक्तश्च।',
    'यः तत्त्वं वेत्ति स विद्वान् पण्डितचाण्डालगावगजेṣu भेदं न पश्यति।',
    'बन्धमोक्षौ अज्ञानकृतौ; आत्मा तु नित्यं मुक्तः।',
    'वैराग्यविवेकशुद्धं मनो ब्रह्मसाक्षात्काराय योग्यं भवति।',
    'यथा सूर्योऽयासेन सर्वं प्रकाशयति, तथाऽऽत्मा सर्वानुभवान् प्रकाशयति।',
    'देहात्मबुद्धिरज्ञानम्; आत्मात्मबोधो मोक्षः।',
    'कामः बन्धनमूलम्; कामक्षये मनः प्रशाम्यति।',
    'संन्यासो न कर्मत्यागः, किं तु कर्तृत्वाभिमानत्यागः।',
    'यथा आकाशं तदन्तर्गतान् पदार्थान् न स्पृशति, तथाऽऽत्मा देहमनोव्यापारैर्न लिप्यते।',
    'अज्ञो नानात्वं पश्यति, ज्ञानी तु एकमेव सत्यं बहुधा भासमानम्।',
    'अज्ञाननाशे सत्यात्मा स्वयमेव प्रकाशते, यथा मेघापाये सूर्यः।',
    'देहसम्बद्धोऽहंभावो मिथ्या; सत्योऽहंभावः शुद्धचैतन्यम्।',
    'जगत् परमार्थतः ब्रह्मव्यतिरेकेण स्वतन्त्रसत्तारहितम्।',
    'तत्त्वविद् जीवन्नपि मुक्तः; सर्वकर्माणि देहस्यैव इति पश्यति।',
    'आचाररहितोऽपि आत्मज्ञानं विना मुक्तिर्न; सहस्रकर्मभिरपि।',
    'नित्यानित्यविवेको ज्ञानमार्गस्य प्रथमः पादः।',
    'आत्मा न कर्ता न भोक्ता; कर्तृत्वं अज्ञानजन्ये अहङ्कारे।',
    'दृश्यं मिथ्या; द्रष्टैव सत्यः।',
    'मनःशुद्धौ सति आत्मज्योतिः स्पष्टं प्रतिबिम्बति।',
    'स्वप्नदृश्याः प्रबोधे नश्यन्ति, तथा तत्त्वबोधे जगत्।',
    'आत्मा जन्ममरणशोकमोहातीतः।',
    'कर्मतो न ज्ञानं; आचार्योपदिष्टविचारेण ज्ञानं जायते।',
    'ज्ञानी साक्षिवदसङ्गः नितरां वर्तते, स्पृहारहितो भयवर्जितश्च।',
    'भेदबुद्धिरज्ञानम्; अद्वैतं सत्यम्।',
    'यो ब्रह्म वेत्ति स ब्रह्म भवति।',
    'आत्मा न ध्यानविषयः; स एव ध्याता।',
    'विवेकवैराग्यहीनो विद्वानपि बद्ध एव।',
    'ज्ञानी जगत् न त्यजति, किं तु जगति सत्यत्वबुद्धिं परित्यजति।',
    'अज्ञानं जगत् कल्पयति; ज्ञानं तद् विलापयति।',
    'आत्मा जाग्रत्स्वप्नसुषुप्तिषु सम एव।',
    'मोक्षोऽज्ञाननिवृत्तिः; न देशान्तरगमनं न स्थित्यन्तरम्।',
    'देहासक्तिर्भयकारणम्।',
    'एकं सत्यं मायावशात् बहुधा भासते।',
    'मनःसमाधाने शुद्धे च ज्ञानोदयः।',
    'आत्मा अनन्तः; देहस्तु ससीमः—एतद्विवेकात् मुक्तो भव।',
    'यः सर्वत्रात्मानं पश्यति स परमां शान्तिम् आप्नोति।',
    'अहङ्कारग्रन्थिरचैतन्यं देहबन्धनकः।',
    'ज्ञानेनैव संसारसागरं तरति।',
    'आत्मा वाङ्मनसातीतः, तथापि स्वयंसिद्धः।',
    'यथा मृत्तिका सर्वेषु मृण्मयेषु सत्यम्, तथा ब्रह्म सर्वनामरूपेषु सत्यम्।',
    'जगत् अनित्यत्वबोधाद् वैराग्यं जायते।',
    'उदितं ज्ञानं न नश्यति।',
    'आत्मा पुण्यपापैर्न लिप्यते।',
    'अज्ञाननाशे जन्ममरणचक्रं निवर्तते।',
    'कर्मणि वर्तमानोऽपि ज्ञानी अकर्मचैतन्यं पश्यति।',
    'मोक्षाय आत्मविचारः प्रत्यक्षोपायः।',
    'आत्मा न करोति न भुङ्क्ते; केवलं प्रकाशयति।',
    'वैराग्यं विना ज्ञानं न दृढं भवति।',
    'ब्रह्माद्वितीयम्।',
    'मुक्तः जगत् अनित्यप्रतिभासं पश्यति।',
    'द्वैतात् भयम्।',
    'आत्मा ज्योतिषां ज्योतिः।',
    'ज्ञानं कर्म मूलतः छिनत्ति।',
    'ज्ञानी आत्मन्येव सन्तुष्टः।',
    'आत्मा नित्यः; देहस्तु नश्वरः।',
    'शोकः मनस एव, नात्मनः।',
    'मोक्षः ब्रह्मात्मैक्यस्य प्रत्यक्षबोधः।',
    'आत्मा निर्गुणः।',
    'अज्ञानात् बन्धः, ज्ञानात् मुक्तिः।',
    'तत्त्वविद् नित्यं तृप्तः।',
    'आत्मा सुखदुःखयोर्न स्पृश्यते।',
    'ब्रह्मैव अस्ति; बहुलता कल्पिता।',
    'ज्ञानी कर्मफलासक्तिं त्यजति।',
    'आत्मज्ञानमेव शाश्वतीं शान्तिं ददाति।',
    'आत्मा जन्मजरामरणातीतः।',
    'अज्ञानात् व्यक्तित्वभ्रमो जायते।',
    'आत्मविद् सर्वशोकात् तरति।',
    'वैराग्यशुद्धमनसि ज्ञानोदयः।',
    'आत्मा नित्यं शुद्धः।',
    'जगत् व्यवहारसत्यं, न परमार्थसत्यं।',
    'ज्ञानी पद्मपत्रवत् असङ्गो वर्तते।',
    'आत्मा सर्वानुभवानां साक्षी।',
    'ज्ञानं अज्ञानं समूलं नाशयति।',
    'तत्त्वज्ञः कुत्रापि भेदं न पश्यति।',
    'आत्मा कारणकार्यविवर्जितः।',
    'वैराग्यं ज्ञानं च सहचरौ।',
    'आत्मैव नित्यः।',
    'बन्धः कल्पितः, मुक्तिः सत्यः।',
    'ब्रह्मविद् परमं आनन्दं प्राप्नोति।',
    'आत्मा न अनुभव्यवस्तु; स अनुभविता।',
    'सर्वशास्त्राणि आत्मज्ञानमेव निर्दिशन्ति।',
    'अज्ञानमेव संसारहेतुः।',
    'आत्मा अनन्तचैतन्यम्।',
    'प्राप्तं ज्ञानं न नश्यति।',
    'ज्ञानी आत्मन्येव विश्राम्यति।',
    'ब्रह्म सर्वसीमातीतम्।',
    'आत्मा नित्यं मुक्तः।',
    'मोक्ष इहैव इदानीम्।',
    'आत्मा सर्वाभासानां आधारः।',
    'आत्मज्ञानं परमं ज्ञानम्।',
    '“अहं ब्रह्मास्मि” इति ज्ञात्वा नित्यशान्तौ प्रतिष्ठते।'
  ],
  [
    Article(
        heading: 'The Nature of Brahman',
        body: 'Brahman is existence absolute, consciousness absolute, and bliss absolute. It is without attributes (nirguna), beyond all qualities and limitations. It is not this, not that (neti neti), yet it is the reality behind all appearances.\n\nBrahman is the ultimate truth, the ground of all being. It is neither born nor does it die, neither increases nor decreases. It is eternal, infinite, and unchanging. The entire universe appears in Brahman like waves in the ocean, yet Brahman remains unaffected.\n\nTo realize Brahman is to understand that the individual self (Atman) and the Supreme Self (Brahman) are one and the same. This realization is not intellectual understanding but direct experience - the culmination of spiritual practice.\n\nBrahman cannot be known through the senses or mind, for it is the very consciousness by which all else is known. It is self-evident, self-luminous, and self-existent. When all superimpositions are removed, what remains is Brahman alone.'
    ),
    Article(
        heading: 'Maya and the World',
        body: 'Maya is the mysterious power by which the one appears as many. It is neither real nor unreal but indescribable (anirvachaniya). Maya veils the true nature of Brahman and projects the world of multiplicity.\n\nThe world, from the absolute standpoint, is neither real nor unreal. It appears real to the ignorant but is known to be apparent to the wise. Like a dream that seems real while being experienced, the world has empirical reality but no ultimate reality.\n\nMaya operates through the three gunas - sattva (harmony), rajas (activity), and tamas (inertia). These three qualities in various combinations create all the diversity we see. The wise transcend the gunas and realize their true nature beyond all qualities.\n\nUnderstanding maya is crucial for liberation. When we realize that the world is a superimposition on Brahman, we are no longer bound by it. We can function in the world while knowing its true nature.'
    ),
    Article(
        heading: 'The Path to Liberation',
        body: 'Liberation (moksha) is not something to be attained but something to be realized. We are already free; ignorance alone makes us feel bound. The path to liberation involves removing this ignorance through knowledge (jnana).\n\nThe traditional path involves three steps: hearing the truth (shravana), reflecting on it (manana), and meditating on it (nididhyasana). Through this process, the truth becomes direct experience.\n\nDiscrimination (viveka) between the real and unreal is essential. We must learn to distinguish between the Self and the not-self, the eternal and the temporary, consciousness and its contents.\n\nDispassion (vairagya) naturally follows discrimination. When we truly understand the temporary nature of worldly pleasures, attachment falls away naturally.\n\nThe four qualifications for spiritual practice are: discrimination, dispassion, the six virtues (including tranquility and self-control), and an intense desire for liberation. With these qualifications and the grace of a guru, liberation is assured.'
    )
  ],
);
