// yogananda_en.dart
// Paramhansa Yogananda quotes and articles

import '../articlesquotes.dart';

final yoganandaSaintSa =   Saint(
  'yogananda',
  'Paramhansa Yogananda',
  'assets/images/paramhansa.jpg',
  [
    'जीवनं साधारणमार्गेण मा नय; यत् अन्यैः न कृतं तत् कुरु—यत् जगत् विस्मययेत्।',
    'विफलताकालः सफलताबीजवपनाय श्रेष्ठः कालः।',
    'यथाशक्ति सरलः भव; तदा पश्यसि—तव जीवनं कियत् अकलुषं सरलम् आनन्दमयं च भवितुम् अर्हति।',
    'वर्तमानक्षणे शान्त्या वस; समक्षं सर्वस्य सौन्दर्यं पश्य। भविष्यं स्वयमेव स्वकार्यं करिष्यति।',
    'केवलं स्वहृदयस्य सुखं आत्मानं न तर्पयति; स्वसुखे आवश्यकतया परेषां सुखमपि समावेशयितुं प्रयत्नः करणीयः।',
    'स्वयं परिवर्तस्व; तेन जगत्परिवर्तने तव भागः कृतः।',
    'धैर्यनिरन्तरता फलानां अवश्यंभावं सुनिश्चितं करोति।',
    'शान्तः, प्रशान्तः, सदा आत्मनि अधिकारवान् भव। ततः जानीषे—सहजीवितं कियत् सुलभम्।',
    'मम आत्मा हृदयेन हसतु, हृदयं नेत्राभ्यां हसतु—येन शोकहृदयेभ्यः समृद्धहास्यं विकिरामि।',
    'अपूर्णकामानां बलमेव मानवदास्यस्य मूलम्।',
    'आनन्दः तव मनःस्थितौ, न तव सम्पदां स्थितौ निर्भरः।',
    'सफलतायाः आनन्दस्य च रहस्यं तव अन्तरेव। यदि बहिः समृद्धिं लभसे, अन्तःशान्तिं तु न, तदा त्वं न यथार्थतः सफलः।',
    'शान्तिः आत्मनः प्रस्रवति; सा पवित्रा अन्तःपरिसरः यत्र यथार्थानन्दः विकासं प्राप्नोति।',
    'बहुधनसम्पत्तौऽपि अन्तःशान्त्यभावः—समुद्रे स्नानं कुर्वन् तृषार्त इव।',
    'यथार्थतः सफलः स—यः स्वसिद्धान्तानुसारं जीवन् हृष्टः सन्तुष्टश्च।',
    'यथार्थशान्तिं आनन्दं च स्वयम् अन्तरेव अन्वेष्टव्यम्; बाह्यानुभवाः केवलं क्रीडारूपाः स्युः।',
    'उन्मत्तानन्दः न कठिनः; शान्तया हर्षेण स्थितिः कठिनतरा—सा एव आदर्शः।',
    'प्रत्येकं वर्तमानक्षणं पूर्णतया जीव; भविष्यं स्वयमेव साधयिष्यति।',
    'यावत् शान्तिसन्निधिं अभ्यासयसि, तावत् तस्य शक्तेः सन्निधिं स्वजीवने अनुभविष्यसि।',
    'अस्तित्वस्य रहस्यं सर्वं—निर्भयता।',
    'दयालुता सा ज्योतिः या आत्मसु, कुटुम्बेषु, राष्ट्रेषु च भित्तीः विलापयति।',
    'जीवने अल्पोऽपि आनन्दः बहुसम्पत्तेः श्रेयः।',
    'यत् भूमिकां त्वं नाट्ये वहसि, तस्या अभिनयः तव सत्यस्वरूपं न स्पृशति—एतद् अवगच्छ।',
    'पुरुषस्य श्रमफलस्य परमो लाभः न यत् स लभते, अपि तु यत् स भवति।',
    'आध्यात्मिकचेतनायाः आशीर्वादेषु त्वं योग्यः।',
    'ध्यानाभ्यासेन जानासि—हृदये स्वर्गमिव वहसि।',
    'आत्मा ध्यानं प्रीयते; यतः आत्मना सह संयोगे परमानन्दः।',
    'ध्यानं देहबन्धनात् आत्मोद्धरणस्य परमार्गः।',
    'ध्यानं यतः भगवच्छान्तिः आत्मनि प्रवहति।',
    'अल्पकाले गभीरध्यानं, दीर्घकाले चञ्चलध्यानात् श्रेयः।',
    'स्थिरो भव; जानीहि—अहमेव देवः।',
    'यः परं प्रयत्नं करोति स भक्तः भगवन्तं लभते; बहून् बहाने अन्वेषमाणो न।',
    'ध्यानकाले सर्वत्र तस्मै द्वाराणि उद्घाटितानि पश्यसि।',
    'देवप्राप्त्यर्थं प्रयत्ने उत्तेजितो वा अधीरः वा मा भव। धैर्यवान् भव। शान्त्या एव दिव्यलक्ष्यं प्रति गच्छ।',
    'मनः तादृशं छलनीवत्—येन विश्वज्ञानप्रवाहः अस्माकं चेतनायां प्रविशति।',
    'यावत् देवं प्रीयसे, तावत् सर्वान् प्रीतुं शक्नोषि; यतः सर्वेषु तमेव पश्यसि।',
    'चरित्रपरीक्षा श्रेष्ठा—यथा स त्यज्येष्वपि जनेषु व्यवहारं करोति।',
    'यत् इच्छसि तत् मा कुरु; ततः यत् रोचते तत् कर्तुं शक्यते।',
    'सफलतायाः आनन्दस्य च रहस्यं तव अन्तरेव।',
    'आसक्तिविमुक्तिं विना यथार्थानन्दो न।',
    'प्रेम प्रत्युत्तरफलम् अनपेक्ष्य ददाति।',
    'प्रियस्य पूर्णताम् इच्छन्, तस्य आत्मानं चिन्तयन् शुद्धानन्दं अनुभवन्—एतत् दिव्यप्रेम; एषा एव यथार्थमैत्री।',
    'प्रेम सा ज्योतिः या आत्मसु, कुटुम्बेषु, राष्ट्रेषु च भित्तीः विलापयति।',
    'ध्यानसमाधौ भगवत्सङ्गमे एव परमो प्रेमानुभवः।',
    'नष्टप्रेमहेतोः मा शोच। प्रेम कदापि न नश्यति; बहुहृदये तु त्वया सह क्रीडति।',
    'यदा त्वं प्रेम ददासि, तद् नित्यं भवेत्—न तस्य समीपवासनया, किन्तु तस्यात्मनः पूर्णकामनया।',
    'समग्रं जगत् आत्मनः क्रीडास्थली।',
    'तस्मै सह सङ्गमे, जगत्क्षतयः अपि तद् आनन्दं शान्तिं च न हर्तुं शक्नुवन्ति।',
    'भगवतः अनन्तप्रेम्णि, मम नित्यत्ववक्षः सर्वं धारयितुं समर्थम्।',
    'मम हृदयं नित्यप्रेम्णः मन्दिरम्।',
    'यथार्थमित्रः भवितुं, परान् स्वात्मवत् प्रीयस्व; तदा तेषां आवश्यकता-दुःखं च अवगन्तुं शक्नोषि।',
    'प्रेम न भावुकता; स सृष्टेः सारतत्त्वे स्थितं सत्यम्।',
    'भगवतः प्रेम, आत्मनः प्रेम—सर्वग्राही प्रेम।',
    'रात्रिन्दिवं भगवत्प्रेममदेन उन्मत्तः भव; यथा देवं विना किञ्चिदपि न जानासि।',
    'आत्मा-परात्मयोः प्रेम परिपूर्णतमं; यद् सर्वे अन्विष्यन्ति तत्।',
    'मर्त्यत्वेन सीमितोऽसि; भगवतः पुत्रत्वेन अनन्तोऽसि।',
    'मानवमनः भगवतः सर्वशक्तिचैतन्यस्य एकः स्फुलिङ्गः।',
    'विचाराः त्वां निर्मान्ति। पापकविचारफलः पापः; शुभविचारफलः शुभः।',
    'यदि दुष्टे विषये विचारान् स्थापयसि, तदा स्वयमेव विकृतो भविष्यसि।',
    'त्वयन्तर्गतं देवबलं—असीमितनियन्त्रणशक्तिः—अतीन्द्रियचेतसि विद्यते।',
    'मरणोत्तरमपि त्वं यथापूर्वं तथैव; किञ्चिदपि न परिवर्तते; देहं केवलं त्यजसि।',
    'मनः शक्ति—या जगदपि जयितुं शक्यते।',
    'दोषविमोचनाय मृत्युम् मा अपेक्षस्व।',
    'त्वयन्तर्गता सर्वसिद्धिक्षमता; सा इच्छाशक्तौ।',
    'मनः उन्मत्तकपिवत्; इच्छा तस्य बन्धनरज्जुः।',
    'यथार्थस्वपरिशीलनं प्रगतिशिल्पानां श्रेष्ठतमम्।',
    'विफलताकालः सफलताबीजवपनाय श्रेष्ठः कालः।',
    'विचाराः वयं भवन्ति; यद् चिन्तयामः, तद् भवामः।',
    'यावत् एकाग्रता वर्धते, तावत् यत् इच्छसि तत् कर्तुं शक्नोषि।',
    'मनोजयः—स्वातन्त्र्यम्।',
    'मृत्युः सुन्दर एव; यदि स अशुभः स्यात्, भगवान् अस्मान् तं न अनुमन्येत।',
    'रोगस्वास्थ्यशोकानन्दस्य मायाछायाम् अपाकुरु; तद् अतिक्राम। आत्मा भव।',
    'सर्वे आत्मानो भगवतः—शुद्धात्मनः पृथग्भूताः किरणाः—स्वस्वपरिपूर्णतां प्रति पुनर्विकासं यान्ति।',
    'तरङ्गः समुद्रवत्; सर्वसमुद्रो न। एवं सृष्टितरङ्गः नित्यात्मसागरस्य अंशः।',
    'इदं जीवनं क्षणिकम्; जगन्मोहाः अनित्याः; परार्थजीवनवन्तः एव जीविताः, शेषे अधिकं मृताः।',
    'परमः संग्रामः स्वमनसि एव।',
    'प्रत्येकः श्वः अद्यैव नियतं भवति।',
    'कस्मादपि मा बिभेः। कञ्चिदपि मा द्वेष्ट। सर्वेभ्यः प्रेम दद, भगवत्प्रेम अनुभूय, सर्वेषु तस्य सन्निधानं पश्य।',
    'क्षणिकविचारैः प्रतिभया वा न तावत्; प्रतिदिनपरिचयाः एव तव जीवनं नियच्छन्ति।',
    'यः जानाति क्व गन्तव्यं, दृढनिश्चयश्च, तस्मै जगत् मार्गं ददाति।',
    'चरित्रपरीक्षा श्रेष्ठा—यथा स त्यज्येष्वपि जनेषु व्यवहारं करोति।',
    'यद् चिन्तयसि तद् भवसि; यद् अनुभवसि तद् आकर्षयसि; यद् कल्पयसि तद् सृजसि।',
    'जीवनस्पर्धायां क्रीडाकुशलो भव; परं स्मर—यथार्थस्पर्धा अन्तः प्रवर्तते।',
    'गभीरध्यानकर्मभिः प्रत्येकः साधकः स्वचञ्चलतां निवारयेत्।',
    'पूर्णस्वास्थ्य-पूर्णानन्द-पूर्णसफलतानां रहस्यं—स्वमनोनियन्त्रणम्।',
    'अनेकेषु जन्मसु स्वयमेव निर्मितचेतनासारः एव त्वम्।',
    'कर्मसिद्धान्तः न दण्डः; स कारणकार्यनियमः, पूर्णन्यायनियमश्च।',
    'प्रत्येकस्य स्वमार्गनिर्वरणे अधिकारः; किन्तु स्ववरणफलान् अपि गृहीतुम् अर्हति।',
    'तव भाग्यं तव हस्तयोः; यतः विचारकर्मपरिवर्तनशक्तिः तव अस्ति।',
    'इच्छाशक्तिः तव अन्तःस्थितदेवप्रतिमायाः करणम्।',
    'दृढेच्छा स्वबलात् सिद्ध्युपायं सृजति।',
    'इच्छाशक्तिः रचनात्मकतया उपयुज्यताम्; न हिंसायै, न तु तुच्छविषयेभ्यः।',
    'तव जीवनं न अकस्मात्; स्वनिर्मितमेव।',
    'जीवनस्य उद्देश्यः—परार्थजीवनं, भगवन्निष्ठा च।',
    'महापातकं—आत्मानं दुर्बलं मन्यते।',
    'विश्वं तस्य सन्निधानस्य महान् मन्दिरम्।',
    'अस्य जीवनस्य छायानाम् अधः तस्य अद्भुतज्योतिः।',
    'आत्मा देहे न; देहः आत्मनि।',
    'सर्वं देवः। सर्वं चेतनम्। सर्वं एकम्।',
    'पदार्थजगत् स्वप्नवत्; किन्तु मनःशक्त्या परिवर्तनीयः स्वप्नः।',
    'जगत् महाव्यायामशाला—यत्र वयं स्वयम् दृढाः भवामः।',
    'पृथक्त्वभ्रमः सर्वदुःखस्य मूलम्।',
    'त्वं नित्यात्मसागरस्य अंशः।',
    'यावत् ध्यायसि, तावत् जानासि—त्वं देहो न, अमरात्मा।',
    'जीवनार्थः—देवेन सह एकत्वप्रत्यभिज्ञानम्।',
    'यावत् परहिताय बहिः निर्याति, तावत् हृदयं शुद्ध्यति।',
    'जगते यत् श्रेष्ठं तव अस्ति, तत् दद; ततः श्रेष्ठतमं पुनरागमिष्यति।',
    'समृद्धिनियमः स्वार्थनियमेन न; परार्थनियमेन।',
    'यः किञ्चिदपि प्रत्युत्तरं न याचते, पूर्णनिःस्वार्थः स एव परमसफलः।',
    'परसेवा देवसेवा।',
    'क्रियायोगः मानवविकासस्य शीघ्रता-हेतुः उपायः—प्राणशक्त्या मनोनिग्रहः; अनन्तस्य प्रति वैज्ञानिकः पन्थाः।',
    'क्रियायोगस्य परिणामाः परमानन्दशान्तिं जनयन्ति—सर्वेषां देहसुखानां योगात् अपि अधिकाम्।',
    'ध्यानानन्दात् मे सहस्रनिद्राभिः तुल्यः विश्रामः लभ्यते; उन्नतयोगिनः सामान्यनिद्रा प्रायः अनावश्यकम्।',
    'आत्मसाक्षात्कारः—सत्येन सह योगः, एकत्वम्—आत्मनः प्रज्ञाभिः सत्यस्य प्रत्यक्षानुभवः।',
    'अस्मिन् आध्यात्मिककर्ममार्गे न अपूर्णप्रयत्नस्य नाशः, न च विपरीतफलोत्पत्तिः।',
    'यथार्थधर्मस्य अल्पोऽपि अंशः पुनर्जन्ममरणचक्रे निहितं महाभयं निवारयति।',
    'योगः आध्यात्मिककर्ममार्गः—कल्पनां साक्षात्कारं नयन् अच्युतः। एतं मार्गं ये गृह्णन्ति, तेषां प्रयत्नः नित्यहितः।',
    'पदार्थजगति सफलताः दृश्यफलैः ज्ञायन्ते; आध्यात्मिकमार्गे फलानि सूक्ष्माणि, चित्तगताः, किन्तु नित्यहितकारिणि।',
    'आध्यात्मिकफलानि चेतनायां सूक्ष्मपरिवर्तनरूपेण आरभन्ते—अन्तःसत्त्वस्य प्रगतिचिह्नानि।',
    'यथार्थधर्मः नित्यधर्मान् तत्वानि समावहति, ये रोग-दुःख-अज्ञानात् मनुष्यं नित्यं रक्षन्ति।',
    'अतीतं विस्मर; गतजीवनानि बहुलज्जया तमोमयानि। दिव्ये न स्थापनं यावत्, तावत् मानुषव्यवहारः चञ्चलः।',
    'यदि वर्तमानकाले निष्कपटं आध्यात्मिकप्रयत्नं क्रियते, तर्हि भविष्ये सर्वं सुधारं प्राप्स्यति।',
    'त्वं सदा आत्मनः परिपूर्णप्रतिबिम्बः; इदानीं मर्त्यत्वं कल्पयसि। स्वस्वरूपध्यानं तव दिव्यस्वभावं स्मारयति।',
    'अमरत्वात् भूसीमाः मा वह।',
    'ध्यानं—देहबोधं सीमाबोधं च निरस्य आत्मना सह एकत्वे स्थितिः, “अहं आत्मा” इति स्मरणम्।',
    'ध्यानं देवसत्तायाः प्रमाणं ददाति।',
    'यः आकाशं पर्वतान् समुद्रं वा पश्यति, स न तावत् दिव्यसन्निधानं पश्यति; स्रष्टुः सूक्ष्मकिरणः अशिक्षितदृष्टये अगोचरः।',
    'ईश्वरः अनन्तः; कस्यचित् रूपे न बध्यते, तथापि सर्वरूपेषु प्रकटः—स सर्वेषु मनुष्येषु साधुषु च समः।',
    'प्राणिषु यथार्थभेदो न; सर्वे प्रकृतेः मातुः उत्पादाः, एकेन देवत्वेन धारिताः।',
    'तेषां भासमाननानात्वं एकमनसः ऐक्ये मूलम्; एतत् जानन् मोक्षं प्राप्नोति, देवेन सह एकत्वं च।',
    'मुक्तः पुरुषः सर्वभूतेषु सर्वसृष्टौ च केवलं प्रभुं पश्यति।',
    'देवः चेतना; विश्वे मनो वा चेतना वा विना किञ्चिदपि न।',
    'देवस्य संस्कृतनाम—सच्चिदानन्दः—नित्यसत्तां, अनन्तचेतनां, नवनवामोदं च बोधयति।',
    'भगवान् सर्वेषां आत्मा सन् अपि, सृष्ट्या न बध्यते; मानवाः तु देवेन पूरिताः सन्तोऽपि मायाबन्धने पतन्ति।',
    'यथार्थबुद्धिः—यथा एकचेतना सर्वं भवति इति बोधः।',
    'पण्डिताः अनित्यवस्तुषु न शोचन्ति; जागतिकं क्षुद्रं, यतः न नित्यं।',
    'ते मर्त्यचञ्चलतां जयन्ति, देहतादात्म्यत्यागे लभ्यां शान्तिं अनुभवन्ति।',
    'यदा एते भक्ताः अचलपरिपूर्णतां प्राप्नुवन्ति, तदा जीवनपरिवर्तनानि अनासक्ताः पश्यन्ति।',
    'परिवर्तनतरङ्गैः तादात्म्यं क्लेशं जनयति; परिवर्तनार्थं जीवितं नित्यताद्वियोगः।',
    'पण्डिताः मित्र-कुटुम्ब-सम्पत्तिभ्यः नित्यानन्दं न अपेक्षन्ते; अमरात्मध्यानात् नित्यशान्तिः।',
    'आधुनिकजीवनं असन्तोषजनकं; बहुकाम-चिन्ता-क्षणिकसुखैः शोकं जनयति।',
    'अस्मिन् लोके सुरक्षा न; रोगाद् दुर्भाग्याद् वा कदा चित् चेतना देहं परित्यक्तुम् बाध्यते।',
    'कालदेशस्य अनित्यप्रदेशे रूपप्रकाशयोः सततपरिवर्तनम्; अन्तःसारः तु नित्यः।',
    'नित्यः मानवात्मा, विश्वात्मा च—कृष्णचैतन्यं ख्रिस्तचैतन्यं चेति—आत्मनः अभिव्यक्तयः।',
    'प्रथमं दुष्टविचारदोषसंस्कारान् विमोचय; द्वितीयं शुभसंस्कारान् स्थापय, सत्कर्माणि च कुरु।',
    'प्रयत्नं कुरुष्व; उन्नतिं यास्यसि। साधुः केवलं पापी—यः कदापि न त्यक्तवान्।',
    'कदापि मा त्यज; यः आध्यात्मिकविचारः त्वया चिन्तितः, स नित्यं तव मित्रं भविष्यति।',
    'यत् पापकाम्यम् उपार्जयसि, तद् यावत् न हन्यते तावत् शत्रुः।',
    'जीवने पदार्थ-आध्यात्मिककर्तव्ययोः सम्यग्साम्यं कुरु; तत् परमानन्दं जनयति।',
    'जाग्रत् भव; पुनः मा निद्रा। अध्ययन-प्रतिज्ञान-एकाग्रता-ध्यानैः चेतनायाः शिक्षणं मोक्षमार्गः।',
    'देहस्य चञ्चलविकारात् मनः निवार्य, सूक्ष्मस्थिरप्राणस्पन्दनेषु उच्चतरचित्तस्थितिषु च मनः स्थापय।',
    'अल्पेषु इदानीं सुखेषु त्यागेषु कृत्वा, ईश्वरस्य नित्यनवानन्दं वृणु; जागतिकसुखं न स्थिरम्।',
    'देह इति मा चिन्तय; देहात् परं हर्षचेतना अमरलाइफ् च त्वम्।',
    'यथार्थाः सत्याः तव न भवन्ति यावत् त्वं तान् अन्तरे साक्षात्करोषि; असाक्षात्कारे ते केवलं विचाराः।',
    'आध्यात्मिकचेतना न धूमिलधर्मविचारः; आत्मसाक्षात्कारलाभ एव।',
    'समुद्रं घटे न गृह्यते यावत् घटस्य विस्तारः न; तथा देवबोधाय मानवीन्द्रियाणां विकासः आवश्यकः।',
    'ग्रहणं आत्मविकासेन प्राप्यं सामर्थ्यम्—न केवलं विश्वासः।',
    'मर्त्यचेतनायाः दुर्बलता त्यज; राजमार्गे उत्थाय चल।',
    'अन्यत् सर्वं प्रतीक्षां करोतु; तव देवशोधः प्रतीक्षां न करोतु।',
    'एता उपदेशाः न केवलं प्रवचनानि; सत्याः—ये त्वां मोचयिष्यन्ति।',
    'क्रियायोगः प्राणशक्त्या चित्तचाञ्चल्यं शमयति, अनन्तेन सह प्रत्यक्षसङ्गमं च साधयति।',
    'ध्यानानन्दः सामान्यदेहसुखान् अतिक्रामति; निद्रायाः अपि गभीरतरः।',
    'आनन्दः न बाह्यघटनाप्रतिक्रिया; स साधनया प्राप्यः चेतनास्थितिः।',
    'यथार्थधर्मः दिव्यसत्यस्य प्रत्यक्षानुभवः, न केवलं बुद्धिस्वीकृतिः।',
    'आध्यात्मिकप्रयत्नः न केवलं अन्तःशान्तिं लभते; भयदुःखात् आत्मानं रक्षति।',
    'आध्यात्मिकसाधनस्य लाभाः सूक्ष्मा अपि नित्या; चेतनां नित्यं परिवर्तयन्ति।',
    'दिव्यनिष्ठा, जगतमोहसुखैः न दातुं शक्यां सुरक्षां ददाति।',
    'ध्यानं प्रज्ञाशक्तिं उद्घाटयति, आत्मजीवनविषये गूढसत्यानि प्रकाशयति।',
    'दिव्यसन्निधानं सूक्ष्मम्—इन्द्रियगोचरातीतम्।',
    'सर्वाणि रूपाणि, नानाविधानि अपि, एकेन देवत्वेन धार्यन्ते।',
    'मोक्षः—देवैक्यबोधेन; बाह्यभेदान् अतिक्रम्य।',
    'जागतिकप्रयत्नाः सम्पत्तयश्च अन्ते लीयन्ते; यत् तु स्थिरं, तत् आत्मसाक्षात्कारः।',
    'अमरत्वं आत्मनः स्वभावः; क्षणिकरूपैः आत्मपरिभाषा मा भवतु।',
    'सृष्टेः सारः चेतना—अनन्तरूपेण प्रकटापि, सारतः एका।',
    'यथार्थबुद्धिः बुद्धिमात्रातीतः; सा प्रज्ञासाक्षात्कारे विश्राम्यति।',
    'मानवचञ्चलता शम्यते यदा चेतना नित्ये स्थितिं गृह्णाति।',
    'परिवर्तनचक्रं तेषां न प्रभवति ये आत्मनि निष्ठिताः।',
    'आध्यात्मिकशान्तेः स्पृहा सकलकामेभ्यः गम्भीरा।',
    'शान्तानुभवक्षमता आत्मस्थित्या नियता।',
    'साधोः धैर्यमेव अज्ञानजयस्य प्रमाणम्।',
    'प्रत्येकः आध्यात्मिकविचारः नित्यशान्त्यै आधारं स्थापयति।',
    'दिव्यसत्ये नित्यवासः आध्यात्मिकप्रगतिं दृढीकरोति।',
    'दुष्टविचाराः यावत् न अतिवर्त्यन्ते, तावत् शत्रवः।',
    'पदार्थकर्तव्य-भक्तिसाम्याद् परमानन्दः।',
    'देहतादात्म्यं त्यक्त्वा चेतनाशिक्षणेन अन्तःस्वातन्त्र्यं प्रकटते।',
    'निरन्तरध्यानात् स्थिराः उच्चचेतनास्थितयः उद्भवन्ति।',
    'दिव्यानन्दवरणेन मोक्षदिशि भाग्यं नीयते।',
    'मर्त्याभिमानः माया; गूढचेतनायां लीयते।',
    'अनुभवे अन्तरीकृताः सत्याः एव जीवनं परिवर्तयन्ति।',
    'देवसाक्षात्कारः परमोऽर्थः—बुद्धिविश्वासात् परः।',
    'दिव्यसत्यग्रहणक्षमतावृद्धिः आध्यात्मिकवृद्धेः कुञ्जिका।',
    'केवलं विश्वासः चेतनां न मोचयति; साक्षात्कारः मोचयति।',
    'आध्यात्मिकमार्गः राजमार्गः; मर्त्यताम् अतिक्रम्य उत्थातुं साहसं याचते।',
    'देवशोधः सर्वेषु अन्योपायेषु श्रेष्ठः; तस्य अग्रे सर्वं गौणम्।',
    'एता उपदेशाः जीवनदायिनः सत्याः, न तु निरर्थककल्पनाः।',
    'ध्यानं सामान्यक्षणान् अमरतापथे पदानि करोति।',
    'आनन्दः—अन्तःस्थितभगवत्सन्निधानस्य साक्षात्बोधः।',
    'आत्मा जीवनात् पलायनेन न; जीवनमध्ये चेतनापरिवर्तनेन एव साक्षात्क्रियते।',
    'प्रत्येकः साधनाकालः अन्तःशान्तिं विस्तारयति।',
    'मानवे दिव्यस्फुलिङ्गः असीमशान्तेः स्रोतः।',
    'चेतना अन्तर्मुखी यदा भवति, तदा मानवविकासः शीघ्रः।',
    'मनश्चाञ्चल्यं आत्मस्वभावं आवृणोति।',
    'ध्यानमौनस्य मध्ये आत्मा नित्यसत्यं वदति।',
    'यथार्थशान्तिः परिस्थितेः परे; सा चेतनास्थितिः।',
    'प्रत्येकः आध्यात्मिकजयः दिव्येन सह सम्बन्धं दृढीकरोति।',
    'भगवतः सन्निधानं सूक्ष्मं किन्तु नित्यं; भक्त्या लभ्यते।',
    'विश्वं दिव्यचेतनायाः अभिव्यक्तिः।',
    'भयनिवारणस्य आदिः—दिव्यस्वात्मनि निष्ठा।',
    'ध्यानं अमरात्मस्वरूपं प्रकाशयति।',
    'नित्यनवानन्दः अन्तिमः साक्षात्कारः—सत्साधकस्य।'
  ],
  [
    Article(
        heading: 'God alone',
        body: 'Who is it who knows all the secrets of all the Souls who ever lived, dazzling the world, and who are now lost and gone?\n\nGod alone! God alone!\n\nWho lived in the loneliness of the eternal void, before the atoms blinked their glittering eyes and danced through all Creation?\n\nGod alone! God alone!\n\nWe came out of Something, we know not what. We know that we live, laugh, and linger now, and most of us will not know what lies in the wilderness of the great Beyond when we fall asleep in the arms of peaceful death. Yet, who knows the secret of Life, both before and after this existence?\n\nGod alone! God alone!\n\nAll things are living; all things are dancing in the rhythm of eternal harmony. No one knows about the grand procession of Creation, which emerged from the mystic chamber of space. No one knows which part of this chamber of the endless void is occupied by objects and Beings, melted by the magic wand of death, except –\n\nGod alone! God alone!\n\nOur loved ones love us, and vow to love us forever, and yet they forget us when they sink into the Great Sleep. Their memories become frozen anon. Yet, who loves us forever without ever telling us, and who remembers us when all others forget us?\n\nGod alone! God alone!\n\nLife and death, stars and wind, love and hate, sorrow and pleasure, and man and beast dance and sleep on the Stygian stage of Time, hiding behind the scenes at death, and coming out to play again on the stage of Time in new costumes of flesh. No one remembers what he did before, or why he is so sure of this temporary rendezvous in this curious caravanserai except –\n\nGod alone! God alone!\n\nWhy God is playing this game, and why He keeps all this knowledge to Himself, only meagerly sharing it with us, His Children, is known by –\n\nGod alone! God alone!\n\nYet, if you roam no more, and come closer to the Infinite Shore within, and change yourself from the undesirable position of being a prodigal son to that of being a true celestial offspring, then you, too, may know all things that you want to know from none other than –\n\nGod alone! God alone!\n\nSince He knows all things, when you change into a demanding Son Divine, you too shall know all things from –\n\nGod alone! God alone!\n\nWhen all friends must leave you, who will be with you?\n\nGod alone! God alone!\n\nSince no things and no one are really yours, learn to love –\n\nGod alone! God alone!'
    ),
    Article(
        heading: 'Acquiring Happiness',
        body: 'Paramhansa Yogananda, November 1936:\n\nWe can never be happy unless we are progressing and seeking satisfaction in doing so, and unless we are guarding our happiness from all the influences which destroy it. Happiness comes, not by helplessly thinking, but by living it in all the moods and actions of life. No matter what you are doing, keep the undercurrent of happiness, the secret river of joy, flowing beneath the sands of various thoughts and the rocky soils of hard trials. Learn to be secretly happy within your heart in spite of all circumstances, and say to yourself, “Happiness is my greatest Divine birthright — the buried treasure of my Soul. I have found that at last I shall secretly be rich beyond the dream of Kings.”\n\nDo not make unhappiness a chronic habit, for it is anything but pleasant to be unhappy, while it is blessedness for yourself and others when you are happy. When it is so easy to wear a silver smile, or to pour sweet happiness through your voice, why be grouchy and scatter unhappiness around you? It is never too late to learn.\n\nHappiness grows by what it is fed on. Learn to be happy by being happy all the time. John said, “If I get money, I shall be happy.” He became wealthy; then he said, “I shall be happy if I get rid of my acute indigestion.” His indigestion was cured, but he thought, “If I get a wife, I shall be happy.” Then bedlam started, for he married a nagging, tongue-lashing woman. He divorced this wife, and after many years married again, but the second wife was worse than the first one. Then he thought that he would be happier if he divorced his second wife, so he did, but at the age of seventy he thought, “No, I shall never be happy unless I can be youthful again.” In this way people try but never reach their goal of happiness. They are like the man who raced in anger to bite his own nose, but never could, of course.\n\nIgnorant people, like animals, do not heed the lessons which accompany pain and pleasure. Most people live a life checkered with sadness and sorrow, for they do not avoid the actions which lead to suffering and do not follow the ways which lead to happiness. Then there are people who are always consciously over-sensitive to sorrow and happiness when they come. Such people are usually extremely crushed by sorrow and are overwhelmed by joy, thus losing their mental balance. There are very few people who, after burning their fingers in the fire of ignorance, learn to avoid misery-making acts.\n\nMany people wish to be happy, and yet they never make the effort to adopt the course of action which leads to happiness. Most people keep rolling down the hill of life only mentally wishing to climb the peak of happiness. They sometimes wake up if their enthusiasm for happiness survives the crash to the bottom of suffering. Most people lack imagination and never wake up until something terrible happens to arouse them from their nightmare of folly.\n\nStagnant people are unhappy, and extremely ignorant people scarcely know how it feels to be either happy or unhappy. They are unfeeling, like the stones. It is better to be unhappy about your own ignorance than to die happily with it. Wherever you are, remain awake and alive with your thought, perception, and intuition, ever ready, like a good photographer, to take pictures of exemplary conduct and to ignore bad behavior. Your highest happiness lies in your being ever ready in desiring to learn and in behaving properly.\n\nPeople seeking happiness must avoid the influence of bad habits which lead to evil actions, for evil actions produce misery sooner or later. Misery corrodes the body, mind, and soul like a silently burning acid, and cannot be endured long. That is why it should be strictly avoided.\n\nCure yourself of evil habits by cauterizing them with the opposite good habits. If you have a bad habit of telling lies, and by so doing have lost many friends, start the opposite good habit of telling the truth. It takes time to form a good habit or a bad one. It is difficult for a bad person to be good and for a good person to be bad; yet, remember that once you become good, it will be natural and easy for you to be good; likewise, if you cultivate an evil habit, you will be compelled to be evil in spite of your desire, and you have to pray, “Father, my Spirit is willing, but my flesh is weak.” That is why it is worth-while to cultivate the habit of being happy.\n\nThe man sliding down evil paths finds no resistance; but as soon as he tries to oppose his evil habits by the adoption of spiritual laws of discipline, he finds countless temptations roused to fight and foil his noble efforts.\n\nDo Not Judge Others\n\nYour individual happiness depends to large extent upon protecting yourself and your family from the evil results of gossiping. See no evil, speak no evil, hear no evil, think no evil, feel no evil. Most people can talk about other people for hours and thrive under the influence of gossip like the temporary influence of intoxicating poisonous wine. Isn’t it strange that people can smoothly, joyously, and with caustic criticism talk about the faults of others for hours but cannot endure reference to their own faults at all?\n\nIf you do not like to talk about your own faults, if it hurts you to do so, you certainly should feel more hurt when saying unkind, harmful things about other people. Train yourself and each member of your family to refrain from talking about others. “Judge not, that ye be not judged.”\n\nBy giving publicity to a man’s weakness, you do not help him. Instead, you either make him wrathful or discouraged, and you shame him, perhaps forever, so that he gives up trying to be good. When you take away the sense of dignity from a person by openly maligning him, you make him desperate.\n\nWhen a man is down, he is too well aware of his own wickedness. By destructive criticism, you push him still farther down into the mire of despondency into which he is already sinking. Instead of gossiping about him, you should pull him out with loving, encouraging words. Only when aid is asked should spiritual and moral help be offered. To your own children or loved ones you may offer your friendly, humble suggestions at any time and thus remove their sense of secrecy or delicacy.\n\nSmile and Be Happy\n\nMake your home a valley of smiles instead of a vale of tears. Smile now and never mind how hard it has been for you to do so. Smile now. All the time remember to SMILE NOW, and you will SMILE ALWAYS.\n\nSome people smile most of the time, while beneath the mask of laughter they hide a sorrow- corroded heart. Such people slowly pine away beneath the shadows of meaningless smiles. There are other people who smile once in a while, and they may also be very serious at times; yet beneath the hard, beautiful outer appearance there may be gurgling a million fountains of laughing peace.\n\nIf you enjoyed good health for fifty years and then were sick for three years, unable to get healed by any method, you would probably forget about the length of time that you enjoyed good health and laughed at the idea of sickness. Now your reaction should be exactly the opposite. Just because you may have been sick for three years is no reason for thinking that you will never be well again.\n\nLikewise, if you were happy a long time, and you have been unhappy a comparatively short time, you are apt to lose hope of ever being happy again. This is lack of imagination. The memory of a long-continued happiness should be a forceful subconscious habit to influence your conscious mind and ward off the consciousness of your present trouble.\n\nWhen wealth only is lost, nothing real is lost, for if one has health and skill one can still be happy and can make more money; but if health is lost, then most happiness is also lost, and when the principle of life is lost, all happiness is lost. After bathing yourself in the Ocean of Peace in dreamland, as you awake with happiness, say, “In sleepland I found myself free from mortal worries. I was a King of Peace. Now, as I work in the daytime and carry on my diurnal battles of duties, I will no longer be defeated by insurgent worries of the kingdom of wakefulness. I am a King of Peace in sleepland, and I shall continue to be such a King in the land of wakefulness. As I come out of my Kingdom of Peace in sleepland, I shall spread that same peace in my land of wakeful dreams.”'
    )
    ,
    Article(
        heading: 'Divine Love',
        body: 'Thou art the mystic echo from the caverns of heart, and the inaudible voice of feeling.\n\nThou unseen charmer of souls, Thou art the fountain flowing from the bosom of friendship.\n\nThou are the unseen cord of self-bound souls and the rays of secret warmth which break buds of feeling into blossoms of endearing, soulful words of poesy and loyalty.\n\nThou art the Divine Cupid, enticing mystic souls to pierce the heart of all living things.\n\nThou art the silent language of souls, and the invisible ink which lovers use to write letters on the pages of their hearts.\n\nThou art the mother of all affections, and in Thy breast of love throbs the heart of God.\n\nLove is the heart-beat of all life, and the angel of incarnation.\n\nLove is the silent conversation between two hearts, and it is the call of God to all creatures, animate and inanimate, to return to His house of Oneness.\n\nLove is born in the garden of soul progress, and it sleeps behind the darkness of outer attachments. It is the oldest and the sweetest nectar, preserved in the bottle of hearts.\n\nIt is the flame which burns all weeds of selfishness, and destroys the walls of family and patriotic narrowness.\n\nIt is the light which dissolves all walls between souls, families, and nations.\n\nIt is the unfading blossom of pure friendship in the garden of both young and mature souls.\n\nLove is the door to heaven, the complete song of souls.\n\nLove is the echo of God’s voice trying to reverberate through mute stones, through rain, wind, fragrance, vitalizing light and plumed songbirds; it reverberates through the cries and laughter of babies, through unconditioned mother love, and through dumb and articulate hearts.'
    ),
    Article(
        heading: 'Finding the joy in life',
        body: 'October 1936, “Finding the Joy in Life”\n\nYou want a thing as long as you are not able to get it; when you have secured it, sooner or later you will tire of it, and then you will want something else. Have you ever tried to find that will-o’-the-wisp of “something else” which you seek at the end of all accomplished desires?\n\nNo matter what you seek, you must seek it with joy, in expectation of having joy by possessing it, and you must feel joyous when you actually get it. When seeking different things directly or indirectly, in reality you are seeking joy. When seeking all things, it is really joy that you seek through all these things and the fulfillment of all desires.\n\nThen, why not seek joy directly? Why seek it through the medium of material desires and material things? You do not want those things in life which bring you sorrow. Neither do you want those things which promise a little joy in the beginning but sink you in deep remorse and suffering in the end.\n\nWhy seek joy by supplicating the favor of short-lasting material things? Why depend upon short-lasting material things for short-lasting joys? Material things and fulfillment of material desires are short-lasting; therefore, all joys born of them are short-lasting. Joys born of eating, smelling fragrance, listening to music, beholding beautiful objects, and touching pleasing things are short-lasting. They last only as long as the sensations born of the senses of taste, smell, hearing, sight, and touch last.\n\nYou do not want a tantalizing joy; you do not want a transitory joy which brings sorrow in its trail; you crave joy which will not disappear like the sudden flicker of gossamer wings beneath the flash of lightning. You should look for joy which will shine forever steadily, like the ever luminous radium.\n\nNeither do you want a joy which has too much sameness; you want a joy which changes and dances itself in many ways to enthrall your mind and keep your attention occupied and interested forever. Any joy that comes by fits and starts is tantalizing; any joy that is monotonous is, of course tiresome; any joy that only comes for a little while and brings sorrow at last is undesirable. Any joy that comes for a little while then flits away, sinking you in a state of indifference, and thus deepens that state by contrast, is torturing.\n\nThe joy that rhythmically changes all the time like the different poses of an actor, and yet remains unchangeable in itself, is what all of us are seeking. Such joy can only be found through regular, deep meditation. Such an ever-new, unchangeable fountain of joy alone can quench our joy-thirst.\n\nIf Nature gave to us all at once everything we wanted-wealth, power, and lost friends-we would sooner or later get tired of all of these, but one thing we can never get tired of, and that is Joy itself. By its very nature, ever-new Joy is the only thing that can never tire the mind or make it want to exchange Joy for something else.\n\nIn the pursuit of evil or good, you are always seeking joy. The former promises joy and gives sorrow; the latter may promise sorrow but will surely give lasting joy in the end. Lasting, ever-new Joy is God, and when you have found Him, you have the eternally elusive will-o’-the wisp “something else” which you always seek at the end of all fulfilled desires. Finding this “something else,” you will not seek any farther. Finding this ever-new joy, you will find everything in it that you ever sought.\n\nMaterial objects which give joy remain outside of the mind; they only gain entry into the mind through imagination. Joy, from its very nature, is something born of the mind and lives closest in it. External, material objects can be destroyed, but this joy within can never be destroyed if one knows how to keep it and unless the possessor of joy changes his mind and becomes sorrowful. This joy is ever-new and indestructible.\n\nDo not seek joy through material mediums, or desires born of such contact. Seek the unconditioned, indestructible Pure Joy within yourself, and you will then have found the ever-conscious, ever-new Joy-God. This joy is not an abstract quality of mind, but it is conscious, self-born, and is the conscious, self-expressing quality of Spirit. Seek it and be comforted forever.\n\nWhen you have attained this ever-new joy, you will not have become a cynic, hating everybody. Rather, it is then that you will be in a position fit to enjoy everything rightly. As an immortal child of God, you are supposed to enjoy everything with a lasting attitude of your eternal nature of perpetual joy. People who enjoy material things become materially-minded. It is a disgrace to behave like a discontented mortal when you are made in God’s image, and when you are immortal.\n\nWhen immortals behave like mortals, they experience the changes of joy, sorrow, and indifference in their natures. That is why you must destroy this grafted nature of changeability on your unchangeable nature of joy. And when you have found your own nature of unchangeable joy, you will be able to enjoy everything, either pleasant or disagreeable with your unchangeable, indestructible joy. Your joy will stand unshaken amidst the crash of breaking earthly pleasures.'
    )
  ],

);
