// anandmoyima_de.dart
// German file for Anandamayi Ma
// Deutsche Datei für Anandamayi Ma

import '../articlesquotes_de.dart';

final anandmoyimaSaintDe = Saint(
  'anandmoyima',
  'Anandamayi Ma',
  'assets/images/anandmoyima.jpg',
  [
    'Dieser Körper ist in eure Welt gekommen, um göttliche Liebe in den menschlichen Herzen zu erwecken.',
    'Gott zu lieben ist natürlich; Ihn nicht zu lieben ist künstlich.',
    'Gott ist überall, in jedem und in allem.',
    'Das Ziel des menschlichen Lebens ist, Gott zu finden.',
    'Wenn du das Selbst erkennst, erkennst du, dass es nichts gibt außer dem Selbst.',
    'Liebe, diene, erinnere dich an Gott – das ist die Essenz aller spirituellen Praxis.',
    'Allein Gott ist wirklich, alles andere ist sein Spiel.',
    'Sei wie ein Kind – schlicht, unschuldig und Gott vertrauend.',
    'Übergib alles Gott, und Er wird sich um dich kümmern.',
    'Der Weg der Liebe ist der leichteste Weg zu Gott.',
    'Sieh Gott in jedem und diene allen als Manifestationen des Göttlichen.',
    'Freude ist die Natur des Selbst – suche sie in dir, nicht außerhalb.',
    'Was auch geschieht, ist zum Besten; vertraue dem göttlichen Willen.',
    'Hingabe reinigt das Herz und bereitet es für die göttliche Verwirklichung vor.',
    'Der Name Gottes ist der größte Reiniger.',
    'Meditation ist Gemeinschaft mit dem Göttlichen.',
    'Der Guru ist die Gnade Gottes in menschlicher Gestalt.',
    'Bleibe in dem Bewusstsein gegründet, dass du allein Gott gehörst.',
    'Gott manifestiert sich gemäß dem Verständnis des Verehrers.',
    'Das ganze Universum ist Gottes Tempel.',
    'Liebe Gott ohne jede Erwartung einer Belohnung.',
    'Das Selbst ist jenseits von Glück und Leid, von Freude und Schmerz.',
    'Diese Welt ist eine Schule, in der wir lernen, Gott zu lieben.',
    'Lachen und Tränen sind beide heilig, wenn sie aus der Liebe zu Gott kommen.',
    'Erblicke den Einen in den Vielen und die Vielen im Einen.',
    'Gott ist der Nächste der Nahen und der Liebste der Lieben.',
    'Die Göttliche Mutter wacht über all ihre Kinder.',
    'Jeder Atemzug sollte eine Darbringung an Gott sein.',
    'In Freude und Leid, in Erfolg und Misserfolg: erinnere dich an Gott.',
    'Das Selbst ist ewige Wonne – das ist deine wahre Natur.',
    'Diene anderen, wie du Gott dienen würdest, denn sie sind nicht verschieden.',
    'Das Gebet ist der Flügel, der die Seele zum Göttlichen erhebt.',
    'Gottes Liebe ist bedingungslos und unendlich.',
    'Die verwirklichte Seele sieht Gott überall und in allem.',
    'Begehre nichts außer Gott, und du wirst alles haben.',
    'Das göttliche Spiel währt ewig – sei ein bewusster Teilnehmer.',
    'Liebe ist die Brücke zwischen der Seele und Gott.',
    'In der Stille spricht Gott zum Herzen.',
    'Das reine Herz spiegelt Gott wie ein klarer Spiegel.',
    'Jeder Augenblick ist eine Gelegenheit, sich an Gott zu erinnern.',
    'Gott ist sowohl in dir als auch jenseits von dir.',
    'Das höchste Gebet ist, zu dem zu werden, zu dem du betest.',
    'Wahrheit, Liebe und Schönheit sind Aspekte des einen Göttlichen.',
    'Lebe in der Welt, aber halte dein Herz bei Gott.',
    'Die Liebe der Göttlichen Mutter kennt keine Grenzen.',
    'Im selbstlosen Dienst löst sich das Ego auf, und Gott leuchtet hervor.',
    'Der Zweck des Lebens ist, deine göttliche Natur zu verwirklichen.',
    'Gottes Gnade fließt immer – öffne dein Herz, um sie zu empfangen.',
    'Sieh alles als Gabe Gottes.',
    'Das Selbst ist der Zeuge aller Erfahrungen, steht selbst jedoch jenseits der Erfahrung.',
    'Da das Höchste in allen Formen wohnt, ist jede einzelne Form die Seine. Ob du Ihn bei diesem oder jenem Namen nennst, ob du Ihn verehrst oder nicht – Er allein ist. Entscheidend ist, zu erwachen zu Dem, was immer ist.',
    'Versuche nicht, Gott mit dem Verstand zu begreifen. Der Verstand kann nur unter Namen und Formen wandeln. Gott wird erkannt, wenn der Geist still wird, wenn er aufhört umherzuirren und in seiner eigenen Quelle ruht.',
    'Jeder ist auf seinem eigenen Weg. Manche gehen schnell, manche langsam, manche stolpern und fallen. Doch alle bewegen sich auf dasselbe Ziel zu, ob sie es wissen oder nicht.',
    'So wie Feuer brennt, ob du es weißt oder nicht, so ist die Wahrheit, was sie ist – unabhängig von deinem Glauben oder Unglauben. Man muss sich ihr nur nähern, um ihre Wärme zu spüren.',
    'Der Körper kommt und geht, doch Das, was den Körper kennt, kommt nicht und geht nicht. Suche Das zu erkennen, und du wirst erkennen, was ewig ist.',
    'Welche Arbeit du auch tust, tue sie als Darbringung an das Höchste. Wenn Handeln ohne Verlangen nach seinen Früchten geschieht, reinigt es das Herz und führt natürlicherweise zum Frieden.',
    'Stille ist die höchste Lehre. In der Stille lösen sich alle Zweifel, alle Fragen finden Antwort, denn in der Stille offenbart sich das Selbst.',
    'Warum sich um die Zukunft sorgen? Der, der bis jetzt für dich gesorgt hat, wird immer für dich sorgen. Ergib dich ganz, und du wirst finden, dass es an nichts fehlt.',
    'Der Geist schafft Bindung, und der Geist schafft Befreiung. Richtest du ihn auf das Ewige, wird er dein Freund; richtest du ihn auf das Vergängliche, bindet er dich.',
    'Gottverwirklichung ist nichts Neues, das erlangt werden müsste. Sie ist nur die Entfernung von Unwissenheit, das Enthüllen dessen, was immer schon gegenwärtig war.',
    'Solange der Eindruck besteht: „Ich bin der Handelnde“, wird Unruhe sein. Wenn Handlungen durch dich geschehen statt von dir, kehrt Frieden von selbst ein.',
    'Gebet ist nicht das Erbitten von Dingen; Gebet ist das Öffnen des Herzens. Wenn das Herz sich vollständig öffnet, wird die immerdar gegenwärtige Gegenwart offenbar.',
    'Jeder Atemzug erinnert an das Göttliche. Erinnerst du dich auch nur einmal mit Aufrichtigkeit an Ihn, geht diese Erinnerung nie verloren.',
    'Vergleiche deinen Weg nicht mit dem eines anderen. Was für den einen taugt, mag für den anderen nicht taugen. Das Höchste weiß, was jeder braucht.',
    'Leiden kommt, um dich zu erwecken, nicht um dich zu bestrafen. Wenn seine Lektion gelernt ist, verschwindet das Leiden.',
    'Wenn du die Wahrheit erkennen willst, sei einfach. Einfachheit ist die Pforte, durch die das Unendliche in das Herz eintritt.',
    'Der Guru gibt dir nichts von außen; der Guru offenbart dir, was schon in dir ist.',
    'Wie Wasser die Form des Gefäßes annimmt, so erscheint das Göttliche gemäß der Haltung des Verehrers.',
    'Anhaftung bindet, weil sie auf dem Glauben beruht, dass Glück von Objekten kommt. Wird diese Überzeugung als falsch erkannt, lockert sich die Anhaftung.',
    'Je mehr du versuchst, Gott zu ergreifen, desto ferner scheint Er. Wenn du das Greifen lässt und loslässt, findest du, dass Er niemals abwesend war.',
    'Gott im Gehen, Sitzen, Essen oder Arbeiten zu erinnern, ist wahre spirituelle Praxis. Äußerlich muss nichts aufgegeben werden.',
    'Unruhe entsteht aus Verlangen. Wird ein Verlangen erfüllt, tritt das nächste an seine Stelle. Nur das Verlangen nach Wahrheit bringt dauerhaften Frieden.',
    'Gott ist nicht weit entfernt. Entfernung existiert nur in der Vorstellung.',
    'Wenn das Ego sich verneigt, fließt Gnade.',
    'Deine Natur ist Freude. Wenn Freude abwesend scheint, liegt es daran, dass die Aufmerksamkeit nach außen statt nach innen gerichtet ist.',
    'Glaube ist kein blinder Glaube; er ist Vertrauen, geboren aus innerer Erfahrung.',
    'Was zu dir kommt, kommt durch Seinen Willen. Nimm es mit Dankbarkeit an, und es wird zu einem Mittel des Wachstums.',
    'Die Welt erscheint real, solange der Geist an ihr haftet. Ruht der Geist im Selbst, verliert die Welt ihre Macht zu binden.',
    'Ein Augenblick wahrer Erinnerung ist Jahre mechanischer Praxis wert.',
    'Liebe, die nichts zurückerwartet, ist göttliche Liebe.',
    'Lass dich durch Misserfolg nicht entmutigen. Jeder aufrichtige Aufwand trägt Frucht, ob sichtbar oder unsichtbar.',
    'Der Körper ist ein Tempel; halte ihn rein, doch verwechsel den Tempel nicht mit der Gottheit.',
    'Gott allein ist der Handelnde. Wenn dies erkannt ist, wird das Leben mühelos.',
    'Der Sinn des Lebens ist, zu dem zu erwachen, was du in Wahrheit bist.',
    'Was du suchst, sucht dich.',
    'Wahre Entsagung ist die Entsagung des Ego, nicht der Objekte.',
    'Wo Demut ist, ist Wahrheit.',
    'Versuche nicht, andere zu verändern. Verändere dich selbst, und alles wird sich verändern.',
    'Das Herz, das aufrichtig verlangt, wird gewiss finden.',
    'Frieden entsteht nicht dadurch, Umstände zu kontrollieren, sondern durch das Verstehen ihrer Natur.',
    'In Hingabe liegt Stärke, nicht Schwäche.',
    'Das Göttliche spielt in unzähligen Formen und bleibt doch immer Eines.',
    'Wenn der Geist still wird, leuchtet das Selbst hervor.',
    'Geduld ist die Gefährtin der Weisheit.',
    'Jede Erfahrung hat ihren Platz im Entfalten des Bewusstseins.',
    'Du bist niemals allein; das Höchste ist näher als dein Atem.',
    'Wenn das Verlangen endet, endet die Angst.',
    'Suche nicht nach Glück; sei still, und Glück wird sich offenbaren.',
    'Die Reise endet, wo sie begann.',
    'Gnade ist immer gegenwärtig; es braucht Empfänglichkeit.',
    'Gott in allen Wesen zu sehen ist wahrer Gottesdienst.',
    'Selbst Zweifel kann zur Wahrheit führen, wenn er aufrichtig verfolgt wird.',
    'Das Leben selbst ist der Lehrer.',
    'Das Selbst ist selbstleuchtend; es bedarf keines Beweises.',
    'Eile nicht; das Ewige kennt keine Hast.',
    'Wo Liebe ist, dort ist Gott.',
    'Suche den Suchenden.',
    'Nichts gehört dir, und doch wird dir nichts verwehrt.',
    'Der Geist, der in Gott ruht, ist frei.',
    'Freude wird nicht verursacht; sie wird freigelegt.',
    'Was bestimmt ist, wird geschehen; deine Aufgabe ist, achtsam zu bleiben.',
    'Der Name Gottes reinigt, selbst wenn er ohne Verständnis wiederholt wird.',
    'Am Ende bleibt nur die Wahrheit.',
    'Sei, wie du bist, doch wisse, wer du bist.',
    'Anstrengung ist nötig, bis Mühelosigkeit anbricht.',
    'Sich völlig hinzugeben ist die höchste Darbringung.',
    'Wo Einfachheit ist, ist Klarheit.',
    'Gott offenbart sich entsprechend deiner Fähigkeit zu empfangen.',
    'Anhaftung verblasst, wenn das Verständnis sich vertieft.',
    'Nichts liegt außerhalb des Göttlichen.',
    'Wenn du aufhörst, außen zu suchen, bist du angekommen.',
    'Das Selbst ist niemals gebunden; Bindung ist eingebildet.',
    'Lebe in der Welt, aber gehöre nicht zu ihr.',
    'Wahrheit ist einfach; der Geist macht sie kompliziert.',
    'Jeder Atemzug kann ein Gebet sein.',
    'Widersetze dich dem Leben nicht; verstehe es.',
    'Frieden ist dein natürlicher Zustand.',
    'In der Stille entstehen alle Antworten.',
    'Lass los, und du wirst getragen.',
    'Das Ende ist gewiss; nur das Tempo variiert.',
    'Gnade wirkt lautlos.',
    'Liebe löst Trennung auf.',
    'Sich selbst zu erkennen heißt, Gott zu erkennen.',
    'Auf dem Weg geht nichts verloren.',
    'Wo Aufrichtigkeit ist, ist Fortschritt.',
    'Allein das Selbst ist wirklich.',
    'Äußere Disziplin bereitet den Weg für innere Freiheit.',
    'Gewahrsein selbst ist Befreiung.',
    'Was du wirklich bist, kann nicht verloren gehen.',
    'Furcht verschwindet, wenn die Wahrheit erkannt ist.',
    'Der Eine erscheint als Viele zur Freude des Spiels.',
    'Sei leer, und du wirst erfüllt.',
    'Das Herz weiß, was der Verstand nicht zu fassen vermag.',
    'Wenn das „Ich“ verschwindet, bleibt nur Gott.',
    'Suche Das, was sich nicht ändert.',
    'Alles vergeht; Das, was weiß, vergeht nicht.',
    'Stille ist erfüllt.',
    'Du bist schon zu Hause.',
    'Verwirklichung ist Wiedererkennen.',
    'Alle Wege enden in derselben Wahrheit.',
  ],
  [
    Article(
      heading: 'Die Lehre der Göttlichen Mutter',
      body:
          'Anandamayi Ma, bekannt als die von Seligkeit durchdrungene Mutter, war eine lebendige Verkörperung göttlicher Liebe und Freude. Schon ihre bloße Gegenwart war eine Lehre und strahlte die bedingungslose Liebe der Göttlichen Mutter aus.\n\nSie lehrte, dass das höchste Ziel des menschlichen Lebens die Gottverwirklichung ist. Das ist nichts uns Fremdes, sondern unsere wahre Natur. Im Spiel der Maya haben wir lediglich vergessen, wer wir sind. Durch spirituelle Praxis, Hingabe und die Gnade Gottes können wir unsere wahre göttliche Natur wiedererinnern.\n\nMa betonte, dass Gott auf jedem Weg erreicht werden kann – sei es durch Hingabe (Bhakti), Erkenntnis (Jnana) oder Handeln (Karma). Entscheidend sind Aufrichtigkeit und einpünktige Ausrichtung. Sie pflegte zu sagen, dass jeder Weg, der mit Liebe und Vertrauen gegangen wird, zum selben Ziel führt.\n\nIhre Lehre war einfach und zugleich tiefgründig: Liebe Gott, diene den anderen und erinnere dich in allen Umständen an das Göttliche. Sie zeigte, dass Spiritualität nicht von unserem Alltag getrennt ist, sondern jeden Augenblick unseres Daseins durchdringen sollte.',
    ),
    Article(
      heading: 'Der Weg der göttlichen Liebe',
      body:
          'Anandamayi Ma verkörperte den Weg reiner Hingabe. Sie lehrte, dass Liebe der natürlichste Weg ist, sich dem Göttlichen zu nähern, denn Gott ist Liebe selbst. Wenn wir Gott von ganzem Herzen, mit Geist und Seele lieben, erkennen wir nach und nach, dass es nichts gibt außer Gott.\n\nDer Weg der Liebe beginnt oft mit der Verehrung einer gewählten Form Gottes, führt aber schließlich zur Erkenntnis, dass Gott formlos ist und doch in allen Formen erscheint. Ma sagte, dass wir anfangs Gott als von uns verschieden sehen, doch je tiefer die Liebe wird, desto mehr erkennen wir, dass wir und Gott eins sind.\n\nSie betonte die Bedeutung der Hingabe (Śaraṇāgati). Vollständige Hingabe an den göttlichen Willen bringt Frieden und befreit von der Last des Ego. Wenn wir uns wahrhaft hingeben, erkennen wir, dass alles in Gottes Händen liegt und wir lediglich Werkzeuge des Göttlichen sind.\n\nDas Leben Mas war selbst ein Zeugnis dieser Hingabe. Sie sagte oft: „Dieser Körper tut, wozu er vom Göttlichen bewegt wird. Es gibt hier keinen eigenen Willen.“ Dieses vollständige Auslöschen des Ego ist das Ziel des Weges der göttlichen Liebe.',
    ),
    Article(
      heading: 'Gott überall sehen',
      body:
          'Einer der zentralen Lehrinhalte Anandamayi Mas war die Übung, Gott in allen Wesen und Situationen zu sehen. Sie sagte, dass, wenn der Blick des Verehrers durch spirituelle Praxis gereinigt wird, er die göttliche Gegenwart überall zu sehen beginnt.\n\nDiese Schau verwandelt die gesamte Beziehung zur Welt. Anstatt getrennte Individuen zu sehen, erblickt man das eine Göttliche, das verschiedene Rollen spielt. Dienst am Nächsten wird zum Gottesdienst. Jede Begegnung wird zu einer Gelegenheit für spirituelles Wachstum.\n\nMa lehrte, dass diese Sicht allmählich durch Übung kultiviert werden muss. Zu Beginn müssen wir uns vielleicht anstrengen, uns an Gott zu erinnern, doch schließlich wird es natürlich und mühelos. Der fortgeschrittene Verehrer lebt in ständiger Gemeinschaft mit dem Göttlichen.\n\nOft erinnerte sie ihre Verehrer daran, dass Gott nicht fern ist, sondern das eigentliche Leben in allen Wesen. Das Göttliche ist unserem eigenen Atem näher, unseren eigenen Gedanken näher. Die Erkenntnis dieser Gottesnähe ist die Frucht spiritueller Praxis und die Quelle ewiger Wonne.',
    ),
  ],
);
