// nisargadatta_de.dart
// German file for Nisargadatta Maharaj
// Deutsche Datei für Nisargadatta Maharaj

import '../articlesquotes_de.dart';

final nisargadattaSaintDe = Saint(
  'nisargadatta',
  'Nisargadatta Maharaj',
  'assets/images/nisargadatta.jpg',
  [
    'Du bist nicht, wofür du dich hältst. Finde heraus, was du bist.',
    'Das Wirkliche stirbt nicht, das Unwirkliche hat nie gelebt.',
    'Weisheit sagt mir: Ich bin nichts. Liebe sagt mir: Ich bin alles. Zwischen beiden fließt mein Leben.',
    'Du bist die höchste Wirklichkeit. Sei nicht kleingeistig.',
    'Um zu erkennen, was du bist, musst du zuerst untersuchen und erkennen, was du nicht bist.',
    'Das Bewusstsein in dir und das Bewusstsein in mir, scheinbar zwei, sind eins; suche Einheit, und das ist Liebe.',
    'Alles, was du brauchst, ist die Gewohnheit abzulegen, dich zu definieren.',
    'Sobald du erkennst, dass der Weg das Ziel ist und dass du immer auf dem Weg bist – nicht um ein Ziel zu erreichen, sondern um seine Schönheit und Weisheit zu genießen –, hört das Leben auf, eine Aufgabe zu sein, und wird natürlich und einfach.',
    'Du bist nicht der Körper. Du bist nicht einmal der Geist. Du bist das Gewahrsein, in dem beide erscheinen.',
    'In dem Moment, in dem du dein wahres Sein erkennst, fürchtest du nichts mehr.',
    'Hör auf, dir vorzustellen, dies oder das zu sein oder zu tun, und die Erkenntnis, dass du Quelle und Herz von allem bist, wird in dir aufgehen.',
    'Nichts, was du wahrnimmst, ist dein Eigen. Nichts, was du wahrnimmst, hat etwas mit dir zu tun.',
    'Verwirf alle traditionellen Maßstäbe. Überlass sie den Anhängern der Tradition.',
    'Dein wahres Zuhause ist im Nichts, in der Leere allen Inhalts.',
    'Wenn ich nach innen schaue und sehe, dass ich nichts bin, ist das Weisheit. Wenn ich nach außen schaue und sehe, dass ich alles bin, ist das Liebe.',
    'Der Geist erschafft den Abgrund, das Herz überschreitet ihn.',
    'Was immer du denkst, dass du es seist – du bist es nicht.',
    'Du hältst dich für eine Person, doch du bist niemals als Person geboren worden.',
    'In Wirklichkeit bist du kein Ding und nicht getrennt von anderen Dingen.',
    'Die Suche nach der Wirklichkeit ist das gefährlichste aller Unternehmen, denn sie zerstört die Welt, in der du zu leben glaubst.',
    'Alle Trennung, jede Art von Entfremdung und Absonderung ist falsch.',
    'Du bist die höchste Möglichkeit, deren Manifestation und Ausdruck das allumfassende Bewusstsein ist.',
    'Das Persönliche braucht Schutz, das Reale braucht keinen Schutz.',
    'Nichts kann dich beunruhigen außer deiner eigenen Vorstellungskraft.',
    'Sobald du mit absoluter Gewissheit weißt, dass nichts dich beunruhigen kann außer deiner eigenen Vorstellung, beginnst du, deinen Wünschen und Ängsten keine Beachtung mehr zu schenken.',
    'Du bist nicht in der Welt; die Welt ist in dir.',
    'Das Gefühl „Ich bin“ ist dein Eigenes. Du kannst dich nicht davon trennen, aber du kannst es allem zuschreiben, etwa: „Ich bin jung“, „Ich bin reich“ usw.',
    'Zwischen den Ufern von Schmerz und Vergnügen fließt der Fluss des Lebens. Erst wenn der Geist sich weigert, mit dem Leben zu fließen und an den Ufern hängen bleibt, entsteht ein Problem.',
    'Freiheit ist Befreiung vom Bekannten.',
    'Deine Schwäche rührt von deiner Überzeugung her, du seist in die Welt geboren worden.',
    'Verlass dich nicht auf den Geist zur Befreiung. Der Geist hat dich in die Bindung gebracht.',
    'Der wahre Lehrer ist das Leben selbst.',
    'Du musst es nicht erreichen, denn du bist es.',
    'Liebe sagt: „Ich bin alles.“ Weisheit sagt: „Ich bin nichts.“ Dazwischen fließt mein Leben.',
    'Die Dreiheit – Geist, Selbst und Spirit – wird, wenn man sie erforscht, zur Einheit.',
    'Sei einfach. Lass deine wahre Natur hervortreten. Störe deinen Geist nicht durch Suchen.',
    'Dein eigenes Selbst ist dein letztendlicher Lehrer. Der äußere Lehrer ist nur ein Wegweiser.',
    'In deiner Welt muss alles einen Anfang und ein Ende haben. Wenn es das nicht hat, nennst du es ewig.',
    'Der Verwirklichte sieht die Welt, wie sie ist: im Wesen eins, im Ausdruck vielfältig.',
    'Lerne, ohne Einbildung zu schauen, ohne Verzerrung zu hören.',
    'Es ist der Geist, der dir sagt, dass der Geist da ist. Lass dich nicht täuschen.',
    'Wahrheit ist keine Belohnung für gutes Verhalten und kein Preis für bestandene Prüfungen.',
    'Das, was dich glauben lässt, ein Mensch zu sein, ist nicht menschlich.',
    'Du hast so viel Energie darauf verwendet, dir ein Gefängnis zu bauen. Verwende jetzt ebenso viel darauf, es abzureißen.',
    'Um zu verstehen, dass du nicht die Person bist, beobachte die Person. Sieh die Person als ein Objekt im Bewusstsein.',
    'Was ist die Schwierigkeit, die Körper-Geist-Identität fallen zu lassen? Du bist schließlich nicht Körper-Geist.',
    'Du fürchtest den Tod, weil du dich selbst nicht kennst. Dein wahres Selbst ist todlos.',
    'Was dich daran hindert, dich als alles und über alles hinaus zu erkennen, ist der auf Erinnerung gegründete Geist.',
    'Der Geist existiert in der Zeit; wir sind jenseits der Zeit.',
    'Du bist Liebe selbst – wenn du keine Angst hast.',
    'Du bist nicht, wofür du dich hältst. Du bist nicht der Körper, nicht der Geist und nicht das Gefühl, eine Person zu sein. Du bist das zeitlose Gewahrsein, in dem all dies erscheint und verschwindet.',
    'In dem Moment, in dem du dich als Bewusstsein und nicht als Person erkennst, endet jedes Leiden. Was bleibt, ist Frieden – keine Erfahrung, sondern dein natürlicher Zustand.',
    'Bevor der Körper war, bevor die Welt erschien, warst du. Verweile bei diesem Gefühl des Seins, das allen Begriffen vorausgeht, und lass alles andere los.',
    'Das „Ich bin“ ist die erste Pforte. Verweile unerschütterlich bei ihm. Wenn sogar das „Ich bin“ sich auflöst, bleibt das Absolute.',
    'Du bist nicht in der Welt; die Welt ist in dir. Du trägst das gesamte Universum in deinem Bewusstsein.',
    'Um zu wissen, was du bist, untersuche zuerst, was du nicht bist. Alles, was gesehen, wahrgenommen oder erlebt werden kann, bist nicht du.',
    'Das wahre Selbst ist nichts, was erlangt werden müsste. Es ist das, was du bist, wenn alle falschen Vorstellungen über dich fallen gelassen sind.',
    'Du bildest dir ein, begrenzt zu sein, und leidest dann unter dieser Begrenzung. In Wahrheit gibt es keine Grenze dessen, was du bist.',
    'Wenn du aufhörst, dich mit Körper und Geist zu identifizieren, entdeckst du, dass du niemals gebunden, niemals in Not, niemals unvollständig warst.',
    'Gewahrsein ist nicht persönlich. Die Person erscheint im Gewahrsein, doch das Gewahrsein gehört nicht der Person.',
    'Bewusstsein selbst ist ein vorübergehender Zustand. Es erscheint und verschwindet. Das, was das Bewusstsein kennt, steht darüber.',
    'Das Absolute ist sich seiner nicht bewusst. Bewusstsein ist ein Phänomen, das im Absoluten aufsteigt – wie eine Welle auf dem Ozean.',
    'Du hältst Bewusstsein für dich selbst, doch sogar Bewusstsein wird beobachtet. Finde das, was des Bewusstseins gewahr ist.',
    'Körper und Welt entstehen gemeinsam mit dem Bewusstsein. Wo kein Bewusstsein ist, ist auch keine Welt.',
    'Vor dem Bewusstsein gibt es keine Erfahrung, keine Zeit, keinen Raum – und doch bist du. Das ist deine wahre Natur.',
    'Bewusstsein hängt vom Körper ab, das Absolute aber von nichts. Erkenne den Unterschied.',
    'Wenn das Bewusstsein beim Tod sich auflöst, stirbt, was du wirklich bist, nicht – denn es wurde nie geboren.',
    'Über das Absolute kann nicht gesprochen werden. Was immer gesagt werden kann, betrifft nur das Bewusstsein.',
    'Verweile an der Quelle des Bewusstseins, und du wirst es transzendieren.',
    'Du hältst die Bewegung des Bewusstseins für die Wirklichkeit. Wirklichkeit ist das, was unbewegt ist.',
    'Deine einzige Sadhana ist, am Gefühl „Ich bin“ festzuhalten und alles andere als Nicht-Selbst zurückzuweisen.',
    'Versuche nicht, das, was erscheint, zu verändern. Erkenne nur, was du bist, und alles ändert sich von selbst.',
    'Anstrengung ist nötig, bis Mühelosigkeit entdeckt ist. Dann fällt sogar Anstrengung weg.',
    'Selbsterforschung ist keine mentale Übung. Sie ist die beständige Weigerung, sich mit irgendetwas zu identifizieren, das erscheint.',
    'Beobachte deine Gedanken, wie du Wolken am Himmel beobachten würdest. Beanspruche sie nicht als deine.',
    'Der Geist wird dir nicht helfen, den Geist zu transzendieren. Du musst über ihn hinausgehen, indem du ihn verstehst.',
    'Wenn du den Geist beobachtest, bist du bereits jenseits von ihm.',
    'Frage nicht, wie lange es dauern wird. Bleibe nur ernsthaft und ehrlich in deiner Erforschung.',
    'Du brauchst den Geist nicht zu reinigen. Höre nur auf, dich mit ihm zu identifizieren.',
    'Stille ist nicht die Abwesenheit von Klang; sie ist die Abwesenheit von Identifikation.',
    'Die Person ist eine Ansammlung von Erinnerungen, Gewohnheiten und Konditionierungen. Du bist nicht diese Ansammlung.',
    'Das Ego ist nur eine Idee – ein falsches Zentrum, das vom Bewusstsein angenommen wird.',
    'Wenn du sagst: „Ich leide“, erforsche, wer dieses „Ich“ ist. Du wirst es nicht finden.',
    'Die Vorstellung „Ich bin der Handelnde“ ist die Bindung. Wenn sie fällt, ist Freiheit.',
    'Persönlichkeit ist nicht Wirklichkeit; sie ist eine Maske, die das Bewusstsein trägt.',
    'Solange du dich für eine Person hältst, wirst du in Angst leben.',
    'Das Gefühl von Individualität kommt mit dem Körper und endet mit ihm.',
    'Du klammerst dich an die Person, weil du das Nichts fürchtest; doch dieses Nichts ist Frieden.',
    'Wenn die Person sich auflöst, bleibt nicht Leere, sondern Fülle.',
    'Das Ego will Kontinuität; die Wirklichkeit kennt keine.',
    'Alles Leiden entsteht aus Identifikation. Du leidest, weil du das Vergängliche für dich selbst hältst.',
    'Begehren entsteht aus dem Gefühl der Unvollständigkeit, das selbst falsch ist.',
    'Angst existiert nur für die Person. Das Selbst kennt keine Angst.',
    'Wenn du weißt, dass du nicht der Körper bist, verliert der Tod seinen Schrecken.',
    'Schmerz ist körperlich; Leiden ist mental. Durch Verstehen kannst du das Leiden transzendieren.',
    'Was du bekämpfst, bleibt bestehen. Was du verstehst, löst sich auf.',
    'Begehren ist in die Zukunft projizierte Erinnerung.',
    'Freiheit ist nicht die Erfüllung von Wünschen, sondern Freiheit von Wünschen.',
    'Leiden ist ein Signal, das dir sagt, dass du dich in dir selbst täuschst.',
    'Wenn die falsche Identität endet, endet das Leiden mit ihr.',
    'Die Welt ist nicht unwirklich, aber sie ist nicht, wofür du sie hältst. Sie ist eine Projektion des Bewusstseins.',
    'Die Welt erscheint real, weil du glaubst, ein Teil von ihr zu sein.',
    'Wenn das Bewusstsein still ist, ist die Welt still.',
    'Das Universum existiert nur, solange es wahrgenommen wird.',
    'Du verleihst der Welt Realität, indem du sie persönlich nimmst.',
    'Die Welt hat keine eigenständige Existenz außerhalb des Bewusstseins.',
    'Die Wirklichkeit ist einfach; Illusion ist kompliziert.',
    'Die Welt ist weder gut noch schlecht. Sie spiegelt nur dein Verständnis.',
    'Was du „wirkliches Leben“ nennst, ist ein Strom von Wahrnehmungen.',
    'Die Welt ist eine Schau, doch das Bewusstsein nimmt sie ernst.',
    'Der Guru gibt dir nichts Neues; er entfernt, was falsch ist.',
    'Gnade ist kein Ereignis; sie ist deine eigene Natur.',
    'Wenn du bereit bist, findet dich die Lehre.',
    'Der Guru weist nur hin; sehen musst du selbst.',
    'Vertraue der Lehre, bis du sie für dich selbst verifiziert hast.',
    'Glaube an den Guru ist Glaube an dein eigenes Selbst.',
    'Worte sind nur Hinweise. Klammere dich nicht an sie.',
    'Die höchste Lehre ist die Stille.',
    'Ein wahrer Lehrer tröstet das Ego nicht; er zerstört es.',
    'Wenn das Verstehen vollständig ist, verschwindet der Guru.',
    'Befreiung ist keine Errungenschaft in der Zeit; sie ist das Erkennen des Zeitlosen.',
    'Du bist jetzt frei, doch du bildest dir ein, gebunden zu sein.',
    'Freiheit ist nicht, zu tun, was dir gefällt, sondern nicht von Verlangen getrieben zu werden.',
    'Wenn es kein „Ich“ gibt, gibt es keine Bindung.',
    'Befreiung ist das Ende der Suche.',
    'Dem Befreiten geschieht nichts, denn da ist niemand, dem etwas geschehen könnte.',
    'Der befreite Zustand ist gewöhnlich, natürlich und unauffällig.',
    'Du wirst nicht frei; du entdeckst, dass du nie gebunden warst.',
    'Der höchste Zustand ist überhaupt kein Zustand.',
    'Wenn Unwissenheit endet, geschieht nichts Besonderes – die Wahrheit zeigt sich einfach.',
    'Du bist kein Fragment der Wirklichkeit; du bist die Wirklichkeit selbst.',
    'Was erscheint, muss verschwinden. Was nicht erscheint, kann nicht verschwinden.',
    'Das Absolute hat keine Eigenschaften, und doch entspringen ihm alle Eigenschaften.',
    'Du kannst das Absolute nicht als Objekt erkennen, denn du bist das.',
    'Das Selbst ist keine Erfahrung; es ist das, was erfährt.',
    'Wenn alle Fragen verstummen, bleibt die Wahrheit.',
    'Dir muss nichts hinzugefügt werden; nur falsche Vorstellungen müssen entfernt werden.',
    'Was du wirklich bist, liegt jenseits von Bejahung und Verneinung.',
    'Sei still und beobachte – das ist alles.',
    'Die Wahrheit ist einfach, doch der Geist sträubt sich gegen Einfachheit.',
    'Verweile beim Gefühl des Seins, bis selbst das sich auflöst.',
    'Versuche nicht, die Wahrheit zu ergreifen; lass die Unwahrheit abfallen.',
    'Verstehen ist der Schlüssel – nicht Erfahrung.',
    'Was wirklich ist, ist immer gegenwärtig.',
    'Du bist vor der Zeit.',
    'An der Wirklichkeit ist nichts falsch; nur deine Vorstellungen sind falsch.',
    'Wenn der Suchende verschwindet, wird das Gesuchte offenbar.',
    'Sei leer von Konzepten.',
    'Du bist der Zeuge, nicht das Bezeugte.',
    'Du bist – und das genügt.'
  ],
  [
    Article(
      heading: 'Wer bin ich? – Die grundlegende Frage',
      body:
          'Die Lehre von Nisargadatta Maharaj kreiste um die grundlegende Frage „Wer bin ich?“. Unermüdlich wies er seine Schüler darauf hin, ihre wahre Natur jenseits aller Konzepte und Identifikationen zu erforschen.\n\n„Du bist nicht, wofür du dich hältst. Finde heraus, was du bist.“ Diese Erforschung ist keine intellektuelle Übung, sondern eine direkte Hinwendung zur Quelle des „Ich“-Gefühls.\n\nMaharaj lehrte, dass wir uns gewöhnlich mit Körper, Geist, Gedanken, Gefühlen und den vielen Rollen identifizieren, die wir im Leben spielen. Doch all dies sind Objekte, die im Bewusstsein erscheinen. Wir sind das Bewusstsein, in dem sie erscheinen – nicht die Objekte selbst.\n\nDer Prozess der Selbsterforschung besteht darin, alles zu verneinen, was du nicht bist – „Ich bin nicht der Körper, ich bin nicht der Geist, ich bin nicht die Gedanken“ –, bis du bei dem ankommst, was bleibt. Was bleibt, ist reines Gewahrsein, reines Sein – deine wahre Natur.\n\n„Um zu wissen, was du bist, musst du zuerst untersuchen und erkennen, was du nicht bist“, betonte Maharaj. Dieser Prozess des Ausschließens führt zur Erkenntnis deiner grundlegenden Natur als reines Bewusstsein – jenseits aller Attribute und Begrenzungen.\n\nDie Frage „Wer bin ich?“ muss mit tiefer Ernsthaftigkeit und Aufrichtigkeit verfolgt werden. Intellektuelles Verständnis genügt nicht; sie muss zu einer lebendigen Erforschung werden, die jeden Moment deines Daseins durchdringt, bis das falsche Gefühl, eine separate Person zu sein, vollständig erlischt.',
    ),
    Article(
      heading: 'Die Natur des Bewusstseins',
      body:
          'Nisargadatta Maharaj erläuterte das Bewusstsein auf eine zugleich tiefgründige und zugängliche Weise. Er unterschied zwischen dem persönlichen Bewusstsein (dem Gefühl „Ich bin“) und der absoluten Wirklichkeit, die jenseits aller Erfahrung liegt.\n\nDas „Ich bin“ ist die erste Regung im Bewusstsein, der Ur-Gedanke, aus dem alle anderen Erfahrungen hervorgehen. Maharaj lehrte, dass wir an diesem reinen „Ich bin“ festhalten sollen, ohne Zusätze wie „Ich bin dies“ oder „Ich bin das“.\n\n„Das Bewusstsein in dir und das Bewusstsein in mir, scheinbar zwei, sind eins“, sagte er. Dieses Verstehen löst die Illusion der Trennung auf und enthüllt die Einheit, die der Vielfalt zugrunde liegt.\n\nMaharaj erklärte, dass Bewusstsein nicht vom Gehirn oder Körper erzeugt wird. Vielmehr erscheinen Körper und Gehirn im Bewusstsein. Bewusstsein ist nicht persönlich; es ist universal, und was wir für individuelles Bewusstsein halten, ist lediglich eine Spiegelung dieses universalen Bewusstseins.\n\nDie absolute Wirklichkeit liegt sogar jenseits des Bewusstseins – sie ist das, in dem Bewusstsein selbst erscheint und verschwindet. Das ist deine wahre Natur, vor Bewusstsein, vor Existenz und Nichtexistenz.\n\n„Du bist die höchste Wirklichkeit“, erklärte Maharaj. „Sei nicht kleingeistig.“ Diese höchste Wirklichkeit kann nicht als Objekt erkannt werden, weil du sie bist. Sie kann nur erkannt werden, wenn alles, wofür du dich hältst, sich auflöst.',
    ),
    Article(
      heading: 'Die Illusion der Person',
      body:
          'Eine der radikalsten Lehren Nisargadattas betrifft die illusionäre Natur der Person. Er sagte: „Du hältst dich für eine Person, doch du bist niemals als Person geboren worden.“\n\nDie Person ist lediglich eine Ansammlung von Erinnerungen, Gedanken und Identifikationen, die eine scheinbare Kontinuität erzeugen. Doch genau betrachtet gibt es keine feste Entität, die „Person“ genannt werden könnte. Es ist wie bei einem Film – einzelne Bilder erzeugen die Illusion von Bewegung und Handlung.\n\nMaharaj lehrte, dass die Person eine mentale Konstruktion ist, ein Bündel von Konzepten ohne unabhängige Wirklichkeit. „Was immer du denkst, dass du es seist – du bist es nicht“, betonte er. Die Person erscheint in dir (im Bewusstsein), aber du bist nicht die Person.\n\nDieses Verständnis befreit, denn es bedeutet, dass alle Probleme, Begrenzungen und das Leiden der Person ebenfalls illusionär sind. Wenn du erkennst, dass du nicht die Person bist, bist du frei vom Schicksal, Karma und den Konditionierungen der Person.\n\n„Nichts, was du wahrnimmst, ist dein Eigen. Nichts, was du wahrnimmst, hat etwas mit dir zu tun“, sagte Maharaj. Das schließt Körper, Geist, Gedanken und Emotionen ein, die wir gewöhnlich für „unser“ halten.\n\nDie Erkenntnis, dass du nicht die Person bist, ist keine philosophische Position, sondern eine direkte Einsicht, die durch ernsthafte Selbsterforschung aufleuchtet. Wird diese Einsicht stabil und unerschütterlich, verweilst du als das, was du wirklich bist – reines Gewahrsein, reines Sein, jenseits aller persönlichen Begrenzungen.',
    ),
    Article(
      heading: 'Liebe und Weisheit – die zwei Flügel der Wahrheit',
      body:
          'Nisargadatta Maharaj brachte das Paradox der Verwirklichung in seinem berühmten Ausspruch wunderschön zum Ausdruck: „Weisheit sagt mir: Ich bin nichts. Liebe sagt mir: Ich bin alles. Zwischen beiden fließt mein Leben.“\n\nWeisheit ist die Erkenntnis deiner wahren Natur als reines Gewahrsein, das keine Attribute, keine Form, keine Eigenschaften hat – im Grunde nichts, was der Geist ergreifen könnte. Aus dieser Perspektive bist du die Leere, der Raum, in dem alle Erfahrung erscheint.\n\nLiebe hingegen ist die Erkenntnis, dass eben dieses Gewahrsein das Wesen von allem ist, was erscheint. Du bist nicht von irgendetwas getrennt; du bist der Eine, der als die Vielen erscheint. Das ist die Liebe, die die gesamte Existenz als dein eigenes Selbst umfasst.\n\nDies sind keine Widersprüche, sondern zwei Aspekte derselben Verwirklichung. Das Absolute ist zugleich Leere und Fülle, Nichts und Alles, transzendent und immanent.\n\n„Wenn ich nach innen schaue und sehe, dass ich nichts bin, ist das Weisheit. Wenn ich nach außen schaue und sehe, dass ich alles bin, ist das Liebe“, erklärte Maharaj. Diese doppelte Erkenntnis ist das Kennzeichen vollständigen Verstehens.\n\nAus dieser Erkenntnis zu leben bedeutet, in dem Frieden gegründet zu sein, der aus dem Wissen erwächst, nichts (kein Ding) zu sein, und zugleich alles zu lieben, was erscheint, als deine eigene Manifestation. Dies ist der natürliche Zustand des Verwirklichten – leer an Selbst, doch voll Liebe für alles.',
    ),
    Article(
      heading: 'Jenseits von Geburt und Tod',
      body:
          'Nisargadatta Maharajs Lehren über Tod und Unsterblichkeit sind besonders kraftvoll und tröstlich. „Das Wirkliche stirbt nicht, das Unwirkliche hat nie gelebt“, sagte er mit völliger Gewissheit.\n\nAus seiner Sicht sind das, was wir Geburt und Tod nennen, lediglich Erscheinungen im Bewusstsein – wie Szenen in einem Traum. Der Körper wird geboren und stirbt, doch du – das Gewahrsein, in dem der Körper erscheint – wirst nie geboren und kannst daher nicht sterben.\n\n„Du fürchtest den Tod, weil du dich selbst nicht kennst“, bemerkte Maharaj. „Dein wahres Selbst ist todlos.“ Diese Angst vor dem Tod entspringt der Identifikation mit dem sterblichen Körper statt der Erkenntnis deines unsterblichen Bewusstseins.\n\nMaharaj lehrte, dass wir in Wahrheit weder Geburt noch Tod je erfahren haben. Wir haben Erinnerungen an Vergangenes und Vorstellungen über Zukünftiges, doch unsere tatsächliche Erfahrung ist immer nur das gegenwärtige Gewahrsein. Dieses Gewahrsein war immer und wird immer sein.\n\nDas Erkennen deiner todlosen Natur ist kein Glaube und kein Trost, sondern eine direkte Einsicht. Wenn du dich wahrhaft als reines Gewahrsein erkennst, verschwindet die Angst vor dem Tod, weil du einsiehst, dass es nichts gibt, was sterben könnte.\n\n„Deine Schwäche rührt von deiner Überzeugung her, du seist in die Welt geboren worden“, sagte er. In Wirklichkeit erscheint die Welt in dir; du erscheinst nicht in der Welt. Diese grundlegende Verschiebung des Verständnisses verwandelt deine gesamte Beziehung zu Leben und Tod.\n\nDie praktische Folge dieser Lehre ist große Freiheit und Furchtlosigkeit. Wenn du dich als die todlose Wirklichkeit erkennst, kannst du vollständig leben und umfassend lieben – ohne dass der Schatten der Sterblichkeit deine natürliche Freude und deinen Frieden verdunkelt.',
    ),
  ],
);
