// ramana_de.dart
// German file for Maharishi Ramana
// Deutsche Datei für Maharishi Ramana
import '../articlesquotes_de.dart';

final ramanaSaintDe = Saint(
  'raman',
  'Maharishi Ramana',
  'assets/images/raman.jpg',
  [
    'Deine eigene Selbstverwirklichung ist der größte Dienst, den du der Welt erweisen kannst.',
    'Es gibt weder Schöpfung noch Zerstörung, weder Schicksal noch freien Willen, weder Weg noch Errungenschaft. Das ist die endgültige Wahrheit.',
    'Glückseligkeit ist deine Natur. Es ist nicht falsch, sie zu begehren. Falsch ist nur, sie außen zu suchen, während sie innen ist.',
    'Die Frage „Wer bin ich?“ vernichtet alle anderen Fragen.',
    'Die Welt verändern zu wollen, ohne das wahre Selbst zu entdecken, ist, als wolltest du die ganze Erde mit Leder bedecken, um die Steine und Dornen nicht zu spüren.',
    'Stille ist ebenfalls Gespräch.',
    'Der Geist ist nichts als Gedanken. Hör auf zu denken – zeig mir dann den Geist.',
    'Der einzige sinnvolle Zweck dieser Geburt ist, sich nach innen zu wenden und das Selbst zu verwirklichen.',
    'Niemand gelingt ohne Mühe. Wer gelingt, verdankt es der Beharrlichkeit.',
    'Lass kommen, was kommt. Lass gehen, was geht. Finde heraus, was bleibt.',
    'Die Frage „Wer bin ich?“ ist keine bloß geistige Übung. Sie ist die höchste Form spiritueller Praxis.',
    'Der „Ich“-Gedanke ist die Wurzel aller Gedanken. Ihn festzuhalten und zu seiner Quelle zurückzuverfolgen, ist der einzige Weg, alle Gedanken zu zerstören.',
    'Das Selbst ist immer gegenwärtig. Du musst es nicht suchen, nur aufhören, das Nicht-Selbst zu suchen.',
    'Die letzte Wahrheit ist: Das „Ich“ ist kein Gedanke; es ist Bewusstsein selbst.',
    'Alles, was zur Selbstverwirklichung erforderlich ist, ist still zu sein.',
    'Du bist das Selbst. Sei das.',
    '„Wer bin ich?“ zu fragen, heißt, den Geist nach innen zu wenden und tief zur Quelle zu tauchen.',
    'Wie eine Schlange nur im Seil gesehen wird, so erscheint das Ego nur im Selbst.',
    'Das Ego ist der Geist. Der Geist ist die Quelle aller Wünsche.',
    'Das Ego ist kein reales Wesen. Es ist eine Gedankenform, ein Schatten, der verschwindet, wenn das Licht des Selbst leuchtet.',
    'Der Geist ist ein Phantom – nichts als ein Bündel von Gedanken.',
    'Wenn der Geist zur Ruhe kommt, wird das Selbst verwirklicht. Der Geist ist das Hindernis.',
    'Verwirklichung ist keine neue Errungenschaft, sondern das Wiedererkennen deiner ewigen Natur.',
    'Körper und Geist bist du nicht. Du bist der Zeuge von beiden.',
    'Wenn der „Ich“-Gedanke verschwindet, verschwinden alle anderen Gedanken mit ihm.',
    'Stille ist die kraftvollste Form spiritueller Unterweisung.',
    'Die beste Praxis ist, in Stille zu verweilen.',
    'Verwirklichung wird nicht erlangt, sondern enthüllt sich in Abwesenheit von Gedanken.',
    'Die Stille des Herzens ist beredter als jede Rede.',
    'Wahres Wissen ist nicht im Intellekt; es ist im Herzen und offenbart sich in der Stille.',
    'Der höchste Zustand ist Stille, in der es kein „Ich“ und kein „Du“ gibt.',
    'Das Selbst wird in vollkommenster Ruhe erkannt.',
    'Still zu sein ist die höchste Form des Gebets.',
    'Wahrer Friede ist Abwesenheit aller Gedanken.',
    'Meditation bedeutet nicht, über Gott zu denken, sondern im Zustand der Stille zu sein – das ist Gott.',
    'Der Geist ist ein ruheloser Affe; nur Stille zähmt ihn.',
    'Stille ist der ewige Zustand des Selbst.',
    'Je mehr du in Stille bist, desto mehr verstehst du die Wahrheit.',
    'Stille ist nicht Abwesenheit von Klang, sondern Gegenwart von Stillheit.',
    'Das einzige wahre Gebet ist: still zu sein und zu wissen: „Ich bin.“',
    'Gott ist kein äußeres Wesen; Gott ist das Selbst.',
    'Die Welt ist Illusion. Allein das Selbst ist wirklich.',
    'Alles, was du siehst, ist Gott. Alles, was du hörst, ist Gott.',
    'Die Welt ist nichts als eine Projektion des Geistes.',
    'Es gibt keine Wirklichkeit außerhalb des Selbst.',
    'Die Welt ist nicht von dir getrennt.',
    'Das Universum ist in dir, nicht du im Universum.',
    'Die einzige Wirklichkeit ist das Selbst. Welt, Ego und Gott sind im Selbst.',
    'Die Welt ist ein Traum. Der Träumer ist das Selbst.',
    'Gott ist die Quelle, der Zeuge und die Wirklichkeit von allem.',
    'Es gibt nur eine Wirklichkeit: Bewusstsein.',
    'Gott ist Liebe; Liebe ist das Licht des Selbst.',
    'Die Welt ist eine Idee; die einzige Wirklichkeit ist das Selbst.',
    'Die Welt ist eine Manifestation Gottes, doch Gott ist durch die Welt nicht begrenzt.',
    'Das Selbst ist der Substrat aller Existenz.',
    'Nicht Handeln bindet – die Vorstellung, der Handelnde zu sein, bindet.',
    'Wahres Handeln ist mühelos und spontan; es fließt aus dem Zustand des Seins.',
    'Sorge dich nicht um die Früchte der Handlung; das Selbst sorgt für alles.',
    'Handeln ohne die Vorstellung des Handelns führt zur Befreiung.',
    'Karma ist eine Kette von Ursache und Wirkung; das Selbst ist frei von Karma.',
    'Lebe in der Welt, aber gehöre nicht zu ihr.',
    'Der einzige Weg, von Karma frei zu werden, ist, das Selbst zu verwirklichen.',
    'Erfülle deine Pflichten ohne Anhaftung an die Ergebnisse.',
    'Ergib dich dem Willen Gottes, und jede Handlung wird mühelos.',
    'Wer das Selbst verwirklicht hat, hat kein Karma.',
    'Sei kein Sklave deiner Sinne oder Wünsche.',
    'Je mehr du anderen dienst, desto mehr erkennst du das Selbst in ihnen.',
    'Die höchste Form des Handelns ist, Zeuge aller Handlungen zu sein.',
    'Handlung ist eine Folge von Gedanken. Stille ist Abwesenheit von beidem.',
    'Die Welt ist eine Bühne. Spiel deine Rolle, aber vergiss nicht, wer du bist.',
    'Der Guru ist keine Person; der Guru ist das Selbst.',
    'Der Guru ist in dir – die innere Stimme.',
    'Der wahre Guru führt dich zum Selbst.',
    'Die Gnade des Guru ist immer da – du musst dich nur öffnen.',
    'Den Guru zu ehren heißt, das Selbst zu verwirklichen.',
    'Der Guru ist ein Spiegel, in dem du dein wahres Selbst siehst.',
    'Die Gnade des Guru ist notwendig für die Selbstverwirklichung.',
    'Der Guru ist nicht der Körper; der Guru ist das Bewusstsein im Herzen aller.',
    'Der Guru ist ein Wegweiser, kein Versorger.',
    'Die Gnade des Guru ist der Wind, der dich segeln lässt; deine Anstrengung ist das Segel.',
    'Vertraue dem Guru – er führt dich zur Wahrheit.',
    'Der Guru ist die lebendige Verkörperung der Wahrheit.',
    'Der Guru ist nicht getrennt von dir – du bist eins mit dem Guru.',
    'Die Lehre des Guru ist Stille.',
    'Der Guru hilft dir, über den Geist hinauszugehen.',
    'Der Geist ist das Ego in Aktion.',
    'Das Ego ist der Glaube: „Ich bin der Körper.“',
    'Wenn das Ego stirbt, leuchtet das Selbst auf.',
    'Das größte Hindernis zur Selbstverwirklichung ist das Ego.',
    'Das Ego ist eine Sammlung von Geschichten – Gedanken, Gefühlen, Erinnerungen.',
    'Der Geist ist ein guter Diener, aber ein gefährlicher Herr.',
    'Befreiung heißt nicht, irgendwohin zu gehen; sie heißt, hier und jetzt zu sein.',
    'Der einzige Weg, das Ego zu „töten“, ist, sich dem Selbst zu ergeben.',
    'Der Geist ist ein großer Täuscher; er erschafft die Illusion eines getrennten Selbst.',
    'Das Ego ist eine Festung aus Angst und Wünschen.',
    'Frei sein heißt, frei vom Geist zu sein.',
    'Der Geist ist ein Spiegel – du siehst nur deine eigenen Gedanken.',
    'Der Geist ist die Ursache allen Leidens; das Selbst ist die Quelle aller Freude.',
    'Das Ego ist die Wurzel aller Probleme – es sagt: „Ich will.“',
    'Der Geist ist eine Traummaschine – er erschafft die Welt und ihre Illusionen.',
    'Der Geist ist ein Fluss; das Selbst ist der Ozean.',
    'Befreiung ist ein Zustand des Seins, kein Ziel.',
    'Der Geist ist ein Werkzeug; du bist der, der es benutzt.',
    'Das Ego ist eine Geschichte, die wir uns erzählen.',
    'Der Geist ist ein Gefängnis; das Selbst ist der Schlüssel.',
    'Der Geist ist eine Wolke, die die Sonne des Selbst verdeckt.',
    'Das Ego ist eine vorübergehende Illusion; das Selbst ist ewige Wirklichkeit.',
    'Der Geist ist der Gast; das Selbst ist der Gastgeber.',
    'Befreiung ist vollkommene Stille und Frieden.',
    'Der einzige Weg, frei zu sein, ist, du selbst zu sein.',
    'Die Frage „Wer bin ich?“ ist nicht dazu da, eine Antwort zu bekommen; die Frage selbst ist die Antwort. Wenn die Quelle des „Ich“-Gedankens standhaft erforscht wird, verschwindet das falsche „Ich“, und das wahre Selbst leuchtet von selbst.',
    'Deine Pflicht ist zu sein, nicht dies oder das zu sein. „Ich bin, der ich bin“ fasst die Wahrheit zusammen. Die Methode ist: „Sei still.“ Stille bedeutet, das Falsche zu zerstören – denn Name und Form sind die Ursache der Unruhe.',
    'Das Selbst ist immer da; es ist dein eigenes Wesen. Es gibt nichts zu erreichen, nur die falsche Idee aufzugeben, man sei nicht das Selbst.',
    'Solange die Idee der Individualität besteht, bestehen auch die Ideen von Welt und Gott. Wenn die Individualität verschwindet, verschwindet alles mit ihr.',
    'Der Geist ist ein Bündel von Gedanken; der „Ich“-Gedanke ist ihre Wurzel. Wird die Wurzel entfernt, werden alle anderen entwurzelt.',
    'Das Selbst wird erkannt, wenn der Geist aufhört zu sein. Solange Geist ist, gibt es Zweifel und Leid.',
    'Stille ist die mächtigste Lehre; in Stille lösen sich alle Zweifel.',
    'Das Selbst ist nicht zu erreichen – du bist es immer; Unwissenheit wird entfernt.',
    'Wenn der Geist sich nach innen wendet und seine eigene Natur erforscht, verschwindet er; was bleibt, ist das Selbst.',
    'Es gibt kein größeres Geheimnis als dieses: Wir sind die Wirklichkeit und suchen die Wirklichkeit.',
    'Der Körper ist ein Gedanke; die Welt ist ein Gedanke. Verschwindet der Geist, verschwinden alle Gedanken.',
    'Gnade ist immer gegenwärtig; Gnade ist das Selbst.',
    'Das größte Hindernis ist die Vorstellung, Verwirklichung sei etwas zu erlangen.',
    'Versuche nicht, das Selbst zu verwirklichen; entferne die Hindernisse, die es zu verdecken scheinen.',
    'Der Geist kann den Geist nicht töten; er stirbt, wenn er nach innen taucht und in seiner Quelle aufgeht.',
    'Selbsterforschung ist nicht ein Mantra „Wer bin ich?“ – es ist das ruhige Verweilen bei dem Gefühl „Ich“, bis seine Quelle offenbar wird.',
    'Das Ego ist nur ein Schatten; suchst du es, verschwindet es.',
    'Wenn das Ego verschwindet, bleibt das Selbst – Wonne.',
    'Es gibt nichts wie „Verwirklichung“; es gibt nur das Ende der Unwissenheit.',
    'Das Selbst ist immer präsent; das Hindernis ist der ruhelose Geist.',
    'Still zu bleiben, heißt Weisheitsschau.',
    'Was immer du tust – untersuche das „Ich“. Das ist der einzige Weg.',
    'Wenn du ohne Gedanken als das Selbst verweilen kannst, lösen sich alle Probleme von selbst.',
    'Das Gefühl „Ich“ erhebt sich im Körper, gehört ihm aber nicht.',
    'Der nach außen gewendete Geist schafft Objekte; der nach innen gewendete Geist geht im Selbst auf.',
    'Die Welt ist nicht außerhalb von dir – sie ist Projektion des Geistes.',
    'Ist der Geist still, erscheint die Welt still.',
    'Erforderlich ist nicht Kontrolle des Geistes, sondern Erforschung seiner Natur.',
    'Solange man denkt: „Ich bin der Körper“, kann man dem Leiden nicht entgehen.',
    'Das Selbst wird nicht durch den Intellekt erkannt; es offenbart sich, wenn der Intellekt ruht.',
    'Wenn der „Ich“-Gedanke endet, bleibt allein das Selbst.',
    'Der „Ich“-Gedanke ist wie ein Dieb, der sich als Polizist ausgibt.',
    'Das Selbst kommt nicht und geht nicht – nur Gedanken kommen und gehen.',
    'Der Zustand der Verwirklichung ist der natürliche Zustand.',
    'Du musst die Welt nicht aufgeben; gib das Ego auf, das sie für getrennt hält.',
    'Körper und Geist sind Instrumente; du bist nicht diese.',
    'Freiheit findet sich nicht außen, sondern in Freiheit vom falschen „Ich“.',
    'Das Selbst wird nicht als Objekt erfahren; es ist der Erfahrende.',
    'Ergründung führt in die Stille, und die Stille enthüllt die Wahrheit.',
    'Der an Objekte gebundene Geist ist gebunden; der losgelöste ist frei.',
    'Es gibt keinen Unterschied zwischen Anstrengung und Gnade.',
    'Wenn du dich vollständig ergibst, bleibt niemand, der Fragen stellt.',
    'Die beste Disziplin ist Selbsterforschung.',
    'Allein das Selbst existiert; der Rest ist Erscheinung.',
    'Das Ego lebt durch Identifikation mit Objekten; endet diese, stirbt das Ego.',
    'Das Selbst ist weder innen noch außen – es allein ist.',
    'Was geboren wurde, muss sterben; was wirklich ist, ist nie geboren.',
    'Als das Selbst zu verweilen, ist die höchste Meditation.',
    '„Wer bin ich?“ zu fragen, heißt, den Geist nach innen zu wenden.',
    'Der Glaube, der Handelnde zu sein, ist die Ursache der Bindung.',
    'Erkennst du, dass du nicht der Handelnde bist, gehen Handlungen weiter – ohne Bindung.',
    'Friede ist deine wahre Natur.',
    'Wunschlosigkeit ist Weisheit.',
    'Das Selbst braucht keinen Schutz.',
    'Leiden entsteht durch Identifikation mit dem Vergänglichen.',
    'Das Selbst ist der Zeuge von Wachen, Träumen und Tiefschlaf.',
    'Schlaf ist wonnig, weil das Ego abwesend ist.',
    'Was dauerhaft ist, kann nicht verloren gehen.',
    'Wer Glück nach außen sucht, wird es nie finden.',
    'Wirklichkeit ist einfach; der Geist verkompliziert sie.',
    'Der Sucher ist das Gesuchte.',
    'Es gibt keine Unwissenheit außer dem Ego.',
    'Wenn das Ego stirbt, leuchtet das Selbst.',
    'Der Geist ist nur eine Bewegung weg vom Selbst.',
    'Sei still und wisse: Du bist das Selbst.',
    'Das Selbst ist selbstleuchtend.',
    'Die Ergründung zerstört Unwissenheit.',
    'Das Selbst wird nicht von dem berührt, was dem Körper widerfährt.',
    'Befreiung ist nicht zukünftig – sie ist jetzt.',
    'Das Ego schafft Bindung; das Selbst ist Freiheit.',
    'Wenn der Geist im Selbst ruht, ist das wahre Entsagung.',
    'Allein das Selbst ist wirklich; das Ego ist unwirklich.',
    'Die Idee „Ich bin der Körper“ ist die ursprüngliche Unwissenheit.',
    'Das Selbst bleibt, wenn alles andere verneint ist.',
    'Meditation heißt, einfach als das Selbst zu bleiben.',
    'Das „Herz“ ist kein Ort – es ist die Quelle des Bewusstseins.',
    'Alle Übungen dienen dazu, den Geist zu stillen.',
    'Wahres Wissen ist Stille.',
    'Das Selbst ist immer verwirklicht.',
    'Du bist nicht gebunden – du glaubst, gebunden zu sein.',
    'Wenn das „Ich“ sinkt, steigt das Selbst.',
    'Allein das Selbst ist – nichts sonst.',
    'Es gibt kein Werden – es gibt nur Sein.',
    'Das Selbst ist jenseits der Zeit.',
    'Das Selbst zu kennen heißt, das Selbst zu sein.',
    'Das Selbst ist reines Gewahrsein.',
    'Ein im Selbst aufgegangener Geist erhebt sich nicht wieder.',
    'Ergründung allein ist direkt.',
    'Das Ego ist der Knoten zwischen Selbst und Körper.',
    'Freiheit ist Freiheit vom Ego.',
    'Wenn der Geist endet, herrscht Frieden.',
    'Das Selbst ist nicht etwas, das erkannt werden muss, sondern etwas, das man ist.',
    'Das Selbst ist stets erreicht.',
    'Das Verschwinden des Ego ist die Verwirklichung des Selbst.',
    'Verweile, wie du bist.',
    'Sein ist die höchste Lehre.',
    'Das Selbst ist in allen das Gleiche.',
    'Die Wahrheit ist: Du bist bereits frei.',
    'Verweile im Selbst, und alles wird gut.'
  ],
  [
    Article(
      heading: 'Lehre von Maharishi Ramana',
      body:
          'Glückseligkeit\n\nAlle Wesen begehren stets Glück – Glück ohne den geringsten Beigeschmack von Leid. Zugleich liebt jeder sich selbst am meisten. Die Ursache der Liebe ist allein Glück. Daher muss dieses Glück in uns liegen. Außerdem erfährt jeder dieses Glück täglich im Schlaf, wenn kein Geist vorhanden ist. Um diese natürliche Glückseligkeit zu erlangen, muss man sich selbst kennen. Dafür ist Selbsterforschung – die Frage „Wer bin ich?“ – das Hauptmittel.\n\nBewusstsein\n\nSein oder Bewusstsein ist die einzige Wirklichkeit. Bewusstsein plus Wachen nennen wir Wachen, Bewusstsein plus Schlaf nennen wir Schlaf, Bewusstsein plus Traum nennen wir Traum. Bewusstsein ist die Leinwand, auf der alle Bilder kommen und gehen. Die Leinwand ist wirklich; die Bilder sind bloße Schatten.\n\nGeist\n\nDer Geist ist eine wunderbare Kraft, die im Selbst innewohnt. Was in diesem Körper als „Ich“ aufsteigt, ist der Geist. Wenn der subtile Geist sich durch Gehirn und Sinne nach außen bewegt, werden grobe Namen und Formen erkannt; wenn er im Herzen verweilt, verschwinden Namen und Formen. Bleibt der Geist im Herzen, vergeht das „Ich“ oder Ego – die Quelle aller Gedanken – und allein das Selbst, das wirkliche, ewige „Ich“, leuchtet. Wo nicht die leiseste Spur des Ego ist, dort ist das Selbst.\n\n„Wer bin ich?“ – Ergründung\n\nDie Quelle aller Gedanken ist der „Ich“-Gedanke. Der Geist vergeht nur durch Selbsterforschung: „Wer bin ich?“. Dieser Gedanke vernichtet alle anderen Gedanken und verschwindet schließlich selbst. Wenn andere Gedanken aufsteigen, soll man nicht versuchen, sie zu Ende zu denken, sondern erforschen: Wem ist dieser Gedanke erschienen? Die Antwort lautet: „Mir“. Fragt man weiter: „Wer bin ich?“, kehrt der Geist zu seiner Quelle zurück, und der Gedanke, der aufstieg, sinkt ab. Durch wiederholte Übung wächst die Kraft des Geistes, in seiner Quelle zu verweilen.\n\nHingabe\n\nEs gibt zwei Wege der Hingabe: den „Ich“-Ursprung zu ergründen und darin aufzugehen, oder zu fühlen: „Ich bin machtlos; allein Gott ist allmächtig, ich habe keinen anderen Schutz, als mich Ihm völlig hinzugeben“ – so reift die Überzeugung, dass allein Gott existiert und das Ego nicht zählt. Beide Wege führen zum selben Ziel. Vollständige Hingabe ist ein anderer Name für Jnana, Befreiung.\n\nDie drei Zustände: Wachen, Traum, Schlaf\n\nZwischen Traum und Wachen besteht kein Unterschied außer dem der Dauer. Beide sind Wirkungen des Geistes. Unser wahrer Zustand ist jenseits von Wachen, Traum und Schlaf – Turiya.',
    ),
    Article(
      heading: 'Wer bin ich? – Das einzige Buch von Maharishi Ramana',
      body:
          'Om Namo Bhagavate Sri Ramanaya\n\nWer bin ich? (Nan Yar?)\n\nDa alle Lebewesen stets glücklich sein wollen – wie im traumlosen Schlaf, in dem kein Geist vorhanden ist – und da jeder sein Selbst am meisten liebt und Glück allein die Ursache der Liebe ist, muss, um dieses Glück zu erlangen, das die eigene Natur ist, das Selbst erkannt werden. Das Haupthilfsmittel dazu ist der Pfad des Wissens, die Ergründung in der Form: „Wer bin ich?“.\n\n1. Wer bin ich?\n\nIch bin nicht der grobe Körper, bestehend aus den sieben Dhatus; nicht die fünf Erkenntnissinne noch die fünf Handlungssinne; nicht die fünf Lebensenergien; nicht einmal der denkende Geist; auch nicht die Unwissenheit, die nur die Eindrücke der Objekte enthält.\n\n2. Wenn ich nichts davon bin – wer bin ich?\n\nNach der Verneinung von „nicht dies, nicht dies“ bleibt jenes reine Gewahrsein, das allein ist – das bin ich.\n\n3. Was ist die Natur dieses Gewahrseins?\n\nSein–Bewusstsein–Wonne.\n\n4–15. (Essenz)\n\nDie Welt verschwindet, wenn der Geist zur Ruhe kommt. Der Geist ist nur eine Kraft, die im Selbst wohnt, und nichts als Gedanken; die Wurzel aller Gedanken ist das „Ich“. Wird dieses „Ich“ bis zur Quelle zurückverfolgt, löst es sich auf, und das Selbst bleibt.\n\nWenn andere Gedanken aufsteigen, frage: „Wem ist dieser Gedanke erschienen?“ – „Mir.“ – „Wer bin ich?“. Durch diese beharrliche Praxis wird der Geist in seinem Ursprung fest. Andere Mittel (Atemkontrolle, Mantra, Bildermeditation) beruhigen den Geist nur vorübergehend; Selbsterforschung vernichtet ihn in seiner Wurzel.\n\nDie Welt ist nur Gedanke; ohne Gedanken keine Welt. Wie die Schlange im Seil verschwindet, wenn das Seil erkannt ist, so verschwindet die Welt, wenn das Selbst erkannt ist.\n\nNicht durch Bücher wird das Selbst erkannt, sondern durch Schweigen des Geistes. Glück ist die Natur des Selbst; wenn der Geist nach außen geht, entsteht Leid; kehrt er heim, ist Glück. Wunschlosigkeit ist Weisheit; Weisheit ist Verweilen im Selbst. Befreiung ist das Erkennen der eigenen wahren Natur.',
    ),
    Article(
      heading: 'Selbst und Nicht-Selbst',
      body:
          'Existenz oder Bewusstsein ist die einzige Wirklichkeit. Bewusstsein plus Wachen nennen wir Wachen; plus Schlaf – Schlaf; plus Traum – Traum. Bewusstsein ist die Leinwand, auf der alle Bilder erscheinen. Die Leinwand ist wirklich; die Bilder sind Schatten.\n\nDie Schule des Ajata-Advaita erklärt: Es existiert nichts außer der einen Wirklichkeit; weder Geburt noch Tod, weder Bindung noch Befreiung. Für Sucher verschiedener Reifegrade werden jedoch auch andere Erklärungen gegeben: drishti–srishti (die Welt wird vom Geist erschaffen) oder srishti–drishti (Gott erschafft die Welt).\n\nWie das Seil nicht von der falschen Schlangenvorstellung berührt wird, so bleibt das Selbst unberührt von Erscheinungen. Der Weise hilft in der Welt – doch ohne die Vorstellung des Handelnden. Dienst an anderen ist Verehrung Gottes in ihnen.\n\nWas wirklich ist, ist allein das Selbst. Welt, Einzelseele und Gott sind Überlagerungen – wie Silber in Perlmutt. Der Weise richtet die Aufmerksamkeit auf das Substrat, nicht auf die Schriftzeichen auf dem Papier, auf dem sie stehen.\n\nFragen nach der Realität der Welt enden, wenn die Frage „Wer bin ich?“ restlos beantwortet wird: ohne Seher gibt es keine gesehene Welt.',
    ),
    Article(
      heading: 'Die acht Glieder der Erkenntnis (Jnana-Ashtanga)',
      body:
          'Frage: Was sind die acht Glieder der Erkenntnis?\n\nAntwort: Es sind dieselben wie im Yoga (yama, niyama usw.), jedoch anders gedeutet:\n\n1) Yama: Die Sinne beherrschen – die Fehlerhaftigkeit von Körper und Welt durchschauen.\n\n2) Niyama: Ununterbrochene Ausrichtung der Gedanken auf das Selbst und Zurückweisung gegenteiliger Tendenzen.\n\n3) Asana: Die Haltung, die müheloses Verweilen in Brahman ermöglicht.\n\n4) Pranayama: Rechaka – Name und Form aus den Objekten entfernen; Puraka – Sein, Bewusstsein, Wonne als ihr Wesen erfassen; Kumbhaka – dieses Erkennen bewahren.\n\n5) Pratyahara: Verhindern, dass Name und Form erneut in den Geist eintreten.\n\n6) Dharana: Den Geist im Herzen ruhen lassen und erkennen: Ich bin das Selbst, Sein–Bewusstsein–Wonne.\n\n7) Dhyana: Meditation in der Form: „Ich bin reines Bewusstsein“ – Verweilen als das leuchtende „Ich“.\n\n8) Samadhi: Das ungeteilte Erkennen (prajñāna), in dem das Selbst sich selbst als Selbst offenbart – Stille.',
    ),
  ],
);
