// shankaracharya_de.dart
// German file for Shankaracharya
// Deutsche Datei für Shankaracharya

import '../articlesquotes_de.dart';

final shankaracharyaSaintDe = Saint(
  'Shankaracharya',
  'Shankaracharya',
  'assets/images/shankaracharya.jpg',
  [
    'Nur Brahman ist wirklich; die Welt ist Erscheinung.',
    'Das Selbst ist jenseits von Geburt und Tod, jenseits aller Eigenschaften und Begrenzungen.',
    'Allein Wissen zerstört Unwissenheit, so wie nur Licht die Dunkelheit vertreibt.',
    'Tat tvam asi – Das bist du.',
    'Aham Brahmasmi – Ich bin Brahman.',
    'Brahman ist Sein, Bewusstsein und Wonne – absolut.',
    'Das Selbst ist der Zeuge von allem, selbst aber jenseits des Zeugenseins.',
    'Maya ist weder real noch unreal, sondern unbeschreiblich.',
    'Die Weisen sehen das Selbst in allen Wesen und alle Wesen im Selbst.',
    'Anhaftung ist die Wurzel allen Leidens.',
    'Entsagung ist nicht Weltflucht, sondern das rechte Verständnis ihrer wahren Natur.',
    'Der Guru ist Brahman selbst, der in menschlicher Gestalt den Schüler führt.',
    'Befreiung ist nichts zu Erlangendes, sondern etwas zu Erkennendes.',
    'Das Selbst verändert sich nie; es ist der ewige Zeuge aller Veränderungen.',
    'Hingabe an Gott reinigt das Herz.',
    'Wissen und Hingabe sind nicht verschieden – zwei Seiten derselben Wahrheit.',
    'Die drei Gunas binden die Seele an Samsara.',
    'Jenseits der drei Gunas ist das ewige, unveränderliche Selbst.',
    'Meditation ist das direkte Mittel zur Selbstverwirklichung.',
    'Der Geist ist Ursache von Bindung und Befreiung.',
    'Wird der Geist gereinigt, leuchtet das Selbst von selbst.',
    'Die Schriften sind wie eine Lampe, die den Weg zum Selbst zeigt.',
    'Die Wahrheit ist eine; die Weisen nennen sie mit verschiedenen Namen.',
    'Jivatman und Paramatman sind wesenseins.',
    'Unwissenheit verhüllt das Selbst wie Wolken die Sonne.',
    'Die Welt ist wie ein Traum – im Erleben real, vom Absoluten aus gesehen unwirklich.',
    'Karma bindet nur das Ego, nicht das Selbst.',
    'Das Selbst ist jenseits von Handeln und Nichthandeln.',
    'Begehren ist der Treibstoff, der das Rad des Samsara dreht.',
    'Zufriedenheit ist der größte Reichtum.',
    'Die Weisen werden durch Freude oder Schmerz nicht erschüttert.',
    'Friede ist die Natur des Selbst.',
    'Das Selbst bedarf keiner Stütze; es ist selbst-existent.',
    'Unterscheidung zwischen Wirklichem und Unwirklichem ist der Beginn der Weisheit.',
    'Das Selbst ist weder dies noch das – es ist reines Bewusstsein.',
    'Im Tiefschlaf bleibt allein das Selbst.',
    'Das Selbst ist das Licht, durch das alles erkannt wird.',
    'Zeit und Raum sind Vorstellungen des Geistes.',
    'Das Selbst ist jenseits von Zeit, Raum und Kausalität.',
    'Hingabe an Gott ist der leichteste Weg zur Befreiung.',
    'Gott ist nicht getrennt von dir – Du bist Das.',
    'Die höchste Wirklichkeit ist jenseits aller Begriffe und Beschreibungen.',
    'Schweigen ist die höchste Lehre.',
    'Das Selbst erkennt sich selbst.',
    'Es gibt keinen Weg zum Selbst – du bist bereits Das.',
    'Die Welle ist nicht verschieden vom Ozean.',
    'Alle Vielfalt ist Überlagerung der einen Wirklichkeit.',
    'Das Selbst ist ewig frei und rein.',
    'Bindung und Befreiung sind Begriffe des Geistes.',
    'Das Selbst ist der Träger aller Erfahrungen.',
    'Brahman ist wirklich, die Welt ist Erscheinung, und der individuelle Selbst ist nicht verschieden von Brahman – das ist die Essenz aller Vedanta.',
    'Solange der Mensch das Selbst nicht erkennt, erfährt er die Fessel der Unwissenheit – Ursache von Geburt, Tod und Leid.',
    'Wissen allein zerstört Unwissenheit; Handlung kann sie nicht zerstören, denn Unwissenheit steht nicht im Gegensatz zur Handlung.',
    'Das Selbst ist der Zeuge des Intellekts und seiner Tätigkeiten – ewig, frei, eins und voll – und verschieden von grobem und subtilen Körper.',
    'Wie im Dunkeln das Seil für eine Schlange gehalten wird, so wird aufgrund von Unwissenheit das Selbst für den Körper gehalten.',
    'Der Weise unterscheidet sorgfältig zwischen Wirklichem und Unwirklichem und erkennt: Brahman allein ist wirklich; alles andere ist vergänglich.',
    'Befreiung ist nichts, was produziert, verändert oder erreicht werden müsste – sie ist die Erkenntnis der eigenen wahren Natur.',
    'Das Selbst ist selbstleuchtend und bedarf keines anderen Erkenntnismittels; es ist erkannt, wenn Unwissenheit zerstört ist.',
    'Weder durch Rituale, noch Nachkommenschaft, noch Reichtum – allein durch Entsagung wird Unsterblichkeit erlangt.',
    'Körper, Sinne und Geist sind Objekte der Wahrnehmung; der Wahrnehmende ist das Selbst – verschieden und ewig frei.',
    'Wer die Wahrheit erkannt hat, sieht keinen Unterschied zwischen Gelehrtem und Ausgestoßenem, zwischen Kuh und Elefant.',
    'Bindung und Befreiung sind Schöpfungen der Unwissenheit; in Wahrheit ist das Selbst immer frei.',
    'Der durch Unterscheidung und Loslösung gereinigte Geist wird tauglich, Brahman zu erkennen.',
    'Wie die Sonne mühelos alles erleuchtet, so erleuchtet das Selbst alle Erfahrungen.',
    'Wer sich mit dem Körper identifiziert, ist unwissend; wer sich als das Selbst erkennt, ist befreit.',
    'Begehren ist die Wurzel der Bindung; wenn es erlischt, wird der Geist friedvoll.',
    'Entsagung bedeutet nicht, Handlungen aufzugeben, sondern die Vorstellung des Handelns.',
    'Wie der Raum unberührt bleibt, so bleibt das Selbst unberührt von den Tätigkeiten von Körper und Geist.',
    'Die Unwissenden sehen Vielfalt; die Weisen sehen die eine Wirklichkeit als viele erscheinend.',
    'Wenn Unwissenheit endet, leuchtet das Selbst von selbst – wie die Sonne, wenn die Wolken sich verziehen.',
    'Das mit dem Körper verknüpfte „Ich“ ist falsch; das wahre „Ich“ ist reines Bewusstsein.',
    'Die Welt ist unwirklich in dem Sinne, dass sie keine eigenständige Existenz neben Brahman hat.',
    'Der Kenner der Wahrheit ist frei, selbst lebend; er sieht alle Handlungen als dem Körper zugehörig.',
    'Ohne Selbsterkenntnis ist Befreiung unmöglich – auch nach unzähligen Ritualen.',
    'Unterscheidung zwischen ewig und vergänglich ist der erste Schritt auf dem Pfad der Erkenntnis.',
    'Das Selbst ist weder Handelnder noch Genießender; das Handeln gehört dem aus Unwissenheit geborenen Ego.',
    'Was gesehen wird, ist unwirklich; der Sehende allein ist wirklich.',
    'Ist der Geist gereinigt, spiegelt er das Licht des Selbst klar.',
    'Wie Traumbilder beim Erwachen verschwinden, so verschwindet die Welt bei der Verwirklichung der Wahrheit.',
    'Das Selbst ist jenseits von Geburt und Tod, jenseits von Leid und Verblendung.',
    'Wissen entsteht nicht aus Handlung, sondern aus Erforschung unter Führung eines Lehrers.',
    'Der Weise lebt ungebunden, wie ein Zeuge – frei von Verlangen und Furcht.',
    'Getrenntheit ist Unwissenheit; Nicht-Dualität ist Wahrheit.',
    'Wer Brahman erkennt, wird Brahman.',
    'Das Selbst ist kein Objekt der Meditation; es ist das Subjekt, das meditiert.',
    'Auch ein Gelehrter bleibt gebunden, wenn ihm Unterscheidung und Loslösung fehlen.',
    'Die Weisen entsagen nicht der Welt, sondern der falschen Vorstellung von ihrer Wirklichkeit.',
    'Unwissenheit projiziert die Welt; Wissen löst sie auf.',
    'Das Selbst ist dasselbe im Wachen, Träumen und Tiefschlaf.',
    'Befreiung ist Freiheit von Unwissenheit – kein Orts- oder Zustandswechsel.',
    'Anhaftung an den Körper ist Ursache der Furcht.',
    'Die eine Wirklichkeit erscheint aufgrund der Illusionskraft als viele.',
    'Wissen dämmert, wenn der Geist ruhig und rein wird.',
    'Das Selbst ist unendlich; der Körper ist endlich. Erkenne diesen Unterschied und sei frei.',
    'Wer das Selbst überall sieht, erlangt höchsten Frieden.',
    'Das Ego ist der Knoten, der Bewusstsein an den Körper bindet.',
    'Nur durch Wissen überquert man den Ozean des Samsara.',
    'Das Selbst ist jenseits von Sprache und Geist – dennoch selbstevident.',
    'Wie Ton in allen Tonformen allein wirklich ist, so ist Brahman in allen Namen und Formen allein wirklich.',
    'Loslösung entsteht aus dem Verstehen der Vergänglichkeit der Welt.',
    'Wissen, einmal aufgegangen, vergeht nicht.',
    'Das Selbst bleibt unberührt von Tugend und Laster.',
    'Wenn Unwissenheit zerstört ist, endet der Kreis von Geburt und Tod.',
    'Der Weise sieht handlungsloses Gewahrsein mitten im Handeln.',
    'Selbsterforschung ist das direkte Mittel zur Befreiung.',
    'Das Selbst handelt und genießt nicht – es erleuchtet nur.',
    'Ohne Entsagung wird Wissen nicht stabil.',
    'Brahman ist eines, ohne ein Zweites.',
    'Der Befreite sieht die Welt als vorübergehende Erscheinung.',
    'Furcht entsteht aus Dualität.',
    'Das Selbst ist das Licht der Lichter.',
    'Wissen vernichtet Karma an der Wurzel.',
    'Der Weise bleibt zufrieden im Selbst allein.',
    'Das Selbst ist ewig; der Körper ist vergänglich.',
    'Alles Leid gehört dem Geist, nicht dem Selbst.',
    'Befreiung ist das direkte Wissen um die eigene Identität mit Brahman.',
    'Das Selbst ist jenseits aller Eigenschaften.',
    'Wie Unwissenheit bindet, so befreit Wissen.',
    'Der Kenner der Wahrheit ist immer zufrieden.',
    'Das Selbst wird nicht von Freude oder Schmerz berührt.',
    'Allein Brahman existiert; Vielheit ist erdacht.',
    'Die Weisen geben die Früchte der Handlung auf.',
    'Nur Selbsterkenntnis bringt dauerhaften Frieden.',
    'Das Selbst ist frei von Geburt, Verfall und Tod.',
    'Die Illusion der Individualität entsteht aus Unwissenheit.',
    'Wer das Selbst erkennt, transzendiert alles Leid.',
    'Wissen dämmert, wenn der Geist durch Entsagung gereinigt ist.',
    'Das Selbst ist immer rein.',
    'Die Welt besitzt nur empirische, nicht absolute Wirklichkeit.',
    'Die Weisen leben unberührt – wie das Lotusblatt im Wasser.',
    'Das Selbst ist der Zeuge aller Erfahrungen.',
    'Wissen entfernt Unwissenheit vollständig.',
    'Der Verwirklichte sieht nirgendwo Unterschied.',
    'Das Selbst ist jenseits von Ursache und Wirkung.',
    'Loslösung und Wissen gehen Hand in Hand.',
    'Allein das Selbst ist dauerhaft.',
    'Bindung ist eingebildet; Freiheit ist wirklich.',
    'Der Kenner Brahmans erlangt höchste Wonne.',
    'Das Selbst ist nicht Objekt der Erfahrung, sondern der Erfahrende.',
    'Alle Schriften weisen auf Selbsterkenntnis hin.',
    'Allein Unwissenheit verursacht die Wanderschaft der Seele.',
    'Das Selbst ist unendliches Bewusstsein.',
    'Wissen, einmal erlangt, vergeht nicht.',
    'Der Weise ruht allein im Selbst.',
    'Brahman ist jenseits aller Begrenzungen.',
    'Das Selbst ist immer frei.',
    'Befreiung ist hier und jetzt.',
    'Das Selbst ist der Träger aller Erscheinungen.',
    'Selbsterkenntnis ist das höchste Wissen.',
    'Erkennt man „Ich bin Brahman“, wird ewiger Friede erlangt.'
  ],
  [
    Article(
      heading: 'Die Natur Brahmans',
      body:
          'Brahman ist absolutes Sein, absolutes Bewusstsein und absolute Wonne – ohne Eigenschaften (nirguna), jenseits aller Begrenzungen. Nicht dies, nicht das (neti neti), und doch die Wirklichkeit hinter allen Erscheinungen.\n\nBrahman ist die höchste Wahrheit, der Grund allen Seins – ungeboren, unsterblich, unendlich und unveränderlich. Das gesamte Universum erscheint in Brahman wie Wellen im Ozean, während Brahman unberührt bleibt.\n\nBrahman zu erkennen heißt zu verstehen, dass individuelles Selbst (Atman) und höchstes Selbst (Brahman) eins sind. Diese Erkenntnis ist kein bloßes Verstehen, sondern unmittelbare Erfahrung – die Vollendung des spirituellen Weges.\n\nBrahman kann nicht durch Sinne oder Geist erkannt werden; es ist das Bewusstsein selbst, durch das alles andere erkannt wird. Es ist selbstevident, selbstleuchtend und selbst-existent. Wenn alle Überlagerungen entfernt sind, bleibt allein Brahman.',
    ),
    Article(
      heading: 'Maya und die Welt',
      body:
          'Maya ist die geheimnisvolle Kraft, durch die das Eine als Vieles erscheint – weder real noch unreal, sondern unbeschreiblich (anirvachaniya). Maya verhüllt die wahre Natur Brahmans und projiziert die Welt der Vielheit.\n\nVom absoluten Standpunkt ist die Welt weder real noch unreal. Für den Unwissenden erscheint sie real; den Weisen ist sie nur scheinbar. Wie ein Traum, der im Erleben real wirkt, besitzt die Welt empirische, nicht aber absolute Wirklichkeit.\n\nMaya wirkt durch die drei Gunas – sattva (Harmonie), rajas (Aktivität) und tamas (Trägheit). In unzähligen Mischungen erzeugen sie die wahrgenommene Vielfalt. Der Weise transzendiert die Gunas und erkennt seine Natur jenseits aller Eigenschaften.\n\nMaya zu verstehen ist wesentlich für die Befreiung. Wenn wir erkennen, dass die Welt eine Überlagerung auf Brahman ist, bindet sie uns nicht länger. Wir handeln in der Welt, wissend um ihre wahre Natur.',
    ),
    Article(
      heading: 'Der Weg zur Befreiung',
      body:
          'Befreiung (moksha) ist nichts zu Erreichendes, sondern etwas zu Erkennendes – wir sind schon frei; nur Unwissenheit lässt uns gebunden erscheinen. Der Weg zur Befreiung besteht darin, diese Unwissenheit durch Wissen (jnana) zu entfernen.\n\nDer traditionelle Weg umfasst drei Schritte: Hören (shravana), Nachdenken (manana) und tiefes Verweilen/Verwirklichen (nididhyasana). So wird die Wahrheit zur unmittelbaren Erfahrung.\n\nUnterscheidung (viveka) zwischen Wirklichem und Unwirklichem ist wesentlich: Selbst und Nicht-Selbst, Ewiges und Vergängliches, Bewusstsein und seine Inhalte.\n\nLoslösung (vairagya) folgt natürlich aus Unterscheidung: Erkennen wir die Vergänglichkeit der weltlichen Freuden, fällt Anhaftung von selbst ab.\n\nDie vier Voraussetzungen (sadhana chatushtaya) sind: Unterscheidung, Loslösung, die sechs Tugenden (z. B. Ruhe und Selbstbeherrschung) und intensives Verlangen nach Befreiung. Mit diesen Qualifikationen und durch die Gnade des Guru ist Befreiung gewiss.',
    ),
  ],
);
