// sivananda_de.dart
// German file for Swami Sivananda
// Deutsche Datei für Swami Sivananda

import '../articlesquotes_de.dart';

final sivanandaSaintDe = Saint(
  'sivananda',
  'Swami Sivananda',
  'assets/images/sivananda.jpg',
  [
      'Ein Quäntchen Praxis ist mehr wert als eine Tonne Theorie!',
      'Lege Herz, Geist und Seele selbst in deine kleinsten Handlungen. Darin liegt das Geheimnis des Erfolgs.',
      'Wenn du den Frieden nicht in dir selbst findest, wirst du ihn nirgendwo sonst finden.',
      'Fürchte die Dunkelheit nicht, wenn du das Licht in dir trägst.',
      'Der Geist ist verantwortlich für die Empfindungen von Freude und Schmerz. Die Beherrschung des Geistes ist das höchste Yoga.',
      'Kultiviere zuerst den Frieden im Garten deines Herzens, indem du das Unkraut von Begierde, Hass, Gier, Egoismus und Neid entfernst.',
      'Blicke nach innen. In dir ist der verborgene Gott. In dir ist die unsterbliche Seele.',
      'Liebe erwartet keine Belohnung. Liebe kennt keine Angst. Göttliche Liebe gibt – sie fordert nicht.',
      'Geduldige und regelmäßige Praxis ist das ganze Geheimnis spiritueller Verwirklichung. Eile nicht im spirituellen Leben.',
      'Mache andere wahrhaft glücklich, während du versuchst, dich selbst glücklich zu machen. Sprich ein hilfreiches Wort. Schenke ein ermutigendes Lächeln. Tue eine gütige Tat.',
      'Diene, liebe, gib, reinige, meditiere, verwirkliche.',
      'Ein Quäntchen Praxis ist besser als eine Tonne Theorie.',
      'Der spirituelle Pfad ist scharf wie die Schneide eines Rasiermessers.',
      'Gott ist keine ferne Wirklichkeit, sondern die innewohnende Realität, dir näher als alles andere auf Erden.',
      'Liebe ist die größte schöpferische Kraft der Welt.',
      'Diese Welt ist dein bester Lehrer. In allem liegt eine Lehre. In jeder Erfahrung liegt eine Lehre. Lerne sie und werde weise.',
      'Selbstanalyse ist die größte Kunst des Fortschritts.',
      'Wo kein Egoismus ist, dort sind Frieden, Freude und Erleuchtung.',
      'Du bist der Schöpfer deines eigenen Schicksals. Du selbst hast es erschaffen. Du allein trägst die volle Verantwortung dafür.',
      'Das Geheimnis vollkommener Gesundheit, vollkommenen Glücks und vollkommenen Erfolgs liegt in der Beherrschung des eigenen Geistes.',
      'Sei weise und erkenne den wahren Sinn des Lebens.',
      'Säe den Samen der Selbstdisziplin. Gieße ihn mit Liebe.',
      'Die Krone des spirituellen Lebens ist die Schau der Einheit.',
      'Entwickle stets positive und konstruktive Gedanken.',
      'Entsage dem Irdischen, wenn du das Ewige erlangen willst.',
      'Jedes Scheitern ist ein Trittstein zum Erfolg.',
      'Das Schwerste auf Erden ist – wenn man ehrlich zu sich selbst ist – wahrhaft gut zu sein.',
      'Demut ist keine Feigheit. Sanftmut ist keine Schwäche. Sie sind spirituelle Kräfte.',
      'Das Göttliche in dir ist stärker als alles, was außerhalb von dir ist.',
      'Wahre Spiritualität bedeutet, ein Athlet im Wettlauf des Lebens zu sein.',
      'Wie du denkst, so wirst du.',
      'Der Mensch sät einen Gedanken und erntet eine Tat. Er sät eine Tat und erntet eine Gewohnheit. Er sät eine Gewohnheit und erntet einen Charakter. Er sät einen Charakter und erntet ein Schicksal.',
      'Ein Berg besteht aus winzigen Erdteilchen. Der Ozean setzt sich aus unzähligen Wassertropfen zusammen. Ebenso ist das Leben eine endlose Abfolge kleiner Details, Handlungen, Worte und Gedanken.',
      'Zerstöre die Neigung, das Böse zu suchen. Entwickle die Fähigkeit, das Gute zu erkennen.',
      'Angst existiert nur in der Dualität. Angst ist Geist. Wenn du dein wahres Selbst bist, gibt es keine Angst.',
      'Der Geist ist die Ursache allen Leids und aller Schmerzen.',
      'Speichere kein nutzloses Wissen in deinem Gehirn. Lerne, den Geist loszulassen.',
      'Wenn du an Katastrophen denkst, ziehst du sie an. Grübelst du über den Tod, beschleunigst du ihn. Denke positiv, kraftvoll, mit Vertrauen und Glauben – dann wird das Leben sicherer.',
      'Jeder Gedanke zieht eine Furche in unser Gesicht.',
      'Der Geist ist verantwortlich für die Empfindungen von Freude und Schmerz.',
      'Ein reiner und ruhiger Geist ist wesentlich für Weisheit.',
      'Die Fähigkeit zur Konzentration ist allen Menschen angeboren; sie ist weder außergewöhnlich noch geheimnisvoll.',
      'Die Beherrschung des Geistes ist das höchste Yoga.',
      'Gedanken werden zu Taten. Taten werden zu Gewohnheiten. Gewohnheiten werden zu Charakter. Charakter wird zu Schicksal.',
      'Der Geist ist wie ein wildes Pferd, das gezähmt werden muss.',
      'Was begrenzt die Schau der individuellen Seele? Allein der Geist.',
      'Gedanken erschaffen Wirklichkeit, wenn sie kraftvoll sind.',
      'Je mehr du meditierst, desto mehr wirst du erkennen, dass du nicht der Körper bist, sondern die unsterbliche Seele.',
      'Das Gesicht ist der Spiegel des Geistes.',
      'Der Geist ist ein großer Speicher des Wissens. Unsere Gedanken sind der einzige Kanal, durch den dieses Wissen hervortritt.',
      'Meditation ist die Auflösung der Gedanken im ewigen Gewahrsein oder reinen Bewusstsein – Wissen ohne Denken.',
      'Regelmäßige Meditation öffnet die Wege intuitiver Erkenntnis.',
      'Die Sprache der Stille ist die Sprache Gottes; die Sprache der Stille ist die Sprache des Herzens.',
      'Meditation ist anfangs schmerzhaft, schenkt aber am Ende unsterbliche Wonne und höchste Freude.',
      'Um dauerhafte Glückseligkeit und absoluten Frieden zu erlangen, müssen wir zuerst lernen, den Geist zu beruhigen, zu sammeln und über ihn hinauszugehen.',
      'Übe Meditation regelmäßig. Meditation führt zur ewigen Glückseligkeit.',
      'Ziehe dich nach innen zurück. Erforsche dich selbst. Erkenne intuitiv.',
      'Um äußere Konflikte zu überwinden, müssen wir in die innere Einsamkeit gehen.',
      'Halte deinen Geist davon ab, nach außen zu streifen; werde still und beobachte ihn.',
      'Stille ist das Tor zum Göttlichen.',
      'Jeder wache Moment ohne Gedanken ist ein Zustand von Samadhi.',
      'Je tiefer du in die Stille eintauchst, desto deutlicher hörst du die innere Stimme.',
      'Der wahre Sinn der Meditation ist Einssein mit dem Göttlichen.',
      'Durch Meditation kannst du dein wahres Selbst entdecken.',
      'Meditation ist der einzige Weg zu dauerhaftem Frieden.',
      'Jeder Mensch ist der Schöpfer seiner eigenen Gesundheit oder Krankheit.',
      'Gesundheit ist jener Zustand, in dem der Mensch springt, singt, lächelt, lacht, pfeift und sich voller Freude und Ekstase bewegt.',
      'Ein gesunder Geist in einem gesunden Körper.',
      'Schmerz ist das Beste in der Welt. Er ist ein Augenöffner. Er weckt deine schlummernden Fähigkeiten.',
      'Körperliche Gesundheit bedeutet, dass der Körper gut funktioniert und den besten Lebensregeln folgt – im Einklang mit dem Rhythmus der Natur.',
      'Je tiefer dein Verständnis der Einheit, desto gesünder bist du.',
      'Die Atome, Moleküle und Zellen im Körper erzeugen disharmonische Schwingungen, wenn Hoffnung, Vertrauen, Glaube, Gelassenheit und Heiterkeit fehlen. Dann sind sie unglücklich.',
      'Dein Gesicht ist ein Spiegel. Was du denkst, schreibt sich unmittelbar in dein Gesicht.',
      'Ein böser Gedanke verdunkelt Gesicht und Aura. Ein göttlicher Gedanke erhellt beides.',
      'Kultiviere zuerst den Frieden im Garten deines Herzens.',
      'Liebe verschönert den Gebenden und erhebt den Empfangenden.',
      'Lieben heißt teilen und dienen.',
      'Liebe erwartet keine Belohnung. Liebe kennt keine Angst. Göttliche Liebe gibt – sie fordert nicht.',
      'Liebe ist das einzige Gesetz. Liebe ist die einzige Wirklichkeit.',
      'Liebe ist die größte schöpferische Kraft der Welt.',
      'Wo Liebe ist, da ist Gott.',
      'Die Lehre des Lebens war immer: Hass wird nicht durch Hass überwunden, sondern allein durch Liebe.',
      'Sei gütig zu jedem, denn jeder kämpft einen schweren inneren Kampf.',
      'Liebe alle, diene allen, denn alle sind eins in Gott.',
      'Anderen zu dienen heißt, Gott zu dienen.',
      'Lege Herz, Geist und Seele selbst in deine kleinsten Handlungen. Darin liegt das Geheimnis des Erfolgs.',
      'Stehe nicht als Bettler vor der Tür der Wissenschaft und suche eine Macht, die mehr tötet als heilt.',
      'Je härter der Kampf, desto glorreicher der Sieg.',
      'Sorge dich niemals darum, was andere sagen oder denken. Tue das Richtige. Bewahre ein reines Gewissen und gehe heiter durchs Leben.',
      'Heute gehört dir. Morgen kommt vielleicht niemals.',
      'Ein Leben ohne gute Gesundheit ist ein elender Zustand.',
      'Sei heiter. Halte an deinem Ideal fest. Sei der Diener aller.',
      'Das Gesetz des Karma ist keine Strafe, sondern ein Gesetz von Ursache und Wirkung.',
      'Das wahre Ziel des Lebens ist die Rückkehr zur Quelle, aus der wir gekommen sind.',
      'Die größte Hilfe für das spirituelle Leben ist Meditation. Die nächste ist gute Gemeinschaft.',
      'Je mehr du nach außen gehst und Gutes tust, desto reiner wird dein Herz.',
      'Du bist der Meister deines eigenen Schicksals.',
      'Das Universum ist ein gewaltiger Tempel Seiner Gegenwart.',
      'Jede Seele ist ihrem Wesen nach göttlich.',
      'Alles Wissen ist in uns. Der menschliche Geist bringt es zum Ausdruck.',
      'Gott offenbart sich auf verschiedenen Stufen der Entwicklung auf unterschiedliche Weise.',
      'Diese Welt ist ein Überfluss der Wonne Gottes.',
      'Der wahre Sinn des Lebens ist die Erkenntnis, dass du eins mit Gott bist.',
      'Du bist ein Funke der Göttlichkeit. Bekräftige dies und gehe furchtlos durchs Leben.',
      'Bewusstsein, obwohl unsichtbar, erleuchtet alles.',
      'Je mehr du Gott liebst, desto mehr wirst du alle anderen lieben können, denn du wirst Gott in ihnen sehen.',
      'Das Ziel des Lebens ist es, das Göttliche im Inneren zu offenbaren, indem man die äußere und innere Natur beherrscht.',
      'Der einzige Weg aufzusteigen besteht darin, die Pflicht zu erfüllen, die direkt vor uns liegt.',
      'Alles ist Gott. Alles ist Geist. Alles ist eins.',
      'Das Ziel des menschlichen Lebens ist die Erlangung der Freiheit.',
      'Dienen, lieben, geben, reinigen, meditieren, verwirklichen – dies ist die einfache und doch tiefgründige Botschaft aller Schriften und das Wesen des spirituellen Lebens.',
      'Warte nicht auf ideale Bedingungen für spirituelle Praxis. Das Leben wird niemals frei von Hindernissen sein. Beginne jetzt, wo du bist, mit dem, was du hast.',
      'Ein Leben selbstlosen Dienstes ist die höchste Form der Verehrung. Wenn du der Menschheit mit reinem Herzen dienst, verehrst du den lebendigen Gott.',
      'Spirituelles Leben verlangt nicht, die Welt zu verlassen, sondern Egoismus, Selbstsucht und Anhaftung loszulassen.',
      'Der Zweck des menschlichen Lebens ist die Gottesverwirklichung, und jeder Gedanke, jedes Wort und jede Handlung sollte letztlich auf dieses höchste Ziel ausgerichtet sein.',
      'Meditation ist der königliche Weg zur Verwirklichung des Selbst. Ohne Meditation kann der Geist nicht gereinigt werden, und ohne Reinheit gibt es keinen Frieden.',
      'Die Beherrschung des Geistes ist die schwierigste Aufgabe – aber auch der glorreichste Sieg, den ein Mensch erringen kann.',
      'Wahre Entsagung ist nicht der Verzicht auf Handlung, sondern der Verzicht auf das Verlangen nach den Früchten der Handlung.',
      'Der ruhelose Geist schweift, weil ihm Disziplin fehlt. Durch regelmäßige Übung und Loslösung kann er unter Kontrolle gebracht werden.',
      'Sieh Gott in jedem Gesicht, fühle Seine Gegenwart in jedem Herzen, und dein ganzes Leben wird zu einem Akt der Verehrung.',
      'Spirituelles Wachstum ist allmählich und kaum wahrnehmbar, wie das Wachsen eines Baumes. Sei nicht ungeduldig; Ausdauer ist der Schlüssel.',
      'Gebet ist keine mechanische Wiederholung von Worten, sondern der innige Ruf der Seele nach Vereinigung mit dem Göttlichen.',
      'Klage nicht über Zeitmangel. Wenn du Zeit für müßiges Gerede findest, findest du gewiss auch Zeit für Meditation.',
      'Der Geist nimmt die Form dessen an, woran er ständig denkt. Denke an Gott, und der Geist wird göttlich.',
      'Stille ist ein großer spiritueller Lehrer. In der Stille wird der Geist ruhig und die Stimme der Seele hörbar.',
      'Wahres Glück entspringt nicht äußeren Dingen, sondern innerem Frieden und Zufriedenheit.',
      'Selbstdisziplin ist das Fundament des spirituellen Lebens. Ohne sie bleiben alle Bestrebungen bloße Träume.',
      'Der Guru ist nicht bloß eine Person; er ist das göttliche Licht, das die Dunkelheit der Unwissenheit vertreibt.',
      'Führe ein einfaches Leben, zügle deine Wünsche und pflege edle Gedanken – dies ist das Geheimnis dauerhaften Friedens.',
      'Der Körper ist ein Instrument; nutze ihn für rechtes Handeln und spirituelle Praxis, nicht für Ausschweifung.',
      'Glaube an Gott und Glaube an dich selbst müssen Hand in Hand gehen; ohne das eine ist das andere unvollständig.',
      'Regelmäßigkeit in der spirituellen Praxis ist wichtiger als Intensität. Wenig jeden Tag ist besser als viel gelegentlich.',
      'Suche nicht die Vollkommenheit in anderen. Suche sie in dir selbst durch ständige Selbstprüfung.',
      'Jede Schwierigkeit im Leben ist eine Lektion des Göttlichen für deine spirituelle Entwicklung.',
      'Loslösung bedeutet nicht Gleichgültigkeit, sondern die Erfüllung der Pflichten mit ruhigem und ausgeglichenem Geist.',
      'Der größte Dienst an der Welt ist die Reinigung des eigenen Herzens.',
      'Wenn das Ego zerstört ist, fließt Liebe ganz natürlich zu allen Wesen.',
      'Ein reines Herz ist der wahre Tempel Gottes.',
      'Spirituelles Leben beginnt mit ethischem Handeln. Ohne moralische Reinheit tragen höhere Praktiken keine Frucht.',
      'Die Sinne sind mächtig, der Geist ist mächtiger, der Intellekt noch mächtiger – doch das Selbst ist das Höchste.',
      'Zufriedenheit ist der größte Reichtum, und Seelenfrieden ist das höchste Glück.',
      'Miss spirituellen Fortschritt nicht an Visionen oder Kräften, sondern an der Abnahme von Egoismus und Begierden.',
      'Der Yogaweg ist der Weg des Gleichgewichts – zwischen Arbeit und Ruhe, Hingabe und Erkenntnis, Anstrengung und Hingabe.',
      'Ein diszipliniertes Leben ist kein Leben der Unterdrückung, sondern eines kluger Ordnung.',
      'Wo Liebe ist, gibt es keine Angst; wo Angst ist, ist die Liebe noch nicht erwacht.',
      'Diene ohne Erwartung, liebe ohne Bedingung und arbeite ohne Anhaftung.',
      'Der Geist wird zu dem, womit er genährt wird. Nähre ihn mit edlen Gedanken und göttlichen Ideen.',
      'Spirituelle Unwissenheit ist die Wurzel allen Leidens.',
      'Sei gütig, mitfühlend und vergebend – das sind die Zierden eines spirituellen Suchenden.',
      'Die Entsagung des Ego ist größer als die Entsagung von Reichtum.',
      'Die wahre Prüfung des spirituellen Lebens ist Gelassenheit inmitten von Schwierigkeiten.',
      'Verschwende keine Energie an Kritik; nutze sie zur Selbstvervollkommnung.',
      'Gott ist nicht fern; Er ist näher als dein eigener Atem.',
      'Ein ruhiger Geist ist der größte Segen.',
      'Die Übung der Wahrheit in Gedanke, Wort und Tat reinigt das ganze Wesen.',
      'Das Licht des Wissens vertreibt die Dunkelheit der Unwissenheit, wie die Sonne die Nacht vertreibt.',
      'Wenn die Begierden schwinden, erwacht der Frieden von selbst.',
      'Spirituelles Leben ist keine Flucht vor dem Leben, sondern ein tieferes Verstehen desselben.',
      'Reinheit, Geduld und Ausdauer sind die drei Säulen des Erfolgs im Yoga.',
      'Schon ein wenig spirituelle Praxis bewahrt vor großer Angst.',
      'Das Ziel des Lebens ist die Erkenntnis deiner Einheit mit allem Sein.',
      'Je mehr du gibst, desto mehr empfängst du – das ist das Gesetz göttlicher Fülle.',
      'Gebet und Meditation verwandeln das Innere und strahlen Frieden in die Welt aus.',
      'Demut ist das Zeichen wahrer Weisheit.',
      'Begierde ist die Wurzel der Unruhe; Entsagung ist die Wurzel des Friedens.',
      'Ein spiritueller Suchender sollte heiter, geduldig und voller Hoffnung sein.',
      'Jeder Augenblick ist eine Gelegenheit zu spirituellem Wachstum.',
      'Göttliche Gnade senkt sich herab, wenn das Herz rein und aufrichtig ist.',
      'Das Geheimnis des Erfolgs liegt in stetiger Anstrengung und unerschütterlichem Glauben.',
      'Sich selbst zu überwinden ist größer, als die Welt zu erobern.',
      'Lebe in der Welt, aber lasse die Welt nicht in dir leben.',
      'Spirituelle Praxis reinigt das Unterbewusstsein und verwandelt den Charakter.',
      'Sieh dasselbe Selbst im Heiligen wie im Sünder.',
      'Liebe erweitert das Herz und zerstört das Gefühl der Getrenntheit.',
      'Ein disziplinierter Geist führt zu Glück; ein undiszipliniert­er Geist führt zu Leid.',
      'Erfülle deine Pflicht freudig als Opfergabe an Gott.',
      'Die Seele ist ewig frei, ewig rein, ewig selig.',
      'Spiritualität ist gelebte Religion im täglichen Leben.',
      'Geduld und Standhaftigkeit sind Zeichen innerer Stärke.',
      'Der größte Feind ist der unbeherrschte Geist.',
      'Einfachheit im Leben führt zu Klarheit des Geistes.',
      'Gottesverwirklichung ist der Höhepunkt allen menschlichen Strebens.',
      'Lass dein Leben eine Botschaft des Friedens und des Wohlwollens sein.',
      'Die Übung des Mitgefühls reinigt das Herz.',
      'Wissen ohne Hingabe ist trocken; Hingabe ohne Wissen ist blind.',
      'Spirituelles Leben erfordert ständige Wachsamkeit.',
      'Frieden kommt von innen; suche ihn nicht im Außen.',
      'Ein edler Gedanke ist ein stilles Gebet.',
      'Der Geist wird rein durch den Umgang mit Weisen.',
      'Der Zweck des Yoga ist die Vereinigung mit dem Göttlichen.',
      'Entsage Hass, Zorn und Neid; pflege Liebe und Vergebung.',
      'Spiritueller Fortschritt wird an innerer Verwandlung gemessen.',
      'Die höchste Bildung ist jene, die Selbstbeherrschung lehrt.',
      'Gottes Gnade fließt dort, wo Demut ist.',
      'Ein tugendhaftes Leben ist das Fundament des Friedens.',
      'Verwandle jede Handlung in Yoga, indem du sie Gott darbringst.',
      'Selbstanalyse führt zur Selbstreinigung.',
      'Das Göttliche offenbart sich in einem reinen und stillen Geist.',
      'Spirituelles Leben ist ein fortwährender Prozess der Verfeinerung.',
      'Löse dich von Ergebnissen und arbeite mit Freude.',
      'Die innere Stimme führt jene, die in der Stille lauschen.',
      'Allein die Wahrheit siegt, und die Wahrheit ist Gott.',
      'Beherrschung der Sprache ist eine mächtige spirituelle Disziplin.',
      'Das Herz, das Gott liebt, liebt alle Wesen.',
      'Yoga ist Harmonie in Gedanke, Wort und Tat.',
      'Glaube versetzt Berge des Zweifels.',
      'Die Übung der Geduld zerstört den Zorn.',
      'Diene mit Demut und Hingabe.',
      'Spirituelles Erwachen ist das Geburtsrecht jedes Menschen.',
      'Erkenne das Selbst und sei für immer frei.'
    ],
  [
    Article(
        id: 'sivananda_guru',
        heading: 'Role of Guru',
        body: 'Content...'
    ),
  ],
);
