// yogananda_de.dart
// Paramhansa Yogananda – Zitate und Artikel (Deutsch)

import '../articlesquotes_de.dart';

final yoganandaSaintDe = Saint(
  'yogananda',
  'Paramhansa Yogananda',
  'assets/images/paramhansa.jpg',
  [
    'Lass dein Leben nicht im gewöhnlichen Trott verlaufen; tue etwas, das niemand sonst getan hat, etwas, das die Welt in Erstaunen versetzt.',
    'Die Zeit des Scheiterns ist die beste Zeit, um die Samen des Erfolgs zu säen.',
    'Sei so einfach, wie du nur sein kannst; du wirst staunen, wie unkompliziert und glücklich dein Leben werden kann.',
    'Lebe still im Augenblick und sieh die Schönheit von allem vor dir. Die Zukunft wird für sich selbst sorgen.',
    'Das Glück des eigenen Herzens allein kann die Seele nicht zufriedenstellen; man muss versuchen, das Glück anderer als notwendig für das eigene Glück einzuschließen.',
    'Verändere dich selbst, und du hast deinen Teil dazu beigetragen, die Welt zu verändern.',
    'Beharrlichkeit garantiert, dass Ergebnisse unvermeidlich sind.',
    'Bleibe ruhig, gelassen und stets Herr deiner selbst. Dann wirst du merken, wie leicht es ist, miteinander auszukommen.',
    'Lass meine Seele durch mein Herz lächeln und mein Herz durch meine Augen lächeln, damit ich reiche Lächeln in traurige Herzen streuen kann.',
    'Die Macht unerfüllter Wünsche ist die Wurzel aller Knechtschaft des Menschen.',
    'Glück hängt vom Zustand deines Geistes ab, nicht vom Zustand deiner Besitztümer.',
    'Das Geheimnis von Erfolg und Glück liegt in dir. Wenn du draußen Erfolg und Wohlstand gefunden hast, aber nicht innen, bist du nicht wirklich erfolgreich.',
    'Frieden strahlt aus der Seele und ist die heilige innere Umgebung, in der wahres Glück erblüht.',
    'Viel Geld zu haben und keinen inneren Frieden ist, als würde man vor Durst sterben, während man im Ozean badet.',
    'Ein wahrhaft erfolgreicher Mensch ist glücklich und zufrieden und lebt nach seinen eigenen Prinzipien.',
    'Du musst wahren Frieden und Glück in dir selbst finden. Deine äußeren Erfahrungen sollten nur ein Spiel sein.',
    'Ekstatisch zu sein ist nicht schwer. Ruhig freudig zu sein ist der schwierige Teil. Das ist das Ideal.',
    'Lebe jeden gegenwärtigen Moment ganz, und die Zukunft wird für sich selbst sorgen.',
    'Je mehr du die Gegenwart des Friedens übst, desto mehr wirst du die Präsenz dieser Kraft in deinem Leben fühlen.',
    'Das ganze Geheimnis der Existenz besteht darin, keine Angst zu haben.',
    'Freundlichkeit ist das Licht, das alle Mauern zwischen Seelen, Familien und Nationen auflöst.',
    'Ein wenig Freude im Leben ist besser als viele Besitztümer.',
    'Erkenne, dass das Ausspielen der Rolle, zu der du berufen bist, dein wahres Sein nicht berührt.',
    'Die höchste Belohnung für die Mühe eines Menschen ist nicht, was er dafür bekommt, sondern was er dadurch wird.',
    'Du bist der Segnungen des geistigen Bewusstseins würdig.',
    'Durch die Praxis der Meditation wirst du feststellen, dass du in deinem Herzen ein tragbares Paradies trägst.',
    'Die Seele liebt es zu meditieren, denn im Kontakt mit dem Geist liegt ihre größte Freude.',
    'Meditation ist der größte Weg, deine Seele aus der Knechtschaft des Körpers zu befreien.',
    'Meditation ist die Quelle, aus der Gottes Frieden in deine Seele fließt.',
    'Kurz und tief zu meditieren ist besser, als lange Stunden zu meditieren, während der Geist wild umherrennt.',
    'Sei still und erkenne: Ich bin Gott.',
    'Der Devotee, der die höchste Anstrengung macht, ist derjenige, der Gott findet. Nicht derjenige, der immer neue Ausreden sucht.',
    'Wenn du meditierst, wirst du Türen finden, die sich überall zu Ihm öffnen.',
    'Werde in deinen Bemühungen, Gott zu finden, nicht aufgeregt oder ungeduldig. Sei geduldig. Gehe deinem göttlichen Ziel stets ruhig und mit Gelassenheit entgegen.',
    'Der Geist wirkt wie ein Sieb, durch das das universelle Wissen in unser Bewusstsein fließt.',
    'Je mehr du Gott liebst, desto mehr wirst du alle anderen lieben können, denn du wirst Gott in allen sehen.',
    'Der beste Test für den Charakter eines Menschen ist, wie er diejenigen behandelt, die nichts für ihn tun können.',
    'Tue nicht, was du willst, und dann darfst du tun, was dir gefällt.',
    'Das Geheimnis von Erfolg und Glück liegt in dir.',
    'Du kannst nicht wirklich glücklich sein, wenn du nicht frei von allen Bindungen bist.',
    'Liebe gibt, ohne etwas im Gegenzug zu erwarten.',
    'Dem Geliebten Vollkommenheit zu wünschen und reine Freude zu empfinden, wenn man an diese Seele denkt, ist göttliche Liebe; und das ist die Liebe wahrer Freundschaft.',
    'Liebe ist das Licht, das alle Mauern zwischen Seelen, Familien und Nationen auflöst.',
    'Die größte Liebe, die du erfahren kannst, ist die Gemeinschaft mit Gott in der Meditation.',
    'Trauere nicht um verlorene Liebe … Liebe selbst geht nie verloren, sondern spielt mit dir Verstecken in vielen Herzen.',
    'Wenn du einmal deine Liebe gegeben hast, muss es für immer sein. Nicht, weil du in der Nähe dieser Person sein willst, sondern weil du Vollkommenheit für diese Seele willst.',
    'Die ganze Welt ist ein Spielplatz für die Seele.',
    'Wenn du Gemeinschaft mit Ihm hast, können nicht alle Verwüstungen der Welt jene Freude und jenen Frieden nehmen.',
    'In der unendlichen Liebe Gottes ist meine ewige Brust groß genug, alles in mir zu halten.',
    'Mein Herz ist ein Tempel ewiger Liebe.',
    'Um ein wahrer Freund zu sein, musst du andere lieben wie dich selbst, denn nur dann kannst du ihre Bedürfnisse und ihren Kummer verstehen.',
    'Liebe ist kein Gefühl; sie ist die Wahrheit im Kern der Schöpfung.',
    'Die Liebe Gottes, die Liebe des Geistes, ist eine alles verzehrende Liebe.',
    'Sei Nacht und Tag so trunken vor der Liebe Gottes, dass du nichts anderes kennst als Gott.',
    'Die Liebe zwischen Seele und Geist ist die vollkommene Liebe, die Liebe, nach der ihr alle sucht.',
    'Als sterbliches Wesen bist du begrenzt, doch als Kind Gottes bist du unbegrenzt.',
    'Der menschliche Geist ist ein Funke des allmächtigen Bewusstseins Gottes.',
    'Deine Gedanken formen dich. Bist du schlecht, so bist du nur das Ergebnis deiner schlechten Gedanken. Bist du gut, so ist es wegen deiner guten Gedanken.',
    'Wenn du deinen Gedanken erlaubst, beim Bösen zu verweilen, wirst du selbst hässlich.',
    'Die Kraft Gottes in dir, die Kraft grenzenloser Kontrolle, liegt im Überbewussten.',
    'Du bist nach dem Tod genau derselbe wie zuvor. Nichts ändert sich; du gibst nur den Körper auf.',
    'Der Geist ist eine Kraft, mit der man die Welt erobern kann.',
    'Verlasse dich nicht auf den Tod, um dich von deinen Unvollkommenheiten zu befreien.',
    'In dir liegt die Kraft, alles zu vollbringen, was du willst; diese Kraft liegt im Willen.',
    'Der Geist ist wie ein verrückter Affe, und der Wille ist das Seil, ihn zu binden.',
    'Wahre Selbstanalyse ist die größte Kunst des Fortschritts.',
    'Die Zeit des Scheiterns ist die beste Zeit, um die Samen des Erfolgs zu säen.',
    'Unsere Gedanken machen uns. Was wir denken, das werden wir.',
    'Je mehr du dich konzentrierst, desto eher wirst du tun können, was du tun willst.',
    'Den Geist zu überwinden bedeutet, frei zu sein.',
    'Der Tod ist wirklich schön; wenn er etwas Schlechtes wäre, würde Gott nicht zulassen, dass er uns widerfährt.',
    'Weise diese Phantasmagorie von Krankheit und Gesundheit, Trauer und Freude zurück. Erhebe dich darüber. Werde zum Selbst.',
    'Alle Seelen kommen von Gott – individualisierte Strahlen reinen Geistes – und entwickeln sich zurück zu ihrer ursprünglichen Vollkommenheit.',
    'Die Welle ist dasselbe wie der Ozean, obwohl sie nicht der ganze Ozean ist. So ist jede Welle der Schöpfung ein Teil des ewigen Ozeans des Geistes.',
    'Dieses Leben ist kurz, die Eitelkeiten der Welt sind vergänglich, doch nur die leben wahrhaft, die für andere leben; die übrigen sind mehr tot als lebendig.',
    'Die größte Schlacht, die du jemals schlagen wirst, ist die mit deinem eigenen Geist.',
    'Jedes Morgen wird durch jedes Heute bestimmt.',
    'Fürchte nichts. Hasse niemanden, schenke allen Liebe, fühle die Liebe Gottes und sieh Seine Gegenwart in jedem.',
    'Es sind nicht so sehr deine flüchtigen Gedanken oder brillanten Ideen, sondern deine schlichten alltäglichen Gewohnheiten, die dein Leben bestimmen.',
    'Die ganze Welt macht einem Menschen Platz, der weiß, wohin er geht, und entschlossen ist, dorthin zu gelangen.',
    'Der beste Test für den Charakter eines Menschen ist, wie er diejenigen behandelt, die nichts für ihn tun können.',
    'Was du denkst, wirst du. Was du fühlst, ziehst du an. Was du dir vorstellst, erschaffst du.',
    'Sei ein Athlet im Rennen des Lebens; aber denke daran, dass das wahre Rennen dasjenige ist, das innen gelaufen wird.',
    'Durch bewusste, tiefere Akte der Meditation muss jeder Sucher seine Unruhe entfernen.',
    'Das Geheimnis vollkommener Gesundheit, vollkommenen Glücks und vollkommenen Erfolgs ist, deinen eigenen Geist zu beherrschen.',
    'Du bist die Summe des Bewusstseins, das wir selbst über eine Reihe von Inkarnationen geschaffen haben.',
    'Das Gesetz des Karmas ist keine Strafe; es ist ein Gesetz von Ursache und Wirkung. Es ist ein Gesetz vollkommener Gerechtigkeit.',
    'Jeder Mensch hat das Recht, seinen eigenen Weg zu wählen, aber er muss auch die Folgen seiner Entscheidungen akzeptieren.',
    'Dein Schicksal liegt in deinen Händen, denn du hast die Macht, deine Gedanken und Handlungen zu verändern.',
    'Deine Willenskraft ist das Instrument des Bildes Gottes in dir.',
    'Ein starker Wille schafft durch seine dynamische Kraft einen Weg zu seiner Erfüllung.',
    'Sei sicher, dass deine Willenskraft konstruktiv eingesetzt wird, nicht für schädliche Zwecke oder belanglose Dinge.',
    'Dein Leben ist nicht das Ergebnis des Zufalls, sondern deiner eigenen Gestaltung.',
    'Der Zweck des Lebens ist, für andere zu leben und in Gott zu leben.',
    'Die größte Sünde ist, sich selbst für schwach zu halten.',
    'Das Universum ist ein gewaltiger Tempel Seiner Gegenwart.',
    'Gleich unter den Schatten dieses Lebens liegt Sein wunderbares Licht.',
    'Die Seele ist nicht im Körper, sondern der Körper ist in der Seele.',
    'Alles ist Gott. Alles ist Geist. Alles ist eins.',
    'Die materielle Welt ist ein Traum, doch ein Traum, der durch die Kraft deines Geistes verändert werden kann.',
    'Die Welt ist das große Gymnasium, in dem wir stark werden sollen.',
    'Die Illusion eines getrennten Selbst ist die Quelle allen Leidens.',
    'Du bist ein Teil des ewigen Ozeans des Geistes.',
    'Je mehr du meditierst, desto mehr wirst du erkennen, dass du nicht der Körper bist, sondern die unsterbliche Seele.',
    'Der wahre Sinn des Lebens ist, zu erkennen, dass du eins mit Gott bist.',
    'Je mehr du hinausgehst und Gutes tust, desto mehr werden eure Herzen gereinigt.',
    'Gib der Welt das Beste, das du hast, und das Beste wird zu dir zurückkehren.',
    'Das Gesetz des Wohlstandes wird nicht vom Gesetz des Egoismus bestimmt, sondern vom Gesetz der Selbstlosigkeit.',
    'Das große Geheimnis wahren Erfolgs, wahren Glücks ist dies: Der Mann oder die Frau, der/die keine Gegenleistung fordert, der vollkommen selbstlose Mensch, ist der erfolgreichste.',
    'Anderen zu dienen heißt Gott zu dienen.',
    'Kriya Yoga ist ein Instrument, durch das die menschliche Evolution beschleunigt werden kann; es kontrolliert den Geist durch die Lebenskraft und ist der wissenschaftlichste Weg zum Unendlichen.',
    'Die Nachwirkungen der Kriya bringen höchsten Frieden und Glückseligkeit mit sich und übertreffen die Freuden aller zusammengenommenen körperlichen Genüsse.',
    'Aus der Freude, die in der Meditation erfahren wird, schöpfe ich die Ruhe von tausend Schlummern, wodurch gewöhnlicher Schlaf für den fortgeschrittenen Yogi nahezu überflüssig wird.',
    'Selbstverwirklichung ist Yoga oder „Einheit“ mit der Wahrheit — die direkte Wahrnehmung der Wahrheit durch die allwissende intuitive Fähigkeit der Seele.',
    'Auf diesem Pfad spiritueller Handlung gibt es keinen Verlust unvollendeter Bemühungen zur Verwirklichung und keine Erzeugung gegenteilig wirkender Ergebnisse.',
    'Schon ein winziges bisschen wahrer Religion schützt vor der großen Furcht, die den wiederholten Zyklen von Geburt und Tod innewohnt.',
    'Yoga ist der Pfad spiritueller Handlung, unfehlbar darin, Konzept in Verwirklichung zu verwandeln; wer diesen Pfad annimmt, findet jeden Einsatz von dauerhaftem Nutzen.',
    'In der materiellen Welt werden alle Erfolge an greifbaren Ergebnissen erkannt; auf dem spirituellen Pfad sind die Ergebnisse psychologisch, immateriell, aber ewig wohltätig.',
    'Spirituelle Ergebnisse beginnen als subtile Transformationen im Bewusstsein und markieren den Fortschritt des inneren Wesens.',
    'Wahre Religion umfasst unveränderliche Prinzipien, die den Menschen dauerhaft vor Krankheit, Unglück und Unwissenheit schützen.',
    'Vergiss die Vergangenheit, denn vergangene Leben sind dunkel von vielen Schanden; menschliches Verhalten ist unzuverlässig, bis es im Göttlichen verankert ist.',
    'Alles Zukünftige wird sich verbessern, wenn man im Gegenwart ernsthaft geistige Anstrengung unternimmt.',
    'Du bist und wirst immer die vollkommene Reflexion des Geistes sein; auch wenn du dich jetzt als sterblich vorstellst, ruft die Meditation über dein wahres Selbst deine Geist-Natur zurück.',
    'Da du unsterblich bist, belaste dich nicht mit irdischen Begrenzungen.',
    'Meditation bedeutet, eins mit der Seele zu werden, das Bewusstsein des Körpers und seiner Begrenzungen zu verbannen und sich zu erinnern, dass man Seele ist.',
    'Meditation bringt den Beweis für die Existenz Gottes.',
    'Ein Mann, der den Himmel, die Berge oder den Ozean betrachtet, erkennt die göttliche Präsenz nicht; der subtile Strahl des Schöpfers ist dem ungeschulten Blick nicht wahrnehmbar.',
    'Gott, da er unendlich ist, kann auf keine Form begrenzt werden und ist doch in allen Formen gegenwärtig; Er ist in jedem Menschen und in jedem Heiligen gleichermaßen anwesend.',
    'Es gibt keinen wirklichen Unterschied zwischen den Geschöpfen; alle sind Produkte der Mutter Natur, erhalten durch dieselbe zugrunde liegende Göttlichkeit.',
    'Ihre scheinbare Vielfalt wurzelt in der Einheit des Einen Geistes, und die Erkenntnis dieser Wahrheit ist Befreiung und Einssein mit Gott.',
    'Ein Befreiter sieht nur den Herrn in allen Geschöpfen und in der gesamten Schöpfung.',
    'Gott ist Bewusstsein; im Wesentlichen gibt es im Universum nichts als Geist oder Bewusstsein.',
    'Der Sanskrit-Begriff für Gott — Sat-Chit-Ananda — bezeichnet Ewiges Sein (Sat), Unendliches Bewusstsein (Chit) und Immer-neue Glückseligkeit (Ananda).',
    'Obwohl Gott als die Seele aller Menschen existiert, verstrickt Er sich nicht in die Schöpfung; doch die Menschen, vom Göttlichen durchtränkt, unterliegen der kosmischen Täuschung.',
    'Wahre Weisheit bedeutet zu verstehen, wie das Eine Bewusstsein zu allem wird.',
    'Die Weisen trauern nicht um Dinge, die unvermeidlich veränderlich sind; weltliche Dinge sind in Gottes Bewusstsein Kleinigkeiten, weil sie nicht ewig sind.',
    'Sie meistern die sterbliche Unruhe und erfahren die Ruhe, die mit der Freiheit von der Identifikation mit dem Körper einhergeht.',
    'Wenn solche Devotees unveränderliche Vollkommenheit erreichen, bezeugen sie die Veränderungen des Lebens, ohne von ihnen bewegt zu werden.',
    'Identifikation mit den Wellen der Veränderung führt zu Elend; für Veränderung zu leben ist Trennung vom Ewigen.',
    'Die Weisen erwarten kein dauerndes Glück von Freunden, Familie oder Besitz; die Meditation über den unsterblichen Geist bringt ewigen Frieden.',
    'Das moderne Leben ist unbefriedigend; es bringt zu viele Wünsche, Sorgen und flüchtige Freuden, die letztlich zu Unglück führen.',
    'Es gibt keine Sicherheit in dieser Welt; jederzeit kann das Bewusstsein gezwungen sein, den Körper wegen Krankheit oder Unglück zu verlassen.',
    'Im vergänglichen Reich von Zeit und Raum gibt es ständige Veränderung in Form und Ausdruck, doch das Wesen innerhalb dieser Veränderungen bleibt bestehen.',
    'Ewig ist die Seele des Menschen und die Seele des Universums — das Krishna- oder Christus-Bewusstsein — Ausdrucksformen des Geistes.',
    'Erstens befreie dich von falschen Gedanken und Gewohnheiten; zweitens etabliere gute Gewohnheiten und vollbringe gute Taten.',
    'Wenn du weiter versuchst, wirst du dich verbessern; ein Heiliger ist einfach ein Sünder, der nie aufgegeben hat.',
    'Gib niemals auf; jeder geistige Gedanke, den du denkst, wird dein ewiger Freund sein.',
    'Jede böse Neigung, die du dir aneignest, wird zu deinem Feind, bis du sie besiegst.',
    'Gleichgewichte materielle und spirituelle Pflichten in deinem Leben; dieses Gleichgewicht bringt höchste Glückseligkeit.',
    'Wache auf, schlafe nicht mehr; die Befreiung des menschlichen Bewusstseins erfordert seine Schulung durch Studium, Affirmation, Konzentration und Meditation.',
    'Wende die Aufmerksamkeit von den unaufhörlichen Schwankungen des Körpers ab und hin zu feineren, stabilen Schwingungen der Lebenskraft und höheren Geisteszustände.',
    'Wähle Gottes ewige Glückseligkeit, erreichbar, indem man jetzt einige Freuden verneint, statt weltliches Glück, das nicht anhält.',
    'Denke nicht von dir als vom Körper, sondern als der freudvollen Bewusstheit und dem unsterblichen Leben dahinter.',
    'Wahrheiten sind für dich keine Wahrheiten, solange du sie nicht in dir selbst verwirklichst; ohne Verwirklichung bleiben sie bloße Ideen.',
    'Geistiges Bewusstsein liegt nicht in vagen theologischen Konzepten, sondern im Erlangen der Selbstverwirklichung.',
    'Der Ozean kann nicht in eine Tasse aufgenommen werden, wenn nicht die Kapazität der Tasse vergrößert wird — ebenso müssen menschliche Fähigkeiten erweitert werden, um Gott zu begreifen.',
    'Empfangen bezeichnet eine durch Selbstentwicklung erworbene Fähigkeit; es ist etwas anderes als bloßer Glaube.',
    'Verlass die Mutlosigkeit der sterblichen Bewusstheit und erhebe dich auf dem königlichen Pfad.',
    'Alles andere kann warten; deine Suche nach Gott kann nicht warten.',
    'Diese Lehren sind nicht nur Predigten, sondern Wahrheiten, die dich befreien werden.',
    'Kriya Yoga richtet die Lebenskraft darauf, den ruhelosen Geist zu stillen und die direkte Gemeinschaft mit dem Unendlichen zu ermöglichen.',
    'Die Glückseligkeit der Meditation übersteigt gewöhnliche körperliche Freuden und ruht tiefer als der Schlaf.',
    'Glückseligkeit ist keine Reaktion auf äußere Ereignisse, sondern ein bewusster Zustand, der durch spirituelle Praxis zugänglich ist.',
    'Wahre Religion ist das bewusste Erleben göttlicher Wahrheit, nicht bloße intellektuelle Zustimmung.',
    'Spirituelle Anstrengung trägt nicht nur zum inneren Frieden bei, sondern schützt die Seele vor Angst und Leid.',
    'Die wirklichen Vorteile spiritueller Praxis sind subtil und doch ewig; sie verändern das Bewusstsein dauerhaft.',
    'Im Göttlichen verankert zu sein, bringt Sicherheit, die die vergänglichen Freuden der Welt nicht bieten können.',
    'Meditation öffnet die intuitive Fähigkeit und enthüllt verborgene Wahrheiten über Leben und Geist.',
    'Die göttliche Präsenz ist subtil, jenseits dessen, was gewöhnliche Sinne erkennen können.',
    'Alle Formen, so vielfältig sie auch sind, werden von einer zugrunde liegenden Göttlichkeit getragen.',
    'Befreiung kommt durch die Erkenntnis, dass das Einssein mit Gott alle äußeren Unterschiede übersteigt.',
    'Weltliche Bestrebungen und Besitztümer verblassen letztlich; was bleibt, ist spirituelle Verwirklichung.',
    'Unsterblichkeit ist die wahre Natur der Seele; vorübergehende Formen sollten die Identität nicht bestimmen.',
    'Das Wesen der Schöpfung ist Bewusstsein, unendlich manifest und doch im Kern Eins.',
    'Wahre Weisheit übersteigt reine intellektuelle Erkenntnis und ruht in intuitiver Verwirklichung.',
    'Menschliche Unruhe zerstreut sich, wenn das Bewusstsein im Ewigen zentriert ist.',
    'Der Kreislauf der Veränderung verliert seine Macht über jene, die im Geist verankert sind.',
    'Das Verlangen nach spirituellem Frieden ist ein tieferer Impuls als jeder weltliche Wunsch.',
    'Der geistige Zustand eines Menschen bestimmt seine Fähigkeit, Frieden zu erfahren.',
    'Die Beharrlichkeit eines Heiligen ist das Maß seines Triumphs über Unwissenheit.',
    'Jeder geistige Gedanke legt ein Fundament für ewigen Frieden.',
    'Das habituelle Verweilen bei göttlicher Wahrheit festigt den spirituellen Fortschritt.',
    'Falsche Gedanken werden zu Feinden, bis sie transzendiert sind.',
    'Höchste Glückseligkeit entsteht aus Harmonie zwischen materieller Verantwortung und spiritueller Hingabe.',
    'Das Bewusstsein zu schulen, die Identifikation mit dem Körper zu transzendieren, eröffnet innere Freiheit.',
    'Stabile höhere Bewusstseinszustände entstehen durch beharrliche Meditation.',
    'Die Entscheidung für göttliche Glückseligkeit lenkt das Schicksal zur Befreiung.',
    'Die sterbliche Identität ist eine Illusion, die in tiefer spiritueller Gewahrsein schmilzt.',
    'Echte Wahrheiten verwandeln das Leben nur, wenn sie durch Erfahrung verinnerlicht werden.',
    'Die Gottesverwirklichung ist der höchste Zweck jenseits aller intellektuellen Überzeugung.',
    'Die Erweiterung der eigenen Fähigkeit für göttliche Wahrheit ist der Schlüssel zum spirituellen Wachstum.',
    'Bloßer Glaube befreit das Bewusstsein nicht; Verwirklichung tut es.',
    'Der spirituelle Weg ist ein königlicher Pfad, der Mut verlangt, über die Sterblichkeit hinauszuwachsen.',
    'Die Suche nach Gott sollte Vorrang vor allen geringeren Bestrebungen haben.',
    'Diese Lehren sind lebensspendende Wahrheiten, keine abstrakten Konzepte.',
    'Meditation verwandelt gewöhnliche Augenblicke in Schritte zur Unsterblichkeit.',
    'Glückseligkeit ist die bewusste Verwirklichung von Gottes Gegenwart in uns.',
    'Der Geist wird nicht durch Flucht aus dem Leben erkannt, sondern durch die Transformation des Bewusstseins im Leben.',
    'Jede Minute, die in spiritueller Praxis verbracht wird, erweitert den inneren Frieden.',
    'Der göttliche Funke im Menschen ist die Quelle unendlichen Friedens.',
    'Die menschliche Entwicklung beschleunigt sich, wenn sich das Bewusstsein nach innen wendet.',
    'Die Unruhe des Geistes ist ein Schleier, der die Natur der Seele verdeckt.',
    'In der Stille der Meditation spricht die Seele ihre ewige Wahrheit.',
    'Wahrer Friede steht über den Umständen; er ist ein Bewusstseinszustand.',
    'Jeder spirituelle Sieg stärkt die Verbindung mit dem Göttlichen.',
    'Gottes Präsenz ist subtil und doch beständig, durch Hingabe zugänglich.',
    'Das Universum ist der Ausdruck göttlichen Bewusstseins.',
    'Die Überwindung der Angst beginnt mit der Verankerung im göttlichen Selbst.',
    'Meditation offenbart die unvergängliche Natur der Seele.',
    'Ewige Glückseligkeit ist die endgültige Verwirklichung für den aufrichtigen Sucher.'
  ],
  [

    Article(
        heading: 'Gott allein',
        body: 'Wer ist es, der alle Geheimnisse aller Seelen kennt, die je gelebt haben, die die Welt in Staunen versetzten und die nun verloren und vergangen sind?\n\nGott allein! Gott allein!\n\nWer lebte in der Einsamkeit des ewigen Nichts, bevor die Atome ihre funkelnden Augen aufschlugen und durch die ganze Schöpfung tanzten?\n\nGott allein! Gott allein!\n\nWir kamen aus Etwas hervor, wir wissen nicht aus was. Wir wissen, dass wir jetzt leben, lachen und verweilen, und die meisten von uns werden nicht wissen, was in der Wildnis des großen Jenseits liegt, wenn wir im Schoß des friedvollen Todes einschlafen. Doch wer kennt das Geheimnis des Lebens, sowohl vor als auch nach diesem Dasein?\n\nGott allein! Gott allein!\n\nAlle Dinge leben; alle Dinge tanzen im Rhythmus ewiger Harmonie. Niemand kennt den großen Zug der Schöpfung, der aus der mystischen Kammer des Raumes hervorging. Niemand weiß, welcher Teil dieser Kammer des endlosen Nichts von Gegenständen und Wesen eingenommen ist, die durch den Zauberstab des Todes geschmolzen wurden, außer –\n\nGott allein! Gott allein!\n\nUnsere Geliebten lieben uns und geloben, uns für immer zu lieben, und doch vergessen sie uns, wenn sie in den Großen Schlaf sinken. Ihre Erinnerungen erstarren bald. Doch wer liebt uns für immer, ohne es uns je zu sagen, und wer erinnert sich an uns, wenn alle anderen uns vergessen?\n\nGott allein! Gott allein!\n\nLeben und Tod, Sterne und Wind, Liebe und Hass, Kummer und Freude, und Mensch und Tier tanzen und schlafen auf der stygischen Bühne der Zeit, verbergen sich beim Tod hinter den Kulissen und kommen wieder hervor, um auf der Bühne der Zeit in neuen Kostümen aus Fleisch zu spielen. Niemand erinnert sich daran, was er zuvor tat, oder warum er sich dieses vorübergehenden Stelldicheins in dieser merkwürdigen Karawanserei so sicher ist, außer –\n\nGott allein! Gott allein!\n\nWarum Gott dieses Spiel spielt und warum Er all dieses Wissen für sich behält und es nur kärglich mit uns, Seinen Kindern, teilt, ist bekannt bei –\n\nGott allein! Gott allein!\n\nDoch wenn du nicht länger umherirrst und dem Unendlichen Ufer in deinem Inneren näherkommst und dich selbst von der unerwünschten Stellung eines verlorenen Sohnes in die eines wahren himmlischen Kindes verwandelst, dann kannst auch du alles wissen, was du wissen willst, von niemand anderem als –\n\nGott allein! Gott allein!\n\nDa Er alles weiß, wirst auch du, wenn du dich in einen fordernden Göttlichen Sohn verwandelst, alles wissen von –\n\nGott allein! Gott allein!\n\nWenn alle Freunde dich verlassen müssen, wer wird bei dir sein?\n\nGott allein! Gott allein!\n\nDa keine Dinge und niemand wirklich dir gehören, lerne zu lieben –\n\nGott allein! Gott allein!'
    ),
    Article(
        heading: 'Das Erlangen von Glück',
        body: 'Paramhansa Yogananda, November 1936:\n\nWir können niemals glücklich sein, es sei denn, wir schreiten voran und suchen Erfüllung darin, und es sei denn, wir hüten unser Glück vor all den Einflüssen, die es zerstören. Glück kommt nicht durch hilfloses Denken, sondern dadurch, dass man es in allen Stimmungen und Handlungen des Lebens lebt. Was immer du auch tust, bewahre die Unterströmung des Glücks, den geheimen Fluss der Freude, der unter den Sanden vielfältiger Gedanken und den felsigen Böden harter Prüfungen fließt. Lerne, in deinem Herzen heimlich glücklich zu sein trotz aller Umstände, und sage dir selbst: „Glück ist mein größtes göttliches Geburtsrecht — der vergrabene Schatz meiner Seele. Ich habe ihn endlich gefunden, und nun werde ich heimlich reicher sein als im Traum der Könige.“\n\nMache das Unglücklichsein nicht zu einer chronischen Gewohnheit, denn es ist alles andere als angenehm, unglücklich zu sein, während es für dich selbst und für andere ein Segen ist, wenn du glücklich bist. Wenn es so leicht ist, ein silbernes Lächeln zu tragen oder süßes Glück durch deine Stimme zu gießen, warum mürrisch sein und Unglück um dich herum verbreiten? Es ist niemals zu spät zu lernen.\n\nGlück wächst durch das, womit es genährt wird. Lerne, glücklich zu sein, indem du die ganze Zeit glücklich bist. Johannes sagte: „Wenn ich Geld bekomme, werde ich glücklich sein.“ Er wurde wohlhabend; dann sagte er: „Ich werde glücklich sein, wenn ich meine akute Verdauungsstörung loswerde.“ Seine Verdauungsstörung wurde geheilt, doch er dachte: „Wenn ich eine Frau bekomme, werde ich glücklich sein.“ Dann begann das Tollhaus, denn er heiratete eine nörgelnde, zungenpeitschende Frau. Er ließ sich von dieser Frau scheiden und heiratete nach vielen Jahren erneut, doch die zweite Frau war schlimmer als die erste. Dann dachte er, er würde glücklicher sein, wenn er sich von seiner zweiten Frau scheiden ließe, also tat er es; doch im Alter von siebzig dachte er: „Nein, ich werde niemals glücklich sein, es sei denn, ich kann wieder jugendlich sein.“ Auf diese Weise versuchen es die Menschen, erreichen jedoch niemals ihr Ziel des Glücks. Sie sind wie der Mann, der im Zorn losrannte, um sich selbst in die Nase zu beißen, was ihm natürlich niemals gelingen konnte.\n\nUnwissende Menschen achten, wie die Tiere, nicht auf die Lehren, die Schmerz und Freude begleiten. Die meisten Menschen leben ein Leben, das mit Traurigkeit und Kummer durchzogen ist, denn sie vermeiden nicht die Handlungen, die zu Leiden führen, und folgen nicht den Wegen, die zum Glück führen. Dann gibt es Menschen, die immer bewusst überempfindlich auf Kummer und Freude reagieren, wenn sie kommen. Solche Menschen werden gewöhnlich durch Kummer zutiefst zermalmt und von Freude überwältigt und verlieren so ihr geistiges Gleichgewicht. Es gibt nur sehr wenige Menschen, die, nachdem sie sich an den Feuern der Unwissenheit die Finger verbrannt haben, lernen, elenderzeugende Handlungen zu vermeiden.\n\nViele Menschen wünschen sich glücklich zu sein, und doch machen sie niemals die Anstrengung, den Weg des Handelns einzuschlagen, der zum Glück führt. Die meisten Menschen rollen den Hügel des Lebens hinab und wünschen sich dabei nur gedanklich, den Gipfel des Glücks zu erklimmen. Manchmal wachen sie auf, wenn ihre Begeisterung für das Glück den Sturz auf den Grund des Leidens überlebt. Den meisten Menschen fehlt die Vorstellungskraft, und sie wachen niemals auf, bis etwas Schreckliches geschieht, das sie aus ihrem Alptraum der Torheit aufrüttelt.\n\nStagnierende Menschen sind unglücklich, und äußerst unwissende Menschen wissen kaum, wie es sich anfühlt, entweder glücklich oder unglücklich zu sein. Sie sind gefühllos wie Steine. Es ist besser, über die eigene Unwissenheit unglücklich zu sein, als glücklich mit ihr zu sterben. Wo immer du bist, bleibe wach und lebendig mit deinem Denken, deiner Wahrnehmung und deiner Intuition, stets bereit, wie ein guter Fotograf, Bilder vorbildlichen Verhaltens aufzunehmen und schlechtes Benehmen zu ignorieren. Dein höchstes Glück liegt darin, stets bereit zu sein, zu lernen, und dich richtig zu verhalten.\n\nMenschen, die Glück suchen, müssen den Einfluss schlechter Gewohnheiten vermeiden, die zu bösen Handlungen führen, denn böse Handlungen erzeugen früher oder später Elend. Elend zerfrisst Körper, Geist und Seele wie eine still brennende Säure und kann nicht lange ertragen werden. Darum sollte es streng vermieden werden.\n\nHeile dich von bösen Gewohnheiten, indem du sie mit den entgegengesetzten guten Gewohnheiten ausbrennst. Wenn du die schlechte Gewohnheit hast, zu lügen, und dadurch viele Freunde verloren hast, beginne die entgegengesetzte gute Gewohnheit, die Wahrheit zu sagen. Es braucht Zeit, eine gute oder eine schlechte Gewohnheit zu formen. Es ist für einen schlechten Menschen schwierig, gut zu sein, und für einen guten Menschen schwierig, schlecht zu sein; doch erinnere dich daran, dass es für dich natürlich und leicht sein wird, gut zu sein, sobald du gut geworden bist; ebenso wirst du, wenn du eine böse Gewohnheit pflegst, trotz deines Wunsches gezwungen sein, böse zu sein, und du musst beten: „Vater, mein Geist ist willig, aber mein Fleisch ist schwach.“ Darum lohnt es sich, die Gewohnheit des Glücklichseins zu pflegen.\n\nDer Mensch, der auf bösen Pfaden hinabgleitet, findet keinen Widerstand; doch sobald er versucht, seine bösen Gewohnheiten durch die Annahme geistiger Gesetze der Disziplin zu bekämpfen, findet er zahllose Versuchungen erweckt, die kämpfen, um seine edlen Bemühungen zu vereiteln.\n\nVerurteile andere nicht\n\nDein persönliches Glück hängt in hohem Maße davon ab, dich selbst und deine Familie vor den bösen Folgen des Klatsches zu schützen. Sieh nichts Böses, sprich nichts Böses, höre nichts Böses, denke nichts Böses, fühle nichts Böses. Die meisten Menschen können stundenlang über andere Menschen sprechen und gedeihen unter dem Einfluss des Klatsches wie unter dem vorübergehenden Einfluss eines berauschenden, giftigen Weines. Ist es nicht seltsam, dass Menschen stundenlang glatt, freudig und mit beißender Kritik über die Fehler anderer sprechen können, aber keinerlei Bezugnahme auf ihre eigenen Fehler ertragen?\n\nWenn du nicht gern über deine eigenen Fehler sprichst, wenn es dir wehtut, dies zu tun, dann solltest du dich gewiss noch mehr verletzt fühlen, wenn du unfreundliche, schädliche Dinge über andere Menschen sagst. Erziehe dich selbst und jedes Mitglied deiner Familie dazu, davon abzusehen, über andere zu sprechen. „Richtet nicht, auf dass ihr nicht gerichtet werdet.“\n\nIndem du die Schwäche eines Menschen öffentlich machst, hilfst du ihm nicht. Stattdessen machst du ihn entweder zornig oder mutlos und beschämst ihn, vielleicht für immer, sodass er aufgibt, gut zu sein. Wenn du einem Menschen durch offenes Verleumden das Gefühl der Würde nimmst, machst du ihn verzweifelt.\n\nWenn ein Mensch am Boden liegt, ist er sich seiner eigenen Bosheit nur zu gut bewusst. Durch zerstörerische Kritik stößt du ihn noch weiter hinab in den Morast der Verzweiflung, in den er bereits sinkt. Statt über ihn zu klatschen, solltest du ihn mit liebevollen, ermutigenden Worten herausziehen. Nur wenn um Hilfe gebeten wird, sollte geistige und moralische Unterstützung angeboten werden. Deinen eigenen Kindern oder Geliebten kannst du jederzeit deine freundlichen, demütigen Vorschläge machen und so ihr Gefühl von Geheimhaltung oder Zartheit nehmen.\n\nLächle und sei glücklich\n\nMache dein Zuhause zu einem Tal des Lächelns statt zu einem Tal der Tränen. Lächle jetzt und kümmere dich nicht darum, wie schwer es dir gewesen ist, dies zu tun. Lächle jetzt. Erinnere dich die ganze Zeit daran, JETZT ZU LÄCHELN, und du wirst IMMER LÄCHELN.\n\nManche Menschen lächeln die meiste Zeit, während sie unter der Maske des Lachens ein von Kummer zerfressenes Herz verbergen. Solche Menschen verkümmern langsam im Schatten bedeutungsloser Lächeln. Es gibt andere Menschen, die nur hin und wieder lächeln und zuweilen auch sehr ernst sein können; und doch mögen unter der harten, schönen äußeren Erscheinung Millionen von Quellen lachenden Friedens sprudeln.\n\nWenn du fünfzig Jahre lang guter Gesundheit erfreut hast und dann drei Jahre krank warst, ohne durch irgendeine Methode geheilt zu werden, würdest du wahrscheinlich die Länge der Zeit vergessen, in der du guter Gesundheit erfreut hast, und über die Vorstellung der Krankheit lachen. Nun sollte deine Reaktion genau das Gegenteil sein. Nur weil du vielleicht drei Jahre krank gewesen bist, gibt es keinen Grund zu glauben, dass du niemals wieder gesund sein wirst.\n\nEbenso bist du geneigt, die Hoffnung, jemals wieder glücklich zu sein, zu verlieren, wenn du lange glücklich warst und vergleichsweise kurze Zeit unglücklich gewesen bist. Dies ist ein Mangel an Vorstellungskraft. Die Erinnerung an ein lang andauerndes Glück sollte eine kraftvolle unterbewusste Gewohnheit sein, um dein bewusstes Denken zu beeinflussen und das Bewusstsein deiner gegenwärtigen Not abzuwehren.\n\nWenn nur Reichtum verloren geht, ist nichts Wirkliches verloren, denn wenn man Gesundheit und Fähigkeit besitzt, kann man noch glücklich sein und mehr Geld verdienen; doch wenn die Gesundheit verloren geht, geht auch das meiste Glück verloren, und wenn das Lebensprinzip verloren geht, geht alles Glück verloren. Nachdem du dich im Traumland im Ozean des Friedens gebadet hast und mit Glück erwachst, sage: „Im Schlafland fand ich mich frei von sterblichen Sorgen. Ich war ein König des Friedens. Nun, da ich am Tage arbeite und meine täglichen Schlachten der Pflichten führe, werde ich nicht länger von aufrührerischen Sorgen des Reiches des Wachens besiegt werden. Ich bin ein König des Friedens im Schlafland, und ich werde ein solcher König auch im Land des Wachens bleiben. Wenn ich aus meinem Königreich des Friedens im Schlafland hervortrete, werde ich denselben Frieden in meinem Land der wachen Träume verbreiten.“'
    ),
    Article(
        heading: 'Göttliche Liebe',
        body: 'Du bist das mystische Echo aus den Höhlen des Herzens und die unhörbare Stimme des Fühlens.\n\nDu unsichtbarer Verführer der Seelen, Du bist die Quelle, die aus dem Busen der Freundschaft fließt.\n\nDu bist das unsichtbare Band selbstgebundener Seelen und die Strahlen geheimer Wärme, die Knospen des Fühlens in Blüten liebenswerter, seelenvoller Worte der Poesie und Treue aufbrechen lassen.\n\nDu bist der Göttliche Amor, der mystische Seelen verlockt, das Herz aller lebenden Dinge zu durchdringen.\n\nDu bist die stille Sprache der Seelen und die unsichtbare Tinte, mit der Liebende Briefe auf die Seiten ihrer Herzen schreiben.\n\nDu bist die Mutter aller Zuneigungen, und in Deiner Brust der Liebe pocht das Herz Gottes.\n\nLiebe ist der Herzschlag allen Lebens und der Engel der Inkarnation.\n\nLiebe ist das stille Gespräch zwischen zwei Herzen, und sie ist der Ruf Gottes an alle Geschöpfe, belebte und unbelebte, in Sein Haus der Einheit zurückzukehren.\n\nLiebe wird im Garten des Seelenfortschritts geboren und schläft hinter der Dunkelheit äußerer Anhaftungen. Sie ist der älteste und süßeste Nektar, bewahrt in der Flasche der Herzen.\n\nSie ist die Flamme, die alles Unkraut der Selbstsucht verbrennt und die Mauern familiärer und patriotischer Enge zerstört.\n\nSie ist das Licht, das alle Mauern zwischen Seelen, Familien und Nationen auflöst.\n\nSie ist die unvergängliche Blüte reiner Freundschaft im Garten sowohl junger als auch reifer Seelen.\n\nLiebe ist die Tür zum Himmel, das vollkommene Lied der Seelen.\n\nLiebe ist das Echo der Stimme Gottes, die versucht, durch stumme Steine, durch Regen, Wind, Duft, belebendes Licht und gefiederte Singvögel zu widerhallen; sie hallt wider durch das Weinen und Lachen von Babys, durch bedingungslose Mutterliebe und durch stumme und sprechende Herzen.'
    ),
    Article(
        heading: 'Die Freude im Leben finden',
        body: 'Oktober 1936, „Die Freude im Leben finden“\n\nDu begehrst eine Sache so lange, wie du sie nicht erlangen kannst; wenn du sie dir gesichert hast, wirst du ihrer früher oder später müde, und dann wirst du etwas anderes wollen. Hast du jemals versucht, dieses Irrlicht des „Etwas anderem“ zu finden, das du am Ende aller erfüllten Wünsche suchst?\n\nWas immer du suchst, du musst es mit Freude suchen, in der Erwartung, durch seinen Besitz Freude zu haben, und du musst Freude empfinden, wenn du es tatsächlich bekommst. Wenn du verschiedene Dinge direkt oder indirekt suchst, suchst du in Wirklichkeit Freude. Beim Suchen aller Dinge ist es in Wahrheit die Freude, die du durch all diese Dinge und durch die Erfüllung aller Wünsche suchst.\n\nWarum also nicht die Freude direkt suchen? Warum sie durch das Medium materieller Wünsche und materieller Dinge suchen? Du willst nicht jene Dinge im Leben, die dir Kummer bringen. Ebenso willst du nicht jene Dinge, die anfangs ein wenig Freude versprechen, dich am Ende jedoch in tiefe Reue und Leiden versenken.\n\nWarum Freude suchen, indem du um die Gunst kurzlebiger materieller Dinge bittest? Warum dich auf kurzlebige materielle Dinge für kurzlebige Freuden verlassen? Materielle Dinge und die Erfüllung materieller Wünsche sind kurzlebig; daher sind alle aus ihnen geborenen Freuden kurzlebig. Freuden, die aus Essen, dem Riechen von Düften, dem Hören von Musik, dem Betrachten schöner Objekte und dem Berühren angenehmer Dinge geboren werden, sind kurzlebig. Sie dauern nur so lange, wie die Empfindungen dauern, die aus den Sinnen des Geschmacks, Geruchs, Gehörs, Sehens und Tastens geboren werden.\n\nDu willst keine quälende Freude; du willst keine vergängliche Freude, die Kummer in ihrem Gefolge bringt; du verlangst nach einer Freude, die nicht wie das plötzliche Flackern von Gaze-Flügeln unter dem Blitz verschwindet. Du solltest nach einer Freude suchen, die für immer stetig leuchtet, wie das ewig leuchtende Radium.\n\nEbenso willst du keine Freude, die zu viel Gleichförmigkeit hat; du willst eine Freude, die sich verändert und sich auf vielerlei Weise selbst tanzt, um deinen Geist zu fesseln und deine Aufmerksamkeit für immer beschäftigt und interessiert zu halten. Jede Freude, die stoßweise kommt, ist quälend; jede Freude, die eintönig ist, ist natürlich ermüdend; jede Freude, die nur für kurze Zeit kommt und zuletzt Kummer bringt, ist unerwünscht. Jede Freude, die nur kurz kommt und dann davonschwebt, dich in einen Zustand der Gleichgültigkeit versenkend und diesen Zustand durch den Kontrast vertiefend, ist folternd.\n\nDie Freude, die sich rhythmisch die ganze Zeit verändert wie die verschiedenen Haltungen eines Schauspielers und dennoch in sich selbst unveränderlich bleibt, ist das, was wir alle suchen. Eine solche Freude kann nur durch regelmäßige, tiefe Meditation gefunden werden. Eine solche immer neue, unveränderliche Quelle der Freude allein kann unseren Freuden-Durst stillen.\n\nWenn die Natur uns auf einmal alles gäbe, was wir wollten — Reichtum, Macht und verlorene Freunde — würden wir ihrer früher oder später überdrüssig werden; doch eine Sache gibt es, deren wir niemals müde werden können, und das ist die Freude selbst. Ihrer Natur nach ist die immer neue Freude das Einzige, was den Geist niemals ermüden oder ihn dazu bringen kann, Freude gegen etwas anderes einzutauschen.\n\nIn der Verfolgung des Bösen oder des Guten suchst du immer Freude. Das Erstere verspricht Freude und gibt Kummer; das Letztere mag Kummer versprechen, wird aber am Ende gewiss dauerhafte Freude geben. Dauerhafte, immer neue Freude ist Gott, und wenn du Ihn gefunden hast, hast du das ewig schwer fassbare Irrlicht des „Etwas anderem“ gefunden, das du immer am Ende aller erfüllten Wünsche suchst. Wenn du dieses „Etwas andere“ gefunden hast, wirst du nicht weiter suchen. Wenn du diese immer neue Freude gefunden hast, wirst du in ihr alles finden, was du je gesucht hast.\n\nMaterielle Objekte, die Freude geben, bleiben außerhalb des Geistes; sie gelangen nur durch die Vorstellungskraft in den Geist. Freude ist ihrer Natur nach etwas, das im Geist geboren wird und ihm am nächsten lebt. Äußere, materielle Objekte können zerstört werden, doch diese innere Freude kann niemals zerstört werden, wenn man weiß, wie man sie bewahrt, und es sei denn, der Besitzer der Freude ändert seinen Geist und wird traurig. Diese Freude ist immer neu und unzerstörbar.\n\nSuche die Freude nicht durch materielle Mittel oder durch aus solchem Kontakt geborene Wünsche. Suche die unbedingte, unzerstörbare Reine Freude in dir selbst, und dann wirst du die immer bewusste, immer neue Freude-Gott gefunden haben. Diese Freude ist keine abstrakte Eigenschaft des Geistes, sondern sie ist bewusst, selbstgeboren und die bewusste, sich selbst ausdrückende Eigenschaft des Geistes. Suche sie und sei für immer getröstet.\n\nWenn du diese immer neue Freude erlangt hast, wirst du kein Zyniker geworden sein, der alle hasst. Vielmehr wirst du dann in der Lage sein, alles richtig zu genießen. Als unsterbliches Kind Gottes sollst du alles mit einer dauerhaften Haltung deiner ewigen Natur fortwährender Freude genießen. Menschen, die materielle Dinge genießen, werden materiell gesinnt. Es ist eine Schande, sich wie ein unzufriedener Sterblicher zu verhalten, wenn man nach Gottes Ebenbild geschaffen ist und unsterblich ist.\n\nWenn Unsterbliche sich wie Sterbliche verhalten, erfahren sie die Wechsel von Freude, Kummer und Gleichgültigkeit in ihren Naturen. Darum musst du diese aufgepfropfte Natur der Veränderlichkeit auf deiner unveränderlichen Natur der Freude zerstören. Und wenn du deine eigene Natur unveränderlicher Freude gefunden hast, wirst du in der Lage sein, alles zu genießen, ob angenehm oder unangenehm, mit deiner unveränderlichen, unzerstörbaren Freude. Deine Freude wird unerschüttert bestehen bleiben inmitten des Zusammenbruchs zerbrechender irdischer Vergnügungen.'
    )

  ],
);
